### ISSUE TITLE
Notification

### ISSUE THREAD

**Issue by IRMobydick** [tonyofrancis/Fetch#1]
Is there any notification?

**Comment by tonyofrancis** [comment]
@IRMobydick If you are talking about Android notifications, fetch does not support this feature. Status and progress update for requests are posted to attached FetchListeners like this.

```java
fetch.addFetchListener(new FetchListener() {

    @Override
    public void onUpdate(long id, int status, int progress, int error) {

        if(downloadId == id) {

            progressBar.setProgress(progress);
            ...
        }
    }     
});
```

**Comment by IRMobydick** [comment]
Yeah, that's exactly what i'm talking about 👍
