### ISSUE TITLE
As migrate from 1.14 to RC3 The download speed get declined dramatically 

### ISSUE THREAD

**Issue by Kevin321an** [tonyofrancis/Fetch#101]
With 1.14, it used to reach 7MB/s but now it is mostly below 1MB/s

Any hint what could cause this? 

Thanks,

**Comment by tonyofrancis** [comment]
Hi @Kevin321an . Thanks for using Fetch. Do you have an example project I can test from? Also if you don't mind sharing the link you are trying to download from, device you are testing on, download speed etc. You should defiantly be getting better speeds from version 2 of the library. What happens if you change the `DownloadBufferSize` when constructing the Fetch builder? The default buffer size is 8192 bytes which is optimal for most cases.

```java
 final int bufferSize = 8192;
 fetch = new Fetch.Builder(context, "Main")
        .setDownloadBufferSize(bufferSize)
        .build();
```

**Comment by sathiyarajcbe** [comment]
Downloading speed is very low when comparing v1.1.5. Even I have added the buffer size to 8192.

**Comment by tonyofrancis** [comment]
Are you able to share the url or a sample project for me to test?

**Comment by sathiyarajcbe** [comment]
Ya sure! I have added the link with Sample app!
https://drive.google.com/open?id=1V80HzqtPIR_jYzP2rrodQXAOCHyI1Wdt
Check in Single download!

**Comment by Kevin321an** [comment]
Hi Tonyo, 
I tried double the defaultBufferSize and it did not solve the issue. 


The download speed from your example "http://download.blender.org/peach/bigbuckbunny_movies/BigBuckBunny_640x360.m4v" perform huge different from my testing. 

with v1 takes few seconds and the download speed could reach 13MB/s
On the other hand, v2 takes about 2 minutes and the download speed only reach 2MB/s Maximum. 

Tese result tested with Pixel and Mi A1

Thanks,

**Comment by sathiyarajcbe** [comment]
check with this link Tonyo,
https://drive.google.com/open?id=1prgIZkhnpdco-qRQGgbKQOIhzjb7oHW1

**Comment by tonyofrancis** [comment]
@Kevin321an @sathiyarajcbe how many concurrent downloads are you running at a given time? If you pass a value greater than one to `setDownloadConcurrentLimit(1)` on the Fetch builder, and then enqueue multiple requests, Fetch will download as many request at the same time as the concurrentLimit allows. The more concurrent downloads you have at a given time, the slower download speeds per download you will get. All downloads have to share the same network bandwidth. 

If you currently have the concurrent limit set to one and still experiencing slow downloads, try using using the okHttp downloader with Fetch. See the readme for more details on Downloaders. Please let me know if this helps.

**Comment by tonyofrancis** [comment]
I will also have a look at the samples and test. Waiting for your feedbacks.

**Comment by Kevin321an** [comment]
I tried the `setDownloadConcurrentLimit(1)` and the OkHTTP downloader but it did not help to increase the downloading speed.

**Comment by sathiyarajcbe** [comment]
For me too same result with limit 1 and OkHttp!

**Comment by tonyofrancis** [comment]
@Kevin321an, @sathiyarajcbe I am now also getting very slow speeds also from the library. Looking into this further. Will label as a bug and try to get a fix asap.

**Comment by sathiyarajcbe** [comment]
Waiting Tonyo!!!

**Comment by Kevin321an** [comment]
Thank you

**Comment by tonyofrancis** [comment]
@Kevin321an @sathiyarajcbe I have pushed a new version of Fetch with fixes. Please see README for new Fetch version and let me know if there are any issues.

**Comment by sathiyarajcbe** [comment]
Working fine thank you!

**Comment by Kevin321an** [comment]
It works now. Thanks,

**Comment by tonyofrancis** [comment]
great.
