### ISSUE TITLE
Feature request: Attach bundle metadata to a request

### ISSUE THREAD

**Issue by sethchhim** [tonyofrancis/Fetch#105]
I'm using 2.0.0-RC5 and everything is working out great.

It would be useful to attach some persistent data to a `Request`. It is not a big deal because I can just clone and persist externally but I think it would be good for your library.

```
//create bundle
val title = "My Title"
val bundle = Bundle()
bundle.putString(KEY_TITLE, title)

//instantiate download with bundle
val request = Request(stringUrl, cacheFilePath, bundle)
fetch.enqueue(request, callback)

//retrieve bundle
fetch.getDownloads(object : Func<List<Download>> {
            override fun call(t: List<Download>) {
                val download = t[0]
                val title = download.request.bundle[KEY_TITLE]
            }
        })

```

**Comment by tonyofrancis** [comment]
@sethchhim Thanks for the suggestion. I've have given this feature much thought, but decided not to implement it to Fetch for the following reasons:

1. The bundle/extra data is not directly tied to information needed by Fetch to perform a download.
2. Adding this extra data will decrease performance for querying download information.
3. The `download.request` object is only a copy of the initial request object. So changes that are made to the initial request after enqueuing a request may not be reflected in the `download.request` object unless the request is updated in Fetch. This can be confusing and error prone.
4. This feature can easily be created using an external backing source to store the extra data and use the `request.getId()` to retrieve the data.
