### ISSUE TITLE
Multiple enqueuing download order

### ISSUE THREAD

**Issue by LudovicBtrs** [tonyofrancis/Fetch#107]
Hi,

I'm trying to use Fetch and it is a very nice lib. Thanks.

However, I'm facing difficulties when I try to download multiples (enqueued) files.

From what I see (from the logs), **my requests are queued in the right order but are not downloaded in the same order**. Moreover, one of the requests has HIGH priority (+ first to be enqueued) but is the last to be downloaded.

I used your multi enqueuing example.

Am I missing or misunderstanding something ?

Regards,
Lud'vic.

**Comment by tonyofrancis** [comment]
@LudovicBtrs Fetch processes requests for download by download Priority and time created. For example if you multi enqueued 5 requests and the last one has a high priority? It will be downloaded first. If the remaining requests has the same priority then Fetch chooses the oldest one by time created. I will have a look at the multi enqueued example again just to verify and will update you.

**Comment by tonyofrancis** [comment]
@LudovicBtrs Just checked and the priority/ timestamp logic for enqueuing downloads is definitely not correct. Working on a fix and will release a new version in a few hours. Thanks for finding this bug. I will post back once I have released.

**Comment by LudovicBtrs** [comment]
@tonyofrancis Sweet, thanks for your work ! I appreciate.
Lud'vic.

**Comment by tonyofrancis** [comment]
@LudovicBtrs just pushed 2.0.0-RC7 with fixes. Please test and let me know if you have any issues.

**Comment by LudovicBtrs** [comment]
@tonyofrancis Hi Francis, 
It works like a charm.
Thanks for your time and reactivity !

Best regards,
Lud'vic.
