### ISSUE TITLE
Allow of setting user generated Request Id

### ISSUE THREAD

**Issue by Nordeast** [tonyofrancis/Fetch#108]
As a feature request I am suggesting a way for a user to set their own request Id. I already track unique Id's for the things I download and having to track the request Id's on top of that seems unnecessary. This makes it easy for me to use the Id's that are already stored in my own database. Any thoughts?

**Comment by tonyofrancis** [comment]
@Nordeast. Working on this feature for the next release. The changes will not affect anything in the library. Library user can set their own id. If the user does not provide an id, the library will auto generate one.

**Comment by tonyofrancis** [comment]
@Nordeast just pushed a new version 2.0.0-RC8 of the library up with this feature. Comment back to let me know if you have any issues.

**Comment by tonyofrancis** [comment]
Just as a note. Each request enqueued in Fetch has to have a unique id.

**Comment by Nordeast** [comment]
Appears to be working in the application I am developing. If I encounter any issues I'll reopen.
