### ISSUE TITLE
Progress and filesize issues

### ISSUE THREAD

**Issue by burhanaksendir** [tonyofrancis/Fetch#11]
Scenario: 
The file is being downloaded:

D/ fetchDebug: id:30547713379280,status:901,progress:25,error:-1
I/ fetchDebug: id: 30547713379280 downloadedBytes: 7428602 / fileSize: 29189424

Then I pause the download and close the application.
Progress and filesize are calculated incorrectly when I reopen the application and resume it.

D/ fetchDebug: id:30547713379280,status:901,progress:100,error:-1
I/  fetchDebug: id: 30547713379280 downloadedBytes: 22283153 / fileSize: 13935572

**Comment by tonyofrancis** [comment]
@burhanaksendir is it possible to provide me with the download link? I would like to run a test. What I am noticing from the example above is that the file sizes are different.

**Comment by burhanaksendir** [comment]
sample link:
https://archive.org/download/Mozart_347/05.mp3

**Comment by tonyofrancis** [comment]
@burhanaksendir I was able to reproduce this bug and will be working on a fix today. Thanks for reporting it.

**Comment by tonyofrancis** [comment]
The fix for this bug has been pushed to the GitHub probject. I will be pushing out Fetch 1.0.2 in a few hours. Thanks
