### ISSUE TITLE
Only onProgress is called when using RxFetch for enqueue

### ISSUE THREAD

**Issue by darkyelox** [tonyofrancis/Fetch#113]
when i use RxFetch for enqueue and set a listener only the onProgress method is called, onQueued, onResume and onCancelled are not called, but using normal Fetch enqueue method with callback parameters works

**Comment by tonyofrancis** [comment]
@darkyelox Going to look into this issue. I was on vacation last week.

**Comment by tonyofrancis** [comment]
@darkyelox I have fixed this issue and it will be in the next release RC9. Which will be released Mar 5, 2018. thanks
