### ISSUE TITLE
Question: Resuming Download from where it left off after failure

### ISSUE THREAD

**Issue by Nordeast** [tonyofrancis/Fetch#114]
I have a question about how I can go about resuming a download when it fails part way through. I am downloading very large files and they sometimes fail to complete. It would be nice to keep the partial download and then finish the rest of the download later. I feel like this Fetch supports that already but I am having trouble figuring out how it would be done. My best guess is by trying the code below.

```
fetch.getDownloadsWithStatus(Status.FAILED, new Func<List<? extends Download>>() {
    @Override
    public void call(List<? extends Download> downloads) {
        for (Download download : downloads) {
            fetch.retry(download.getId());
        }
     }
});
```

Or maybe I should be calling `fetch.resume()` instead?

**Comment by Nordeast** [comment]
Seems I got it right here though if there is some piece that I could be missing please feel free to add more details. I will try and find some time and help add some more documentation.

**Comment by kevin-deep** [comment]
I think fetch.resume()  will not resume/retry the task already failed but fetch.retry() does. 
In this case, you have to use Retry
