### ISSUE TITLE
A Minor Issue on how Fetch works! 

### ISSUE THREAD

**Issue by Xenolion** [tonyofrancis/Fetch#117]
I have started using some Features of Fetch though I have some misunderstandings on how it works. Help me with this questions:

Does Fetch store all the downloads I have ever downloaded or tried to download using it? So if I want a download list of example 400 downloads do I still get all of them or are they cleared after some time or after a certain limit?

Can Fetch send a Broadcast so I can use a BroacastReceiver to receive a change in my download's status or should I just use a service that runs listening to the event?

In the current SampleApp when I run it, the DownloadListActivity start each download each time I enter the Activity. Was this intended for Demonstration or does Fetch real cant continue stopped or resume downloads and so restart them when an Activity is run again? Though for this question I kinda think it is intended for demonstration but I am not 100% sure.

**Comment by tonyofrancis** [comment]
@Xenolion Thanks for using Fetch.

1. Fetch stores all downloads in a database unless you delete or remove them.
2. Attach a FetchListener to fetch to listen for status changes or you can query download information directly from Fetch.
3.  The sample app deletes the content for demonstration.

**Comment by Xenolion** [comment]
Thanks for your fast a clear answer. Be blessed bro. Also Thanks for bringing Fetch.

**Comment by Xenolion** [comment]
We can close this now!

**Comment by Xenolion** [comment]
Instead of open another Issue I have another misunderstanding concerning the SampleApp. I was trying to make a follow up of the code so I added `DownloadListActvity` in my own Testing App but I moved the method `getFetch` to the same Activity `DownloadListActivity`. But now whenever I call the method `onBackPressed` or when the user get out of the Activity by actually pressing the back button, The activity is closed but the App freezes for some seconds and get ANR Application Not Responding! What is the cause of this?? I have not edited your code much in this Test App.

**Comment by Xenolion** [comment]
Solved after commenting `fetch.close();` temporarily. But now I can not get the same instance due to 

`Caused by: com.tonyodev.fetch2.exception.FetchException: Namespace:DefaultFetch already exists. You cannot have more than one active instance of Fetch with the same namespace. Did your forget to call close the old instance?`

Is there a way I can retrieve the same `Fetch` instance and add more downloads! Or set the FetchListener?
