### ISSUE TITLE
getProgress() and getDownloadedBytes() issues

### ISSUE THREAD

**Issue by burhanaksendir** [tonyofrancis/Fetch#12]
Scenario 2:
The file is being downloaded.
https://archive.org/download/Mozart_347/05.mp3

D/fetchDebug: id:165363055600,status:901,progress:5,error:-1
I/fetchDebug: id: 165363055600 downloadedBytes: 1875132 / fileSize: 17487404
D/fetchDebug: id:165363055600,status:901,progress:6,error:-1
I/fetchDebug: id: 165363055600 downloadedBytes: 2207640 / fileSize: 17487404
D/fetchDebug: id:165363055600,status:901,progress:7,error:-1
I/fetchDebug: id: 165363055600 downloadedBytes: 2585160 / fileSize: 17487404

.......

Then I pause the download, progress and downloadedBytes values are set to 0.

D/fetchDebug: id:165363055600,status:902,progress:0, error:-1
I/fetchDebug: id: 165363055600 downloadedBytes: 0 / fileSize: 17487404

When I pause, I want to show the last updated values in the download.

**Comment by tonyofrancis** [comment]
@burhanaksendir Thanks for reporting this bug. I noticed it when I was fixing the other progress bug you reported earlier. I am working on a fix and will push it up as soon as possible.

**Comment by burhanaksendir** [comment]
@tonyofrancis Thank you so much.

**Comment by tonyofrancis** [comment]
A bug fix for this issue has been pushed to GitHub. This fix will make it into Fetch 1.0.2 which will be released in a few hours.
