### ISSUE TITLE
Failed to resume download

### ISSUE THREAD

**Issue by AminDeveloper** [tonyofrancis/Fetch#120]
In my app normally starting and pausing and resuming download works well 
but if I repeat  pausing and resuming for several times it fails on resume with unknown error
here is the log info:

D/Main: Resumed download Download(id=2, namespace='Main', url='http://tct-cdn.cdn.p30download.com/p30dl-mobile/Elite.Killer.SWAT.v1.3.3_p30download.com.apk?1520424991', file='/storage/emulated/0/Download/m2m.apk', group=0, priority=NORMAL, headers={}, downloaded=12509168, total=21600554, status=FAILED, error=UNKNOWN, networkType=ALL, created=24982482383666, tag=null)

I appreciate this library but because of this problem i will be forced to think about an alternative.

**Comment by AminDeveloper** [comment]
Ok i will change the link to see if it happens with new link or no 
but what can i do to handle this kind of unknown errors? Is it correct to remove download and restart it again or it can be some sort of temporary problems like timeout or something like that and retry will solve it?

**Comment by tonyofrancis** [comment]
@AminDeveloper It defiantly does seem like a timeout issue. What you can do is call `fetch.retry(id)` for the download to retry at the current position. Keep a counter of the retry attempts. If after lets say 2 attempts then you can stop retrying. I will defiantly look into this a bit further and verify that the library is reporting timeouts correctly.

**Comment by tonyofrancis** [comment]
@AminDeveloper RC11 is now out. Can you test and let me know if you are still getting the UNKNOWN error for the download link?
