### ISSUE TITLE
if once group is created add more download in group

### ISSUE THREAD

**Issue by mudi256** [tonyofrancis/Fetch#124]
i am begginer in android, here i am face an issue,
i am developing an app for video download, here problem is that if once group is created and downloading is started, how to add another download

update group with new request

**Comment by tonyofrancis** [comment]
@mudi256 See the `fetchBuilder.setDownloadConcurrentLimit(limit)` method on the FetchBuilder object. Note that the more concurrent downloads you have running, the longer it takes for all downloads to complete.
