### ISSUE TITLE
Issue with SDK version

### ISSUE THREAD

**Issue by RobbieArmz** [tonyofrancis/Fetch#127]
I really like this library, however as it seems it is required to have my sdk set to 27.0.2 which is not ideal for me for compatibility purposes, is there any way rather than downloading the files and importing them directly to my project to get around that?

**Comment by tonyofrancis** [comment]
@RobbieArmz You should be able to add resolution strategy to your apps build.gradle file to use the sdk version of you choice. You can try the following code. Add it to the bottom of you app's build.gradle file.

```
configurations.all {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        def requested = details.requested
        if (requested.group == 'com.android.support') {
            if (!requested.name.startsWith("multidex")) {
                details.useVersion "supportVersion"
            }
        }
    }
}

```
replace `supportVersion` with the sdk version you need. Please let me know if that help.

**Comment by RobbieArmz** [comment]
Hi tony, thanks for the support. I tried the code you gave me and it ran just fine, thanks alot.

One more question, how do I set to run 1 download at a time?

**Comment by tonyofrancis** [comment]
@RobbieArmz Glad it worked
