### ISSUE TITLE
Requests Lost when a group is paused

### ISSUE THREAD

**Issue by Sergios21** [tonyofrancis/Fetch#129]
I'm using the pauseGroup functionality. I'm doing this so that the downloads pause when the connectivity changes to Mobile data only (no wifi), I then prompt the user whether he wants to continue or keep the downloads paused. When pausing, usually 4-5 downloads are received as failed in the onError of my FetchListener. I collect the requests of these downloads in a sepparate Arraylist that contains failed requests. When all other files have downloaded I enqueue the failed requests again, but nothing happens. Following are snapsots of one of the failed downloads and the request of the download:

**Download**
created = 522297234078517
downloaded = 0
error = {Error@9163} "REQUEST_NOT_SUCCESSFUL"
file = "/path/www/images/bg.png"
group = 2121210
headers = {EmptyMap@9165}  size = 0
id = -2545041
namespace = "app_assets"
networkType = {NetworkType@9167} "ALL"
priority = {Priority@9168} "NORMAL"
status = {Status@9169} "FAILED"
tag = null
total = 0
url = "https://path/images/bg.png?_=1520509119"

**Request**
file = "/path/images/bg.png"
id = -2545041
url = "https://path/images/bg.png?_=1520509119"
groupId = 2121210
headers = {LinkedHashMap@9181}  size = 0
networkType = {NetworkType@9167} "ALL"
priority = {Priority@9168} "NORMAL"
tag = null

**Comment by tonyofrancis** [comment]
@Sergios21 Are you calling `fetch.enqueue(downloads, SuccessCallback, ErrorCallback)` to retry the downloads?. If that is the case then you are doing it wrong. The enqueue methods will only enqueue a new download if the request does not already exist. If you try to enqueue a request that Fetch already has, the ErrorCallback will be called.

The correct method to call is `fetch.retry(ids)`. This method retries a `failed` or `cancelled` download from the last position. Please let me know if this helps

**Comment by Sergios21** [comment]
Hello Tony, you are correct, I am using the retry method now and it works, in some very rare cases some requests fail again (could be a server error) so I have implemented a retry logic that keeps trying until the file is downloaded (will add a retries counter). Thank you.

**Comment by tonyofrancis** [comment]
@Sergios21 Glad you got a fix.

**Comment by Sergios21** [comment]
Hello again Tony, I noticed that the first retry works, but when a file fails to download a second time, it isn't added to the download queue (even though the retry method is called for its id), is there a maximum retry count for every file? If so, can I change this parameter somehow?

**Comment by tonyofrancis** [comment]
@Sergios21 sorry for the late reply. If you are using the `ConnectivityManager.CONNECTIVITY_ACTION` broadcast receiver that is fired by the system to retry the downloads and get `REQUEST_NOT_SUCCESSFUL`, it most likely means that internet connection is not established. When the broadcast receiver is called it simply means that the device is connect to a network not that the device has internet connection. The Fetch Builder has a `enableRetryOnNetworkGain(true)` feature that will retry failed downloads because internet connection was lost. It has since been improved in recent versions of Fetch.
