### ISSUE TITLE
Help wanted

### ISSUE THREAD

**Issue by smart222** [tonyofrancis/Fetch#130]
Hi,

  Is it possible with fetch? ow can do it

**Comment by tonyofrancis** [comment]
@smart222 Yes it is possible with Fetch. Have you tried the sample app?.  What you do is create a new instance of Fetch in the Application class of your app and reference it in the different activities. What you can also do is create a single global instance of fetch and a global fetch listener and share that global listener with the different activities. Hope this helps.

**Comment by smart222** [comment]
@tonyofrancis could you add some samples for global listener and how to enqueue and state update adapter rows it will help me.

**Comment by tonyofrancis** [comment]
@smart222 The sample app does have global instance of Fetch. in the App.java class. That is referenced in other Activities. Probably best to take the time and go through the code to get a better understanding of how Fetch works. Cannot do the work for you.
