### ISSUE TITLE
Removing requests from database when completed.

### ISSUE THREAD

**Issue by marcin-adamczewski** [tonyofrancis/Fetch#137]
Hi,

I have two questions.

1. How to download a file twice with same url and file path?
For example there is a song under url = "www.url.com/newSet.mp3"
and I want to save it to ".../DOWNLOAD_PATH/newSet" path.
User fetched the file for the first time...then deleted it...and then fetched again.
Unfortunately it is impossible because I get error REQUEST_WITH_ID_ALREADY_EXIST.

The only solution that worked for me was calling
`fetch.delete(id);` or `fetch.remove(id);`
before each download. 
Do you need to store requests in database that succeed or failed? What about removing them just after download succeed or failed?

2. How to download from two different urls to same directory?
So same scenario like above but we have two different urls.
Firstly we fetch from the first one...then delete the file...then download from second url.
I get error like REQUEST_WITH_FILE_PATH_ALREADY_EXIST.
Unfortunately I don't have solution for this. The only thing that comes to my mind is to remove
all Requests immediately when they completes download (success or error).
But why it cannot be done by library? 

Thanks in advance for your time :)

**Comment by tonyofrancis** [comment]
@marcin-adamczewski 

Question 1. 
**Reason for Fetch's behavior**
By default, Fetch stores all request in a database. Unless you provide your own ID for a request, Fetch uses a request's url + file path to create a unique `ID`. If that unique ID is already found in the Fetch database, Fetch will not enqueue a new request with the same information. Also, Fetch will not enqueue any new request with a File Path that already exist in the database for another request. The reason for this is because we do not want two request that are downloading with the same file path try to save data in that one file. This would cause data corruption. In the case of a user deleting the file outside your app, Fetch will still maintain a record of the request for that downloaded file. You must remove the existing request first before enqueuing it again.

Solution 1: Remove exiting request and enqueue again
```
    @Override
    public void onCreate() {
        super.onCreate();
        final Request request = new Request("some url","some file path");
       //Check if requests exist first
        fetch.getDownload(request.getId(), new Func2<Download>() {
            @Override
            public void call(@Nullable Download download) {
                if (download == null) {
                    //Request does not exist enqueue new request
                    enqueueRequest(request);
                } else {
                    //Request does exist. Delete it and enqueue the new request
                    fetch.delete(request.getId());
                    enqueueRequest(request);
                }
            }
        });
    }
    
    private void enqueueRequest(Request request) {
        fetch.enqueue(request, new Func<Download>() {
            @Override
            public void call(@NotNull Download download) {
                //Request enqueued Successfully
            }
        }, new Func<Error>() {
            @Override
            public void call(@NotNull Error error) {
                //Error occurred enqueuing request.
            }
        });
    }
```

Solution 2: If you do not want Fetch to permanently store request data to a database on the local storage disk, you can create a temporary in memory database. Fetch will not persist any data from an in memory temporary database when the app is closed. Get a new Instance of Fetch like the following:

```
  final Fetch fetch = new Fetch.Builder(this, "namespace")
                .enabledInMemoryDatabase(true) 
                .build();
```
Solution 3: You can simply delete a request from Fetch when a download completes or fails. 

Question 2
The information I provided in question 1 about Fetch's behaviors answers this question in part.
The reason why Fetch was designed with a database is to help resume incomplete downloads and to also provide you with request information when needed. You should delete request information from Fetch when no longer needed.
 
What I can do is to add a new option on the Fetch Builder that you can enable to auto delete records from the Fetch database when a download completes or fails after Fetch has reported this information to the Fetch Listeners. 

Let me know if this helps or if you have more questions

**Comment by marcin-adamczewski** [comment]
Thank you for very detailed answer 👍 
I understand that storing all requests in database prevents multiple downloads to the same file
path and also is needed for resuming incomplete downloads. Although I think you don't have to store in database the requests that already succeed or failed. You suggested to add optional feature to be able to clear such requests when finished. IMHO it should be default behaviour. It's like currently I have to think (check) if the requests exists instead of just enqueue download and don't think about anything else.  What do you think?

**Comment by tonyofrancis** [comment]
@marcin-adamczewski The above solution will work with Fetch version 2.0.0-RC17 and older. Just released a new version of Fetch version 2.0.0-RC18 which has a **new RequestOptions feature**. With RequestOptions, you can tell Fetch when to take certain actions depending on a situation. 

Your first issue can be solved with RequestOptions. Example:
```
 final Fetch fetch = new Fetch.Builder(this, "namespace")
                .setLogger(new FetchTimberLogger())
                .setDownloader(new OkHttpDownloader())
                .setDownloadConcurrentLimit(4)
                .enableLogging(true)
                .enableRetryOnNetworkGain(true)
                .addRequestOptions(RequestOptions.REPLACE_ON_ENQUEUE_FRESH,
                 RequestOptions.AUTO_REMOVE_ON_COMPLETED)
                .build();
```
The `RequestOptions.REPLACE_ON_ENQUEUE_FRESH` option will allow Fetch to enqueue and replace the request even if it already exist in the Fetch database. This option also forces the download to start from the beginning. If you would like to replace the request and continue from the current downloaded position, use option `RequestOptions.REPLACE_ON_ENQUEUE`.

Other RequestOptions are:
`RequestOptions.ADD_AUTO_INCREMENT_TO_FILE_ON_ENQUEUE` - If the file already exist, Fetch will append a number to the file of this request. See the Java documents for more information.

`RequestOptions.AUTO_REMOVE_ON_COMPLETED` - Removes a request record from Fetch after a download completes.

`RequestOptions.AUTO_REMOVE_ON_FAILED` - Removes a request record from Fetch after a download fails.

See the RequestOptions documentation and updated sample app for more information.

Please let me know if this helps.

**Comment by marcin-adamczewski** [comment]
@tonyofrancis Wow, you're fast :) 
I like the customisations you introduced. I'll test it tomorrow :)
Nevertheless I think that if you want to not make options like AUTO_REMOVE_ON_COMPLETED and
AUTO_REMOVE_ON_FAILED default, then such behaviour should be mentioned in Wiki so people are not confused and won't get into trouble.

Thanks 👍

**Comment by marcin-adamczewski** [comment]
@tonyofrancis I find it problematic to download to the same file path twice using options you've added.
I've used REPLACE_ON_ENQUEUE_FRESH option. It works fine if I try to download using Request with same id twice but not when trying to download from two different url to same path.

Here is a code to reproduce it.

`   private void twoDifferentUrlsToSameDirectory() {
        final String filePath = getFilesDir() + "/TestDownload/file";
        final String url1 = "http://storage.googleapis.com/ix_choosemuse/uploads/2016/02/android-logo.png";
        final String url2 = "http://media.mongodb.org/zips.json";

        fetch.addListener(new AbstractFetchListener() {
            @Override
            public void onCompleted(@NotNull Download download) {
                super.onCompleted(download);
                final Request request = new Request(url2, filePath);
                fetch.enqueue(request, null, new Func<Error>() {
                    @Override
                    public void call(@NotNull Error error) {
                        Log.e("lol", error.toString());
                    }
                });
            }

            @Override
            public void onError(@NotNull Download download) {
                super.onError(download);
                Log.e("lol", download.getError().toString());
            }
        });
        
        final Request request = new Request( url1, filePath);
        fetch.enqueue(request, null, new Func<Error>() {
            @Override
            public void call(@NotNull Error error) {
                Log.e("lol", error.toString());
            }
        });
    }`

I probably could achieve what I want using ADD_AUTO_INCREMENT_TO_FILE_ON_ENQUEUE option, but it complicates figuring out file path later on if I would like to access this file.

What about  removing all database records that contains a file path that is the same as in Request being enqueued before each request? I find it reasonable at least for REPLACE_ON_ENQUEUE_FRESH option. 

If you'd like to know a real live use case then here it is:
1. User downloaded a music file to /PATH/music_id.mp3. Url to the file is "https://blablabla/temp_path_id_music_id.mp3". The file name is a music id so it can be easily accessed later on.
2. User deleted the file 
3. Now, user is trying to download same file again, but as the url to the music expired, url has changed to "https://blablabla/temp_path_2_id_music_id.mp3". It will result enqueuing Request with different url to the same file path.

**Comment by tonyofrancis** [comment]
@marcin-adamczewski I understand the use case. mhmmmm. There are two requirements that needs to be met before Fetch is able to enqueue a request. 
1. The file path needs to be unique to prevent data corruption in a multi downloading environment.
2. The request id need to be unique. Identifying purposes.

I'm not sure if you know this, but you can create a request with your own unique id `new Request(uniqueId, url, file);`. If you don't provide an id, Fetch will auto generate a unique id based on the url and file path. This has been one of the things I have had a hard time conveying to users. I will need to update the documentation and will start creating a wiki as soon to make this more clear. This is where too much customization/flexibility could cause issues.

I have just pushed a new version of Fetch 2.0.0-RC19 with new options `RequestOptions.REPLACE_ALL_ON_ENQUEUE_WHERE_UNIQUE` and `RequestOptions.REPLACE_ALL_ON_ENQUEUE_WHERE_UNIQUE_FRESH`. These option first removes any requests in the database that matches the enqueuing request's id or file . I think this is the option you are looking for. Let me know if this works well for you.

 I value your feedback making Fetch better and simpler. If it's not to much to ask. When possible can you let me know what are the most confusing parts when using the library. I would like to know whats not clear and what could me made simpler. My email address is on my profile page. Thanks.

**Comment by marcin-adamczewski** [comment]
@tonyofrancis 
Yes, I've seen those UNIQUE constraints on database. And you're right that creating wiki would be very helpful to users so they can understand how it works without looking into the code.

I think the new option you've added will solve my problem. I will be able to test it on Friday though.

I'm just thinking now...do we need all those RequestOptions.
If you'd remove from database all Request just after they are finished or failed 
you wouldn't have to create all those options, right?.
**What are the benefits of having such Requests in database (completed, failed) ?**
For Requests resuming it would be enough to store only Requests that are 'alive' (Enqueued, Pending, In Progress, Paused). Storing 'alive' requests prevents also from downloading to the same file in the same time.  
Sorry for confusing you, but I made your code more complicated because of all those options that may not be actually needed and I fell little bit bad about it haha :D

Thanks for your work and time 👍

**Comment by tonyofrancis** [comment]
@marcin-adamczewski 

**Benefits of the many Request Options**
 For example while developing an app, I want to ensure that I am not enqueuing and overriding any existing requests, but only want to delete it if it fails. Different apps will defiantly have different use cases. Depending on feedback I get, I will add or remove them from the library as we go.

**The benefits for keeping requests in a database.**
For example you are creating a video app. You may want to collect data as to how many videos the user  successfully downloaded in a time period. How many movies the user paused the downloading for and never completed(Analytics). The video app may also have a downloaded section that will show all completed downloads or downloads with the different statuses.

**Download Manager**
Fetch was not designed to only be used to downloading files. That's what the okHttp library is for. lol. But it was designed to manage downloads. Just like the built in download manager for Android. Fetch is more flexible, supports pause, resume etc.

**Comment by ababo** [comment]
Hi!

I'm facing the same problems:
1. I don't want Fetch to produce memory leaks remembering all my processed requests, since my Fetch-instance will last for a long time.
2. Sometimes I get `onCompleted` called when the target file is empty. Enqueuing a new request with the same url and filename leads to the same situation. But I can download the file easily using a browser or any other tool.

**Comment by ahsan265** [comment]
Hi, I am using this library on native side i have test this library, My use case is when i try to download the 50 files, the native android app start lagging / stuck. How we can fix this issue.
