### ISSUE TITLE
Cofiguratin problem

### ISSUE THREAD

**Issue by ahshoaib** [tonyofrancis/Fetch#14]
The build.gradle is configured and during rebuild gives the following errors:

/Users/shoaibrafa/AndroidStudioProjects/MyApp/app/build/intermediates/res/merged/debug/values-v24/values-v24.xml
Error:(3) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.
Error:(4) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.
Error:(3) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.
Error:(4) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.
Error:Execution failed for task ':app:processDebugResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

**Comment by tonyofrancis** [comment]
@ahshoaib The Fetch library is using the following gradle configuration
```groovy
compileSdkVersion 25
buildToolsVersion "25.0.2"

//support library
compile 'com.android.support:appcompat-v7:25.2.0'
```

From your code snippet it seems that your app is using v24 of the build tools or support library. Please verify that this is true. Try changing it to match Fetch's configuration and let me know if that worked.

**Comment by CoMatu** [comment]
I have some problem
![2018-02-15 1 06 16](https://user-images.githubusercontent.com/30466272/36225456-8fe8144a-11ec-11e8-84fd-e882799330be.png)
