### ISSUE TITLE
Update progress when app is closed

### ISSUE THREAD

**Issue by nowkin** [tonyofrancis/Fetch#141]
Hello
is it somehow possible to get progressupdates when the app is closed? Want to use if for android notifications in the notification bar. When the app is opened its all working but as soon as closing the app the notification dont get any updates anymore from onProgress or onCompleted

kind regards and thanks alot for your hard work

**Comment by tonyofrancis** [comment]
@nowkin There is no way to get a list of fetch listeners. I am curious as to why you would want to get a list of the listeners? Maybe others my need this added.
