### ISSUE TITLE
I need some help with multiple downloads

### ISSUE THREAD

**Issue by MotherChickenCOL** [tonyofrancis/Fetch#143]
Hi im so sorry, im hoping that you can help me with this, this is my first app and my first download system, im using your library because its pretty cool and  easy to use.

But im stuck in one part, i created a service wich processs my downloads, send a broadcast to another class to update my ui, and store  the content in a database that i use.

The problem is that when i put like 5 different downloads once 1 download finish the Fetch its inserting all 5 downloads in the database, but i just want to insert that download, i think that its because im adding multiple listeners to my fetch, but im using my fetch public to be called from another class to retrieve the downloads so how can i adapt my code to solve this?, im honestly really sorry for asking this, but i have tried  like 25 differents ways and this is the way that works for me, well not pretty good but it works, ill leave my code, if you want to help me i'll be grateful for ever, thanks for your awesome library.

Code from my service:

`package anime.app.com.appnimu;

import android.app.NotificationManager;
import android.app.PendingIntent;
import android.app.Service;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.os.Environment;
import android.os.Handler;
import android.os.HandlerThread;
import android.os.IBinder;
import android.os.Looper;
import android.os.Message;
import android.support.annotation.Nullable;
import android.support.v4.app.NotificationCompat;
import android.support.v4.content.ContextCompat;
import android.support.v4.content.LocalBroadcastManager;
import android.util.Log;
import android.widget.Toast;

import com.tonyodev.fetch2.Download;
import com.tonyodev.fetch2.Error;
import com.tonyodev.fetch2.Fetch;
import com.tonyodev.fetch2.FetchListener;
import com.tonyodev.fetch2.Func;
import com.tonyodev.fetch2.NetworkType;
import com.tonyodev.fetch2.Priority;
import com.tonyodev.fetch2.Request;
import com.tonyodev.fetch2downloaders.OkHttpDownloader;

import org.jetbrains.annotations.NotNull;

import java.io.File;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

import io.objectbox.query.Query;
import okhttp3.OkHttpClient;

/**
 * Created by Andrés on 23/04/2018.
 */

public class DownloaderService extends Service {

    public DownloaderService() {
        super();
    }
    private Looper mServiceLooper;
    private ServiceHandler mServiceHandler;
    public static final String BROADCAST_ACTION = "com.anime.app.com.broadcasttest";

    private Intent intent;
    private LocalBroadcastManager broadcastManager;

    public static FetchListener fetchListener;
    public static ArrayList<Fetch> fetchList;
    public static Fetch fetch;
    public static NotificationManager mNotifyManager;
    public static NotificationCompat.Builder notificationBuilder;

    private final class ServiceHandler extends Handler {
        public ServiceHandler(Looper looper) {
            super(looper);
        }
        @Override
        public void handleMessage(Message msg) {

        }
    }

    @Override
    public void onCreate() {
        // Get the HandlerThread's Looper and use it for our Handler
        broadcastManager = LocalBroadcastManager.getInstance(this);

        intent = new Intent(BROADCAST_ACTION);

        final OkHttpClient okHttpClient = new OkHttpClient.Builder()
                .build();

        fetch = new Fetch.Builder(getApplicationContext(), "VerEpisodio")
                .setDownloader(new OkHttpDownloader(okHttpClient))
                .setDownloadConcurrentLimit(24) // Allows Fetch to download 4 downloads in Parallel.
                .enableLogging(true)
                .build();

       // fetch.deleteAll();

        intent.setAction(TabDescargas.mBroadcastStringAction);
        intent.putExtra("FinishedNotify","Update");
        sendBroadcast(intent);
    }

    @Override
    public int onStartCommand(Intent intent, int flags, int startId) {
        // For each start request, send a message to start a job and deliver the
        // start ID so we know which request we're stopping when we finish the job
        HandlerThread thread = new HandlerThread("ServiceStartArguments");
        thread.start();
        mServiceLooper = thread.getLooper();
        mServiceHandler = new ServiceHandler(mServiceLooper);

        if(intent != null && intent.hasExtra("URL")){
            Bundle extras = intent.getExtras();
            String titulo = (String) extras.get("Titulo");
            String folder = (String) extras.get("Folder");
            String url = (String) extras.get("URL");
            String anime = (String) extras.get("Anime");
            String episodio = (String) extras.get("Capitulo");
            String titlean = (String) extras.get("TitleAnime");
            initDownload(url,folder,titulo,anime,episodio,titlean);

        }

        // If we get killed, after returning from here, restart
        return START_NOT_STICKY;
    }
    @Nullable
    @Override
    public IBinder onBind(Intent intent) {

        return null;
    }

    public String getRootDirPath(Context context) {
        if (Environment.MEDIA_MOUNTED.equals(Environment.getExternalStorageState())) {
            File file = ContextCompat.getExternalFilesDirs(context.getApplicationContext(), null)[0];
            return file.getAbsolutePath();
        } else {
            return context.getApplicationContext().getFilesDir().getAbsolutePath();
        }
    }

    private static String getBytesToMBString(long bytes){
        return String.format(Locale.ENGLISH, "%.2fMb", bytes / (1024.00 * 1024.00));
    }

    private void initDownload(String url, final String folder, String fileName, final String Anime, final String Episodio,final String titlean) {
        String dirPath = getRootDirPath(getApplicationContext());
        Log.e("IN DESCARGA URL:", url);

        final Request request = new Request(url, folder);
        request.setPriority(Priority.HIGH);
        request.setNetworkType(NetworkType.WIFI_ONLY);
        request.addHeader("clientKey", "SD78DF93_3947&");
        request.setTag("C. "+Episodio+" - "+titlean);

        fetch.enqueue(request, new Func<Download>() {

                    @Override
                    public void call(Download download) {
                        Toast.makeText(getApplicationContext(), "Descarga agregada a la cola de descargas, puede consultarla en el menú de descargas o deslizando hacia abajo para ver las notificaciones, por favor no cierre la app.", Toast.LENGTH_LONG).show();
                        mNotifyManager = (NotificationManager) getSystemService(Context.NOTIFICATION_SERVICE);
                        notificationBuilder = new NotificationCompat.Builder(getApplicationContext());
                        notificationBuilder.setContentTitle("C. "+Episodio+" - "+titlean)
                                .setContentText("Comenzando descarga..")
                                .setSmallIcon(R.drawable.ic_download).setOngoing(true);
                    }
                }, new Func<Error>() {
                    @Override
                    public void call(Error error) {
                        Toast.makeText(getApplicationContext(), "Error al iniciar la descarga "+error+" .", Toast.LENGTH_SHORT).show();

                    }
                }

        );

         fetch.addListener(new FetchListener() {
            @Override
            public void onQueued(@NotNull Download download) {
                intent.setAction(TabDescargas.mBroadcastStringAction);
                intent.putExtra("FinishedNotify","Update");
                sendBroadcast(intent);
            }

            @Override
            public void onCompleted(@NotNull Download download) {

                if(download.getStatus().getValue() == 4){

                Query<TablaAnimes> query = Home.boxTAnime.query().equal(TablaAnimes_.nombre,"").build();
                List<TablaAnimes> animeq =  query.setParameter(TablaAnimes_.nombre,Anime).find();
                if(animeq.size() > 0){

                    Query<TablaCapitulos> querycap = Home.boxTCaps.query().equal(TablaCapitulos_.nombre,"").build();
                    List<TablaCapitulos> capin =  querycap.setParameter(TablaCapitulos_.nombre,Episodio).find();

                    String cap = Episodio.replaceAll(" ","");

                    if(capin.size()==0){
                        TablaCapitulos tc = new TablaCapitulos(0,cap,folder,animeq.get(0).getId(),0,0);
                        Home.boxTCaps.put(tc);
                     }

                }else{

                    TablaAnimes ta = new TablaAnimes(0,Anime);
                    Home.boxTAnime.put(ta);

                    Query<TablaAnimes> queryin = Home.boxTAnime.query().equal(TablaAnimes_.nombre,"").build();
                    List<TablaAnimes> animeqin =  queryin.setParameter(TablaAnimes_.nombre,Anime).find();

                    Query<TablaCapitulos> querycap = Home.boxTCaps.query().equal(TablaCapitulos_.nombre,"").build();
                    List<TablaCapitulos> capin =  querycap.setParameter(TablaCapitulos_.nombre,Episodio).find();

                    if(capin.size()==0){

                        String cap = Episodio.replaceAll(" ","");

                        TablaCapitulos tc = new TablaCapitulos(0,cap,folder,animeqin.get(0).getId(),0,0);
                        Home.boxTCaps.put(tc);
                    }

                }
                intent.setAction(TabDescargas.mBroadcastStringAction);
                intent.putExtra("FinishedNotify","Update");

                sendBroadcast(intent);

                }
            }

            @Override
            public void onError(@NotNull Download download) {
                final Error error = download.getError();
                final Throwable throwable = error.getThrowable(); //can be null
                if (error == Error.UNKNOWN && throwable != null) {
                    Log.d("Fetch", "Throwable error", throwable);
                }
            }

            @Override
            public void onProgress(@NotNull Download download, long etaInMilliSeconds, long downloadedBytesPerSecond) {

                if(notificationBuilder != null) {
                    Log.e("DESCARGANDO", "Progreso: " + download.getProgress());
                    String progreso = download.getProgress() + "% - " + getBytesToMBString(download.getDownloaded()) + "/" + getBytesToMBString(download.getTotal()) + "";

                    notificationBuilder.setContentTitle(download.getTag());
                    notificationBuilder.setContentText(progreso);
                    notificationBuilder.setProgress((int) download.getTotal(), (int) download.getDownloaded(), false);
                    notificationBuilder.setOngoing(false);
                    Intent intents = new Intent(getApplicationContext(), Descargas.class);
                    PendingIntent pendingIntent = PendingIntent.getActivity(getApplicationContext(), 0,
                            intents, PendingIntent.FLAG_CANCEL_CURRENT);
                    notificationBuilder.setContentIntent(pendingIntent);

                    mNotifyManager.notify(download.getId(), notificationBuilder.build());
                }
                intent.setAction(TabDescargas.mBroadcastStringAction);
                intent.putExtra("UpdateNotify","Update");

                sendBroadcast(intent);

            }

            @Override
            public void onPaused(@NotNull Download download) {
                if(notificationBuilder != null) {
                    notificationBuilder.setContentText("Descarga pausada")
                            // Removes the progress bar
                            .setProgress(0, 0, false);
                    mNotifyManager.notify(download.getId(), notificationBuilder.build());
                }
                intent.setAction(TabDescargas.mBroadcastStringAction);
                intent.putExtra("FinishedNotify","Update");
                sendBroadcast(intent);
            }

            @Override
            public void onResumed(@NotNull Download download) {
                intent.setAction(TabDescargas.mBroadcastStringAction);
                intent.putExtra("FinishedNotify","Update");
                sendBroadcast(intent);
            }

            @Override
            public void onCancelled(@NotNull Download download) {

                if(notificationBuilder != null) {
                    notificationBuilder.setContentText("Descarga cancelada")
                            // Removes the progress bar
                            .setProgress(0, 0, false);
                    mNotifyManager.notify(download.getId(), notificationBuilder.build());
                }
                intent.setAction(TabDescargas.mBroadcastStringAction);
                intent.putExtra("FinishedNotify","Update");
                sendBroadcast(intent);
            }

            @Override
            public void onRemoved(@NotNull Download download) {

                if(notificationBuilder != null){
                    notificationBuilder.setContentText("Descarga removida")
                            // Removes the progress bar
                            .setProgress(0, 0, false);
                    mNotifyManager.notify(download.getId(), notificationBuilder.build());
                }

                intent.setAction(TabDescargas.mBroadcastStringAction);
                intent.putExtra("FinishedNotify","Update");
                sendBroadcast(intent);
            }

            @Override
            public void onDeleted(@NotNull Download download) {
                notificationBuilder.setContentText("Descarga eliminada")
                        // Removes the progress bar
                        .setProgress(0, 0, false);
                mNotifyManager.notify(download.getId(), notificationBuilder.build());
                intent.setAction(TabDescargas.mBroadcastStringAction);
                intent.putExtra("FinishedNotify","Update");
                sendBroadcast(intent);
            }
        });

    }

    private void sendNotification(Download download, int id) {

    }

    private void sendIntent(Download download, int id) {

    }

    @Override
    public void onTaskRemoved(Intent rootIntent) {

    }
}`

**Comment by tonyofrancis** [comment]
@MotherChickenCOL Thanks for using Fetch.

I think your issue is the request. Right now it’s `final Request request = new Request(url, folder);` it needs to be `final Request request = new Request(url, folder + "/" + fileName);`

If that’s not your question can you please rephase it so I can better understand the issue.

**Comment by MotherChickenCOL** [comment]
Thanks for answering i think i already solved my issue, my issue was that de FetchListener was duplicating rows on my database, i forgot to validate the next thing

 if(request.getId() == download.getId())

As your documentation says, sorry my bad, now im not having any issue, just a question, well actually two.

The first one is would you recommend to limit the downloads? and how much do you think that is an apropiate limit, i mean its like a app to watch series and stuffs, so people can download like 24 chapters of one serie and 24 from another, so maybe this can mess the memory of the android device

And the second one, its, when i close my app the download just stops, i added Start_sticky to the service, do you know how to run that service on backgroud, i mean that at least finish the download if the app get closed?

**Comment by tonyofrancis** [comment]
@MotherChickenCOL You what have to limit the downloads based on what your app users expect and what would be the best performance for your app. Apps like Netflix tends to queue all the downloads and process 3 to 5 downloads at a time. I would say that is an appropriate range.

**Comment by Hashsharma** [comment]
@MotherChickenCOL @tonyofrancis can you please provide fetch downloader with intentservices in an another activity. I am newbie and just begin developing need your support with this problem.
