### ISSUE TITLE
Readme needs updating

### ISSUE THREAD

**Issue by the-kenneth** [tonyofrancis/Fetch#145]
The methods below no longer exist. Can these be set per request anymore?

`request.setPriority(Priority.HIGH);
  request.setNetworkType(NetworkType.WIFI_ONLY);`

**Comment by tonyofrancis** [comment]
@the-kenneth They are still available. Ensure that you are importing the proper classes.
```java
import com.tonyodev.fetch2.NetworkType;
import com.tonyodev.fetch2.Priority;
import com.tonyodev.fetch2.Request;
```
```java
 final Request initialRequest = new Request(url, filePath);
 initialRequest.setPriority(Priority.HIGH);
 initialRequest.setNetworkType(NetworkType.WIFI_ONLY);
```
