### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by chimzycash** [tonyofrancis/Fetch#146]
Hello...

I came across your amazing project and i wanted to help contribute to your awesome project by using my logo Design Skills to help create a logo for your project... 

I am already working on some ideas... i will update it here for you to give feedback and possibly any change or tweek you may want...

Regards.

**Comment by chimzycash** [comment]
Hello...

Here is my design idea... please do let me know if you want any tweak or change in colour or design. 
You can also share your own idea...

if you find this design good enough and you like it... please do let me know so i can send you all the files including the vector files for your use...

**Comment by tonyofrancis** [comment]
@chimzycash This is awesome!! Thanks for the contribution. The design with the blue background and white text will surly catch everyone's eye. Great Work. Notable credit will be given for your work and contribution! :)

**Comment by tonyofrancis** [comment]
@chimzycash would it also be possible to squeeze this linke somewhere on the big logo? 

Simple, powerful, customizable file download manager library for Android.

**Comment by chimzycash** [comment]
@tonyofrancis i'm really glad you like the design... ;)


do you want the words SIMPLE, POWERFUL, CUSTOMIZABLE FILE DOWNLOAD LIBRARY FOR ANDROID

to be included in the files?

**Comment by chimzycash** [comment]
Like this?



![logo design_fetch_thumbnail 2](https://user-images.githubusercontent.com/37814297/40086170-1ec49c3a-5895-11e8-9a30-f439e36cf8d3.jpg)

**Comment by tonyofrancis** [comment]
Its missing the `Library` work in the statement but it looks great

**Comment by chimzycash** [comment]
@tonyofrancis i have added it...

is there any other thing you would want me to change so i can do it and get all the FILES READY for you to use

![logo design_fetch_thumbnail 2](https://user-images.githubusercontent.com/37814297/40161794-b99a008c-59a9-11e8-96d2-acd6ae610f16.jpg)

**Comment by tonyofrancis** [comment]
@chimzycash This is perfect! At the bottom right you can add `created by: @chimzycash` to the files. I would like others to know that you created it when they see the logo instantly. This Project is open source others need to know your contributed. Thanks.

**Comment by chimzycash** [comment]
@tonyofrancis 
I am really glad you like and accepted the design... and also glad to contribute to your amazing project...

i will prepare all the files including the vector files and upload for your use...

I appreciate the fact that you want me to be recognized as the logo creator :) ... but it wouldn't look great and work well on a logo... 

I will get the files ready for your use...

**Comment by chimzycash** [comment]
The files are ready for your use and merge

Here are the google drive files:
https://drive.google.com/drive/folders/1vn0qWqopQUwCF-WEwRNVTjwO4-7iqb3q?usp=sharing

**Comment by tonyofrancis** [comment]
@chimzycash awesome! I will update the project. Thanks!
