### ISSUE TITLE
Downloads staying on queue

### ISSUE THREAD

**Issue by MotherChickenCOL** [tonyofrancis/Fetch#149]
Hi, first of all i want to thank you a lot!, this library is awesome, its perfect, and a lot of my users are happy now with the download system.

But there  is some users that are saying that the downloads are not working, they sent me screenshots and it  appears like the download doesnt start, it stays in queue for ever, but its weird because in my device it works perfect, and in 15k devices too, there is just like 2% of people that is facing this issue.

So im wondering if someone else have faced this issue, and if you guys have a solution, i dont actually know if the users tried to download the same file more than once and that blocked the system, i really dont know, thats  why im here.

Im sorry for disturbing your peace, and honestly thanks!, this is amazing library

#TeamFetch

**Comment by tonyofrancis** [comment]
@MotherChickenCOL Thanks for using Fetch. What version of Fetch is bundle with your application? The current release is 2.0.0-RC21. I suspect that the users may be trying to download the same request and Fetch may be rejecting it. Fetch now supports RequestOptions that will force an request to enqueue even if its already in Fetch. The previous request will be discarded.  This [thread](https://github.com/tonyofrancis/Fetch/issues/137)  should help with implementing `RequestOptions` with your Fetch configuration and explain how they work. You can also provide your users a setting to delete downloads that have the status of completed, failed, etc. Let me know if any of these solutions work. Awaiting your feedback.
