### ISSUE TITLE
Progress 

### ISSUE THREAD

**Issue by Mahan3340** [tonyofrancis/Fetch#15]
Hi , I Keep logging the progress amount but it will not go up to 100 but the files is already downloaded

**Comment by tonyofrancis** [comment]
Hello @Mahan3340 can you share the download link or example code?

**Comment by Mahan3340** [comment]
Hey , I just deleted the line Checking for the downloadID and Status in onUpdate Listener and its just working fine (don't know if this was the problem) but just there is another quick thing that I would appreciate if you add it soon and that's somehow be able to disable the auto download when pushing new downloads to Fetch instance cause its not working even when I call pause() method just after I push the new file to the queue and it just keeps downloading the first file . 
thanks .

**Comment by tonyofrancis** [comment]
It may be best for you to store your requests in a list. When you are ready for the download to begin, enqueue that list using `fetch.enqueue(list);`

**Comment by Mahan3340** [comment]
Goood ! and wont this act like the normal fetch.enqueue(a single request ) ? I mean starting the download immediately

**Comment by tonyofrancis** [comment]
Yes. Once you enqueue the first download in the list will begin to download.

**Comment by Mahan3340** [comment]
ahaa got it thank you so much
