### ISSUE TITLE
Request Feature 

### ISSUE THREAD

**Issue by DeevD** [tonyofrancis/Fetch#150]
So powerful download manager library bro. Thank for this library .Please add  Custom Field for download object and notification for download status bro.

**Comment by tonyofrancis** [comment]
@DeevD Thanks for using Fetch. The request and download object has a tag field that you can use to add custom data on a download. Example

```java
        final Request newRequest = new Request(url, file);
        newRequest.setGroupId(newGroupId);
        newRequest.setTag("Custom Data. You can use custom json"); // set custom data here

        fetch.enqueue(newRequest, new Func<Download>() {
            @Override
            public void call(Download download) {
                //Enqueued Successfully
                
                download.getTag(); //Get the custom data here
            }
        }, new Func<Error>() {
            @Override
            public void call(Error error) {
                //Error occurred when trying to enqueue.
            }
        });
```

As for notifications, I do not believe that Fetch should handle this. Being that notifications has to be custom to each application, it would be best for the application developer to provide the notifications. The Fetch Listener provides all the callbacks needed to show the right notification.

**Comment by DeevD** [comment]
thank bro can you provide sample for notification in next release version  bro ?

**Comment by tonyofrancis** [comment]
See my previous comment. Fetch will not be implementing notifications.
