### ISSUE TITLE
Downloads completed  not called

### ISSUE THREAD

**Issue by tosam144** [tonyofrancis/Fetch#151]
I enqueue a number of files using 

            mainFetch.enqueue(requestList, new Func<List<? extends Download>>() {
                @Override
                public void call(List<? extends Download> downloads) {

                }
            }, new Func<com.tonyodev.fetch2.Error>() {
                @Override
                public void call(com.tonyodev.fetch2.Error error) {
                    error.getThrowable().printStackTrace();
                }
            });

It works fine and all fines are being downloaded properly. However, I am trying to get notified once all downloads are completed. So I did:

            mainFetch.getDownloadsWithStatus(Status.COMPLETED, new Func<List<? extends Download>>() {
                @Override
                public void call(List<? extends Download> downloads) {

                }
            });

But this function is only called once before the download starts. It never gets called once the downloads are completed. Can you help me?

**Comment by tonyofrancis** [comment]
@tosam144 the `getDownloadsWithStatus` method queries Fetch about the status of downloads at a given time. It is not continuously called.  What you must do is attach a Fetch Listener before enqueuing the downloads. Every time a download completes, the FetchListener's `onCompleted(download)` method is called.

**Comment by tosam144** [comment]
Thanks for the commment. Yes, I have added the Fetch Listener already. So if I have multiple files enqueued,  how do I know that ALL individual downloads have been completed? Do I have to check each individual file in the Listener to the ones enqueued, or how do I know that ALL files are downloaded?

**Comment by tonyofrancis** [comment]
@tosam144 This code should work for what you want to do.
```java
      //Create a new group id for this group of request. Make sure this groupid does not exit in Fetch
        //or else these request will be added to an existing group.
        final int groupId = UUID.randomUUID().toString().hashCode(); 
        final List<Request> requestList = Data.getFetchRequests();
        for (Request request : requestList) {
            request.setGroupId(groupId); //Sets the same group id for the request in the list
        }
        fetch.addListener(new AbstractFetchListener() {
            @Override
            public void onCompleted(@NotNull Download download) {
                
                fetch.getDownloadsInGroupWithStatus(groupId, Status.COMPLETED, new Func<List<? extends Download>>() {
                    @Override
                    public void call(@NotNull List<? extends Download> downloads) {
                        if (downloads.size() == requestList.size()) {
                            //ALL DOWNLOADS HAVE BEEN COMPLETED
                        }
                    }
                });
            }
        });
```

**Comment by tosam144** [comment]
OK, thanks, that is exactly what I have done. It works! Thanks.
