### ISSUE TITLE
question

### ISSUE THREAD

**Issue by DeevD** [tonyofrancis/Fetch#154]
I would like to ask for fetch bro .It can download in background service ?

**Comment by DeevD** [comment]
thank you bro. It really help for me :D

**Comment by zunjae** [comment]
> call Fetch from there to continue downloading.

I've been through every issue here on GitHub and you mention this a lot without specifying what you mean.

Let's say I enqueue a download in WhateverActivity, how do I continue downloading the file through a service? I've already injected a Fetch instance into my Service subclass. What "continue download" method do I need to use?
