### ISSUE TITLE
File slicing

### ISSUE THREAD

**Issue by duncanokeyo** [tonyofrancis/Fetch#155]
Lets assume that we have set slicing count to 5 for split download.. and the server does not support multithreaded download, will fetch fall back to downloading sequentially, or how do we handle this scenerio.

**Comment by tonyofrancis** [comment]
@duncanokeyo Fetch will automatically handle this situation. Fetch first checks if the server responds with Http OK code or Http Partial code. If the server responds with OK then only a single connection is made egnoring the slice count and download will begin from the very start. If the PARTIAL code is returned, then Fetch will open connects totaling the slice count and continue to download where it left off. Fetch also checks if the slice count is different before a download begins. This is to ensure download integrity.

**Comment by duncanokeyo** [comment]
Thanks.... it works

**Comment by duncanokeyo** [comment]
Another concern, is there a callback to show each block progress information, if am downloading using PARALLEL? just like the way IDM does?

**Comment by tonyofrancis** [comment]
The parallel downloader only reports the progress as a whole not in blocks. Would you be able to give me a solid example for reporting each block progress?

**Comment by duncanokeyo** [comment]
i thought it would be a nice feature to add

**Comment by tonyofrancis** [comment]
@duncanokeyo I have not come a cross a solid reason to add this feature that's why I asked. Each new feature adds a burden on the library and I want to ensure that features are not added to the library because they are nice to have but are needed.
