### ISSUE TITLE
Preallocate space

### ISSUE THREAD

**Issue by duncanokeyo** [tonyofrancis/Fetch#158]
does fetch preallocate space  before downloading a file, if not how does it handle situations where there is not enough enough disk space during download

**Comment by tonyofrancis** [comment]
@duncanokeyo Fetch does not preallocate space before downloading. That would be slow and in efficient. Fetch will begin a download and if there is no more space available. The download stops, and its status is changed to `Failed` and the Error returned is `Error.NO_STORAGE_SPACE`.

Example:
```java
         fetch.addListener(new AbstractFetchListener() {
                    @Override
                    public void onError(@NotNull Download download) {
                        if (download.getError() == Error.NO_STORAGE_SPACE) {
                            //The device or sdcard has no storage the download has stopped.
                        }
                    }
                });
```
Resume the failed download after space is made available
```java
fetch.retry(download.getId()); //to retry a failed download continuing where it left off
```
