### ISSUE TITLE
more callbacks 

### ISSUE THREAD

**Issue by duncanokeyo** [tonyofrancis/Fetch#159]
so far i like the library but i think you should add the following callbacks
1) when connecting to the server to fetch resource
2) when there is a drop in connection and we are in waiting state

**Comment by tonyofrancis** [comment]
@duncanokeyo Can you give me a solid use case for adding these methods?.

**Comment by duncanokeyo** [comment]
ok when am displaying these downloads in a listview , i want the user to know the state of each download in a more detailed way. for example, when there is no connectivity, the user should be able to know that the download is waiting for network...

**Comment by tonyofrancis** [comment]
@duncanokeyo The FetchListener provides several callback methods to update the user interface when the state of a download changes. In terms of network connectivity, the Fetch library should not be the one alerting the user interface about network connection status. If `retryOnNetworkGain` is set on Fetch, currently downloading downloads `status` will be changed back to `Queued`, Fetch listeners are notified and Fetch will  resume the downloads when the network becomes available.

**Comment by tonyofrancis** [comment]
@duncanokeyo on second thought it maybe possible to do this with Fetch easily. Let me have a second look and I will update this post.

**Comment by tonyofrancis** [comment]
@duncanokeyo I was able to figure out a way. I will post back when the new version is released.

**Comment by duncanokeyo** [comment]
thanks
