### ISSUE TITLE
Split count

### ISSUE THREAD

**Issue by duncanokeyo** [tonyofrancis/Fetch#160]
Please enable the option of setting file split count on a request object and not Fetch instance... this way i will be able to set different split count variables for different requests

**Comment by tonyofrancis** [comment]
@duncanokeyo Fetch supports both Parallel and Sequential downloading. Adding split count onto the request class will confuse users. The getFileSlicingCount method on the downloader does pass the request object. You can use this information to determine the splitting per request. You can extend HttpUrlConnectionDownloader or the OkHttpDownloader.
