### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by sn32247** [tonyofrancis/Fetch#161]
When a few videos are in the download queue,android Profiler in android studio shows 322.16 MB has been used and the app stops.
java.lang.OutOfMemoryError:Failed to allocate a 48 byte allocation with 3968 free bytes and 3KB until OOM.

**Comment by tonyofrancis** [comment]
@sn32247 What version of Fetch are you using?. Can you replicate? Share logs?. What devices were you testing on?
