### ISSUE TITLE
File changes

### ISSUE THREAD

**Issue by duncanokeyo** [tonyofrancis/Fetch#162]
how does fetch handle a situation where a file that is being downloaded is changed from the server side?

**Comment by tonyofrancis** [comment]
@duncanokeyo what kind of changes? Can you give an example?

**Comment by duncanokeyo** [comment]
Let’s say we a downloading a file  x which has 10mb, then let’s assume the same file on the server has been changed to 20mb.... how does fetch handle such a situation

**Comment by tonyofrancis** [comment]
@duncanokeyo Fetch keeps track of how many bytes have been downloaded so far and it also checks the content length when connected to the server and will update. So if the content length is greater it will download the addition bytes. If the content length is less Fetch will assume that the download has been completed and mark it as complete. I will be looking at implementing ETags soon which will help with this.
