### ISSUE TITLE
Response headers

### ISSUE THREAD

**Issue by Ziejer** [tonyofrancis/Fetch#167]
Hi,
I'm looking for the way to get response headers. In "Download" interface there is only:

 `/** The headers used by the downloader to send header information to`
  `   * the server about a request.*/`
  `  val headers: Map<String, String>`

but it contains only request headers. I need a way to get some from response.

Thanks for any response.

**Comment by tonyofrancis** [comment]
@Ziejer If you are using a version of Fetch older than 2.1.0-RC6, its only possible to get the response headers if you are using the OKHttp downloader and adding an interceptor to the okhttp client. 

If you are using Fetch version 2.1.0-RC6 just released, you have to create a custom HttpDownloader that extends from Downloader or one of it subclasses, and overriding the `onServerResponse(request: ServerRequest, response: Response)` method. The response parameter object contains the server response headers.

Example extending from the OkHttpDownloader and creating custom downloader:
```java
import com.tonyodev.fetch2okhttp.OkHttpDownloader;

public class CustomOkHttpDownloader extends OkHttpDownloader {
        
        @Override
        public void onServerResponse(@NotNull ServerRequest request, @NotNull Response response) {
            //Access response headers and other information here. A header key can have multiple values.
            // Most of the time you only need to access the first one in the list
            Map<String, List<String>> responseHeaders = response.getResponseHeaders();
            List<String> valueList = responseHeaders.get("Content-Length");
            if (!valueList.isEmpty()) {
                long length = Long.parseLong(valueList.get(0));
            }
        }
    }
```
Set custom http downloader on Fetch like this:
```java
  final FetchConfiguration fetchConfiguration = new FetchConfiguration.Builder(this)
                .enableRetryOnNetworkGain(true)
                .setDownloadConcurrentLimit(3)
                .setHttpDownloader(new CustomOkHttpDownloader()) // set custom downloader here
                .build();
  Fetch fetch = Fetch.Impl.getInstance(fetchConfiguration);
```

**Comment by emanzanoaxa** [comment]
But it can be useful to have the response headers saved on the Download object to have the content-type information tied to the download file. To know what type of file it is.
Overriding OkHttpDownloader lets you know that header but you have to manage the relation between the download request and the headers.
