### ISSUE TITLE
Logo offer for Fetch File Downloader

### ISSUE THREAD

**Issue by familqasimov** [tonyofrancis/Fetch#169]
Hi sir. I'm graphics designer. I have studied your work. Your current logo is very good but I think a new simple logo will make you more visible. I would like to offer logo. I can give you all the formats of the design free. If you want I send you PR or a change please specify.

![untitled-1](https://user-images.githubusercontent.com/36432269/41675152-f91c7e76-74d2-11e8-85ae-3cdc857d172f.png)

Good luck everyday...
Best Regard
Famil

**Comment by tonyofrancis** [comment]
@familqasimov I am happy with the current logo. Thanks for taking the time to present another.
