### ISSUE TITLE
Do not replace existing file

### ISSUE THREAD

**Issue by sethchhim** [tonyofrancis/Fetch#170]
Current version `2.1.0-RC7`, issue after upgrading from `2.0.0-RC22`

I enqueue two of the exact same Request:
`D/FetchService: Request(url='omit', file='omit', id=-840885301, groupId=68352, headers={Authorization=Basic Og==}, priority=NORMAL, networkType=ALL, tag=68354)`

`D/FetchService: Request(url='omit', file='omit', id=-840885301, groupId=68352, headers={Authorization=Basic Og==}, priority=NORMAL, networkType=ALL, tag=68354)`

While on `2.0.0-RC22`, the second request would throw `ERROR.REQUEST_ALREADY_EXIST` which is my desired outcome. The issue is  that while on the newer `2.1.0-RC7`, the download starts anew and replaces the existing file. 

I have explored `EnqueueAction` but there is no option for this behavior. Any advice on how to prevent the replace download and throw an error instead?

**Comment by tonyofrancis** [comment]
@sethchhim Released new Fetch version 2.1.0-RC9. Added new Enqueue Action option: EnqueueAction.DO_NOT_ENQUEUE_IF_EXISTING.  Fetch will call the error callback and pass the error: Error.REQUEST_WITH_FILE_PATH_ALREADY_EXIST. 

You will have to set the EnqueueAction.DO_NOT_ENQUEUE_IF_EXISTING option on newly created requests. The default enqueue action for request is still EnqueueAction.REPLACE_EXITING.
