### ISSUE TITLE
Possibility to change URL after expiration

### ISSUE THREAD

**Issue by Ziejer** [tonyofrancis/Fetch#171]
I got something very similar to #26. But I cannot find this method `fetch.updateUrlForRequest` in Fetch2. Is it implemented?

**Comment by tonyofrancis** [comment]
@Ziejer Looking into this. Will update you soon.

**Comment by tonyofrancis** [comment]
@Ziejer I have just pushed a new version of Fetch 2.1.0-RC10. Use the `fetch.updateRequest(oldRequestId, newRequest, callback, callback)` method to update an existing request.

**Comment by rohangho** [comment]
Hi when we are updating the url using  **"fetch.updateRequest(oldRequestId, newRequest, callback, callback) "**
the download is starting again from the beginning.
Is it possible to continue the dowmload from the same place again?
