### ISSUE TITLE
add option

### ISSUE THREAD

**Issue by duncanokeyo** [tonyofrancis/Fetch#173]
add option to add download and let the user download on demand, not enqueing where the download is downloaded automatically

**Comment by tonyofrancis** [comment]
@duncanokeyo Sorry. I do not understand this request.

**Comment by duncanokeyo** [comment]
instead on enqueueing  the download so that it is downloaded automatically, let the download be added to the download list, so that the user can choose to download

**Comment by tonyofrancis** [comment]
@duncanokeyo looking into this issue.

**Comment by duncanokeyo** [comment]
yeah, for example in ADM we have two option when user inputs URL, first option is to start the download,
second is just to add the download in the download list,

**Comment by tonyofrancis** [comment]
@duncanokeyo New version of Fetch released 2.1.0-RC11. This release adds a new boolean field on the Request class called downloadOnEnqueue. If true, Fetch will begin downloading the request when its turn arrives after being enqueued. If false, Fetch will only store the request in the database with a status of Status.None after being enqueued. The Fetch Listener onQueued method will still be called for request that were successfully enqueued with the downloadOnEnqueue == false .

Example:
```java
Request request = new Request(url, file);
request.setDownloadOnEnqueue(false); //true by default.
fetch.enqueue(request, successCallback, errorCallback);

// The request will be added to Fetch but the request will not begin downloading until you call the resume method on the Fetch instance.

fetch.resume(request.getId()); //The request will now be queued for downloading and downloading will begin when its turn arrives in the downloading queue.
```
@duncanokeyo Please let me know if this works well for you.

**Comment by duncanokeyo** [comment]
Thanks alot, but it would be more concise if we store this request in the database with a status of ADDED.

**Comment by tonyofrancis** [comment]
@duncanokeyo Agreed. Working on a revision update
