### ISSUE TITLE
progress report for each block

### ISSUE THREAD

**Issue by duncanokeyo** [tonyofrancis/Fetch#174]
Could we have download status for each block, 
something like this

fun onProgressBlock(download:Download,blockIndex:Int,offset:Long,endBytes:Long)
so that we can debug each block progress...

**Comment by duncanokeyo** [comment]
let me intergrate it, will give you a feedback

**Comment by duncanokeyo** [comment]
thanks alot, it works very well.

**Comment by duncanokeyo** [comment]
Could the block info be persisted in the database, such that we can get the information about each block
for example . also 
ArrayList<BlockInfo>blocks  = fetch.getBlockInfoList();

**Comment by tonyofrancis** [comment]
@duncanokeyo New release version of Fetch 2.1.0-RC13 has a new method `fetch.getDownloadBlocks(downloadId: Int, func: Func<List<DownloadBlock>>)`
