### ISSUE TITLE
Redownload file

### ISSUE THREAD

**Issue by duncanokeyo** [tonyofrancis/Fetch#177]
Add the ability to redownload a file with COMPLETE status
so that we have something like

fetch.redownload(id);

**Comment by tonyofrancis** [comment]
@duncanokeyo I do not understand your issue clearly. Fetch current behavior: If a file is already downloaded/has a status of `COMPLETE`, and you enqueue it again with `request.setEnqueueAction(EnqueueAction.REPLACE_EXISTING);`. The download will start again from the start. Note that is the default behavior.

**Comment by duncanokeyo** [comment]
okay, thanks
