### ISSUE TITLE
Request not successfull

### ISSUE THREAD

**Issue by duncanokeyo** [tonyofrancis/Fetch#178]
Fetch throws request not successful error in this url,
https://medicitvod-vh.akamaihd.net/i/abr/4267/4267_full_en_20180628_RCM_MVengerovMasterclass_def_hd_,720,1030,1450,2110,3010,.mp4.csmil/segment2_4_av.ts?start=0&end=180

**Comment by tonyofrancis** [comment]
@duncanokeyo I was able to download the file fine both with the Okhttp and httpurlConnection downloaders with Fetch. Both Parallel and Sequential mode worked. The file is 3.83MB in size.
