### ISSUE TITLE
download butch , and display progress

### ISSUE THREAD

**Issue by duncanokeyo** [tonyofrancis/Fetch#179]
there are some videos which are split into various chunks and loaded.. these videos usually come with a meta file which shows all the urls that will be loaded. for example you can take a look at this m3u8 file

https://proxy-074.dc3.dailymotion.com/sec(x352c8abc0193ba0d774e7825b3c6260)/video/775/221/402122577_mp4_h264_aac_l2.m3u8

the file will contain several download links.
can you add the ability for fetch to butch download all the urls as one.

**Comment by tonyofrancis** [comment]
@duncanokeyo Solution:
1. Get all the urls from the meta file.
2. Create a request for each link with a different file name or use `EnququeAction.INCREMENT_FILE_NAME`
3. Set the same groupId for each request.
4. Enqueue the list of requests
5. In the attached Fetch Listener `onProgress` and `onComplete` methods check if the `download.groupId` match and update the UI progress accordingly. 
6. After all the downloads complete. Eg (10/10) Merge them into one file if necessary.
7. If you would like Fetch to manage the merged file use `fetch.addCompletedDownload(completedDownload, callback, callback)`

**Comment by ahar** [comment]
Do you know if concurrent limit is per request or per group of requests?

**Comment by tonyofrancis** [comment]
@ahar concurrent limit is per Fetch instance. You can create as many Fetch instances as you would like. All you have to do is change the namespace on the FetchConfiguration builder. See the FetchConfiguration java docs.
