### ISSUE TITLE
App crashing when downloading a file from server

### ISSUE THREAD

**Issue by him2016** [tonyofrancis/Fetch#181]
Hi,
I'm new to this library and was testing it by integrating it into my app. But when I try downloading a file from server the app crashes with message in logcat:
Abort message: 'heap corruption detected by dlmalloc_real'

Please help.. thanks..

**Comment by tonyofrancis** [comment]
@him2016 Can you provide sample code?. The environment you tested in??. More detail is needed to further assist.
