### ISSUE TITLE
Missing callbacks for some operations

### ISSUE THREAD

**Issue by cc-rock** [tonyofrancis/Fetch#184]
Since all operations that fetch exposes perform some database writing, they are all offloaded to a background thread, but not all of them can be passed a callback to be notified that the operation has completed.
All fetch operations should accept an optional callback argument, a function to be called after the operation has completed.
Actually, most of fetch operation cannot be passed a callback, for example freeze, unfreeze, resume, cancel, cancelAll, delete, remove..

**Comment by tonyofrancis** [comment]
@cc-rock Thanks for using Fetch. The methods you mentioned should in fact always execute the intended operation **without fail**. Is there a case where this is not happening?.

**Comment by cc-rock** [comment]
@tonyofrancis it's not about knowing whether the operation has failed or not, but rather knowing WHEN it has completed, in order to proceed with other operations that need the given operation to be completed first, to avoid potential timing conflicts.

**Comment by tonyofrancis** [comment]
Looking into this. Will post back.

**Comment by tonyofrancis** [comment]
@cc-rock Just published Fetch 2.2.0-RC1. It has new methods that take 2 optional callbacks. The changelog is huge so you may want to review it. Looking forward to your feedback.
