### ISSUE TITLE
How I define GET metod request ????

### ISSUE THREAD

**Issue by bryanollivie** [tonyofrancis/Fetch#186]
Some amazon links only accept GET request.

**Comment by tonyofrancis** [comment]
@bryanollivie Fetch sends a get request. Can you explain your issue in detail? Also, you can provide Fetch a custom downloader. See the downloader section in the readme. https://github.com/tonyofrancis/Fetch

**Comment by bryanollivie** [comment]
Hi @tonyofrancis, 
Well... my setup is this. I need to make a download request to an amazon server, I have customized the downloader and made the request that it is fixed as HEAD, not as GET. 
But the amazon server does not accept HEAD.
I saw that in your class"ParallelFileDownloaderImpl" this setting is fixed.
Metod run()
`val openingRequest = getRequestForDownload(initialDownload, HEAD_REQUEST_METHOD)`

My code is:
` override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        val fetchConfiguration = FetchConfiguration.Builder(this)
                .enableRetryOnNetworkGain(true)
                .setDownloadConcurrentLimit(3)
                .setHttpDownloader(getOkHttpDownloader())
                .build()
        Fetch.setDefaultInstanceConfiguration(fetchConfiguration)
}


    private fun getOkHttpDownloader(): OkHttpDownloader {

        val spec = ConnectionSpec.Builder(ConnectionSpec.COMPATIBLE_TLS)
                .tlsVersions(TlsVersion.TLS_1_2)
                .allEnabledTlsVersions()
                .cipherSuites(
                        CipherSuite.TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,
                        CipherSuite.TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,
                        CipherSuite.TLS_DHE_RSA_WITH_AES_128_GCM_SHA256)
                .build()

        val okHttpClient = OkHttpClient.Builder()
                .connectionSpecs(Collections.singletonList(spec))
                .build()


        return OkHttpDownloader(okHttpClient,
                Downloader.FileDownloaderType.PARALLEL)
    }


`

**Comment by tonyofrancis** [comment]
@bryanollivie Ah I see the problem. ParallelFileDownloaderImpl uses the Head request for the initial check to see if the server supports Partial downloading and was suppose to help fix some other issues/performance. What I can do is add a method to Downloader that will check if head is supported for the url.

**Comment by bryanollivie** [comment]
Great @tonyofrancis. Thaks

**Comment by tonyofrancis** [comment]
@bryanollivie Just pushed out a new version of Fetch 2.1.0-RC15. Please let me know if it works well for you. The downloader has a new method `fun getHeadRequestMethodSupported(request: ServerRequest): Boolean` which you can override and return false for urls pointing to a server not supporting the `HEAD` method.
