### ISSUE TITLE
Getting reference of last fragment in viewPager

### ISSUE THREAD

**Issue by zubairehman** [tonyofrancis/Fetch#187]
Hi,
Thanks for such a great library.
I have two pagers one is to show active downloads and one is to show completed ones. I am getting the same data on both of the fragments because reference.get()?.onQueued(download, waitingOnNetwork) is always giving me the reference of last fragment.

Please guide me how to solve the issue. Thanks :)

**Comment by zubairehman** [comment]
Here is my code:
Fragment 1:
`public class QueueFragment extends BaseFragment implements ActionListener {

    //static variables
    private static final int STORAGE_PERMISSION_CODE = 200;
    private static final long UNKNOWN_REMAINING_TIME = -1;
    private static final long UNKNOWN_DOWNLOADED_BYTES_PER_SECOND = 0;
    private static final int GROUP_ID = "listGroup".hashCode();

    //UI variables
    private RecyclerView recyclerView;
    private DownloadFileAdapter mFileAdapter;

    //binding
    FragmentQueueBinding binding;

    //fetch
    private Fetch fetch;

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        binding = DataBindingUtil.inflate(inflater, R.layout.fragment_queue, container, false);
        return binding.getRoot();
    }

    @RequiresApi(api = Build.VERSION_CODES.M)
    @Override
    public void onViewCreated(View view, @Nullable Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);

        initGui();
        fetch = FetchHelper.getInstance().getFetchInstance();
        checkStoragePermissions();
    }

    private void initGui() {
        //initialize recycler view
        recyclerView = binding.rvQueuedFiles;
        recyclerView.setLayoutManager(new LinearLayoutManager(getContext()));
        recyclerView.addItemDecoration(new DividerItemDecoration(Objects.requireNonNull(getContext()), DividerItemDecoration.VERTICAL));
        mFileAdapter = new DownloadFileAdapter(getActivity(), this);
        recyclerView.setAdapter(mFileAdapter);
    }

    @Override
    public void getExtras(ArrayList<Object> extras) {

    }

    @Override
    public void onResume() {
        super.onResume();
        fetch.getDownloadsInGroup(GROUP_ID, downloads -> {
            Log.i("list size in queue", "onResume: " + downloads.size());

            final ArrayList<Download> list = new ArrayList<>(downloads);
            Collections.sort(list, (first, second) -> Long.compare(first.getCreated(), second.getCreated()));
            for (Download download : list) {
                mFileAdapter.addDownload(download);
            }
        }).addListener(fetchListener);
    }

    @Override
    public void onPause() {
        super.onPause();
        fetch.removeListener(fetchListener);
    }

    @Override
    public void onDestroy() {
        super.onDestroy();
        fetch.close();
    }

    private final FetchListener fetchListener = new AbstractFetchListener() {
        @Override
        public void onQueued(@NotNull Download download, boolean waitingOnNetwork) {
            mFileAdapter.addDownload(download);
            mFileAdapter.update(download, UNKNOWN_REMAINING_TIME, UNKNOWN_DOWNLOADED_BYTES_PER_SECOND);
        }

        @Override
        public void onCompleted(@NotNull Download download) {
            mFileAdapter.update(download, UNKNOWN_REMAINING_TIME, UNKNOWN_DOWNLOADED_BYTES_PER_SECOND);
        }

        @Override
        public void onError(@NotNull Download download) {
            mFileAdapter.update(download, UNKNOWN_REMAINING_TIME, UNKNOWN_DOWNLOADED_BYTES_PER_SECOND);
        }

        @Override
        public void onProgress(@NotNull Download download, long etaInMilliseconds, long downloadedBytesPerSecond) {
            mFileAdapter.update(download, etaInMilliseconds, downloadedBytesPerSecond);
        }

        @Override
        public void onPaused(@NotNull Download download) {
            mFileAdapter.update(download, UNKNOWN_REMAINING_TIME, UNKNOWN_DOWNLOADED_BYTES_PER_SECOND);
        }

        @Override
        public void onResumed(@NotNull Download download) {
            mFileAdapter.update(download, UNKNOWN_REMAINING_TIME, UNKNOWN_DOWNLOADED_BYTES_PER_SECOND);
        }

        @Override
        public void onCancelled(@NotNull Download download) {
            mFileAdapter.update(download, UNKNOWN_REMAINING_TIME, UNKNOWN_DOWNLOADED_BYTES_PER_SECOND);
        }

        @Override
        public void onRemoved(@NotNull Download download) {
            mFileAdapter.update(download, UNKNOWN_REMAINING_TIME, UNKNOWN_DOWNLOADED_BYTES_PER_SECOND);
        }

        @Override
        public void onDeleted(@NotNull Download download) {
            mFileAdapter.update(download, UNKNOWN_REMAINING_TIME, UNKNOWN_DOWNLOADED_BYTES_PER_SECOND);
        }
    };

    @Override
    public void onPauseDownload(int id) {
        fetch.pause(id);
    }

    @Override
    public void onResumeDownload(int id) {
        fetch.resume(id);
    }

    @Override
    public void onRemoveDownload(int id) {
        fetch.remove(id);
    }

    @Override
    public void onRetryDownload(int id) {
        fetch.retry(id);
    }

    @RequiresApi(api = Build.VERSION_CODES.M)
    private void checkStoragePermissions() {
        if (getActivity().checkSelfPermission(android.Manifest.permission.WRITE_EXTERNAL_STORAGE) != PackageManager.PERMISSION_GRANTED) {
            requestPermissions(new String[]{Manifest.permission.WRITE_EXTERNAL_STORAGE}, STORAGE_PERMISSION_CODE);
        } else {
//            enqueueDownloads();
        }
    }

    @Override
    public void onRequestPermissionsResult(int requestCode, @NonNull String[] permissions, @NonNull int[] grantResults) {
        super.onRequestPermissionsResult(requestCode, permissions, grantResults);
        if (requestCode == STORAGE_PERMISSION_CODE && grantResults.length > 0 && grantResults[0] == PackageManager.PERMISSION_GRANTED) {
//            enqueueDownloads();
        } else {
            ((BaseActivity) getActivity()).showMessage(getActivity().getResources().getString(R.string.permission_not_enabled), Toast.LENGTH_LONG);
        }
    }

    private void enqueueDownloads() {
        final List<Request> requests = Data.getFetchRequestWithGroupId(getActivity(), GROUP_ID);
        fetch.enqueue(requests, updatedRequests -> {

        }, error -> ((BaseActivity) getActivity()).showMessage("DownloadListActivity Error: " + error.toString(), Toast.LENGTH_LONG));

    }

    public void addDownload (String url) {
        Request request =  Data.getRequest(getActivity(), url, GROUP_ID);
        fetch.enqueue(request, updatedRequests -> {

        }, error -> ((BaseActivity) getActivity()).showMessage("DownloadListActivity Error: " + error.toString(), Toast.LENGTH_LONG));
    }
}`

Fragment 2:
`public class FinishedFragment extends BaseFragment implements ActionListener {

    //static variables
    private static final int STORAGE_PERMISSION_CODE = 200;
    private static final long UNKNOWN_REMAINING_TIME = -1;
    private static final long UNKNOWN_DOWNLOADED_BYTES_PER_SECOND = 0;

    //UI variables
    private RecyclerView recyclerView;
    private DownloadFileAdapter mFileAdapter;

    //binding
    FragmentFinishedBinding binding;

    //fetch
    private Fetch fetch;

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        binding = DataBindingUtil.inflate(inflater, R.layout.fragment_finished, container, false);
        return binding.getRoot();
    }

    @RequiresApi(api = Build.VERSION_CODES.M)
    @Override
    public void onViewCreated(View view, @Nullable Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        initGui();
        fetch = FetchHelper.getInstance().getFetchInstance();
    }

    private void initGui() {
        //initialize recycler view
        recyclerView = binding.rvFinishedFiles;
        recyclerView.setLayoutManager(new LinearLayoutManager(getContext()));
        recyclerView.addItemDecoration(new DividerItemDecoration(getContext(), DividerItemDecoration.VERTICAL));
        mFileAdapter = new DownloadFileAdapter(getActivity(), this);
        recyclerView.setAdapter(mFileAdapter);
    }


    @Override
    public void getExtras(ArrayList<Object> extras) {

    }

    @Override
    public void onResume() {
        super.onResume();
        //Get all downloads with a status
        fetch.getDownloadsWithStatus(Status.COMPLETED, downloads -> {
            Log.i("list size in finished", "onResume: " + downloads.size());

            //Access downloads that are downloading
            final ArrayList<Download> list = new ArrayList<>(downloads);
            Collections.sort(list, (first, second) -> Long.compare(first.getCreated(), second.getCreated()));
            for (Download download : list) {
                mFileAdapter.addDownload(download);
            }
        }).addListener(fetchListener);
    }

    @Override
    public void onPause() {
        super.onPause();
        fetch.removeListener(fetchListener);
    }

    @Override
    public void onDestroy() {
        super.onDestroy();
        fetch.close();
    }

    private final FetchListener fetchListener = new AbstractFetchListener() {
        @Override
        public void onQueued(@NotNull Download download, boolean waitingOnNetwork) {
            mFileAdapter.addDownload(download);
            mFileAdapter.update(download, UNKNOWN_REMAINING_TIME, UNKNOWN_DOWNLOADED_BYTES_PER_SECOND);
        }

        @Override
        public void onCompleted(@NotNull Download download) {
            mFileAdapter.update(download, UNKNOWN_REMAINING_TIME, UNKNOWN_DOWNLOADED_BYTES_PER_SECOND);
        }

        @Override
        public void onError(@NotNull Download download) {
            mFileAdapter.update(download, UNKNOWN_REMAINING_TIME, UNKNOWN_DOWNLOADED_BYTES_PER_SECOND);
        }

        @Override
        public void onProgress(@NotNull Download download, long etaInMilliseconds, long downloadedBytesPerSecond) {
            mFileAdapter.update(download, etaInMilliseconds, downloadedBytesPerSecond);
        }

        @Override
        public void onPaused(@NotNull Download download) {
            mFileAdapter.update(download, UNKNOWN_REMAINING_TIME, UNKNOWN_DOWNLOADED_BYTES_PER_SECOND);
        }

        @Override
        public void onResumed(@NotNull Download download) {
            mFileAdapter.update(download, UNKNOWN_REMAINING_TIME, UNKNOWN_DOWNLOADED_BYTES_PER_SECOND);
        }

        @Override
        public void onCancelled(@NotNull Download download) {
            mFileAdapter.update(download, UNKNOWN_REMAINING_TIME, UNKNOWN_DOWNLOADED_BYTES_PER_SECOND);
        }

        @Override
        public void onRemoved(@NotNull Download download) {
            mFileAdapter.update(download, UNKNOWN_REMAINING_TIME, UNKNOWN_DOWNLOADED_BYTES_PER_SECOND);
        }

        @Override
        public void onDeleted(@NotNull Download download) {
            mFileAdapter.update(download, UNKNOWN_REMAINING_TIME, UNKNOWN_DOWNLOADED_BYTES_PER_SECOND);
        }
    };

    @Override
    public void onPauseDownload(int id) {
        fetch.pause(id);
    }

    @Override
    public void onResumeDownload(int id) {
        fetch.resume(id);
    }

    @Override
    public void onRemoveDownload(int id) {
        fetch.remove(id);
    }

    @Override
    public void onRetryDownload(int id) {
        fetch.retry(id);
    }
}`

**Comment by duncanokeyo** [comment]
In queuefragment onresume method, you are getting downloads in a particular group, but you are not specifying the kind of downloads you want (status,) so you might display downloads with status complete in query fragment.

**Comment by zubairehman** [comment]
actually in queue fragment i need all statuses but in finished fragment i need only completed. but the problem is when im setting listener and using singleton fetch object, its sending call back to finished fragment with download object so i need to put check everywhere in this case 
`                if(download.getStatus() == Status.COMPLETED) 
`

is there any other way to do it?

**Comment by tonyofrancis** [comment]
@zubairehman in `FinishedFragment`. You fetchListener listener is override all methods with the different status of the download. Use the `AbstractFetchListener` and only override the onComplete method.

```java

final FetchListener fetchListener = new AbstractFetchListener() {

    @Override
    public void onCompleted(@NotNull Download download) {
       // show new completed download here.
    }

     //Ignore other callback methods.
}
```

Let us know if that helped.

**Comment by zubairehman** [comment]
thanks @tonyofrancis its working fine now :)
