### ISSUE TITLE
Not able to update download status flag in Realm DB

### ISSUE THREAD

**Issue by him2016** [tonyofrancis/Fetch#188]
@tonyofrancis I am maintaining the files that need to be downloaded in Realm DB. In the activity class, I have setup the fetch configuration and the listener. From my adapter class, I try to make a Request object and enqueue it. I am not getting a callback when media has been downloaded so that I can update my Realm DB.

Please help..

**Comment by tonyofrancis** [comment]
@him2016 did you attach a FetchListener to the fetch instance and override the onComplete method?.
```java
  final FetchConfiguration fetchConfiguration = new FetchConfiguration.Builder(this)
                .enableRetryOnNetworkGain(true)
                .setDownloadConcurrentLimit(3)
                .setHttpDownloader(new HttpUrlConnectionDownloader(Downloader.FileDownloaderType.PARALLEL))
                .build();

  final Fetch fetch = Fetch.Impl.getInstance(fetchConfiguration);

  fetch.addListener(new AbstractFetchListener() {
        @Override
        public void onCompleted(@NotNull Download download) {
            if (download.getId() == downloadId) {
                //save completed download to realm
            }
        }
    });

``` 
You can also have a fetch listener notify you of the status of all downloads when you attach a listener. Eg:
```java
fetch.addListener(fetchListener, true);
```
