### ISSUE TITLE
Getting file size before starting download

### ISSUE THREAD

**Issue by AminDeveloper** [tonyofrancis/Fetch#190]
Hi
I'd like to ask is it possible to get download file size before starting to download?

**Comment by tonyofrancis** [comment]
@AminDeveloper. The file size is retrieved when Fetch starts downloading the request for the first time.

**Comment by AminDeveloper** [comment]
It is right but I just want to show file size to the user before he decide to start download.
is there a special method like getDownloadInfo() for example for getting file info like file size without starting download?
or would you add it if not?
Thanks

**Comment by tonyofrancis** [comment]
@AminDeveloper let me brain storm and see if there is a simple way of doing this in Fetch and will post back here soon.

**Comment by tonyofrancis** [comment]
@AminDeveloper I will be adding a new method to Fetch called `fun getContentLengthForRequest(request: Request, fromServer: Boolean, func: Func<Long>): Fetch`. Ill post back here soon.

**Comment by tonyofrancis** [comment]
@AminDeveloper  Just published Fetch 2.2.0-RC1. It has new method getContentLengthForRequest(request: Request, fromServer: Boolean, func: Func<Long>): Fetch . Looking forward to your feedback. Changelog in this version is huge. Please review.

**Comment by AminDeveloper** [comment]
Thanks a lot
