### ISSUE TITLE
New progress callback (started)

### ISSUE THREAD

**Issue by duncanokeyo** [tonyofrancis/Fetch#191]
fetch should include a callback that will notify us when a download in the queue is about to be processed. ie started(Download download);

**Comment by tonyofrancis** [comment]
@duncanokeyo yup. Working on a new release and just noticed that there was no started callback. Going to implement one.

**Comment by tonyofrancis** [comment]
@duncanokeyo Just published Fetch 2.2.0-RC1. FetchListener has new method `onStarted(download)`. Looking forward to your feedback. Changelog in this version is huge. Please review.

For your other question. The downloader can provide the fileslice information. Fetch has a new method ` fun getContentLengthForRequest(request: Request, fromServer: Boolean, func: Func<Long>, func2: Func<Error>?): Fetch` that provides the content length
