### ISSUE TITLE
Option to control downloading speed 

### ISSUE THREAD

**Issue by zubairehman** [tonyofrancis/Fetch#192]
Hi,
i have been using this library and its working really good but i want to control the downloading speed and assign a particular download speed to a file being downloading.

e.g. Suppose i have three files and i want to define:

1. File one = 30 KB/s
2. File two = 70 KB/s
3. File three = 100 KB/s

or can i do it globally for all the downloads because i dont want to reserve all my bandwidth for downloads. Please guide me how can i achieve this. Thanks

**Comment by tonyofrancis** [comment]
@zubairehman let me know into this. Fetch at this moment does not support controlling download speeds. Working on the next release now and will post back.

**Comment by tonyofrancis** [comment]
@cc-rock Just published Fetch 2.2.0-RC1. You can now use a custom downloader to limit the download speed of a download. See the readme on how to add a custom downloader then override method `fun getRequestBufferSize(request: ServerRequest): Int` to return a smaller or larger buffersize for each download. Note that the android framework limits the buffersize to max 8192 bytes. The changelog is huge so you may want to review it. Looking forward to your feedback.
