### ISSUE TITLE
setDownloadConcurrentLimit on FetchConfiguration doesn't work 

### ISSUE THREAD

**Issue by zubairehman** [tonyofrancis/Fetch#196]
Hi,

I have been using fetch and trying to change `setDownloadConcurrentLimit` at runtime but it doesn't work. I have set `setDownloadConcurrentLimit = 3` and started 2 downloads, then i changed it to 1 but both files were downloading (one file should wait in a queue). Even i closed my application and next time i initialized FetchConfiguration with `setDownloadConcurrentLimit = 1` but both files are still downloading. Please help me out with this, thanks :)

**Comment by duncanokeyo** [comment]
i think fetch does not support runtime change of concurrentlimit, but possibly you could create a new fetch instance using the same namespace and set the new concurrent limit

**Comment by tonyofrancis** [comment]
@zubairehman . I think I may have spotted a bug. Testing. Also as Duncanokeyo mention,
you can only set the concurrent limit when you create a new Fetch instance but you can have multiple instances of Fetch that has the same namespace open with different concurrent limits. Make sure you close Fetch instances when no longer needed.

**Comment by zubairehman** [comment]
@tonyofrancis  thanks for you feedback, i tried creating new fetch instance with the same namespace but it didn't work :(

**Comment by tonyofrancis** [comment]
its a bug. Just applied a fix. Need to run some tests before pushing out this release. hopefully tomorrow.

**Comment by tonyofrancis** [comment]
@zubairehman Just published Fetch 2.2.0-RC1. This version should have the fix. The changelog is huge so you may want to review it. Looking forward to your feedback.

**Comment by zubairehman** [comment]
@tonyofrancis  thanks for the update, will get back to you on this shortly :)

**Comment by zubairehman** [comment]
i put 2 files on download and i tired creating new instance with `setDownloadConcurrentLimit = 1` but both of them are downloading. I tired closing fetch instance before creating second one but the result is the same :(

**My Code**

**HomeActivity:**

`FetchHelper.getInstance().getFetchInstance().close();
  FetchHelper.getInstance().createFetchConfigInstance(HomeActivity.this);`

**FetchHelper:**

`public class FetchHelper {

    //config
    private static final String FETCH_NAMESPACE = "DefaultNamespace";

    //Declare singleton instance
    private FetchConfiguration fetchConfiguration;
    private static FetchHelper mInstance;

    private FetchHelper(Context context) {

        fetchConfiguration = new FetchConfiguration.Builder(context)
                .enableRetryOnNetworkGain(true)
                .setNamespace(FETCH_NAMESPACE)
                .enableLogging(BuildConfig.DEBUG)
                .setGlobalNetworkType(getGlobalNetworkType(DownloadConfiguration.getInstance().isOnlyWifi()))
                .setDownloadConcurrentLimit(DownloadConfiguration.getInstance().getSimultaneousDownloads())
                .setHttpDownloader(getOkHttpDownloader())
                .build();
        Fetch.Impl.setDefaultInstanceConfiguration(fetchConfiguration);
    }

    public static synchronized void initializeInstance(Context context) {
        if (mInstance == null) {
            mInstance = new FetchHelper(context);
        }
    }

    public static synchronized FetchHelper getInstance() {
        if (mInstance == null) {
            throw new IllegalStateException(FetchHelper.class.getSimpleName() +
                    " is not initialized, call initializeInstance(..) method first.");
        }
        return mInstance;
    }

    public Fetch getFetchInstance() {
        return Fetch.Impl.getInstance(fetchConfiguration);
    }

    public void createFetchConfigInstance(Context context) {
        fetchConfiguration = new FetchConfiguration.Builder(context)
                .enableRetryOnNetworkGain(true)
                .setNamespace(FETCH_NAMESPACE)
                .enableLogging(BuildConfig.DEBUG)
                .setGlobalNetworkType(getGlobalNetworkType(DownloadConfiguration.getInstance().isOnlyWifi()))
                .setDownloadConcurrentLimit(DownloadConfiguration.getInstance().getSimultaneousDownloads())
                .setHttpDownloader(getOkHttpDownloader())
                .build();
        Fetch.Impl.setDefaultInstanceConfiguration(fetchConfiguration);
    }

    private OkHttpDownloader getOkHttpDownloader() {
        final OkHttpClient okHttpClient = new OkHttpClient.Builder().build();
        return new OkHttpDownloader(okHttpClient,
                Downloader.FileDownloaderType.PARALLEL);
    }

    private NetworkType getGlobalNetworkType(boolean isWifiOnly) {
        if (isWifiOnly) {
            return NetworkType.WIFI_ONLY;
        } else {
            return NetworkType.ALL;
        }
    }

}
`

**Comment by tonyofrancis** [comment]
@zubairehman 
Namespace Define: Allows you to create instances of Fetch that reference the same or different databases that store requests/downloads information. Example: You can have a general Fetch downloader and a Fetch downloader for specific purposes like downloading game files.  

In conjunction with the above definition of namespaces, each new Fetch instance can maintain a different FetchConfiguration settings. That means if you have two different FetchConfigurations with the same namespace, new instances of Fetch created is allowed to download requests in the shared waiting queue if it is not correctly downloading. 

With that said an idea came to me. If you want one instance of Fetch to do the downloading and the other instances with the same namespace to receive updates and modify requests, the fetch  configuration needs to set the download limit to 0. In the current version setting the concurrent limit to zero will throw an exception. What I can do is remove that limit. 

A work around right now is to use 1 instance of Fetch with a given namespace.

I would like you feedback on how you understand namespaces and Fetch instances to work so we can improve the library.

**Comment by zubairehman** [comment]
@tonyofrancis 
Thanks for your feedback and explanation about namespaces. Actually what i am trying to do is to have only one instance of fetch and to use it across my app. I have created a singleton fetch instance in my app but when i am trying to change queue size or GlobalNetworkType either my downloading stops (with status downloading) or my queue doesn't get resized.

i tested it in many ways and i think its a bug, please do check and let me know how can i achieve above mentioned scenario by using fetch :)

**Comment by tonyofrancis** [comment]
@zubairehman closing this ticket as we already have a new one open that shows this issue

**Comment by MohammadFneish7** [comment]
Any updates here?!! still facing the same issue
thanks
