### ISSUE TITLE
on progress called after onpause called

### ISSUE THREAD

**Issue by duncanokeyo** [tonyofrancis/Fetch#197]
am experiencing issues, where sometimes onProgressCallback is still called (only once) after i call onpause. usually, the expected behaviour is that when onpause is called, onprogress should not be called..

**Comment by tonyofrancis** [comment]
Testing. I think this is a bug.

**Comment by tonyofrancis** [comment]
@duncanokeyo  Just published Fetch 2.2.0-RC1. This issue should now be fixed in this version. The changelog is huge so you may want to review it. Looking forward to your feedback.
