### ISSUE TITLE
Progress

### ISSUE THREAD

**Issue by burhanaksendir** [tonyofrancis/Fetch#2]
Great, thanks. I have a question:
How to display progress of number of bytes download and % of data download ?

**Comment by tonyofrancis** [comment]
@burhanaksendir version 1.0.0 only reports the progress/percentage of a download request.

```
fetch.addFetchListener(new FetchListener() {
    @Override
    public void onUpdate(long id, int status, int progress, int error) {

        Log.d("fetchDebug","id:" + id + ",status:" + status + ",download percentage:" + progress
             + ",error:" + error);
    }
 });
```

New version 1.0.1 which will be released soon will support download percentage ,downloaded bytes,
and total bytes.

```
fetch.addFetchListener(new FetchListener() {
    @Override
    public void onUpdate(long id, int status, int progress, long downloadedBytes, long fileSize, int error) {

        Log.i("fetchDebug","id: " + id + " downloadedBytes: " + downloadedBytes + " / fileSize: " + fileSize);
    }
});
```
I have pushed this code up to Github and is stable enough to use. Once 1.0.1 is finalized, it will be pushed up to bintray/marven.

**Comment by burhanaksendir** [comment]
Great job! Thank you for your effort. 
Kind regards,
