### ISSUE TITLE
error in verbose

### ISSUE THREAD

**Issue by milindrc** [tonyofrancis/Fetch#20]
com.tonyodev.fetch.exception.EnqueueException: DatabaseHelper already containsFilePath a request with the filePath:

**Comment by tonyofrancis** [comment]
@milindrc This error occurs when a request that was already enqueued is being enqueued again. The FetchService database already contains this exact request and will not enqueue it again. 

I do notice that the logging can be excessive and will try to find the best way to enable and disable logging.

**Comment by milindrc** [comment]
I am getting the error, even for a new url. I even reinstalled the app cleared the cache and did a  reset to everything.

On Mar 28, 2017 8:56 PM, Tonyo Francis <notifications@github.com> wrote:

@milindrc<https://github.com/milindrc> This error occurs when a request that was already enqueued is being enqueued again. The FetchService database already contains this exact request and will not enqueue it again.

I do notice that the logging can be excessive and will try to find the best way to enable and disable logging.

**Comment by tonyofrancis** [comment]
@milindrc That is not the intended behavior.  Are you able to replicate this and share a sample project with me?

**Comment by milindrc** [comment]
Here is the code where I am using it it’s giving an not fatal error at the .enqeue



submissionDownloadAttachment.setOnClickListener(new View.OnClickListener() {
                        @Override
                        public void onClick(View v) {
                            final Fetch fetch = Fetch.getInstance(activity);
                            Request request = new Request("http://" + data.getFileUrl(), Environment.getExternalStorageDirectory() + "/HWjunction/Downloads/", "" + SystemClock.currentThreadTimeMillis());  //data.getId()+data.getFileUrl().substring(data.getFileUrl().indexOf(".")
                            final long downloadId = fetch.enqueue(request);
                            fetch.addFetchListener(new FetchListener() {

                                @Override
                                public void onUpdate(long id, int status, int progress, long downloadedBytes, long fileSize, int error) {

                                    if (downloadId == id && status == Fetch.STATUS_DOWNLOADING) {

                                        Log.d("----", progress + "%");

//                                        ((TopicActivity) activity).getProgressBar().setVisibility(View.VISIBLE);
                                        ((TopicActivity) activity).getProgressBar().setProgress(progress);
//                                        progressBar.setProgress(progress);
                                    } else {
//                                        ((TopicActivity) activity).getProgressBar().setVisibility(View.GONE);
                                        fetch.release();
                                    }
                                }
                            });
                        }
                    });

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by tonyofrancis** [comment]
@milindrc I was not able to replicate this issue.
