### ISSUE TITLE
is there any way to download files from indirect links?

### ISSUE THREAD

**Issue by zubairehman** [tonyofrancis/Fetch#204]
Hi,
 is there any way to download files from indirect links.
e.g. `https://dl.apkmos.com/?dl=423b122b186bac91faf269d8432d393c`

**Comment by tonyofrancis** [comment]
@zubairehman the link you shared is a link to a webpage not a file. Here is the download link `https://dl.apkmos.com/download/dXBsb2Fkcy9BRE0tUHJvXzZfNF8wLUFwa21vc19jb20uYXBr/h/e3d854c9d418ff4af04bd4b8b98fa7ae/sh/333d9ea1a018b416c39ad0e6f87fad9e`. Fetch is able to follow redirected links by default.
