### ISSUE TITLE
EnqueueAction.REPLACE_EXISTING not working

### ISSUE THREAD

**Issue by tuhin10** [tonyofrancis/Fetch#206]
I'm trying to redownload an existing file but getting "UNKNOWN" error from fetch.enqueue.
I'm creating a new request with the same url and file path. If I delete the file first using fetch.delete before calling enqueue it's working fine.

```
 Request request = new Request(url, getFilePath(url, fileName));
        request.setGroupId(grpId);
        request.setEnqueueAction(EnqueueAction.REPLACE_EXISTING); 
        return request;
```

**Comment by tuhin10** [comment]
Just to clarify the both requests are having same url and file path but the request objects are different with exact same properties, I mean all the fields have same value.

**Comment by tonyofrancis** [comment]
Can you share sample code so I can recreate the issue?.

**Comment by tuhin10** [comment]
This is the Fetch global config
```
final FetchConfiguration fetchConfiguration = new FetchConfiguration.Builder(SpaceApp.applicationContext)
                .setDownloadConcurrentLimit(MAX_CONCURRENT_DOWNLOADS)
                .enableAutoStart(false)
                .enableLogging(false)
                .enableRetryOnNetworkGain(false)
                .setProgressReportingInterval(PROGRESS_INTERVAL)
                .setHttpDownloader(new OkHttpDownloader(Downloader.FileDownloaderType.PARALLEL))
                .setNamespace(FETCH_NAMESPACE)
                .build();
        mFetch = Fetch.Impl.getInstance(fetchConfiguration); 
         mFetch.setGlobalNetworkType(NetworkType.ALL); 
        mFetch.addListener(mFetchListener);
```
This is how I enqueue the request. here error.toString() returning "UNKOWN"
```
public void enqueueAndStartDownload(String url, String fileName, int grpId) {
        mFetch.enqueue(getFetchRequest(url, fileName, grpId, true),
                updatedRequests -> {

                },
                error -> {
                    Toast.makeText(this, this.getResources()
                            .getString(R.string.download_err)+". "+error.toString(), Toast.LENGTH_SHORT).show();
                }
        );
    }
```

```
    @NonNull
    private Request getFetchRequest(String url, String fileName, int grpId, boolean autoStart) {
        Request request = new Request(url, getFilePath(url, fileName));
        request.setGroupId(grpId);
        request.setEnqueueAction(EnqueueAction.REPLACE_EXISTING);
        request.setDownloadOnEnqueue(autoStart); //true by default.
        return request;
    }
```

**Comment by abdurahmanadilovic** [comment]
will EnqueueAction.REPLACE_EXISTING remove and start downloading a file that has been already downloaded? Or is it just to control the queue, meaning if an item is queued and not downloaded/started yet then it will replace that item?

**Comment by tuhin10** [comment]
@abdurahmanadilovic My understanding was it will override any existing download but instead its failing to enqueue and throwing "UNKNOWN" error

**Comment by tonyofrancis** [comment]
The existing request whether downloading or queued will be removed first and the new request will be enqueued.

**Comment by tuhin10** [comment]
@tonyofrancis But it is not replacing the existing download. It is failing to enqueue and giving "UNKNOWN" error. Am I missing something?

**Comment by tonyofrancis** [comment]
found the bug working on a fix

**Comment by tuhin10** [comment]
@tonyofrancis It's not working this time the downloaded file is getting deleted then its throwing same "UNKNOWN" error. I uninstalled the app and cleared all previously downloaded files and installed the new apk with updated library.

**Comment by tonyofrancis** [comment]
@tuhin10 are you testing on a device or emulator?

**Comment by tuhin10** [comment]
@tonyofrancis on device Samsung S8 and Huawei Honor 8.

**Comment by tonyofrancis** [comment]
@tuhin10 just released a new version of Fetch. 2.2.0-RC7 with loads of fixes. Please let me know if it fixes this issue for you.

**Comment by tuhin10** [comment]
@tonyofrancis Thanks for the update. I'm getting the same error response with the latest update(RC8). EnqueueAction.INCREMENT_FILE_NAME is working fine it's creating a new file with a incremented name but EnqueueAction.REPLACE_EXISTING is throwing "UNKNOWN" error. Is the new updated working for you?
If I delete the existing download before en queuing its working fine

```
        mFetch.delete(existingDownloadedId);
        mFetch.enqueue(getFetchRequest(url, pageUrl, fileName, grpId, false),
                updatedRequests -> {

                },
                error -> {
                    
                }
        );
```
```
@NonNull
private Request getFetchRequest(String url, String fileName, int grpId, boolean autoStart) {
        Request request = new Request(url, getFilePath(url, fileName));
        request.setGroupId(grpId);
        request.setEnqueueAction(EnqueueAction.REPLACE_EXISTING);
        request.setDownloadOnEnqueue(autoStart); //true by default.
        return request;
    }
```
