### ISSUE TITLE
FetchConfiguration  enableAutoStart is not working

### ISSUE THREAD

**Issue by tuhin10** [tonyofrancis/Fetch#207]
Even if I set enableAutoStart to false once I enqueue any request it's getting downloaded immediately. 

```
FetchConfiguration fetchConfiguration = new FetchConfiguration.Builder(SpaceApp.applicationContext)
                .setDownloadConcurrentLimit(3)
                .enableAutoStart(false)
                .enableLogging(false)
                .enableRetryOnNetworkGain(true) 
                .setHttpDownloader(new OkHttpDownloader(Downloader.FileDownloaderType.PARALLEL))
                .setNamespace(FETCH_NAMESPACE)
                .build();
        mFetch = Fetch.Impl.getInstance(fetchConfiguration);
```

**Comment by tonyofrancis** [comment]
@tuhin10 enableAutoStart only prevents the instance of Fetch from processing requests already managed by Fetch when the new Fetch instance is newly created. The option you are looking for is set on the request. Set `request.setDownloadOnEnqueue(false);` to prevent the default behavior. Note that you will have to call `fetch.resume(downloadId)` or `fetch.retry(downloadId)` to start the download process.

**Comment by tuhin10** [comment]
Got it misunderstood the method. And thanks a lot for this awesome library.
