### ISSUE TITLE
How to enqueue new download synchronously?

### ISSUE THREAD

**Issue by abdurahmanadilovic** [tonyofrancis/Fetch#208]
I need to enqueue a download and I want to return its request id in a blocking way. Is that possible?
I guess I can force it with while(true) and break out of the loop once the success or error is returned, and wrap all of that in a suspendCoroutine in kotlin. Is there a better way?

**Comment by abdurahmanadilovic** [comment]
what about when a new download is successfully added, can call a method which will throw an exception if a request could not be added? Since I am already using fetch on a background thread I would like to perform everything synchronously.

**Comment by tonyofrancis** [comment]
Fetch is fully Async. As you suggested your best bet is to use a while loop to wait.

```java
boolean notCompleted = true;
fetch.doWork(callback {
  //work is done on a background thread. when done set notCompleted to false;
 notCompleted = false;
});
while(notCompleted) {
 //wait
}
```

If you are familiar with RxJava you can use RxFetch/Futures.

**Comment by abdurahmanadilovic** [comment]
this is what I came up with I think others may find this useful, I did not like the while(true) since coroutines already have a suspendedCoroutine, the tricks is to use the runBlocking to block the thread while the suspendedCoroutine is still running. I guess this can be added to the documentation under _Synchronous execution_ section, if you find it interesting

```kotlin
  return runBlocking {
            return@runBlocking suspendCoroutine<Boolean> { continuation ->
                fetchInstance.pause(id.toInt(), Func {
                    continuation.resume(true)
                }, Func {
                    continuation.resume(false)
                })
            }
        }
```

I will close the issue, thanks for the help!

**Comment by vkotovv** [comment]
I've used this code to enqueue synchronously using RxJava Completable:

```
    private fun createEnqueueOperation(requests: List<Request>): Completable {
        return Completable.create {
            fetch.enqueue(requests,
                Func { result ->
                    for ((request, error) in result) {
                        if (error == Error.NONE) {
                            ...
                        } else {
                            ...
                        }
                    }
                    return@Func it.onComplete()
                })
        }
    }

    createEnqueueOperation(requests).blockingAwait()
```
