### ISSUE TITLE
Update file name after download completes.

### ISSUE THREAD

**Issue by tuhin10** [tonyofrancis/Fetch#209]
Is there any way to update the "file" property of an download object if it's in Completed status?
I have tried to update it via  
       
      
        Request oldRequest = oldDownload.getRequest();
        int oldRequestId = oldRequest.getId(); 
        final String url = oldRequest.getUrl();
        final String fileWithPath = oldRequest.getFile();
        int lastIndex = fileWithPath.lastIndexOf('/') + 1;
        String onlyFilePath = fileWithPath.substring(0, lastIndex);
        String onlyFileName = fileWithPath.substring(lastIndex);
        String newFileWithPath = onlyFilePath + "TestName.mp4";
        final int oldGroupId =  oldRequest.getGroupId();
        final Request newRequest = new Request(url, fileWithPath);
        newRequest.setGroupId(oldGroupId);
        newRequest.setEnqueueAction(EnqueueAction.INCREMENT_FILE_NAME);
        mFetch().updateRequest(oldRequestId, newRequest, new Func<Download>() {
            @Override
            public void call(Download updatedDownload) {          }
        }, new Func<Error>() {
            @Override
            public void call(Error error) {        }
        }); 
 
But its not working. What it does I believe it enqueues and tries to download the remaining bytes. But I just want to change the File name in the download object which has already been downloaded.

**Comment by tonyofrancis** [comment]
The update method only allows you to update some changeable fields on the request but not the file name. You can update the file name in your own method and call addCompetedDownload to add a new completed request.

**Comment by tuhin10** [comment]
That is exactly what i was looking for thanks.
