### ISSUE TITLE
Parallel download

### ISSUE THREAD

**Issue by sanatyanky1988** [tonyofrancis/Fetch#21]
download not allowed in parallel only one download at a time.

**Comment by tonyofrancis** [comment]
@sanatyanky1988 It is something I am looking into, and hoping to integrate in the next release.

**Comment by sanatyanky1988** [comment]
great work!! any plans for next release soon?

**Comment by tonyofrancis** [comment]
@sanatyanky1988 Ill have to do extensive testing before integrating such a change and that may take time. But I will keep this issue open until the next release and will post back here. I am hoping to do so very soon.

**Comment by tonyofrancis** [comment]
@sanatyanky1988 Parallel Downloads have now been added to Fetch 1.1.0. Check out the Readme, App Sample and Fetch Documentation.
