### ISSUE TITLE
Calling start on file server that has been shutdown?

### ISSUE THREAD

**Issue by Karuhanga** [tonyofrancis/Fetch#210]
Does the api allow calling `fileServer.start();` to restart a File Server that has been shutdown via `fileServer.shutDown();` or after a timeout?

P.S: This is a stackoverflow kind of question except I can't seem to find the `fetch2` tag, hence resorting to this.

**Comment by tonyofrancis** [comment]
After calling the shutDown method you will not be able to restart the server calling the start method. You have to get a new instance and call start.

**Comment by Karuhanga** [comment]
alright then. thanks. please look into creating a fetch SO fetch2 tag.
