### ISSUE TITLE
request.setEnqueueAction(EnqueueAction.REPLACE_EXISTING)

### ISSUE THREAD

**Issue by Ramkesh9** [tonyofrancis/Fetch#214]
I used request.setEnqueueAction(EnqueueAction.REPLACE_EXISTING); but this is not working for my case,
 i want to download again (Re-download) the same files for some reasons. but when i going to re-download same files from same url , then it is actually not downloading , showing only progress bar. but without any progress . i am using rx-fetch to download multiple file with enqueue.
i am following your sample to get expected results and what i did in my app.

app.gradle
    implementation "com.tonyodev.fetch2rx:fetch2rx:2.2.0-RC4"

App.java  (application class)

final FetchConfiguration fetchConfiguration = new FetchConfiguration.Builder(this)
                .enableRetryOnNetworkGain(true)
                .setDownloadConcurrentLimit(3)
                .setHttpDownloader(new    HttpUrlConnectionDownloader(Downloader.FileDownloaderType.PARALLEL))
                .build();
        Fetch.Impl.setDefaultInstanceConfiguration(fetchConfiguration);
        RxFetch.Impl.setDefaultRxInstanceConfiguration(fetchConfiguration);

and this for making queue of urls 

GameFilesActivity.class 

 request.setPriority(Priority.HIGH);
 mListRequests.add(request);
 requestId = request.getId();

i just want to remove saved request id from your server and want to download again . please help me urgently 
thanx for awsome library.

**Comment by Ramkesh9** [comment]
if i unistalling the app and re-install again and also deleting files from internal memory , then it is downloading the files again otherwise not ?

**Comment by tuhin10** [comment]
@abdurahmanadilovic I think by cancel you are referring to remove(int id)

**Comment by tonyofrancis** [comment]
found the bug working on a fix

**Comment by Ramkesh9** [comment]
@tonyofrancis thanx for review, please fix this bug 👍

**Comment by Ramkesh9** [comment]
@tonyofrancis  actually i have some urgency's of work, so if you are able fix it in asap ,then it would be big help for me :)

**Comment by Ramkesh9** [comment]
i also tried to opt :

 if (completedFiles == totalFiles) {
                     
            rxFetch.removeAll();
            fetch.remove(requestId);
            rxFetch.remove(requestId);
        } 

====
with 
requestId = request.getId();
request.setEnqueueAction(EnqueueAction.REPLACE_EXISTING);
=====
 the coming request id is : -238833965

and response is coming as :

android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: requests._id (code 1555)
and also decoded value message : REQUEST_WITH_ID_ALREADY_EXIST

please check it and let me know if any fix you have found :)
Thanx

**Comment by tonyofrancis** [comment]
@Ramkesh9  Just released Fetch 2.2.0-RC5 with this fix. Please let me know if it works well for you.

**Comment by Ramkesh9** [comment]
Yes, off course i will let you know within few hours, it was nice to see you fix the bug instantly,

**Comment by tonyofrancis** [comment]
@Ramkesh9 Which enqueue method are you using. `fetch.enqueue(request, func, func)` or `fetch.enqueue(requestList, func, func)`?. If you are using the second method and a request in the list does not have replace existing all the others will fail. If you want to send your full code to me via email. you can get my email on my profile. That way I can better help.

**Comment by tonyofrancis** [comment]
@Ramkesh9 I was finally able to replicate your actual issue. The error occurs when you have a list of requests that contains two or more request with the same url and file and you use `fetch.enqueue(requestList, func, func)`. I have a fix and it will make it in RC6. The work around right now is to use the `fetch.enqueue(request, func, func)` and enqueue each request 1 at a time.

**Comment by tonyofrancis** [comment]
@Ramkesh9 Just released Fetch 2.2.0-RC6 with fixes. Please let me know if it works well for you.
