### ISSUE TITLE
Handle manual deletion of downloaded files.

### ISSUE THREAD

**Issue by tuhin10** [tonyofrancis/Fetch#215]
In the current implementation if we manually delete a successfully downloaded file the status of the "Download" object returned as "Failed" from Fetch. And if you en-queue the same request it directly goes to "Completed" status without actually downloading the file again. Will it be possible to add a check and if the file is not present in the system start the download again once en-queue with same Request object.

**Comment by tonyofrancis** [comment]
@tuhin10 I think this issue is related to the Enqueue.Action issue. About to push a fix up. Will post back in the next few mins

**Comment by tonyofrancis** [comment]
@tuhin10 Just released Fetch 2.2.0-RC5 with this fix. Please let me know if this release fixes this issue.

**Comment by tonyofrancis** [comment]
@tuhin10 I just tried replicating this issue on 2.2.0-RC5 and was not able to get it to happen. Can you share sample code that causes this issue?. If it happening on emulators or devices?

**Comment by tuhin10** [comment]
@tonyofrancis I am testing on device.

```
public void enqueueAndStartDownload(String url, String fileName, int grpId, int existingDownloadedId) {
      
        mFetch.enqueue(getFetchRequest(url, fileName, grpId, true),
                updatedRequests -> {

                },
                error -> {
                    Toast.makeText(this, error.toString(), Toast.LENGTH_SHORT).show();
                }
        );
    }
```

```
 @NonNull
    private Request getFetchRequest(String url, String fileName, int grpId, boolean autoStart) {
        Request request = new Request(url, getFilePath(url, fileName));
        request.setGroupId(grpId);
        request.setEnqueueAction(EnqueueAction.REPLACE_EXISTING);
        request.setDownloadOnEnqueue(autoStart); //true by default.
        return request;
    }
```
I'm not user if I need to get the `Request`  object from the Fetch and setEnqueueAction as EnqueueAction.REPLACE_EXISTING. Something like

   ```
mFetch.getDownload(existingDownloadedId, new Func2<Download>() {
            @Override
            public void call(@Nullable Download result) {
                Request request = result.getRequest();
                request.setEnqueueAction(EnqueueAction.REPLACE_EXISTING);
                request.setDownloadOnEnqueue(autoStart); //true by default.
            }
        });
```

**Comment by tonyofrancis** [comment]
@tuhin10 just released a new version of Fetch. 2.2.0-RC7 with loads of fixes. Please let me know if it fixes this issue for you.

**Comment by tuhin10** [comment]
@tonyofrancis Thanks for the update. Unfortunately I'm getting the same error response with the latest update(RC8). EnqueueAction.INCREMENT_FILE_NAME  is working fine it's creating a new file with a incremented name but EnqueueAction.REPLACE_EXISTING is throwing "UNKNOWN" error. Is the new updated working for you?

**Comment by tonyofrancis** [comment]
If you are still encountering this issue. Please try the newer version of Fetch with lots of fixes.

**Comment by ClarkXP** [comment]
Iḿ having the same error. With a breakpoint in Error callback I can see that the exception is: `java.lang.IllegalArgumentException: Unknown URL file:///data/user/0/<appId>/cache/<folder>/<fileName>`

**Comment by ClarkXP** [comment]
Following her stacktrace when you are using EnqueueAction.REPLACE_EXISTING, fetch try to delete a file that not exists because the manual deletion, Causing this error in method StorageResolverHelper.deleteFile: Line 137

**Comment by amin-amini** [comment]
From my experience, this issue still exists in `xfetch2 version: 3.1.6` and as I've seen (I don't know why) but that file will be created with the length of 0 and this is how I managed to fix it :

```
FetchConfiguration.Builder(get())
            .setStorageResolver(object : DefaultStorageResolver(appContext, getFileTempDir(appContext)){
                override fun fileExists(file: String): Boolean {
                    val superVal = super.fileExists(file)
                    if(superVal){
                        val f = Uri.parse(file).toFile()
                        if(!f.exists() || f.length() == 0L){
                            return false
                        }
                    }
                    return superVal
                }
            })
            .build()
```
