### ISSUE TITLE
2.2 version, use RxFetch , can not Paused.

### ISSUE THREAD

**Issue by runylin** [tonyofrancis/Fetch#216]
implementation "com.tonyodev.fetch2rx:fetch2rx:2.2.0-RC5" 
After I call fetch.pause(request.getId()) , but it keep download.  The log below:
```
    D/debug: onStarted
    D/debug: onDownloadBlockUpdated
    D/debug: onDownloadBlockUpdated
    D/debug: onProgress 17
    D/debug: pause
    D/debug: onDownloadBlockUpdated
    D/debug: onProgress 39
    D/debug: onDownloadBlockUpdated
    D/debug: onProgress 77
    D/debug: onDownloadBlockUpdated
    D/debug: onProgress 100
    D/debug: onCompleted
```

And before , the project  implementation "com.tonyodev.fetch2rx:fetch2rx:2.1.0-RC15" , use the same sample code , after call fetch.pause(request.getId()), it can work. 

@tonyofrancis , I don't know where to go wrong.  Can U check this problem？Thanks a lot

**Comment by tonyofrancis** [comment]
@runylin I do not understand the issue. Please restate the whole issue here.

**Comment by runylin** [comment]
This is the code:

package com.example.linrunyu.testdownload;

import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.util.Log;
import android.view.View;
import android.widget.Button;
import com.tonyodev.fetch2.Download;
import com.tonyodev.fetch2.Error;
import com.tonyodev.fetch2.FetchConfiguration;
import com.tonyodev.fetch2.FetchListener;
import com.tonyodev.fetch2.Request;
import com.tonyodev.fetch2core.DownloadBlock;
import com.tonyodev.fetch2rx.RxFetch;
import org.jetbrains.annotations.NotNull;
import java.util.List;

public class MainActivity extends AppCompatActivity implements View.OnClickListener{
    private RxFetch fetch;
    private  String url = "xxx";
    private String file = "xxx";
    private String TAG = "debug";

    private Request request = null;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        Button start = findViewById(R.id.start);
        Button pause = findViewById(R.id.pause);
        Button resume = findViewById(R.id.resume);
        start.setOnClickListener(this);
        pause.setOnClickListener(this);
        resume.setOnClickListener(this);
        initDownload();
        initDownloadListener();
    }

    private void initDownload(){
        FetchConfiguration fetchConfiguration = new FetchConfiguration.Builder(this)
                .setDownloadConcurrentLimit(3)
                .build();

        fetch = RxFetch.Impl.getRxInstance(fetchConfiguration);

    }

    private void initDownloadListener(){
        FetchListener fetchListener = new FetchListener() {
            @Override
            public void onStarted(Download download, List<? extends DownloadBlock> list, int i) {
                Log.d(TAG,"onStarted");
            }

            @Override
            public void onDownloadBlockUpdated(Download download, DownloadBlock downloadBlock, int i) {
                Log.d(TAG,"onDownloadBlockUpdated");
            }

            @Override
            public void onError(Download download, Error error, Throwable throwable) {
                Log.d(TAG,"onError");
            }

            @Override
            public void onWaitingNetwork(Download download) {
                Log.d(TAG,"onWaitingNetwork");
            }

            @Override
            public void onAdded(Download download) {
                Log.d(TAG,"onAdded");
            }

            @Override
            public void onQueued(@NotNull Download download, boolean waitingOnNetwork) {
                Log.d(TAG,"onQueued");
            }

            @Override
            public void onCompleted(@NotNull Download download) {
                Log.d(TAG,"onCompleted");
            }



            @Override
            public void onProgress(@NotNull Download download, long etaInMilliSeconds, long downloadedBytesPerSecond) {
                Log.d(TAG,"onProgress " + download.getProgress());
            }

            @Override
            public void onPaused(@NotNull Download download) {
                Log.d(TAG,"onPaused");
            }

            @Override
            public void onResumed(@NotNull Download download) {
                Log.d(TAG,"onResumed");
            }

            @Override
            public void onCancelled(@NotNull Download download) {
                Log.d(TAG,"onCancelled");
            }

            @Override
            public void onRemoved(@NotNull Download download) {
                Log.d(TAG,"onRemoved");
            }

            @Override
            public void onDeleted(@NotNull Download download) {
                Log.d(TAG,"onDeleted");
            }
        };

        fetch.addListener(fetchListener);
    }


    @Override
    public void onClick(View view) {
        switch (view.getId()){
            case R.id.start:
                Log.d(TAG,"start");
                request = new Request(url, file);
                fetch.enqueue(request).asObservable().subscribe();
                break;
            case R.id.pause:
                Log.d(TAG,"pause");
                fetch.pause(request.getId());
                break;
            case R.id.resume:
                Log.d(TAG,"resume");
                fetch.resume(request.getId());
                break;
        }
    }
}

**Comment by tonyofrancis** [comment]
@runylin I was not able to replicate this issue in 2.2.0-RC5. The downloaded callbacks worked as expected. Run the following tests:

1. Make sure that only 1 download is being downloaded. Set the `concurrentDownloadLimit(1)` on the Fetch Configuration.
2. Also log the download id so we can verify that the same download is indead calling the status callbacks in the wrong order.

**Comment by runylin** [comment]
@tonyofrancis I try setDownloadConcurrentLimit(1) on the Fetch Configuration. but it doesn't work also. And the log below .

Are you replicate this issue with **RxFetch** this class?
The same version , when I replace 
```
private RxFetch fetch;
```
with 
```
private Fetch fetch;
```
, It can work normally. 


```
D/debug   ( 6394): onStarted , id : -452749065
D/debug   ( 6394): onDownloadBlockUpdated , id : -452749065
D/debug   ( 6394): press start, id : -452749065
D/debug   ( 6394): onAdded , id : -452749065
D/debug   ( 6394): onQueued , id : -452749065
D/debug   ( 6394): onStarted , id : -452749065
D/debug   ( 6394): onDownloadBlockUpdated , id : -452749065
D/debug   ( 6394): onDownloadBlockUpdated , id : -452749065
D/debug   ( 6394): onProgress -452749065 , progress is 1
D/debug   ( 6394): onDownloadBlockUpdated , id : -452749065
D/debug   ( 6394): onProgress -452749065 , progress is 2
D/debug   ( 6394): press pause, id : -452749065
D/debug   ( 6394): onDownloadBlockUpdated , id : -452749065
D/debug   ( 6394): onProgress -452749065 , progress is 3
D/debug   ( 6394): onDownloadBlockUpdated , id : -452749065
D/debug   ( 6394): onProgress -452749065 , progress is 4
D/debug   ( 6394): onDownloadBlockUpdated , id : -452749065
D/debug   ( 6394): onProgress -452749065 , progress is 5
D/debug   ( 6394): onDownloadBlockUpdated , id : -452749065
D/debug   ( 6394): onProgress -452749065 , progress is 6
```

**Comment by tonyofrancis** [comment]
@runylin Thanks for the logs. Checking into this.

**Comment by tonyofrancis** [comment]
@runylin I was able to replicate the issue using the Parallel downloader and RxFetch. Looking into a fix

**Comment by runylin** [comment]
@tonyofrancis Is there any progress on this issue?

**Comment by tonyofrancis** [comment]
@runylin  just released a new version of Fetch. 2.2.0-RC7 with loads of fixes. Please let me know if it fixes this issue for you. Note there are breaking changes in this release. Please see release notes first.

**Comment by runylin** [comment]
@tonyofrancis this issue still exist on 2.2.0-RC7 version.

**Comment by runylin** [comment]
@tonyofrancis ,  I have already sent the full sample code to you.  Please receive mail. Thanks for help.

**Comment by tonyofrancis** [comment]
looking into it

**Comment by tonyofrancis** [comment]
@runylin I figured out your issue. The download was not getting paused because the Flowable was not subscribed. If a method returns a Convertible it must be converted to a Flowable or Observable and subscribed in order for the action to take place. 
eg:
```java
     fetch.pause(request.getId()).asObservable().subscribe(new Consumer<Download>() {
                    @Override
                    public void accept(Download download) throws Exception {
                        //update views
                    }
                }, new Consumer<Throwable>() {
                    @Override
                    public void accept(Throwable throwable) throws Exception {
                        //handle error
                    }
                });
```

**Comment by runylin** [comment]
@tonyofrancis get it. Thanks for your answer.
