### ISSUE TITLE
download blocks

### ISSUE THREAD

**Issue by duncanokeyo** [tonyofrancis/Fetch#218]
` public void onStarted(Download download, List<? extends DownloadBlock> list, int i)`

is totaldownloadblocks always equal to the downloadblock size? or there are some situations which can render this to be false?

**Comment by duncanokeyo** [comment]
And could you please shed more light on the blocks returned by fetch.getDownloadBlocks  and blocks returned in onstart?

**Comment by tonyofrancis** [comment]
@duncanokeyo There are two situations that the totalDownloadblocks value can change.

1. If you change the sliceCount with a custom downloader. The next time Fetch tried to resume downloading the file using the Parallel FileDownloader and the slice count is different from the previous slice count, Fetch has to recompute and download all the blocks from the beginning. 
2. When Fetch tries to resume a download using the Parallel FileDownloader and It cannot find the previous sliceCount information.(very rare)

**Comment by tonyofrancis** [comment]
yup
