### ISSUE TITLE
How to re download file?

### ISSUE THREAD

**Issue by bobongski** [tonyofrancis/Fetch#22]
Hi,

Nice fetcher by the way I have an error:
com.tonyodev.fetch.exception.EnqueueException: DatabaseHelper already containsFilePath a request with the filePath:

How can I re download file using this fetcher? thanks

**Comment by tonyofrancis** [comment]
@bobongski To re download the file at the same filePath, you must first delete the existing request by calling `fetch.remove(id)`. If you do not have/saved the download ID, you can call `fetch.get(request)`. This method will return a RequestInfo object if Fetch contains the request. You can then call `fetch.remove(requestInfo.getId())` to delete the request. See the JavaDocs for more on the get methods supported by Fetch.

**Note**: The FilePath is the location on the device where Fetch will save the downloaded file. Fetch will never override an existing file. If you do not want to delete an existing request, simply append a unique identifier to the filePath. eg: `/storage/downloads/_todaysDate_sampleFile.txt`
