### ISSUE TITLE
How To use in webview ?

### ISSUE THREAD

**Issue by arifbillah24** [tonyofrancis/Fetch#222]
Dear Sir,

        How to use webview  in fetch ?

**Comment by tonyofrancis** [comment]
@arifbillah24 I am not sure what what you are asking. Please restate your question.

**Comment by arifbillah24** [comment]
actually i am use android webview application now i am use android internal download manager ..
How to integrate fetch download manager in webview application ?

**Comment by tonyofrancis** [comment]
@arifbillah24 its easy to replace the download manager. Have a look at the sample apps for examples

**Comment by arifbillah24** [comment]
But sample url you use arraylist<string>... when any users click webview links automatical download 
Files  how to replace into sampleurl ...?

**Comment by arifbillah24** [comment]
public boolean shouldOverrideUrlLoading(WebView view, String url) {


                if (url.contains("/download/")) {

                    FetchConfiguration fetchConfiguration = new FetchConfiguration.Builder(activitywebview.this)
                            .setDownloadConcurrentLimit(3)
                            .build();

                    fetch = Fetch.Impl.getInstance(fetchConfiguration);

                    String surl = mywebview.getUrl();
                    String sfile = getFilePath(url);

                    final Request request = new Request(surl, sfile);
                    request.setPriority(Priority.HIGH);
                    request.setNetworkType(NetworkType.ALL);
                    request.addHeader("clientKey", "SD78DF93_3947&MVNGHE1WONG");

                    fetch.enqueue(request, updatedRequest -> {
                        Toast.makeText(getApplicationContext(),"Download Added" , Toast.LENGTH_LONG).show();
                    }, error -> {
                        Toast.makeText(getApplicationContext(),"Download Error" , Toast.LENGTH_LONG).show();
                    });


                }


                return false;
            }


your sample code ................


 public static final String[] sampleUrls = new String[]{
            "http://speedtest.ftp.otenet.gr/files/test100Mb.db",
            "http://download.blender.org/peach/bigbuckbunny_movies/BigBuckBunny_640x360.m4v",
            "http://media.mongodb.org/zips.json", "http://www.example/some/unknown/123/Errorlink.txt",
            "http://storage.googleapis.com/ix_choosemuse/uploads/2016/02/android-logo.png",
            "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"};

    private activitywebview() {

    }

    @NonNull
    public static List<Request> getFetchRequests() {
        final List<Request> requests = new ArrayList<>();
        for (String sampleUrl : sampleUrls) {
            final Request request = new Request(sampleUrl, getFilePath(sampleUrl));
            requests.add(request);
        }
        return requests;
    }

    @NonNull
    public static List<Request> getFetchRequestWithGroupId(final int groupId) {
        final List<Request> requests = getFetchRequests();
        for (Request request : requests) {
            request.setGroupId(groupId);
        }
        return requests;
    }


how to send request  via webview url ?

**Comment by tonyofrancis** [comment]
@arifbillah24 are you trying to display the download progress to the user?. If you are then you will have to create an ongoing notification that shows the download progress. Attach a FetchListener to the fetch instance(see sample app) and using the listener callbacks to update the ongoing notification. https://developer.android.com/training/notify-user/build-notification

**Comment by arifbillah24** [comment]
Its not my answer sir...i want integrate fetch download manager like adm .....

**Comment by tonyofrancis** [comment]
@arifbillah24 I am unclear as to what you are trying to achieve apart from wanting to integrate Fetch in your app. The sample app and previous issue here have lots of information that will guide you in the right direction.
