### ISSUE TITLE
option to start fetch when listeners are attached

### ISSUE THREAD

**Issue by duncanokeyo** [tonyofrancis/Fetch#223]
lets say i am downloading file A, then i close the service, the file will have a status of DOWNLOADING. 
then i start the download service, fetch will continue downloading the file but in this case i some callbacks will not be called since i attach the listener after` Fetch.Impl.getInstance(fetchConfiguration);`
there should be an option where fetch will autostart once a listener has been attached so that we capture all information from the callbacks

**Comment by tonyofrancis** [comment]
@duncanokeyo looking into this

**Comment by tonyofrancis** [comment]
@duncanokeyo  just released a new version of Fetch. 2.2.0-RC7 with loads of fixes. Please let me know if it fixes this issue for you. Note there are breaking changes in this release. Please see release notes first.

**Comment by tonyofrancis** [comment]
fetch 2.2.0-RC8 has been released with fixes

**Comment by duncanokeyo** [comment]
works as expected..
