### ISSUE TITLE
Fetch returns status FAILED

### ISSUE THREAD

**Issue by duncanokeyo** [tonyofrancis/Fetch#224]
am implementing group downloads, where after downloading the files, i merge them, so i nolonger need the old files, i delete them (not using fetch), but now fetch fetch returns status of failed on all group downloads, yet all the downloads were successfully completed... 
i think Failed should only be when the download has failed or disk errors occuring , but not when the file has been deleted AFTER download is complete,

**Comment by tonyofrancis** [comment]
@duncanokeyo making fixes. plan on releasing a new version tomorrow with lots of improvements

**Comment by tonyofrancis** [comment]
@duncanokeyo  just released a new version of Fetch. 2.2.0-RC7 with loads of fixes. Please let me know if it fixes this issue for you. Note there are breaking changes in this release. Please see release notes first.

**Comment by duncanokeyo** [comment]
Not working as intended, when i create fetch instance, i set autostart as false, then i fetch all downloads and display in a list, after this, i attach listener with autostart enabled... but now when i start a new download it stays with state QUEUED forever without startting download

 ```
final FetchConfiguration fetchConfiguration = new FetchConfiguration.Builder(this)
                .enableRetryOnNetworkGain(true)
                .enableAutoStart(false)
                .enableLogging(BuildConfig.DEBUG)
                .enableMd5Check(false)
                .setNamespace("singleDownloads")
                .setDownloadConcurrentLimit(2).setProgressReportingInterval(500)
                .setHttpDownloader(new DownloadHelper(Downloader.FileDownloaderType.PARALLEL, false))
                .build();
```

```
 if(isSingleFetchInstanceValid()) {
                    fetch.addListener(singleDownloadListener,false,true);
                }
```

**Comment by tonyofrancis** [comment]
@duncanokeyo I was able to replicate this bug and have a fix.

**Comment by tonyofrancis** [comment]
fetch 2.2.0-RC8 has been released with fixes

**Comment by duncanokeyo** [comment]
works ,
