### ISSUE TITLE
Error in report listeners 

### ISSUE THREAD

**Issue by duncanokeyo** [tonyofrancis/Fetch#225]
So I start a download , and it fails with status REQUEST_NOT_SUCCESSFUL , that’s okay as I intentionally want the download to fail... now in the listener onError(Download download ......
I try to log this download information , specifically the ID and group Id , but they are all 0 
and the status is NONE ... 

Now , when I restart the download service and log status for this specific download I tried , it shows FAILED and I can also see the ID..which is the intended behaviour

**Comment by tonyofrancis** [comment]
@duncanokeyo I was able to replicate this bug. working on a fix.

**Comment by tonyofrancis** [comment]
fixed applied. will be in next release today.

**Comment by tonyofrancis** [comment]
fetch 2.2.0-RC8 has been released with fixes

**Comment by duncanokeyo** [comment]
works as expected , will be doing more testing with other callbacks
