### ISSUE TITLE
onupdate never called

### ISSUE THREAD

**Issue by altaf2892** [tonyofrancis/Fetch#23]
> i just simple implemented this lib as u suggested but on update never be called you can see below code ... and if u might wud say to fetch.release().. so i t also didn't work

```
`public void fetchMethod(String url, String fileName) {
        Toast.makeText(DownloadService.this, "downloading started", Toast.LENGTH_SHORT).show();
        File file = new File(Environment.getExternalStorageDirectory(), File.separator + getString(R.string.app_name));
        if (!file.exists()) {
            file.mkdirs();
        }
        new Fetch.Settings(getApplicationContext())
                .setAllowedNetwork(Fetch.NETWORK_ALL)
                .enableLogging(true)
                .setConcurrentDownloadsLimit(3)
                .apply();
        Fetch fetch = Fetch.getInstance(this);
        Log.e("check", file.getAbsolutePath() + " " + fileName);
        Request request = new Request(url, file.getAbsolutePath(), File.separator + fileName);
        final long downloadId = fetch.enqueue(request);
        fetch.addFetchListener(new FetchListener() {

            @Override
            public void onUpdate(long id, int status, int progress, long downloadedBytes, long fileSize, int error) {

                if (downloadId == id && status == Fetch.STATUS_DOWNLOADING) {
                    Toast.makeText(DownloadService.this, "downloading   " + progress, Toast.LENGTH_SHORT).show();
                } else {
                    Toast.makeText(DownloadService.this, "no file" + progress, Toast.LENGTH_SHORT).show();
                }
            }
        });
    }`
```

**Comment by leeyc09** [comment]
i think you add fetch listener before fetch enqueue.

**Comment by tonyofrancis** [comment]
@altaf2892 The main reason why the file is not being downloaded in the example you provided is because you are adding a separator before the file name, so your file path ends up having an invalid filePath. You only need to provide the filePath eg: `/storage/downloads` and the file name eg `test.txt` 

example Request:`new request(getCacheDir(),"sample.txt");`

**Comment by altaf2892** [comment]
@leeyc09  it totally cleared in above example that   i have added enqueue  before the onupdate

**Comment by altaf2892** [comment]
@tonyofrancis  i got log from below code
` /storage/sdcard0/VideoDownloader MakeMostOfNow - Find your way with the Data Strong Net.mp4`
**code **
`public void fetchMethod(String url, String fileName) {
        List<Model> contacts = mydb.getAllContacts();

        File file = new File(Environment.getExternalStorageDirectory() + File.separator + getString(R.string.app_name));
        if (!file.exists()) {
            file.mkdirs();
        }
        new Fetch.Settings(getApplicationContext())
                .setAllowedNetwork(Fetch.NETWORK_ALL)
                .enableLogging(true)
                .setConcurrentDownloadsLimit(3)
                .apply();
        Fetch fetch = Fetch.getInstance(this);
        Log.e("check", file.getAbsolutePath() + " " + fileName);
        Request request = new Request(url, file.getAbsolutePath(), fileName);
        final long downloadId = fetch.enqueue(request);

        fetch.addFetchListener(
                new FetchListener() {
                    @Override
                    public void onUpdate(long id, int status, int progress, long downloadedBytes, long fileSize, int error) {

                        if (downloadId == id && status == Fetch.STATUS_DOWNLOADING) {
                            Log.e("update", "downloading");
                        } else if (downloadId == id && status == Fetch.STATUS_NOT_QUEUED) {
                            Log.e("update", "not queued");
                        } else if (downloadId == id && status == Fetch.STATUS_DONE) {
                            Log.e("update", "done");
                        } else if (downloadId == id && status == Fetch.STATUS_ERROR) {
                            Log.e("update", "error");
                        } else if (downloadId == id && status == Fetch.STATUS_PAUSED) {
                            Log.e("update", "paused");
                        } else if (downloadId == id && status == Fetch.STATUS_REMOVED) {
                            Log.e("update", "rem,oved");
                        } else if (downloadId == id && status == Fetch.ERROR_ENQUEUE_ERROR) {
                            Log.e("update", "enque error");
                        } else if (downloadId == id && status == Fetch.ERROR_FILE_ALREADY_CREATED) {
                            Log.e("update", "already file created");
                        } else {
                            Log.e("update", "error  " + error);

                        }
                        if (downloadId == id && status == Fetch.STATUS_ERROR) {

                            switch (error) {
                                case Fetch.ERROR_NO_STORAGE_SPACE: {
                                    //take action1
                                    Log.e("found", error + "");
                                    break;
                                }
                                case Fetch.ERROR_HTTP_NOT_FOUND: {
                                    //take action2
                                    break;
                                }
                                case Fetch.ERROR_UNKNOWN: {
                                    //take action3
                                    break;
                                }
                                default:
                                    //take general action


                            }
                        }
                    }
                }

        );
        Model model = new Model();
        model.setDownloadId((int) downloadId);
        model.setFilename(fileName);
        mydb.addVideo(model);

        for (Model m : contacts) {

            Log.e("model", m.getDownloadId() + " " + m.getFilename());


        }

    }`

**Comment by tonyofrancis** [comment]
@altaf2892 I noticed a few things:

1. You may be trying to enqueue a request that was already enqueued and `fetch.enqueue(id);` is returning a download ID of  -1. This means that the request was not inserted and will not download. **Note**: You cannot have two requests with the same download path. While testing you may want to delete the previous test request by calling `fetch.removeAll();` or appending a unique id to the new file path. For example: `/storage/downloads/todaysData_SampleVideoFile.mp4`;
2. Its best to always attach the FetchListener before performing any operations on fetch.

Example:
```java
  private long downloadId = -1;

    public void downloadFile() {

        final Fetch fetch = Fetch.getInstance(this);

        fetch.addFetchListener(new FetchListener() {
            @Override
            public void onUpdate(long id, int status, int progress, long downloadedBytes, long fileSize, int error) {

                if(id == downloadId) {

                    switch (status) {

                        case Fetch.STATUS_DOWNLOADING: {
                                //do work like update progress
                            break;
                        }
                        case Fetch.STATUS_ERROR: {
                                //Check error and take action. Retry?fetch.retry(downloadId);
                            break;
                        }
                        default:
                            //general action
                    }

                }
            }
        });

        String url = "http://download.blender.org/peach/bigbuckbunny_movies/BigBuckBunny_320x180.mp4";
        Request request = new Request(url,getCacheDir().getAbsolutePath(),System.nanoTime() + "_bunnyVideo.mp4");

        downloadId = fetch.enqueue(request);


        if(downloadId == -1) {
            Log.i("Fetch","Download was not enqueued because it already exists, or no space is available on the device");
        }else {
            //Do other work
            Log.i("Fetch","Request was enqueued successfully. Listen for updates inside a FetchListener");
        }

```

**Comment by altaf2892** [comment]
[new1.txt](https://github.com/tonyofrancis/Fetch/files/931969/new1.txt)
**see text file and i have attached full code maybe i am doing something wrong or something else so plz have look at**

**Comment by altaf2892** [comment]
**what   fetch.remove(id); actually does**

> i call remove method after downloading done but it removes the file (downloaded video from path), i though i would remove  only id from requests  example if i have set max request=3 and already i have requested 2 and i call remove then it make 2 requests available for me.

`start.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {

                    url = bundle.getString("url");
                    dirPath = bundle.getString("filepath");
                    fileName = bundle.getString("filename");
                    final Request request = new Request(url, dirPath, fileName);
                    long downloadId = fetch.enqueue(request);
                    Model model = new Model();
                    model.setDownloadId(downloadId);
                    model.setFilename(fileName);
                    model.setFilePath(dirPath);
                    model.setDuration("00.00");
                    model.setProgress("0");
                    model.setUrl(url);
                    dbHelper.insert(model);

                    list = dbHelper.getAllVideo();
                    for (Model m : list) {
                        Log.e("db", m.getDownloadId() + "  " + m.getFilename() + "  " + m.getFilePath());
                    }

                    fetch.addFetchListener(new FetchListener() {

                        @Override
                        public void onUpdate(long id, int status, int progress, long downloadedBytes, long fileSize, int error) {
                            Log.e("fetch", "update:  " + id);
                            setUpadte( status, id, fetch, progress);


                        }
                    });


                }
            });

        }


    }

    public void setUpadte( int status, long id, Fetch fetch, int progress) {
        List<RequestInfo> requestInfo = fetch.get();
        for (RequestInfo requestInfo1 : requestInfo) {
            if (requestInfo1.getId() == id) {

                switch (status) {
                    case Fetch.STATUS_DOWNLOADING:
                        Log.e("fetch", "downloading:  " + id + " progress  " + progress);
                        break;
                    case Fetch.STATUS_QUEUED:
                        Log.e("fetch", "queued:  " + id + " progress  " + progress);
                        break;
                    case Fetch.STATUS_DONE:
                        Log.e("fetch", "done:  " + id + " progress  " + progress);
                        fetch.remove(id);
                        break;
                    case Fetch.STATUS_NOT_QUEUED:
                        Log.e("fetch", "not queued:  " + id + " progress  " + progress);
                        break;
                    case Fetch.ERROR_REQUEST_ALREADY_EXIST:
                        Log.e("fetch", "already exist:  " + id + " progress  " + progress);
                        break;
                    case Fetch.STATUS_REMOVED:
                        Log.e("fetch", "removed:  " + id + " progress  " + progress);
                        break;
                    case Fetch.ERROR_UNKNOWN:
                        Log.e("fetch", "unknown error:  " + id + " progress  " + progress);
                        break;

                }

            }


        }
    }`
```

**Comment by altaf2892** [comment]
ok now i update get called but i have two question
****

**Comment by altaf2892** [comment]
**please have look at file**

> i simply copy and paste from a class which extends Appcompactactivity  to a class which extends service 
still same problem update never called but download is ongoing..see below both file

[Desktop.zip](https://github.com/tonyofrancis/Fetch/files/933968/Desktop.zip)

**please above zip it having two class files and please soon update  i m just about to finished this task**

**Comment by tonyofrancis** [comment]
@altaf2892 Notice what is happening in your Activity's `onCreate(Bundle)` method. You are creating an instance of Fetch in this method. Once the method returns, Your fetch instance is then claimed by the garbage collector. Your fetch instance needs to be an instance field in your Activity class. The same goes for your Service code.

**Comment by altaf2892** [comment]
if u mean to say is i declare globally fetch and do  fetch = Fetch.getInstance(this);on create or onstartcommand in service if yes then i have tried it bu no luck...

**Comment by tonyofrancis** [comment]
@altaf2892 Have you tired implementing this code and testinh it in a different project? I have been successful in testing all the code you provided and cannot replicate the issue.

**Comment by altaf2892** [comment]
> ok
 i tried it in diff project now i gets updated but when app get destroyed i lose running download file

> i know i have to handle this myself but i ask u to help me to fixed 

> what i have tried is on activty onDestroy metho d i putextra and check it in service method see code for detail
`
```
public class AppService extends Service {
    Fetch fetch;


    @Override
    public void onCreate() {
        super.onCreate();
        if (fetch != null) {
            Log.e("fetch", "oncreate  " + "called");
        }
    }

    @Override
    public int onStartCommand(Intent intent, int flags, int startId) {
        fetch = Fetch.getInstance(this);
        DownloadFile(intent);
        return START_STICKY;
    }

    @Nullable
    @Override
    public IBinder onBind(Intent intent) {
        if (intent != null) {
            Log.d("fetch", "bind  " + intent.getData().toString());
        }
        if (fetch != null) {
            Log.e("fetch", "bind  " + "called");
        }
        return null;
    }

    public void DownloadFile(Intent intent) {

        if (intent == null && intent.getStringExtra("ondestroy").equals("true") || intent != null) {
            Toast.makeText(this, "download restart see log for update", Toast.LENGTH_SHORT).show();
            try {
                fetch.addFetchListener(new FetchListener() {
                    @Override
                    public void onUpdate(long id, int status, int progress, long downloadedBytes, long fileSize, int error) {
                        setUpdate(status, id, fetch, progress);
                    }
                });
            } catch (Exception e) {
                Toast.makeText(this, "Sorry! try again", Toast.LENGTH_SHORT).show();

            }

        } else {

            if (intent != null || !intent.getStringExtra("url").equals(""))
                Toast.makeText(this, "download start see log for update", Toast.LENGTH_SHORT).show();
                Log.e("intent", intent.getStringExtra("url"));
            String url = intent.getStringExtra("url");
            String path = Environment.getExternalStorageDirectory() + File.separator + "/Test";
            final Request request = new Request(url, path, System.nanoTime() + "_bunnyVideo.mp4");
            long downloadId = fetch.enqueue(request);

            fetch.addFetchListener(new FetchListener() {

                @Override
                public void onUpdate(long id, int status, int progress, long downloadedBytes, long fileSize, int error) {
                    Log.e("fetch", "update:  " + id);
                    setUpdate(status, id, fetch, progress);
                }
            });


        }
    }

    public void setUpdate(int status, long id, Fetch fetch, int progress) {
        List<RequestInfo> requestInfo = fetch.get();
        for (RequestInfo requestInfo1 : requestInfo) {
            if (requestInfo1.getId() == id) {

                switch (status) {
                    case Fetch.STATUS_DOWNLOADING:
                        Log.e("fetch", "downloading:  " + id + " progress  " + progress);
                        // setToDb(id, progress);
                        break;
                    case Fetch.STATUS_QUEUED:
                        // setToDb(id, progress);
                        Log.e("fetch", "queued:  " + id + " progress  " + progress);
                        break;
                    case Fetch.STATUS_DONE:
                        // setToDb(id, progress);
                        Log.e("fetch", "done:  " + id + " progress  " + progress);
                        //    fetch.remove(id);
                        break;
                    case Fetch.STATUS_NOT_QUEUED:
                        //  setToDb(id, progress);
                        Log.e("fetch", "not queued:  " + id + " progress  " + progress);
                        break;
                    case Fetch.ERROR_REQUEST_ALREADY_EXIST:
                        // setToDb(id, progress);
                        Log.e("fetch", "already exist:  " + id + " progress  " + progress);
                        break;
                    case Fetch.STATUS_REMOVED:
                        //  setToDb(id, progress);
                        Log.e("fetch", "removed:  " + id + " progress  " + progress);
                        break;
                    case Fetch.ERROR_UNKNOWN:
                        //setToDb(id, progress);
                        Log.e("fetch", "unknown error:  " + id + " progress  " + progress);
                        break;

                }

            }


        }


    }
`
**activity class**
```
`
public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        Intent intent = new Intent(this, AppService.class);
        intent.putExtra("url", "http://download.blender.org/peach/bigbuckbunny_movies/BigBuckBunny_320x180.mp4");
        startService(intent);

    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        Intent intent = new Intent(this, AppService.class);
        intent.putExtra("ondestroy", "true");
        startService(intent);

    }
````

**Comment by tonyofrancis** [comment]
@altaf2892 Being that the library works in your other projects and the listener is working as intended, there is not much I can help with. The issues you are facing seems to be more of an implementation issue within your project.
