### ISSUE TITLE
A connection to https://... was leaked. Did you forget to close a response body? And Is download file running in  background ?

### ISSUE THREAD

**Issue by phukhanhlee** [tonyofrancis/Fetch#230]
When I download a file with Fetch. I didn't set custom okhttpclient

        if (fetch == null){
            FetchConfiguration fetchConfiguration = new FetchConfiguration.Builder(DictBoxApp.getInstance().getApplicationContext())
                    .setDownloadConcurrentLimit(3)
                    .build();

            fetch = Fetch.Impl.getInstance(fetchConfiguration);
        }

fetch.enqueue(request, new Func<Request>() {
                    @Override
                    public void call(@NotNull Request updatedRequest) {

                    }
                }, new Func<Error>() {
                    @Override
                    public void call(@NotNull Error error) {
                        Log.d("error","download_file:"+ error.toString());
                    }
                });

**Comment by tonyofrancis** [comment]
@phukhanhlee Fetch does perform the downloads on a background thread. If you need Fetch to continue downloads when the application closes, you will need to create a service or use the new Work Manager.

Also for `A connection to https://... was leaked` can you replicate and show the logs or sample code???
