### ISSUE TITLE
Enqueue same request twice result into FAILED state with EnqueueAction.REPLACE_EXISTING

### ISSUE THREAD

**Issue by tleveque** [tonyofrancis/Fetch#232]
In my app, the following code may be called several times for same media to download. Depending on the ordering and asynchronous updates, this code is sometimes called twice for the same media in the very small period of time.
In this case, the download in the database becomes as FAILED and FILE_NOT_FOUND error.

final Request request = new Request(url, mediaPath);
request.setDownloadOnEnqueue(true);
request.setEnqueueAction(EnqueueAction.REPLACE_EXISTING);
request.setPriority(Priority.HIGH);
request.setNetworkType(NetworkType.ALL);
request.setTag("media");
MutableExtras extras = Extras.getEmptyExtras().toMutableExtras();
extras.putString(MEDIA_ID_EXTRA_KEY, mediaId);
request.setExtras(extras);
mFetch.enqueue(request, updatedRequest -> {
       Log.i(TAG, "downloads enqueued");
}, error -> {
       Log.e(TAG, "downloads enqueue error", error.getThrowable());
});

I took a look at the source code and the following part of sanitize method seems wrong to me:
                Status.QUEUED -> {
                    if (!fileExist) {
                        downloadInfo.status = Status.FAILED
                        downloadInfo.error = Error.FILE_NOT_FOUND
                        downloadInfo.downloaded = 0L
                        downloadInfo.total = -1L
                        changedDownloadsList.add(downloadInfo)
                        delegate?.deleteTempFilesForDownload(downloadInfo)
                    }
                }
I think that Status.QUEUED should have same processing than Status.ADDED as it may have not started yet when sanitize.

**Comment by tonyofrancis** [comment]
@tleveque I am looking into this. will report back

**Comment by tleveque** [comment]
@tonyofrancis 
I think that problem is more related to ensure target file creation. 
I found the following problem when debugging.
In FetchHandlerImpl, during enqueue the second request (same one), the file has not been created but the previous download does exist in db.

val existingDownload = databaseManager.getByFile(downloadInfo.file)
        if (existingDownload == null) {
            createFileIfPossible(File(downloadInfo.file))
        }
        if (downloadInfo.enqueueAction == EnqueueAction.DO_NOT_ENQUEUE_IF_EXISTING && existingDownload != null) {
            throw FetchException(REQUEST_WITH_FILE_PATH_ALREADY_EXIST)
        } else if (downloadInfo.enqueueAction == EnqueueAction.REPLACE_EXISTING && existingDownload != null) {
            deleteDownloads(listOf(downloadInfo.id))
        } else if (downloadInfo.enqueueAction == EnqueueAction.INCREMENT_FILE_NAME && existingDownload != null) {
            val file = getIncrementedFileIfOriginalExists(downloadInfo.file)
            downloadInfo.file = file.absolutePath
            downloadInfo.id = getUniqueId(downloadInfo.url, downloadInfo.file)
            createFileIfPossible(file)
        }

**Comment by tleveque** [comment]
My app is a priv app and I think that sometimes, there is a problem to create file in app internal storage.
It seems that target cannot be created but Fetch does not log any file creation error.
Could you add a log when file creation does not work ?

fun createFileIfPossible(file: File) {
    try {
        if (!file.exists()) {
            if (file.parentFile != null && !file.parentFile.exists()) {
                if (file.parentFile.mkdirs()) {
                    file.createNewFile()
                }
            } else {
                file.createNewFile()
            }
        }
    } catch (e: IOException) {
    }
}

**Comment by tleveque** [comment]
I was able to workaround the issue by 
1. create target file
2. enqueue if it is a new download, otherwise update existing download

`mFetch.getDownloads(downloads -> {
                Download foundDownload = null;
                for (Download download : downloads) {
                    String curMediaId = getMediaIdOf(download);
                    if (curMediaId != null && curMediaId.equals(mediaId)) {
                        foundDownload = download;
                        break;
                    }
                }
                if (foundDownload == null) {
                    mFetch.enqueue(request, updatedRequest -> {
                        Log.i(TAG, "download enqueued for media " + mediaId);
                    }, error -> {
                        Log.e(TAG, "download enqueue error for media " + mediaId, error.getThrowable());
                    });
                } else {
                    mFetch.updateRequest(foundDownload.getId(), request, updatedRequest -> {
                        Log.i(TAG, "download updated for media " + mediaId);
                    }, error -> {
                        Log.e(TAG, "download updated error for media " + mediaId, error.getThrowable());
                    });
                }
            });`

**Comment by tonyofrancis** [comment]
@tleveque Were you testing on a emulator or physical device? Seems like Fetch enqueue is working correctly. So i'll mark this issue as closed.

**Comment by tonyofrancis** [comment]
@tleveque Just released Fetch 2.2.0-RC11. Downloads status are no longer set to failed if the destination file does not exist.
