### ISSUE TITLE
Download stuck at QUEUED

### ISSUE THREAD

**Issue by duncanokeyo** [tonyofrancis/Fetch#234]
so , i start group downloads, and it fails to download some requests, this is okay .. but now when i retry the group downloads, the download that failed is stuck at QUEUED. this is hard to reproduce as this behaviour does not occur frequently
also note that there are no other ongoing downloads taking place, so it means that the priorityqueue can process this failed download
```

group id -1431967297 status FAILED url http://172.20.10.3:3000/video31.mp4
08-26 08:42:35.233 6643-6643/com.dans.apps.downloadmanager D/DownloadService: group id -1431967297 status COMPLETED url http://172.20.10.3:3000/video3.mp4
08-26 08:42:35.233 6643-6643/com.dans.apps.downloadmanager D/DownloadService: group id -1431967297 status COMPLETED url http://172.20.10.3:3000/video10.mp4
08-26 08:42:35.233 6643-6643/com.dans.apps.downloadmanager D/DownloadService: group id -1431967297 status COMPLETED url http://172.20.10.3:3000/video23.mp4
08-26 08:42:35.233 6643-6643/com.dans.apps.downloadmanager D/DownloadService: group id -1431967297 status COMPLETED url http://172.20.10.3:3000/video36.mp4
08-26 08:42:35.233 6643-6643/com.dans.apps.downloadmanager D/DownloadService: group id -1431967297 status COMPLETED url http://172.20.10.3:3000/video8.mp4
08-26 08:42:35.233 6643-6643/com.dans.apps.downloadmanager D/DownloadService: group id -1431967297 status COMPLETED url http://172.20.10.3:3000/video15.mp4
08-26 08:42:35.233 6643-6643/com.dans.apps.downloadmanager D/DownloadService: group id -1431967297 status COMPLETED url http://172.20.10.3:3000/video28.mp4

```
`D/batchDownloads: Queued DownloadInfo(id=-2016919605, namespace='batchDownloads', url='http://172.20.10.3:3000/video31.mp4', file='/storage/emulated/0/Android/data/com.dans.apps.downloadmanager/files/DownloadThemAll/.batchvideos/video31.mp4~31', group=-1431967297, priority=NORMAL, headers={}, downloaded=0, total=-1, status=QUEUED, error=NONE, networkType=ALL, created=1535261464824, tag={"batch_folder_path":"\/storage\/emulated\/0\/Android\/data\/com.dans.apps.downloadmanager\/files\/DownloadThemAll\/.batchvideos","file_name":"videos.mp4","type_code":4,"type":"video"}, enqueueAction=INCREMENT_FILE_NAME, identifier=0, downloadOnEnqueue=true, extras={}) for download`

**Comment by tonyofrancis** [comment]
@duncanokeyo I have experienced this on a few rare occations. will check into this.

**Comment by tonyofrancis** [comment]
@duncanokeyo what happens if you close the app and restarts does the download get processed or does it still wait in queued

**Comment by duncanokeyo** [comment]
it wont download even if i kill and restart the application..

**Comment by Chrispassold** [comment]
same issue here 😢

**Comment by tonyofrancis** [comment]
working on this. Have not pin pointed the cause yet.

**Comment by duncanokeyo** [comment]
these logs suggest that

`08-29 14:14:13.531 12265-12332/com.dans.apps.downloadmanager D/batchDownloads: Enqueued download DownloadInfo(id=-2145567824, namespace='batchDownloads', url='http://172.20.10.3:3000/video39.mp4', file='/storage/emulated/0/Android/data/com.dans.apps.downloadmanager/files/DownloadThemAll/.batchvideos_2/video39.mp4~39', group=783495536, priority=NORMAL, headers={}, downloaded=0, total=-1, status=QUEUED, error=NONE, networkType=ALL, created=1535541253485, tag={"file_name":"videos_2.mp4","type":"video","batch_folder_path":"\/storage\/emulated\/0\/Android\/data\/com.dans.apps.downloadmanager\/files\/DownloadThemAll\/.batchvideos_2","type_code":4}, enqueueAction=INCREMENT_FILE_NAME, identifier=0, downloadOnEnqueue=true, extras={})`
`
08-29 14:14:13.859 12265-12265/com.dans.apps.downloadmanager D/batchDownloads: Added DownloadInfo(id=-2145567824, namespace='batchDownloads', url='http://172.20.10.3:3000/video39.mp4', file='/storage/emulated/0/Android/data/com.dans.apps.downloadmanager/files/DownloadThemAll/.batchvideos_2/video39.mp4~39', group=783495536, priority=NORMAL, headers={}, downloaded=0, total=-1, status=QUEUED, error=NONE, networkType=ALL, created=1535541253485, tag={"file_name":"videos_2.mp4","type":"video","batch_folder_path":"\/storage\/emulated\/0\/Android\/data\/com.dans.apps.downloadmanager\/files\/DownloadThemAll\/.batchvideos_2","type_code":4}, enqueueAction=INCREMENT_FILE_NAME, identifier=0, downloadOnEnqueue=true, extras={})`


`08-29 14:14:13.859 12265-12265/com.dans.apps.downloadmanager D/batchDownloads: Queued DownloadInfo(id=-2145567824, namespace='batchDownloads', url='http://172.20.10.3:3000/video39.mp4', file='/storage/emulated/0/Android/data/com.dans.apps.downloadmanager/files/DownloadThemAll/.batchvideos_2/video39.mp4~39', group=783495536, priority=NORMAL, headers={}, downloaded=0, total=-1, status=QUEUED, error=NONE, networkType=ALL, created=1535541253485, tag={"file_name":"videos_2.mp4","type":"video","batch_folder_path":"\/storage\/emulated\/0\/Android\/data\/com.dans.apps.downloadmanager\/files\/DownloadThemAll\/.batchvideos_2","type_code":4}, enqueueAction=INCREMENT_FILE_NAME, identifier=0, downloadOnEnqueue=true, extras={}) for download`

`status for download id -2145567824 ---> FAILED`

`08-29 14:14:32.632 12265-12265/com.dans.apps.downloadmanager D/batchDownloads: Queued DownloadInfo(id=-2145567824, namespace='batchDownloads', url='http://172.20.10.3:3000/video39.mp4', file='/storage/emulated/0/Android/data/com.dans.apps.downloadmanager/files/DownloadThemAll/.batchvideos_2/video39.mp4~39', group=783495536, priority=NORMAL, headers={}, downloaded=0, total=-1, status=QUEUED, error=NONE, networkType=ALL, created=1535541253485, tag={"file_name":"videos_2.mp4","type":"video","batch_folder_path":"\/storage\/emulated\/0\/Android\/data\/com.dans.apps.downloadmanager\/files\/DownloadThemAll\/.batchvideos_2","type_code":4}, enqueueAction=INCREMENT_FILE_NAME, identifier=0, downloadOnEnqueue=true, extras={}) for download
`
the last log is where the download is stuck at queued...
also these logs suggest that Fetch somehow did not call the onError callback or it some how wrongly sets the download as failed

**Comment by duncanokeyo** [comment]
This problem occurs when am using the sequential downloader.....

**Comment by tonyofrancis** [comment]
@duncanokeyo thanks for the logs. this gives me a good idea where to start. i will report back.

**Comment by tonyofrancis** [comment]
@duncanokeyo @Chrispassold Just released Fetch 2.2.0-RC11 with a fix that should resolve this issue. Please let me know if it works. See Changelog for changes.

**Comment by duncanokeyo** [comment]
ok, let me do some more testing

**Comment by Chrispassold** [comment]
to me, it is working as expected now. thx
