### ISSUE TITLE
When kill App. Downloading stop.

### ISSUE THREAD

**Issue by pethanihiten** [tonyofrancis/Fetch#24]
Hi,

I have download long file it is download but when app kill in background download stoped. and it is not a store in database.

Thanks

**Comment by altaf2892** [comment]
if u want to keep download running u should downloading i service ...

**Comment by pethanihiten** [comment]
@altaf2892 
yes, there is download in services.

**Comment by tonyofrancis** [comment]
@pethanihiten @altaf2892 Fetch performs all download operations in a background service called FetchService. When an app is placed in the background, it will continue to download requests. If the app is killed, that means all services and components of the app are killed. That is the expected behavoir. What you can do is create a service that will start the fetch service again. You can use the `AlarmManager` service or the `JobScheduler` Service to fire off your service or the `FetchService.class`. The Fetch class has the method `Fetch.startService(getApplicationContext());` that you can call from any other Android Component to start the FetchService without getting an instance of Fetch.

**Comment by hitenpethani** [comment]
@tonyofrancis 
ok, i will handle this. i have download your simple demo and used multiple file download example when download start going to main screen listview list clear atomically . How can i manage multiple file download with database? how to store file in database and handle to start/pause/cancel/stop. you shown fetch folder in databasehelper.java file and methods. i need you help.

**Comment by altaf2892** [comment]
@hitenpethani  did u solve your issue?

**Comment by pethanihiten** [comment]
@altaf2892 
no, @tonyofrancis give a feedback. he is right. when app kills all the background process automatic stopped. if other solution possible of your side. so I will send my simple demo and implement my project.

**Comment by tonyofrancis** [comment]
@hitenpethani Fetch stores all requests in a database with their current state,progress and other information needed. What you can do is call the `fetch.get()` method. This method will return all requests that are currently being managed by Fetch. You can then iterate over the list and populate your listview with the current download state, etc for each request.
