### ISSUE TITLE
AGPBI: {"kind":"error","text":"Program type already present: com.tonyodev.fetch2.database.DownloadDao_Impl$1","sources":[{}],"tool":"D8"}

### ISSUE THREAD

**Issue by tobybonhof** [tonyofrancis/Fetch#245]
I'm getting this error and im not sure why. I know it has to do with the fact that i have multiple depedencies on my app module. But they all depend on the same version of fetch2.

Can it have to do with the fact that my app is also using Room?

The weird thing however is that this error only occurs when trying to build a release build type. with debug type this does not happen

**Comment by tonyofrancis** [comment]
@tobybonhof Strange. Your app may be using a different version of room than the library. Try adding this to your apps build.gradle file and let me know if it helps.
```java
configurations.all {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        def requested = details.requested
        if (requested.group == 'android.arch.persistence.room') {
            details.useVersion roomVersion
        }
    }
}
```

**Comment by tobybonhof** [comment]
Figured out why it was showing the error:

I was trying to add DownloadsDao to my own Database.kt class. That's why it was generating two DownloadsDao_impl.kt files
