### ISSUE TITLE
Pass downloaded file as complete

### ISSUE THREAD

**Issue by alirezaafkar** [tonyofrancis/Fetch#246]
Is there any way to pass downloaded file as completed download?

**Comment by tonyofrancis** [comment]
@alirezaafkar Fetch has an addCompletedDownload method that allows you to add a completed download for Fetch to manage.

**Comment by alirezaafkar** [comment]
Nope.
Now I am managing this manually. By checking if file exists and its size is equal to total length of download request. If yes then it is downloaded and I call onCompleted.
.

**Comment by tonyofrancis** [comment]
@alirezaafkar I may not be understanding your request/issue properly. Can your rephrase??

**Comment by alirezaafkar** [comment]
@tonyofrancis 
For example we want to download 10 files:

If it is already downloaded completely -> _Should call onComplete without downloading again._
If downloaded only percent of file and not completed -> _Should resume._
If not downloaded before -> _Download from beginning._

**Comment by tonyofrancis** [comment]
@alirezaafkar Looking info this.

**Comment by tonyofrancis** [comment]
@alirezaafkar New release of Fetch . Version of Fetch 2.2.0-RC14.
There is a new EnqueueAction **_EnqueueAction_UPDATE_ACCORDINGLY_** option that you can set on the request your are enqueuing to achieve the following:

1. If it is already downloaded completely -> Should call onComplete without downloading again.
2. If downloaded only percent of file and not completed -> Should resume.
3. If not downloaded before -> Download from beginning.

Note this is now the default behavior in Fetch and newly created Request objects will have this option enabled by default. Please let me know if it works well for you.

**Comment by alirezaafkar** [comment]
@tonyofrancis It seems works perfectly. I'll let you know if it has any issues. Thanks!
