### ISSUE TITLE
Kotlin Version of the Screenshot (Fetch Demo)

### ISSUE THREAD

**Issue by ARSujonx** [tonyofrancis/Fetch#248]
The Screenshot(fetch demo) that provided in documentation, can anyone please provide the kotlin version of it. Like only file.kt and file.xml . It would very helpful because i don't know anything about java and can't find any documentation on kotlin.

![screenshot](https://user-images.githubusercontent.com/37956905/45993215-9cf65800-c0af-11e8-8793-9db19f9c6f3b.png)

So that i can tweek with those file & learn from that.

**Comment by tonyofrancis** [comment]
@ARSujonx Its super easy to convert a java class to a kotlin class. Please have a look at https://developer.android.com/studio/projects/add-kotlin#convert-to-kotlin-code

**Comment by Xenolion** [comment]
The problem I am facing is that some methods can not be converted to Kotlin from Java. Example enqueue downloads in DownloadListActivity.java?? How to do it in Kotlin.
