### ISSUE TITLE
Creating a new data object that the url is passed to

### ISSUE THREAD

**Issue by adtoba** [tonyofrancis/Fetch#249]
Anyone who has done something like that?

**Comment by tonyofrancis** [comment]
@adtoba Can you explain what you are trying to accomplish?. The title does not tell us anything.

**Comment by adtoba** [comment]
I'm trying to use the library for a download activity in my browser app.
But then, I need to pass the unique URL gotten from the download manager
from my webview Into the model for my fetch download.. It should get the
new URL, pass it into the data then add it to a list in download activity

**Comment by tonyofrancis** [comment]
So just so I understand. You are using a webview. If the user downloads a file the file goes to the default download manager. What you want to achieve is get the url for that download and have Fetch download the request instead of the default download manager. Sounds correct?

**Comment by adtoba** [comment]
Yes. Totally correct!  Can you do that for me?

**Comment by tonyofrancis** [comment]
@adtoba I cannot do that for you but point you to resources that will help. To get the download information from the download manager you can follow this guide: https://www.androidtutorialpoint.com/networking/android-download-manager-tutorial-download-file-using-download-manager-internet/

Also see the Fetch Sample app.
