### ISSUE TITLE
How to have single Fetch instance?

### ISSUE THREAD

**Issue by sough** [tonyofrancis/Fetch#25]
Hello, I want to add to a single download queue from different activities and have single listener, is it possible?

**Comment by tonyofrancis** [comment]
@sough This can easily be done. Fetch does not depend on the Activity context, but on the Application context. You can create a single instance of Fetch in a wrapper class and share it throughout you application. You can do something like this:

Example:
```java
public final class DownloadManager {

    /*Do not worry about the lint warning for context. We are using the Application context.*/
    private static Fetch fetch;

    private static final FetchListener fetchListener = new FetchListener() {
        @Override
        public void onUpdate(long id, int status, int progress, long downloadedBytes, long fileSize, int error) {
            //D0 CHECKS HERE 
        }
    };
    
    public static Fetch getSingleFetchInstance(Application application) {

        if(fetch == null) {
            fetch = Fetch.getInstance(application);
            fetch.addFetchListener(fetchListener);
        }

        return fetch;
    }

}

```

Hope this helps

**Comment by sough** [comment]
Thx, I just made all settings + listener in CustomApplication class, as I understood that Fetch depends only from AppContext and every call of Fetch.getInstance(context) will return that instance from CustomApplication
