### ISSUE TITLE
How to build project?

### ISSUE THREAD

**Issue by samanatabaki** [tonyofrancis/Fetch#250]
Hi! 
Your source code is not building. after so much try, I'm receiving this error message:

Cause: com.novoda.gradle.release.AndroidLibrary$LibraryUsage.getDependencyConstraints()Ljava/util/Set;

how should I fix this?

**Comment by tonyofrancis** [comment]
@samanatabaki Seems like the novoda plugin is broken with the new recently release versions of gradle/android studio. Looking into a fix.

**Comment by tonyofrancis** [comment]
@samanatabaki just disabled the plugin that causing this issue. Try pulling the latest changes again.
