### ISSUE TITLE
I can download?

### ISSUE THREAD

**Issue by sealiasheq** [tonyofrancis/Fetch#251]
I have bellow url but I can't download and say me `EMPTY_RESPONSE_FROM_SERVER`:
`http://XX.XX.XX:XXX/file-upload/Y2xoSJJZpC3cMtK7T/20181002_112136.mp4?rc_uid=yZbAgbYuKg4CLCs4v&rc_token=UxV7k2LIidspKRo_EPhv_xuC-dpc1oVFieLRI3LJ9UD`

I used from header but can't download.

**Comment by tonyofrancis** [comment]
@sealiasheq Are you able to download this file in a web browser or another client with no issues?
Try:
```java
final String url = "http://XX.XX.XX:XXX/file-upload/Y2xoSJJZpC3cMtK7T/20181002_112136.mp4";
final Request request = new Request(url, file);
request.addHeader("rc_uid", "yZbAgbYuKg4CLCs4v&rc_token=UxV7k2LIidspKRo_EPhv_xuC-dpc1oVFieLRI3LJ9UD");
fetch.enqueue(request, successCallback, errorCallback);
```

**Comment by sealiasheq** [comment]
Not work.

**Comment by tonyofrancis** [comment]
@sealiasheq If you need further help with this link email me and I will try to see if I can get it to work with Fetch
