### ISSUE TITLE
How to get progress updates of several downloads from a Fetch request that is working in Service ?

### ISSUE THREAD

**Issue by amrkhamis** [tonyofrancis/Fetch#252]
Since I have a view with list of downloads that present the progress of each download, and having fetch work in service, what is the best practice to get the progress of each downlaod ? I thought about making a a loop that runs every second to check progress for each download but thats not efficient, can I access the listener in the activity from the Fetch inside the service ?

**Comment by iamfaraz** [comment]
What I understood from your question, i can assume that you want your Fetch instance available to all activities. For this you can initialize a static instance of fetch in Application class and then use that instance anywhere you want. Sorry for my bad english.

**Comment by tonyofrancis** [comment]
@amrkhamis as @amrkhamis mentioned. Create a global instance of Fetch that can be accessed from any component. If you are familiar with RXJava you can use RC to dispatch calls to listener observables also.
