### ISSUE TITLE
ENQUEUED_REQUESTS_ARE_NOT_DISTINCT Error when trying to queue request list

### ISSUE THREAD

**Issue by MickeCast** [tonyofrancis/Fetch#257]
Hello, I am trying to enqueue an array list of requests, but I alway get this error on the error callback of the enqueue call
`
for (String num :
                    downloadFiles) {
//Process to get the remote path and file name to store
final Request request = new Request(srcAudioRemote, possibleFile.getAbsolutePath());
                                request.setPriority(Priority.HIGH);
                                request.setNetworkType(NetworkType.ALL);
                                request.addHeader("nombre", num);
                                requests.add(request);
}
downloadListener.enqueue(requests,func1,func2);
`
What could I be doing wrong?

**Comment by tonyofrancis** [comment]
It means that the list you are enqueuing has 2 requests that point to the same file for download. Fetch does not allow more than one request pointing to a file path to be enqueued.

**Comment by MickeCast** [comment]
Ok, you're right, I was duplicating a path in the list, thanks!!
