### ISSUE TITLE
How to enqueue downloads in Kotlin, Java to Kotlin conversion in download list is not working?

### ISSUE THREAD

**Issue by Xenolion** [tonyofrancis/Fetch#258]
This java to Kotlin conversion is a mess:
     
     `private void enqueueDownloads() {
        final List<Request> requests = Data.getFetchRequestWithGroupId(GROUP_ID);
        fetch.enqueue(requests, updatedRequests -> {

        }, error -> Timber.d("DownloadListActivity Error: %1$s", error.toString()));

    }`
This conversion has multiple errors like `Java to Kotlin error Cannot infer a type for this parameter. ` etc How should the method be? Should the FetchApp demo be written to full kotlin since conversion is a mess sometimes.

**Comment by tonyofrancis** [comment]
```kotlin
val requests = Data.getFetchRequestWithGroupId(GROUP_ID)
fetch.enqueue(requests, Func { updatedRequests ->
    //handle enqueued requests
}, Func { error ->
    //handle error
})
```
The converter does its best but it is not perfect.

**Comment by Xenolion** [comment]
It turns out the solution failed but I solved like this:

    private fun enqueueDownloads() {
        val requests = Data.getFetchRequestWithGroupId(GROUP_ID)
        fetch.enqueue(requests, object : Func<List<Request>> {
            override fun call(result: List<Request>) {

            }
        }, object : Func<Error> {
            override fun call(result: Error) {

            }
        })

    }
This was not even Fetch issue. It is Kotlin thing in Android. But thanks @tonyofrancis
