### ISSUE TITLE
Possibility to change the download URL when it expires 

### ISSUE THREAD

**Issue by MaciekZ-NHM** [tonyofrancis/Fetch#26]
Hello, i would like to use this library into my project, but i have one problem.
I have download URL with expiration time, and when user pause download, expiration time is over, and user want to resume download, fetcher give me STATUS_ERROR, that is fine. 
My ask is: is there any possibility to change download URL to continue download file with different download link?
Because for now i can't continue download, i need to remove request and starts again, losing proviously dowloaded part of the file.

**Comment by tonyofrancis** [comment]
@MaciekZ-NHM This is a very interesting scenario. It is possible to implement this in Fetch. I would have to find/test for the best way to implement this feature and to also test for the effects this can have on the library. Let me circle back back in a day.

**Comment by MaciekZ-NHM** [comment]
Thank you for the quick answer, I'll wait ;)

**Comment by tonyofrancis** [comment]
@MaciekZ-NHM Still looking into this. I will keep this thread updated

**Comment by tonyofrancis** [comment]
@MaciekZ-NHM Version 1.1.1 has been pushed and contains a new method `fetch.updateUrlForRequest(id,url)`. This will allow you to update the url of a download request that has been enqueued. If a url expires and the download cannot continue, The request status will be set to `Fetch.STATUS_ERROR` and fetch listeners will be alerted. After updating a request's url, it status will automatically be set to `Fetch.STATUS_QUEUED` and fetch will try to continue the download.
