### ISSUE TITLE
HTTP code when download finishes

### ISSUE THREAD

**Issue by cdn34** [tonyofrancis/Fetch#261]
This is a follow up on this issue https://github.com/tonyofrancis/Fetch/issues/244. 

I've created a custom downloader and overridden `onServerResponse`.

```
public class CustomDownloader extends HttpUrlConnectionDownloader implements Downloader {

    public CustomDownloader(FileDownloaderType fileDownloaderType) {
        super(fileDownloaderType);
    }

    @Override
    public void onServerResponse(ServerRequest serverRequest, Response response) {
        System.out.println("Response: "+ response.getCode());
    }


}
```  

By using this, I do get a status code (206) multiple times for each download, but not once the download finishes. How can that be retrieved ?

**Comment by tonyofrancis** [comment]
@cdn34 The status code is returned only when a new connection is opened. Why would you need to get the status code when the download finishes?. Is there a need for a new callback in the downloader to state when a download finishes??? Please give a use case.

**Comment by cdn34** [comment]
@tonyofrancis Thanks for the reply. This may not be needed after all, I was having issues downloading certain files and the goal was to check whether or not it was actually succeeding. I was using an older version of the library, but after trying it on the latest one, it seems to be working correctly.
