### ISSUE TITLE
Can we use Uri instead of File?

### ISSUE THREAD

**Issue by jpvs0101** [tonyofrancis/Fetch#262]
final Request request = new Request(url, file);

Can we pass Uri instead of file?
Uri is got from Storage Access Framework.

**Comment by tonyofrancis** [comment]
@jpvs0101 It is possible to use uri with Fetch. But will also need to create a custom Downloader to handle the stream. Example:

```java
    @Override
    public void onCreate() {
        super.onCreate();
        final FetchConfiguration fetchConfiguration = new FetchConfiguration.Builder(this)
                .enableRetryOnNetworkGain(true)
                .setDownloadConcurrentLimit(3)
                .setHttpDownloader(new MyDownloader(this, Downloader.FileDownloaderType.PARALLEL))
                .build();
        Fetch.Impl.setDefaultInstanceConfiguration(fetchConfiguration);

        final Uri uri = Uri.parse("/some/file/dir/file.txt");
        final Request request = new Request("http:example.com/file.txt", uri.toString());

        final Fetch fetch = Fetch.Impl.getDefaultInstance();
        fetch.enqueue(request, new Func<Request>() {
            @Override
            public void call(@NotNull Request result) {
                //result request
            }
        }, new Func<Error>() {
            @Override
            public void call(@NotNull Error result) {
                //error handling
            }
        });
    }

    private class MyDownloader extends OkHttpDownloader {

        private final Context context;

        public MyDownloader(Context context, @NotNull Downloader.FileDownloaderType fileDownloaderType) {
            super(fileDownloaderType);
            this.context = context;
        }

        @Nullable
        @Override
        public OutputResourceWrapper getRequestOutputResourceWrapper(@NotNull Downloader.ServerRequest request) {
            final Uri uri = Uri.parse(request.getFile());
            final ContentResolver contentResolver = context.getContentResolver();
            try {
                final ParcelFileDescriptor descriptor = contentResolver.openFileDescriptor(uri, "rw");
                if (descriptor != null) {
                    final FileOutputStream fileOutputStream = new FileOutputStream(descriptor.getFileDescriptor());
                    return getResourceWrapper(fileOutputStream);
                }
            } catch (FileNotFoundException e) {
                e.printStackTrace();
            }
            return null;
        }

        private OutputResourceWrapper getResourceWrapper(final FileOutputStream fileOutputStream) {
            return new OutputResourceWrapper() {
                @Override
                public void write(@NotNull byte[] byteArray, int offSet, int length) throws IOException {
                    fileOutputStream.write(byteArray, offSet, length);
                }

                @Override
                public void setWriteOffset(long offset) throws IOException {
                    fileOutputStream.getChannel().position(offset);
                }

                @Override
                public void flush() throws IOException {
                    fileOutputStream.flush();
                }

                @Override
                public void close() throws IOException {
                    fileOutputStream.close();
                }
            };
        }
    }
```
It does seem like a lot of work, but you get full customization. Let me know if this helps.

**Comment by jpvs0101** [comment]
Thank you, but this is overkill,😳, also will it handle pause/resume?

My need is simple, I just need a simple call!

Anyway thank you for this, this may help to someone!

On Thursday, October 18, 2018, Tonyo Francis <notifications@github.com>
wrote:
> @jpvs0101 It is possible to use uri with Fetch. But will also need to
create a custom Downloader to handle the stream. Example:
>
> @Override
> public void onCreate() {
> super.onCreate();
> final FetchConfiguration fetchConfiguration = new
FetchConfiguration.Builder(this)
> .enableRetryOnNetworkGain(true)
> .setDownloadConcurrentLimit(3)
> .setHttpDownloader(new MyDownloader(this,
Downloader.FileDownloaderType.PARALLEL))
> .build();
> Fetch.Impl.setDefaultInstanceConfiguration(fetchConfiguration);
>
> final Uri uri = Uri.parse("/some/file/dir/file.txt");
> final Request request = new Request("http:example.com/file.txt",
uri.toString());
>
> final Fetch fetch = Fetch.Impl.getDefaultInstance();
> fetch.enqueue(request, new Func<Request>() {
> @Override
> public void call(@NotNull Request result) {
> //result request
> }
> }, new Func<Error>() {
> @Override
> public void call(@NotNull Error result) {
> //error handling
> }
> });
> }
>
> private class MyDownloader extends OkHttpDownloader {
>
> private final Context context;
>
> public MyDownloader(Context context, @NotNull
Downloader.FileDownloaderType fileDownloaderType) {
> super(fileDownloaderType);
> this.context = context;
> }
>
> @Nullable
> @Override
> public OutputResourceWrapper getRequestOutputResourceWrapper(@NotNull
Downloader.ServerRequest request) {
> final Uri uri = Uri.parse(request.getFile());
> final ContentResolver contentResolver = context.getContentResolver();
> try {
> final ParcelFileDescriptor descriptor =
contentResolver.openFileDescriptor(uri, "rw");
> if (descriptor != null) {
> final FileOutputStream fileOutputStream = new
FileOutputStream(descriptor.getFileDescriptor());
> return getResourceWrapper(fileOutputStream);
> }
> } catch (FileNotFoundException e) {
> e.printStackTrace();
> }
> return null;
> }
>
> private OutputResourceWrapper getResourceWrapper(final FileOutputStream
fileOutputStream) {
> return new OutputResourceWrapper() {
> @Override
> public void write(@NotNull byte[] byteArray, int offSet, int length)
throws IOException {
> fileOutputStream.write(byteArray, offSet, length);
> }
>
> @Override
> public void setWriteOffset(long offset) throws IOException {
> fileOutputStream.getChannel().position(offset);
> }
>
> @Override
> public void flush() throws IOException {
> fileOutputStream.flush();
> }
>
> @Override
> public void close() throws IOException {
> fileOutputStream.close();
> }
> };
> }
> }
>
> It does seem like a lot of work, but you get full customization. Let me
know if this helps.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci3.googleusercontent.com/proxy/Uq8WIyO5k-8-Ph1-TF93gzl7-mi9AN8z-c5baZl8_drnVaYGYJAMok_cZAqOWJgHG8lqKZk6Tr8Pmx9ZU8TlbrOD4bLaz13XKHQ7sCs1hByuGtowHa6aeGtGIUKgDZk6VRDeu8jrCqRnpb6YBdjdgg6i0eX6kg=s0-d-e1-ft#https://github.com/notifications/beacon/AkhD6iA6DXBaXoernmRcE9sSS7V9Fqi_ks5umI0lgaJpZM4XtR8y.gif>

**Comment by tonyofrancis** [comment]
@jpvs0101 Yes it will handle pause/resume as normal. I am still looking for ways to make your use case easy in Fetch whiles keeping the library small and very flexible. But the above solution will work well for now.

**Comment by jpvs0101** [comment]
Great, waiting for that! Only thing missing is uri support! Otherwise seems
cool!

On Wednesday, October 24, 2018, Tonyo Francis <notifications@github.com>
wrote:
> @jpvs0101 Yes it will handle pause/resume as normal. I am still looking
for ways to make your use case easy in Fetch whiles keeping the library
small and very flexible. But the above solution will work well for now.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci5.googleusercontent.com/proxy/lH49wCgNGI34Po92-hM4A0I5rERZxTn4rntectPDN1DA9YN4OZyCf04zpYLT1bq0TM1MUqj3wq5Cino-i2nWGgAjUxC5X5xW1zZjkP2z1zcBH5fNM7pTJq3UkmBj-UpfrrJjzgKaYYulASEH1tYdz9Dx3oL2dA=s0-d-e1-ft#https://github.com/notifications/beacon/AkhD6sjqe_YMEA32vs5_A4bgXnNkNSrkks5un28EgaJpZM4XtR8y.gif>

**Comment by jpvs0101** [comment]
Thanks, I tried, but it's seems like little messy, It would be awesome if
you implement direct uri support just like file paths, only thing I miss in
this cool library is uri support, waiting for that!

On Friday, October 26, 2018, Tonyo Francis <notifications@github.com> wrote:
> @jpvs0101 you can use the above code for production. Just make sure it
works well for your uris.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci5.googleusercontent.com/proxy/HtIuhE7sftRC9k09B3QDYHxO_KwK9n_6g-4cqjF2qCcQPc4WHePUhD4tBdJSnDbSpKD9fWqFjXmuCtdH8aepjVpNBOrNONHbMw3FpWskOzDKAnCptdY6iS1nFSwVOGcrHPnOgG5_L0spPAR3957afdtg1Trbgw=s0-d-e1-ft#https://github.com/notifications/beacon/AkhD6p4jAB706PrF0UzDwRkd37d7TNuxks5uoyjtgaJpZM4XtR8y.gif>

**Comment by tonyofrancis** [comment]
@jpvs0101 Just released a **new** Fetch version. **2.3.0-RC1.** This version has lots of fixes and **breaking changes** so be sure to check out the [CHANGELOG](https://github.com/tonyofrancis/Fetch/releases).
Fetch now supports saving to URIs right out the box. If you need more complex URI handling, see the StorageResolver and DefaultStorageResolver class in Fetch. Please let me know if it works well for you.

**Comment by jpvs0101** [comment]
Awesome, I will check it...

On Wednesday, November 7, 2018, Tonyo Francis <notifications@github.com>
wrote:
> @jpvs0101 Just released a new Fetch version. 2.3.0-RC1. This version has
lots of fixes and breaking changes so be sure to check out the CHANGELOG.
> Fetch now supports saving to URIs right out the box. If you need more
complex URI handling, see the StorageResolver and DefaultStorageResolver
class in Fetch. Please let me know if it works well for you.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci4.googleusercontent.com/proxy/WljbKvaUDCamYTWt3RcQGklmpkAQnaKvyqvL_ElvYhZGWoitW3tu2IOqQtE3sjsRXGvm2-6SIz7mRyV-SlxrnYRwFY3_zKrqzLDduLRZ4o6CGv-TTcpDnJM_gwpxBHnsQGKlHzsjk4lJx3On1nb6LPGPPw=s0-d-e1-ft#https://github.com/notifications/beacon/AkhD6kCpk3T0JqywUJax4r8hB1YMg1PWks5usxongaJpZM4XtR8y.gif>
