### ISSUE TITLE
[Ask] Download in background

### ISSUE THREAD

**Issue by dreasn** [tonyofrancis/Fetch#263]
What is the best scenario to make Fetch2 able to keep on downloading whenever user move to other activities?

Should I use single Fetch instant?

**Comment by tonyofrancis** [comment]
@dreasn You can create a global Fetch instance that you can reference from any Activity. For example you can extend the Application class and place your Fetch global instance there. Then you can access your custom application class and reference the Fetch instance. In the activity you can then attach and detach Fetch listeners. Have a look at the sample project to see different use cases. Hope this helps.

**Comment by dreasn** [comment]
alright.  already did so.  Thanks.

**Comment by AlexStarc** [comment]
I approached it with FetchService (background long-running service) which communicates via broadcasts with the rest of the app (also binder can be easily applied). Since there's single service it holds single Fetch reference.
