### ISSUE TITLE
I want the download to start instantly?

### ISSUE THREAD

**Issue by Xenolion** [tonyofrancis/Fetch#264]
I have two activities so:
1. One for enqueueing a download at runtime and it may enqueue more than one download. I open an instance of fetch with namespace "ALL_DOWNLOADS" and enqueue a request. But I never display any progress in this activity.

2. The second activity displays the progress of all downloads. So I open an instance of Fetch with the same namespace and display the progress for each download. 

I can see all downloads, but something is happening: The download does not start until I enter the next activity. I want the download to start instantly in the background just after enqueueing in the first activity. And only display progress when I go to the second activity.

How can I achieve this??

**Comment by tonyofrancis** [comment]
@Xenolion 
Make sure the new request you are creating has the `downloadOnEnqueue` property set to true. Example:
```java
Request request = new Request("url", "file");
request.setDownloadOnEnqueue(true);
```
Let me know if this helps.

**Comment by tonyofrancis** [comment]
the behavior was not changed
