### ISSUE TITLE
UNIQUE constraint failed: requests._file error for EnqueueAction.REPLACE_EXISTING

### ISSUE THREAD

**Issue by marcin-adamczewski** [tonyofrancis/Fetch#265]
Hello Tony,

I'm getting Unique constraint error when trying to enqueue request.
I know that there is such constraint on FILE column in the database,
however REPLACE_EXISTING should allow for downloading again to 
the same file path. 

I was debugging your code and indeed, before enqueueing request you 
delete previous download from database:

**FetchHandler:105**
```
  EnqueueAction.REPLACE_EXISTING -> {
                    deleteDownloads(listOf(downloadInfo.id))
                    return false
                }
```
However, you delete downloads with given id, and id of download
is hash of file path and url. And here is the problem...
In my case url expires after 15 minutes. So when I try to download
again after this 15 minutes to the same file path I will get an error.

When I checked a request table in database, I've seen that there are entries with
status CANCELLED. And for those I was getting UNIQUE_CONSTRAINT error.
So I suppose the case is as follow:
1. User started downloading a file
2. User cancelled downloading (group.cancel)
3. After 15 minutes or more (url expired) user tried to download again and got error

Not sure what would be the best solution here. Maybe deleting all
entries with downloading file path?

For now as a workaround I remove all entries with status Cancelled, Failed before enqueueing.

Could you help?

Btw, I've noticed once or twice that despite a file has been downloaded it had status DOWNLOADING in database.

version 2.2.0-RC14

**Comment by tonyofrancis** [comment]
@marcin-adamczewski as of Fetch 2.2.0-RC14 the default enqueue action for new requests is `EnqueueAction.UPDATE_ACCORDINGLY`. Verify that the requests your are enqueuing have an enqueue action of `EnqueueAction.REPLACE_EXISTING`.
Documentation for `EnqueueAction.UPDATE_ACCORDINGLY`:
```java
  /** If Fetch is already managing an existing request with the same file path do one the following:
     * 1: If existing download is completed, Fetch will call onComplete method on attached Fetch Listeners.
     * 2: If existing download is not completed, resume download normally.
     * 3: If not downloaded, download will proceed normally.
     * Note: If download is existing, Fetch will not update the existing download with the settings from
     * the new passed in request. Use the updateRequest method instead.
     * */
```

Also, Fetch has a method called ` updateRequest`. Use this method to update an existing request in the database. This will generate a new download id. I am looking into ways to making this much more simpler. If you have suggests please let me know.

For the completed downloads with the Status of Downloading, are you able to replicate? Also which DownloaderType are you using. Sequential or Parallel?

**Comment by marcin-adamczewski** [comment]
@tonyofrancis
I'm sure that I use EnqueueAction.REPLACE_EXISTING.

I think that `updateRequest(requestId)` won't help as `requestId` consists of `url` and `file`.

```
    /** Unique Identifier. Used to identify a download.*/
    val id: Int = getUniqueId(url, file)

```
In my case url may change for the same song after 15 minutes. That being said I will never be able to update request.

The only idea that comes to my mind is to make something like this:
```
 EnqueueAction.REPLACE_EXISTING -> {
                    deleteDownloadsWithIdAndFilePath(downloadInfo.id, downloadInfo.file)
                    return false
                }
```

where `deleteDownloadsWithIdAndPath` would call following query:
"DELETE * FROM requests where COLUMN_ID = id OR COLUMN_FILE = file"

That way we are sure that we will be able to enqueue new request without any conflicts,
and we are also sure that we won't remove any unwanted request because there can't be two requests with same id and file path.


Unfortunately I couldn't reproduce it, however I'll be playing with it soon so I'll let you know. Downloader type is Sequential.

**Comment by marcin-adamczewski** [comment]
@tonyofrancis
I'm sure that I use EnqueueAction.REPLACE_EXISTING.

I think that updateRequest(requestId) won't help as requestId consists of url and file.

    /** Unique Identifier. Used to identify a download.*/
    val id: Int = getUniqueId(url, file)

In my case url may change for the same song after 15 minutes. That being said I will never be able to update request.

The only idea that comes to my mind is to make something like this:

 EnqueueAction.REPLACE_EXISTING -> {
                    deleteDownloadsWithIdAndFilePath(downloadInfo.id, downloadInfo.file)
                    return false
                }
where deleteDownloadsWithIdAndPath would call following query:
"DELETE * FROM requests where COLUMN_ID = id OR COLUMN_FILE = file"

That way we are sure that we will be able to enqueue new request without any conflicts,
and we are also sure that we won't remove any unwanted request because there can't be two requests with same id and file path.

Unfortunately I couldn't reproduce it, however I'll be playing with it soon so I'll let you know. Downloader type is Sequential.

**Comment by tonyofrancis** [comment]
@marcin-adamczewski let me do some more digging on this easy. I think we can make this more simpler. Not sure when Ill have the solution, but will keep updating.

**Comment by marcin-adamczewski** [comment]
@tonyofrancis Thank you for quick action.

Unfortunately it doesn't work for me.
Not sure if I'm checking well, however I didn't see any change related to `EnqueueAction.REPLACE_EXISTING` action.

Anyways, maybe my example wasn't that clear, so I'll try to give a simpler one.

1. I enqueued a song for download 
2. The song has been downloaded
3. I enqueue same song again with action `EnqueueAction.REPLACE_EXISTING`
4. I'm getting an unique constraint on file error

If you need more background what my app does ->
1. User may download all playlist songs by switching on a switch
2. All files are downloaded to `music_id_tmp` file, which is encrypted and stored in `music_id` file and then deleted. So file that has been downloaded (music_id_tmp) is always removed from disk just after encryption finishes.
3. User is able to remove encrypted music and re-download it again.

What I would expect from EnqueueAction.REPLACE_EXISTING is to always allow for downloading a file without any unique constraint problems.

What do you think?

**Comment by tonyofrancis** [comment]
@marcin-adamczewski 2.2.0-RC16 should def fix this. Please let me know if it works well for you.

**Comment by marcin-adamczewski** [comment]
@tonyofrancis Thanks for quick fix.

I did some testing and it seems to be working well. I'll do some more testing tomorrow and let you know.

I see one more thing that could be added. Basically if user is downloading a song (Status.DOWNLOADING), it might be better to not re-enqueue it when user enqueued again with `Action.REPLACE_EXISTING`. It would only reset all progress and start downloading from beginning. I don't think it is good for any case. What do you think?

Currently before enqueueing, I just check if there is no download with status DOWNLOADING for the file path I try to download to. Something like this:
```fetch.getDownloadsWithStatus(Status.DOWNLOADING, Func { downloads ->
                val isDownloading = downloads.any { it.file == request.file }
                if (!isDownloading) enqueue(request)
               ...
}```

But it is kind of workaround

**Comment by tonyofrancis** [comment]
Fetch has as another enqueue action that works as your described. Its called `Update_ Accordingly`. So if a download is completed it will not get enqueued. If a download is already downloading it stays the same. For your case this option would not work because of the changing urls.

This can get really complicated because of all the different requirements each apps has when using this library. So your work around may be the best one at the moment. 

I'll continue to look into making request enqueuing much more simpler. If you have ideas you want to bounce around or seen resources, please let me know. I'd be happy to have a look.

**Comment by marcin-adamczewski** [comment]
@tonyofrancis I was playing with it a bit today and it seems to work good.

I understand your concern that it might get complicated. I remember old versions of Fetch where there was over 10 different download actions :D I was wondering how you will be maintaining that.

Anyways, thanks again. Issue can be closed.

**Comment by tonyofrancis** [comment]
I'm reopening this issue because I've made improvements to `Update_ Accordingly` that should handle your case without all the extra checks. Will post back when the new version has been released.

**Comment by tonyofrancis** [comment]
@marcin-adamczewski  Just released a **new** Fetch version. **2.3.0-RC1.** This version has lots of fixes and **breaking changes** so be sure to check out the [CHANGELOG](https://github.com/tonyofrancis/Fetch/releases).
`EnqueueAction.Update_ Accordingly` should now do exactly what you need without all the checks. Please let me know if it works well for you.
