### ISSUE TITLE
equivalent of Fetch.STATUS_NOT_QUEUED in com.tonyodev.fetch2.Status

### ISSUE THREAD

**Issue by Vahhab** [tonyofrancis/Fetch#266]
I was using com.tonyodev.fetch:fetch:1.1.2 for managing downloads in my application . Now I'm going to migrate to com.tonyodev.fetch2:fetch2:2.2.0-RC14.

I want to know what is the equivalent of _Fetch.STATUS_NOT_QUEUED_ in fetch V2?

Currently Status is enumerated by _com.tonyodev.fetch2.Status_ in fetch v2 which have no enumeration equivalent to _STATUS_NOT_QUEUED_
I'm looking for equivalent of below filter at fetch2:

```
filter {
                it.downloadStatus != Fetch.STATUS_NOT_QUEUED
            }
```

**Comment by tonyofrancis** [comment]
@Vahhab If you are using the Fetch migrator the status of `Fetch.STATUS_NOT_QUEUED` will be equal to `Status.NONE` in Fetch2. Let me know if this helps.
