### ISSUE TITLE
[Ask] Check if fetch instance has listener and get it

### ISSUE THREAD

**Issue by dreasn** [tonyofrancis/Fetch#267]
How do I check if a fetch instance has listener(s) and get that listener(s)?

**Comment by tonyofrancis** [comment]
@dreasn Fetch does not have this built in. Are you not able to monitor the attached listeners and save them to a list?

**Comment by tonyofrancis** [comment]
@dreasn new version of Fetch released. 2.2.0-RC15. Fetch now has a method that returns a set of attached listeners.
