### ISSUE TITLE
hasActiveDownloads return true when should be false

### ISSUE THREAD

**Issue by LucasCFerraz** [tonyofrancis/Fetch#268]
Im facing an issue when running fetch inside a foreground service.
What happens is that hasActiveDownloads returns true even when I print the list of downloads and all downloads are with Completed Status.

**Comment by tonyofrancis** [comment]
@LucasCFerraz What version of Fetch are you running?

**Comment by tonyofrancis** [comment]
@LucasCFerraz Just ran some tests and Fetch does report hasActiveDownload inaccurately. Working on a fix.

**Comment by LucasCFerraz** [comment]
Thank you Tonyo, I'm using latest version.

**Comment by tonyofrancis** [comment]
@LucasCFerraz new version of Fetch release. 2.2.0-RC15. This includes fixes to correctly report active downloads. Please verify that this works well for you.

**Comment by LucasCFerraz** [comment]
Worked!   ##Thank you Tonyo!
