### ISSUE TITLE
Wrong error type returned

### ISSUE THREAD

**Issue by marcin-adamczewski** [tonyofrancis/Fetch#269]
Hi @tonyofrancis 

I got an error of type Error.UNKOWN for following message
```android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: requests._file (code 2067)```

Shouldn't it be Error.REQUEST_WITH_FILE_PATH_ALREADY_EXIST ?

[screenshot](https://www.dropbox.com/s/ll2ud5ho862ujym/Screenshot%202018-10-22%2019.33.17.png?dl=0)

**Comment by tonyofrancis** [comment]
@marcin-adamczewski Looking into this

**Comment by tonyofrancis** [comment]
New version of Fetch 2.2.0-RC15 now handles this correctly.
