### ISSUE TITLE
EnqueueAction.DO_NOT_ENQUEUE_IF_EXISTING does not work

### ISSUE THREAD

**Issue by sethchhim** [tonyofrancis/Fetch#271]
Version 2.2.0-RC16

In the sample app, for `SingleDownloadActivity.java`, I will attempt to enqueue a request with DO_NOT_ENQUEUE_IF_EXISTING.

```
    private void enqueueDownload() {
        final String url = Data.sampleUrls[0];
        final String filePath = Data.getSaveDir() + "/movies/" + Data.getNameFromUrl(url);
        request = new Request(url, filePath);
        request.setExtras(getExtrasForRequest(request));
        request.setEnqueueAction(EnqueueAction.DO_NOT_ENQUEUE_IF_EXISTING); //add this line for test
        fetch.enqueue(request, updatedRequest -> {
            request = updatedRequest;
        }, error -> Timber.d("SingleDownloadActivity Error: %1$s", error.toString()));
    }
```

This is a clean install with the download directory cleared but it fails to download. 

`com.tonyodev.fetchapp D/SingleDownloadActivity: SingleDownloadActivity Error: REQUEST_WITH_FILE_PATH_ALREADY_EXIST`

**Comment by tonyofrancis** [comment]
@sethchhim  Just released a **new** Fetch version. **2.3.0-RC1.** This version has lots of fixes and **breaking changes** so be sure to check out the [CHANGELOG](https://github.com/tonyofrancis/Fetch/releases).
This enqueueAction bug should now be fixes. Please let me know if it works well for you.

**Comment by sethchhim** [comment]
Upgrade 2.2.0-RC14 to 2.3.0-RC1 

The fix works, thank you.
