### ISSUE TITLE
Can I set the download speed limit?

### ISSUE THREAD

**Issue by runylin** [tonyofrancis/Fetch#273]
When download 3 files， other apps have very slow internet speeds. Can I set the download speed limit? like 80% of whole

**Comment by tonyofrancis** [comment]
@runylin Have a look at this related issue [192](https://github.com/tonyofrancis/Fetch/issues/192)

**Comment by tonyofrancis** [comment]
Also if you are using the Parallel Downloader. That will cause other downloads to be slow.
