### ISSUE TITLE
About tag

### ISSUE THREAD

**Issue by jacksPeak** [tonyofrancis/Fetch#274]
hi Why is the associated download tag defined as the base type？I need an Object type tag What should I do

![image](https://user-images.githubusercontent.com/13911593/47949325-f3429a80-df7b-11e8-9534-41c1d96a000c.png)
![image](https://user-images.githubusercontent.com/13911593/47949333-0eada580-df7c-11e8-8635-a11fdc6cc8dd.png)

**Comment by tonyofrancis** [comment]
@jacksPeak The tag is set as a String so that It can be saved to the database.  If you need a more structured dataset, the request and download objects have an extras property. Hope this helps.
