### ISSUE TITLE
Add Download Notification Support

### ISSUE THREAD

**Issue by tonyofrancis** [tonyofrancis/Fetch#276]
Add Download Notification Support

**Comment by tonyofrancis** [comment]
Download Notification support has been added in Fetch Version **2.3.0-RC1**. Please see the FetchNotificationManager and the DefaultFetchNotificationManager class for more information. Also see the sample project for more information.

**Comment by altaf2892** [comment]
**Notification not showing with this setting**
> ` FetchConfiguration fetchConfiguration = new FetchConfiguration.Builder(this)
                .setDownloadConcurrentLimit(5)
                .setNotificationManager(new FetchNotificationManager() {
                    @Override
                    public long getProgressReportingIntervalInMillis() {
                        return System.currentTimeMillis();
                    }

                    @Override
                    public void setProgressReportingIntervalInMillis(long l) {

                    }

                    @Override
                    public boolean updateGroupSummaryNotification(int i, @NotNull NotificationCompat.Builder builder, @NotNull List<DownloadNotification> list, @NotNull Context context) {
                        return true;
                    }

                    @Override
                    public void updateNotification(@NotNull NotificationCompat.Builder builder, @NotNull DownloadNotification downloadNotification, @NotNull Context context) {

                        if (downloadNotification.isCompleted()) {
                            Toast.makeText(PersonalChatActivity.this, downloadNotification.getDownload().getFile() + "Downloaded", Toast.LENGTH_SHORT).show();
                            builder.setSmallIcon(R.mipmap.ic_launcher_round);
                            builder.setContentText("Downloaded");

                        }
                    }

                    @Override
                    public void notify(int i) {

                    }

                    @NotNull
                    @Override
                    public PendingIntent getGroupActionPendingIntent(int i, @NotNull List<DownloadNotification> list, @NotNull DownloadNotification.ActionType actionType) {
                        return null;
                    }

                    @NotNull
                    @Override
                    public PendingIntent getActionPendingIntent(@NotNull DownloadNotification downloadNotification, @NotNull DownloadNotification.ActionType actionType) {
                        return null;
                    }

                    @Override
                    public void cancelOngoingNotifications() {

                    }

                    @Override
                    public void cancelNotification(int i) {

                    }

                    @Override
                    public void createNotificationChannels(@NotNull Context context, @NotNull NotificationManager notificationManager) {

                    }

                    @NotNull
                    @Override
                    public String getChannelId(int i, @NotNull Context context) {
                        return null;
                    }

                    @Override
                    public boolean postNotificationUpdate(@NotNull Download download, long l, long l1) {
                        return true;
                    }

                    @Override
                    public void handleNotificationOngoingDismissal(int i, int i1, boolean b) {

                    }

                    @Override
                    public long getOngoingDismissalDelay(int i, int i1) {
                        return System.currentTimeMillis();
                    }

                    @NotNull
                    @Override
                    public NotificationCompat.Builder getNotificationBuilder(int i, int i1) {
                        return null;
                    }
                })
                .setNamespace("ican").build();

        fetch = Fetch.Impl.getInstance(fetchConfiguration);
        fetch.enableLogging(true);
        fetch.addListener(this);`
