### ISSUE TITLE
SQLiteException when invoking removeAll

### ISSUE THREAD

**Issue by MaikelDegrande** [tonyofrancis/Fetch#277]
Exception occurs when trying to invoke `removeAll` on the fetch instance. 
It seems this requests all `DownloadInfo` objects from the database, extracts the ids and then performs a delete statement using those ids. The problem is that the number of ids exceeds the maximum number of permitted SQL variables.

**Stacktrace**
`2018-11-09 12:59:18.485 9425-9506/com.onlinedaisy.android.anderslezen E/SQLiteLog: (1) 
2018-11-09 12:59:18.485 9425-9506/com.onlinedaisy.android.anderslezen E/LibGlobalFetchLib: Fetch with namespace LibGlobalFetchLib error
    android.database.sqlite.SQLiteException: too many SQL variables (Sqlite code 1): , while compiling: SELECT * FROM requests WHERE _id IN (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?), (OS error - 11:Try again)
        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:925)
        at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:536)
        at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:603)
        at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:63)
        at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
        at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
        at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1397)
        at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1367)
        at androidx.sqlite.db.framework.FrameworkSQLiteDatabase.query(FrameworkSQLiteDatabase.java:161)
        at androidx.room.RoomDatabase.query(RoomDatabase.java:238)
        at com.tonyodev.fetch2.database.DownloadDao_Impl.get(DownloadDao_Impl.java:516)
2018-11-09 12:59:18.485 9425-9506/com.onlinedaisy.android.anderslezen E/LibGlobalFetchLib:     at com.tonyodev.fetch2.database.DatabaseManagerImpl.get(DatabaseManagerImpl.kt:163)
        at com.tonyodev.fetch2.fetch.FetchHandlerImpl.removeDownloads(FetchHandlerImpl.kt:227)
        at com.tonyodev.fetch2.fetch.FetchHandlerImpl.removeAll(FetchHandlerImpl.kt:214)
        at com.tonyodev.fetch2.fetch.FetchImpl$removeAll$1.invoke(FetchImpl.kt:343)
        at com.tonyodev.fetch2.fetch.FetchImpl$removeAll$1.invoke(FetchImpl.kt:14)
        at com.tonyodev.fetch2.fetch.FetchImpl$executeRemoveAction$$inlined$synchronized$lambda$1.invoke(FetchImpl.kt:371)
        at com.tonyodev.fetch2.fetch.FetchImpl$executeRemoveAction$$inlined$synchronized$lambda$1.invoke(FetchImpl.kt:14)
        at com.tonyodev.fetch2core.HandlerWrapper$sam$i$java_lang_Runnable$0.run(HandlerWrapper.kt)
        at android.os.Handler.handleCallback(Handler.java:761)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:156)
        at android.os.HandlerThread.run(HandlerThread.java:61)`

**Comment by tonyofrancis** [comment]
@MaikelDegrande This seems to be a bug or limitation with the room library. The workaround for right now is to batch this operation. Do you know how many downloads you are trying to remove when calling this method?

**Comment by tonyofrancis** [comment]
Each database has its pros and cons. In Fetch's case speed is not the only deciding factor. Room was chosen for its size, speed, stability and that it is part of the android support libraries. Some applications/companies are not able to include third party libraries like objectbox or realm in their applications for many reason.

I am still looking for a solid solution for this problem. I will post back soon.

**Comment by Karuhanga** [comment]
Just to add something tiny. Room is just an abstraction on top of sqlite which is supported by default by android.
I agree with you. I don't think introducing a different db would make sense.

Lincoln Karuhanga

-----Original Message-----

**Comment by MaikelDegrande** [comment]
@tonyofrancis 
Thanks for getting back to me so fast. The case I presented above was trying to remove roughly 1450 files. How exactly would I go about implementing such a batch operation because I'm not entirely sure if this would resolve the problem as the batch operation would still be requesting all the `DownloadInfo` objects and throw the exception when exceeding the maximum allowed SQL variables?

**Comment by jpvs0101** [comment]
> Each database has its pros and cons. In Fetch's case speed is not the only deciding factor. Room was chosen for its size, speed, stability and that it is part of the android support libraries. Some applications/companies are not able to include third party libraries like objectbox or realm in their applications for many reason.
> 
> I am still looking for a solid solution for this problem. I will post back soon.

Solid solution? So it might be give an simple interface, let the developers does rest!

**Comment by MaikelDegrande** [comment]
@tonyofrancis 
I think I might have a solution. 

After a close look at the source code I found that all remove methods are based on ids. However, the actual `removeDownloads` method (that is invoked by the other methods) might actually benefit from accepting a `List<Download>` parameter. What happens now is each and every remove method performs their specific query to retrieve a `List<Download>` (except for the first one, but I'll get back to that), this is then mapped to a `List<Int>` of ids and I believe this step to be the problem. If you were to pass the results of the query, i.e. the `List<Download>` directly to the `removeDownloads` method, it won't then have to query the downloads again using those ids. 

    val downloads = databaseManager.get(downloadIds).filterNotNull()

The `cancelDownloadsIfDownloading` method used in `removeDownloads` could also just accept the `List<Download>` and iterate that to get the ids on the fly instead of iterating the ids directly. The whole reason I suggest this is because the rest of the `removeDownloads` method operates solely on that `List<Download>`, so why retrieve them, extract the ids, only to retrieve them again using those ids. Now getting back to the first remove method `remove(ids: List<Int>)`, this is where you would then perform the `databaseManager.get(downloadIds)` query and pass the results (`List<Download>`) to the `removeDownloads`. That way each remove method queries the database for a `List<Download>` based on its specific parameter(s) and the actual `removeDownloads` method can always expect a `List<Download>` argument. I believe this would not only fix the problem, but also increase performance a little.

    override fun remove(ids: List<Int>): List<Download> {
        return removeDownloads(ids)
    }

    override fun removeGroup(id: Int): List<Download> {
        return removeDownloads(databaseManager.getByGroup(id).map { it.id })
    }

    override fun removeAll(): List<Download> {
        return removeDownloads(databaseManager.get().map { it.id })
    }

    override fun removeAllWithStatus(status: Status): List<Download> {
        return removeDownloads(databaseManager.getByStatus(status).map { it.id })
    }

    override fun removeAllInGroupWithStatus(groupId: Int, status: Status): List<Download> {
        return removeDownloads(databaseManager.getDownloadsInGroupWithStatus(groupId, status).map { it.id })
    }

    private fun removeDownloads(downloadIds: List<Int>): List<Download> {
        cancelDownloadsIfDownloading(downloadIds)
        val downloads = databaseManager.get(downloadIds).filterNotNull()
        databaseManager.delete(downloads)
        downloads.forEach {
            it.status = Status.REMOVED
            databaseManager.delegate?.deleteTempFilesForDownload(it)
        }
        return downloads
    }

**Comment by tonyofrancis** [comment]
@MaikelDegrande Thanks for pointing some of these issues out. I have not had the chance to do a proper test because I have been so busy. Will try to have a look today or tomorrow.

**Comment by tonyofrancis** [comment]
@MaikelDegrande Your solution works well and is performant! Planning on releasing later today.

**Comment by tonyofrancis** [comment]
@MaikelDegrande Fetch 2.3.1  stable is now released. Please try and let me know if this fixes the issue for you.

**Comment by MaikelDegrande** [comment]
@tonyofrancis Works like a charm!
