### ISSUE TITLE
Annoying notification sound and vibration while downloading + no view action

### ISSUE THREAD

**Issue by Zeliret** [tonyofrancis/Fetch#278]
Hi there! Thank you for this amazing library! 
I have found some small issues with a DefaultFetchNotificationManager.

1. Notification sound and vibration trigger so many times when a big file is downloading. 
2. There is no action on a final complete notification. Is it possible to open a download folder or create a new intent action for this to catch it in a custom receiver?

I know I can always override this class and fix those problems but I think while this class is a part of this library it should be as perfect as the rest code ;D 

And the last minor thing. When the downloading process is completed there is still progress bar in the notification. Probably it should be replaced with a text for example "Completed".

**Comment by tonyofrancis** [comment]
Thanks for using Fetch. The NotificationManager was added in the last version of Fetch so lots of feedback is welcome! Being that notifications are a very custom part of every app, It is strongly recommend to override the `updateGroupSummaryNotification` and `updateNotification` to customize the notification behavior as much as possible. Unfortunately there is no one size fit all solution here. The update methods passes in a cached `notificationBuilder` and `DownloadNotification ` objects. Use these to update the notificationBuilder fields accordingly.

Feedback is appropriated. I'll look into the progress bug soon.

**Comment by MohammadFneish7** [comment]
I have the same issue, during downloading any file, notifications (beep sound) keep coming out on every update, here is how I use it, knowing that I'm not facing the issue on my emulator with Android 7.1 it only appears on my mobile device with Android 9.1:

```
        FetchConfiguration fetchConfiguration = new FetchConfiguration.Builder(getApplicationContext())
                .setDownloadConcurrentLimit(3)
                .enableRetryOnNetworkGain(true)
                .enableAutoStart(false)
                .setAutoRetryMaxAttempts(3)
                .enableLogging(true)
                .setNamespace(Constants.NAMESPACE)
                .setNotificationManager(new DefaultFetchNotificationManager(getApplicationContext()) {
                    @NotNull
                    @Override
                    public Fetch getFetchInstanceForNamespace(@NotNull String namespace) {
                        return fetch;
                    }

                    @Override
                    public boolean shouldCancelNotification(@NotNull DownloadNotification downloadNotification) {
                        if (downloadNotification.getStatus() == Status.CANCELLED) {
                            return true;
                        } else {
                            return super.shouldCancelNotification(downloadNotification);
                        }
                    }
                })
                .build();
```
