### ISSUE TITLE
Getting file name before download start...

### ISSUE THREAD

**Issue by jpvs0101** [tonyofrancis/Fetch#279]
Getting file name & size before download is a very basic requirement but missing most of the libraries, I know 'Fetch' has function for getting file size, but what about file name?

**Comment by tonyofrancis** [comment]
@jpvs0101 are you talking getting the file name from header field `Content-Disposition: attachment` from the server response?

**Comment by jpvs0101** [comment]
Yep, from server, file name before starting download (Also you might be
aware that not all servers has correct name or name on their
contents-disposition, so we need to extract from redirected URL, also some
URLs are malformed, we also need to work around that)


For example:
1) I enqueued a download in Fetch
2) After that download.getRemoteFilename()

On Friday, November 9, 2018, Tonyo Francis <notifications@github.com> wrote:
> @jpvs0101 are you talking getting the file name from header field
Content-Disposition: attachment from the server response?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci5.googleusercontent.com/proxy/XxSRM741lf4jFJiR4zIxp1e4g9FiiKvGlzahfylvrSvsoattaIlva-iWkd_Y74sOdXEmZddvuPLQ1L0JuYiLg8IyQDwj_5mWRadjG4ZLX8RkipVcop38S3tn0Pgcpt6wGK_J0nwonxKFTiBuT5u9qGe0HA=s0-d-e1-ft#https://github.com/notifications/beacon/AkhD6l5tbyrnxkyITshFpooATvDG-PbXks5utbAmgaJpZM4YWw5U.gif>

**Comment by tonyofrancis** [comment]
Instead of adding a getRemoteFilename method. I think the best solution would be to provide a method that returns the server response headers and the developer can determine/extract the file name. Don't want to bog the library down with individual methods that get fields from the server response headers. The getContentLength make sense because it very commonly used.

**Comment by jpvs0101** [comment]
Hmm, will it work on redirected link?
I mean you will return the first response headers or final response
headers? because sometimes the file name is found in 1st response, some
times last, even some times not found, so we use URL to find the name!

If your solution works, then great!

As an user, I just need 3 details before download!

1) File name - to make sure I clicked the correct link and the file is
exactly what I want
2) File size - to determine whether I use mobile data or WiFi, download now
or later, size is expected or huge.
3) Resume support - to determine should I download in one shot or wait for
good signal strength.

Most importantly, it should be known BEFORE start download!

Without these, whatever is an app, its just crap!

Your library is already cool on other aspects, just need few steps to make
us to build awesome apps!

**Comment by tonyofrancis** [comment]
@jpvs0101  Fetch 2.3.1  stable is now released. Fetch has a new getServerResponse method, that returns a response object with the server response headers, contentlength etc. Please let me know if this works well for you.

**Comment by jpvs0101** [comment]
I will test it...

**Comment by jpvs0101** [comment]
I am testing getServerResponse() method...

One question:
Does getServerResponse() use request("HEAD") [requesting just headers from the server]? or other?
Because I heard that HEAD method is fast & proper way to get only just details, any other methods are slow & waste of resources!
