### ISSUE TITLE
Problems downloading files

### ISSUE THREAD

**Issue by cdn34** [tonyofrancis/Fetch#281]
In most cases I'm able to download the files using this library, however I'm not able to download files from here https://journals.plos.org/, I keep getting `EMPTY_RESPONSE_FROM_SERVER`

An example would be when trying to download from this URL:
- https://journals.plos.org/plosbiology/article/file?id=10.1371/journal.pbio.1001883&type=printable

The file is accessible by following the link on the browser. 
Running `wget "https://journals.plos.org/plosbiology/article/fileid=10.1371/journal.pbio.3000038&type=printable"` seems to work as well
And I'm also able to download it in the iOS version of the app.

**Version of the library: 2.2.0-RC12**

**Comment by tonyofrancis** [comment]
@cdn34 A newer version of Fetch was released that fixes this problem. Version 2.3.0-RC1. Please have a look at the [ChangeLog](https://github.com/tonyofrancis/Fetch/releases) as lots of breaking changes were made to improve the library.
