### ISSUE TITLE
Can we remove fetch permissions & broadcast reciever?

### ISSUE THREAD

**Issue by jpvs0101** [tonyofrancis/Fetch#284]
By default fetch implicitly add two permissions & a broadcast receiver.

<uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />

<receiver name="com.tonyodev.fetch2.FetchNotificationBroadcastReceiver"/>

How to remove the above, if none of the features required that rely on those?
For example, if we don't need notification, then no need of broadcast receiver.

**Comment by tonyofrancis** [comment]
1. The permissions are needed to check network availability and Fetch depends on those strongly. 
2. The Notification BroastcastReciever is not used if no instances of Fetch has a Notification Manager attached. Also it does not pose a security risk externally because it is not exported. So in essence it is just a declaration until needed.

**Comment by jpvs0101** [comment]
The permissions should be loosely coupled, for example why didn't you add
INTERNET permission? Dev will add when necessary, likewise for an app, its
better to give control to the dev in case of permissions, if we don't use
features like "use WiFi only to download", then we don't need access WiFi
state.

Nowadays users seriously watch permissions, some users misunderstand that
access network state permission is to monitor their work, so they scared,
that's why I asked.

Please think about it.

**Comment by tonyofrancis** [comment]
I will continue to look into this in future releases.

**Comment by jpvs0101** [comment]
@tonyofrancis
Read this XDA article https://www.xda-developers.com/android-permissions-bypass-play-store-apps/

Users will definitely scare of ACCESS_NETWORK_STATE & ACCESS_WIFI_STATE.

Consider to give option to remove those permissions as soon as possible. It is getting late. They are come close.
