### ISSUE TITLE
Download always resume from beginning, if we use uri!

### ISSUE THREAD

**Issue by jpvs0101** [tonyofrancis/Fetch#285]
#262 
I tested with uri, but the download seems to not resume. It always start from 0%.

  final FetchConfiguration fetchConfiguration = new FetchConfiguration.Builder(this)
                .setDownloadConcurrentLimit(3)
                .setProgressReportingInterval(1000)
               .setNotificationManager(new DefaultFetchNotificationManager(this))
                .setHttpDownloader(getOkHttpDownloader())
                .build();
        Fetch.Impl.setDefaultInstanceConfiguration(fetchConfiguration);

Link: any download link

**Comment by tonyofrancis** [comment]
Looking into this

**Comment by tonyofrancis** [comment]
@jpvs0101  Fetch 2.3.1  stable is now released. Please try and let me know if this fixes the issue for you.

**Comment by jpvs0101** [comment]
Hello @tonyofrancis ,
 The issue is not solved, it seems like same as before, download always starts from 0%

**Comment by tonyofrancis** [comment]
looking into this

**Comment by jpvs0101** [comment]
Waiting for this... 😊

**Comment by tonyofrancis** [comment]
@jpvs0101 this should be fixed in v2.3.2

**Comment by jpvs0101** [comment]
Awesome!

**Comment by jpvs0101** [comment]
It works!
