### ISSUE TITLE
Will deleted download entries retain in db?

### ISSUE THREAD

**Issue by jpvs0101** [tonyofrancis/Fetch#287]
We can query for DELETED status. So the question is, 
Will deleted download entries retain in db? or will it removed from after the callback?

**Comment by tonyofrancis** [comment]
@jpvs0101 You can query for a deleted status, however the operation will always return empty. When you call the delete method for a request that Fetch is currently managing, Fetch will change its status to deleted, return the download to the callback function and delete the entry from the database.
```java
     fetch.delete(request.getId(), download -> {

            //download.getStatus() is the only time a download will have a status of deleted. same goes  
           // for removed

        }, error -> {

        });
```

Note: The difference between the delete and the remove methods. The remove method will remove the request/download from Fetch's database. The delete method will remove the entry and also delete the downloaded file.

**Comment by jpvs0101** [comment]
Like I guessed, Got it!
