### ISSUE TITLE
Question: Single vs multiple connections

### ISSUE THREAD

**Issue by jpvs0101** [tonyofrancis/Fetch#289]
I heard that some download links allows only one connection at a time, in that case how will fetch react if we set Parallel option?

Will it automatically reduce connections?

**Comment by tonyofrancis** [comment]
Fetch makes an initial call to the server to see if multi connections are supported. If not the Parallel downloader will act as a Single/Sequential downloader.  This is automatic.

**Comment by jpvs0101** [comment]
Awesome awewome!
