### ISSUE TITLE
No char escaping while write http path to DB

### ISSUE THREAD

**Issue by sough** [tonyofrancis/Fetch#29]
android.database.sqlite.SQLiteException: near "text": syntax error (code 1): , while compiling: INSERT INTO requests VALUES ( 5800091702000, 'http://ex.com/some'text.txt', '/storage/emulated/0/Download/id.txt', 900, '{}', 0, 0, -1, 600 )

**Comment by sough** [comment]
Writing to db you need something like DatabaseUtils.sqlEscapeString(String). But then have to convert that string back to normal http string =(

**Comment by tonyofrancis** [comment]
@sough Thanks for catching this. Will fix and ship in next release.

**Comment by sough** [comment]
When you plan it?

**Comment by tonyofrancis** [comment]
some time next week.

**Comment by tonyofrancis** [comment]
This issue has been fixed and will make it in the next version of fetch. I will post another update in this thread.

**Comment by tonyofrancis** [comment]
Version 1.1.1 has been pushed
