### ISSUE TITLE
Background download

### ISSUE THREAD

**Issue by robbyl** [tonyofrancis/Fetch#293]
Thank you for this great library. 
Please help with an example how can I setup fetch with FetchNotificationManager so it can continue to download in the background when a user exits the app. I know it can be achieved with a background service but I can't get it to work especially with the background restrictions which requires the  service to run in the foreground.

**Comment by robbyl** [comment]
Thank you for your quick reply.
Have used the attached sample app but I can't get the app to download in the background. The download notification stays on even after I close the app and remove it from recent apps but download does not continue. Here is what have done so far

`public class DownloadBoosterApplication extends Application {

    @Override
    public void onCreate() {
        super.onCreate();

        AppCompatDelegate.setCompatVectorFromResourcesEnabled(true);
        checkAppReplacingState();

        if (BuildConfig.DEBUG)
            Timber.plant(new Timber.DebugTree());


        OkHttpClient client = new OkHttpClient.Builder().build();
        CustomDownloader customDownloader = new CustomDownloader(client);

        final FetchConfiguration fetchConfiguration = new FetchConfiguration.Builder(this)
                .enableRetryOnNetworkGain(true)
                .setDownloadConcurrentLimit(99)
                .setHttpDownloader(customDownloader)
                .setProgressReportingInterval(500)
                .setNamespace(FETCH_NAMESPACE)
                .setNotificationManager(new DefaultFetchNotificationManager(this))
                // OR
                //.setHttpDownloader(getOkHttpDownloader())
                .build();
        Fetch.Impl.setDefaultInstanceConfiguration(fetchConfiguration);

        SharedPreferences sharedPreferences = getSharedPreferences("Settings", Context.MODE_PRIVATE);

        //Schedule the periodic worker once
        if (!sharedPreferences.getBoolean("prefs_bg_downloader_scheduled", false)) {
            scheduleBackgroundDownloader();
            sharedPreferences.edit().putBoolean("prefs_bg_downloader_scheduled", true).apply();
        }
    }

    @Override
    protected void attachBaseContext(Context base) {
        super.attachBaseContext(base);
        MultiDex.install(this);
    }

    private void checkAppReplacingState() {
        Timber.d("app start...");
        if (getResources() == null) {
            Timber.d("app is replacing...kill");
            android.os.Process.killProcess(android.os.Process.myPid());
        }
    }


    private void scheduleBackgroundDownloader() {
        Constraints constraints = new Constraints.Builder()
//                .setRequiredNetworkType(NetworkType.UNMETERED)
//                .setRequiresStorageNotLow(true)
//                .setRequiresBatteryNotLow(true)
                .build();
        WorkRequest workRequest = new PeriodicWorkRequest.Builder(FileDownloaderWorker.class, 1, TimeUnit.MINUTES) //CHANGE THIS TIME TO A SHORTER TIME FOR TESTING
                .setConstraints(constraints)
                .addTag("FileDownloadWorker")
                .build();

        WorkManager.getInstance().enqueue(workRequest);
    }
}`

`public class FileDownloaderWorker extends Worker {
    private final String TAG = FileDownloaderWorker.class.getSimpleName();

    Context mContext;

    public FileDownloaderWorker(@NonNull Context context, @NonNull WorkerParameters workerParams) {
        super(context, workerParams);
        mContext = context;
    }

    @NonNull
    @Override
    public Result doWork() {
        Fetch fetch = Fetch.Impl.getDefaultInstance();

        while (fetch.getHasActiveDownloads()) {
            try {
                Thread.sleep(2000); //let the thread sleep being that fetch is using its own thread.
                Log.d(TAG, "Sleep for 2 sec");

            } catch (Exception e) {
                e.printStackTrace();
            }
        }

        return Result.SUCCESS;
    }
}`

**Comment by tonyofrancis** [comment]
@robbyl a Periodic worker is not like a Service where it runs on demand. Workers run when the constraints are met and the system deems that it is okay to do so. If I am not mistaken Workers run at a minimum of 15 minutes interval. So they should run every 15 minutes or more in in the background. Your code currently has it set to 1 mins. The Default Notification manager will dismiss a notification a shortly after no updates are received the the download is still in progress.

**Comment by robbyl** [comment]
Thank you!
I have tested the code again, the download notification stays on but actually the download does not continue, after 7 to 10 mins the download resumes and completes. I wonder why Google put time interval even in MICROSECONDS when creating a PeriodicWorkRequest and worker seems to ignore this specified interval.

**Comment by tonyofrancis** [comment]
In terms of the TimeUnit I think Google wanted to keep it standard but did make it clear in the documentation the limit. 

Are you able to share sample code, here or via Email in terms of the download notifications?. Email is on my profile page.

**Comment by robbyl** [comment]
Have decided to use AlarmManager and broadcasts. What have done is when the app exits and has active downloads I schedule a repeating alarm within 2 seconds and a receiver keeps the instance of fetch running when the app is closed and the download continues. It seems to work but have to run more tests
