### ISSUE TITLE
How to use Extras in request object to send few string values?

### ISSUE THREAD

**Issue by ramanatzoptal** [tonyofrancis/Fetch#294]
Like i want to send some string values 2-3 values and use it later
Can you please tell me how to use this   request.setExtras(); 
What values do i need to pass in this method and how ?

**Comment by jpvs0101** [comment]
One of the great featute, most useful & important thing is, extras are
persistent!

**Comment by ramanatzoptal** [comment]
Thanks i will check it and let you if there is any issue very soon
