### ISSUE TITLE
EnqueueAction.INCREMENT_FILE_NAME not working correctly when file doesn't exist

### ISSUE THREAD

**Issue by marcino1** [tonyofrancis/Fetch#298]
After performing download request for file 'file.txt' using INCREMENT_FILE_NAME and file with that name doesn't exist, two file are created, empty file 'file.txt' and 'file (1).txt' with correct content.

**Comment by tonyofrancis** [comment]
@marcino1 will check on this issue and will post back soon.

**Comment by tonyofrancis** [comment]
@marcino1 Fetch 2.3.4 has been released with this bug fix. Please let me know if it works well for you.

**Comment by marcino1** [comment]
Yes, it works fine for me. Thanks.
