### ISSUE TITLE
Get the List of all queued requests

### ISSUE THREAD

**Issue by raju249** [tonyofrancis/Fetch#30]
Hi @tonyofrancis 
This is one of the awesome library I have seen so far, very easy to user, very light weight and well documented.
I just have one question, how do I get the list of queued requests ?

Thanks for your help 😄

**Comment by tonyofrancis** [comment]
@raju249 You can get all requests from the database by status.
```java
fetch.getByStatus(Fetch.STATUS_QUEUED);
fetch.getByStatus(Fetch.STATUS_DONE);

//etc...
```

**Comment by raju249** [comment]
Ok, 
Thanks for you help  😊
