### ISSUE TITLE
Downloads failing

### ISSUE THREAD

**Issue by cdn34** [tonyofrancis/Fetch#300]
Related to a previous issue: https://github.com/tonyofrancis/Fetch/issues/281

Updating the library last time seemed to fix some of the issues I was having with the downloads, however I'm still getting issues on certain urls, here are a couple which fail consistently(_All of which are accessible by following the link_):

- http://www.jrnjournal.org/article/S1051227616000443/pdf
- https://www.jtcvs.org/article/S0022-5223(13)01519-5/pdf
- https://www.clinicalmicrobiologyandinfection.com/article/S1198-743X(14)61351-3/pdf
- http://www.anesthesiology.theclinics.com/article/S193222751400086X/pdf

Error: `com.tonyodev.fetch2.exception.FetchException: request_not_successful`
**Version of the library: 2.3.3**

**Comment by permadiberlianto** [comment]
add this
request.addHeader("Connection","close");
can solved it

**Comment by tonyofrancis** [comment]
@cdn34 Going to have a look into this and will post back soon.

**Comment by cdn34** [comment]
@permadiberlianto Thanks, but adding `request.addHeader("Connection","close");` doesn't solve the issue for me.

**Comment by cdn34** [comment]
@tonyofrancis Using the OkHttp Downloader works for all the links above when used in the following manner: 

```
  CookieManager cookieManager = new CookieManager();
  cookieManager.setCookiePolicy(CookiePolicy.ACCEPT_ALL);
  OkHttpClient okHttpClient = new OkHttpClient.Builder().cookieJar(new JavaNetCookieJar(cookieManager)).build();

 FetchConfiguration fetchConfiguration = new FetchConfiguration.Builder(context)
    .setDownloadConcurrentLimit(10)
    .setProgressReportingInterval(100)
    .setNamespace("PPBgDownloader")
    .setHttpDownloader(new OkHttpDownloader(okHttpClient))
    .build();
```

**Comment by jpvs0101** [comment]
```
 final FetchConfiguration fetchConfiguration = new FetchConfiguration.Builder(this)
                .setDownloadConcurrentLimit(3)
                .enableAutoStart(false)
                .setProgressReportingInterval(1100)
                .setHttpDownloader(new HttpUrlConnectionDownloader(Downloader.FileDownloaderType.PARALLEL))
                .build();
        Fetch.Impl.setDefaultInstanceConfiguration(fetchConfiguration);
```

For the above links, normal configuration (without OkHttp) works for me in Android. I don't know why ;)

**Comment by tonyofrancis** [comment]
Will have a look very soon. Been a very busy week for me.

**Comment by tonyofrancis** [comment]
@cdn34 Fetch 2.3.4 has been released with this improvement. a default cookie manager is set for both okhttp and httpurlconnection clients if one is not provided.
