### ISSUE TITLE
Skip downloaded files

### ISSUE THREAD

**Issue by alirezaafkar** [tonyofrancis/Fetch#301]
I think your app does not check the file size and considers file with 0 size as downloaded file. And if I delete that file manually from file manager then fetch not works.

**Comment by tonyofrancis** [comment]
@alirezaafkar I do not fully understand the problem. Can you give an example?

**Comment by tonyofrancis** [comment]
@alirezaafkar what version of Fetch are you using. Please verify that you are on the latest version.

**Comment by tonyofrancis** [comment]
@alirezaafkar are you still having this issue in the latest version of Fetch?

**Comment by alirezaafkar** [comment]
Hi. Yes I am on the latest version. Some files size are 0 kb and Fetch doesn't download them.
How do you check if a download id done? only by checking that file exist or with that size?

**Comment by tonyofrancis** [comment]
Fetch uses the content length field to get the file size. If the content length is not determined fetch will still download the file(Reading until the end of the stream). Can you share an example url I can download where the file is 0 kb and fetch will not download?
