### ISSUE TITLE
I deep clone object fail.

### ISSUE THREAD

**Issue by bangdinh** [tonyofrancis/Fetch#303]

**Comment by bangdinh** [comment]
```
public final class PiepmeObjectV2 {
    /**
     * Makes a deep copy of any Java object that is passed.
     */
    public static Object deepCopy(Object object) {
        try {
            ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
            ObjectOutputStream outputStrm = new ObjectOutputStream(outputStream);
            outputStrm.writeObject(object);
            ByteArrayInputStream inputStream = new ByteArrayInputStream(outputStream.toByteArray());
            ObjectInputStream objInputStream = new ObjectInputStream(inputStream);
            return objInputStream.readObject();
        } catch (Exception e) {
            Log.e("PiepmeObjectV2: ", e.toString());
            return null;
        }
    }
}
```

**Comment by bangdinh** [comment]
class Attach  implements Serializable {
@Nullable
    public Download download;
    public long eta = -1;
    public long downloadedBytesPerSecond = 0;
    public int id;
}

**Comment by bangdinh** [comment]
Attach attachClone = PiepmeObjectV2.deepCopy(attach);
=> attach have data
=> attachClone : null
Log catch : java.io.NotSerializableException: com.tonyodev.fetch2.database.DownloadInfo

I think com.tonyodev.fetch2.database.DownloadInfo implement Pracelable. While Object Attach implement Serializable. How to fix?
Thank so much.

**Comment by tonyofrancis** [comment]
@bangdinh the DownloadInfo class does not implement the Serializable interface but the Parcelable interface. That is the cause of the error you are experiencing. I am currently working on the next release and will implement this.

**Comment by bangdinh** [comment]
Thank @tonyofrancis . Wait for the next release. 
Nice day.!

**Comment by tonyofrancis** [comment]
@bangdinh Fetch 2.3.4 has been released. The Download class now extends Serializable. Please let me know if this works well for you.

**Comment by bangdinh** [comment]
Thank. Working perfect. Library best working for download.
