### ISSUE TITLE
Enhancements for groups

### ISSUE THREAD

**Issue by marcin-adamczewski** [tonyofrancis/Fetch#304]
Hello @tonyofrancis 

It would be nice to have things like:
1. Callback that a group has been enqueued
2. Callback with a group download progress which would be for instance the sum of progresses of all group's downloads with Status.DOWNLOADING divided by the count of downloads with status DOWNLOADING and QUEUED. 
3. Callback that group download has finished

It would be useful for example when the group has downloads for all playlist songs and you want to track playlist download progress, etc.
Btw I was missing method like 
`fetch.getDownloadsInGroupWithStatus()`  that accepts a list of statuses instead of single status.

What do you think?

**Comment by marcin-adamczewski** [comment]
@tonyofrancis Yeah, I query fetch database every two seconds either way so there wouldn't be  performance difference to me. Anyways having in on other thread won't make it problematic.
It may be also a good idea to create a method like `setGroupProgressReportingInterval`.

BTW I've just made a PR for querying groups with multiple query. Please have a look in free time.

**Comment by tonyofrancis** [comment]
@marcin-adamczewski I am looking into the group callbacks. Would it be possible for you to email  sample code with your current implementation on how you are grouping in the current fetch listener? I would like to see how Fetch interacts with the application and get an idea of how the code looks and is expected to work. Would like to see if we can get this done right the first time. My email is on my profile.

**Comment by tonyofrancis** [comment]
Still working on this. Have been very busy lately. Hoping to get some time soon.

**Comment by tonyofrancis** [comment]
@marcin-adamczewski This enhancement has been added in the next release. will report back once released.

**Comment by tonyofrancis** [comment]
@marcin-adamczewski  Fetch version 3.0.0 has been released with FetchGroupListener. Please have a look and let me know what you think. Thanks for your contribution.
