### ISSUE TITLE
Blob type files

### ISSUE THREAD

**Issue by jpvs0101** [tonyofrancis/Fetch#305]
Related to  #148 

Issue:
- Goto http://bennadel.github.io/JavaScript-Demos/demos/href-download-text-blob/ 
- Click Download
- Fetch error "UNKNOWN"

Expected behaviour:
Download the file.

I hope you can do it.

**Comment by tonyofrancis** [comment]
@jpvs0101 Looked into this a little but have not found any references to download blobs with a java client. If you are able to find code that shows its possible, I'll look into this, otherwise we will have to move on from this.

**Comment by tonyofrancis** [comment]
No hacky way I can find to be honest. This seems something specific to the Javascript world. I'll close this issue for now but if we ever find a solution we can revisit this.
