### ISSUE TITLE
play video while downloading

### ISSUE THREAD

**Issue by sajjadyousefnia** [tonyofrancis/Fetch#309]
I want to download video with this library and play the same video simultaneously, how I can do It?

**Comment by tonyofrancis** [comment]
Using the Sequential Downloader will guarantee that you are downloading the video file from bytes 0 - until complete. What you can do is monitor the download progress, say when it passes the 50% mark or 75% mark then playback can begin. Being that Fetch is a downloader library and not a video playback library that is the furthest I will be able to help. Hope this helps.
