### ISSUE TITLE
Not working correctly android 9

### ISSUE THREAD

**Issue by badrazizi** [tonyofrancis/Fetch#311]
in previous version of android tested from 4.1 to 8.1 and it's working fine but in android 9 download reach between 40% and 80% and show download completed, unable to resume since it's show download completed

**Comment by tonyofrancis** [comment]
@badrazizi Just tested on android 9 with the sample app and all downloads downloaded correctly. Can you provide a sample link and code?

**Comment by badrazizi** [comment]
Sorry for late answer i'll test with sample app and see if it's happening, I'll update you with test results, it's might be to this particular device Moto x4, I'll test it both in Moto x4 and emulator
