### ISSUE TITLE
Meaning of onCancelled, onRemoved and onDeleted in FetchListener

### ISSUE THREAD

**Issue by ankit-agrahyah** [tonyofrancis/Fetch#312]
Please explain under what conditions or states will the following methods be called from the FetchListener:
onCancelled, onRemoved and onDeleted

**Comment by tonyofrancis** [comment]
`onCancelled` - called directly after a download has been cancelled
` onRemoved` - called directly after a download has been removed from the Fetch database
`onDeleted` - called directly after a download has been deleted both file and record from Fetch database.

**Comment by jpvs0101** [comment]
@tonyofrancis Like we discussed earlier, better naming will be helpful, even if the name is long...
