### ISSUE TITLE
Question about readTimeout(), connectTimeout() in OkHttpDownloader

### ISSUE THREAD

**Issue by jpvs0101** [tonyofrancis/Fetch#315]
The documentation says 

> A value of 0 means no timeout

for both of the methods. 
But what actually happen if we set 0 for both?
Will it leads to any memory leak or something?

Because I suspect that the issue #314 is related to this settings...

**Comment by tonyofrancis** [comment]
Closing this ticket. Answer provided in #314

**Comment by tonyofrancis** [comment]
Setting the timeout to zero will allow the client to wait for as long as possible(no time limit) for a response/data. Say for example you are using okhttp in a service and setting the client read and connection timeout to 0, the client will wait on the server to respond for as long as possible, maybe forever(rare) unless something causes the socket to disconnect, such as the server closes the connection or network interface is reset. The service will be kept alive during that time. So you can view that as a memory leak if the socket is never disconnected. Those situations are rare.
