### ISSUE TITLE
Just a note when download any attachments on XDA forum or similar sites which having very defensive webserver

### ISSUE THREAD

**Issue by jpvs0101** [tonyofrancis/Fetch#318]
Note: Fetch is working correctly, root cause of this issue is webserver desing. This info may be helpful for future users.

1) Goto any XDA froum for ex; https://forum.xda-developers.com/android/apps-games/app-rootless-pixel-2-launcher-google-t3688393
2) Try to download an attachment posted on forum (apk, screenshots, etc but not the ads)
```
E/LibGlobalFetchLib: FileDownloader download:DownloadInfo(id=-20948839, namespace='LibGlobalFetchLib', url='https://forum.xda-developers.com/attachment.php?attachmentid=4416379&d=1518348771', file='content://com.android.providers.downloads.documents/document/637', group=0, priority=HIGH, headers={Cookie=__cfduid=dadeae4bb56d631a85a802c617443feab1547384518; __browsiSessionID=2ea11e66-7e81-4a0d-bc89-8b99fa4fdeb1%26false%26false%26DEFAULT%26in%262.18.3%26false; __browsiUID=913c2e72-1129-42b8-ae56-262e3b6e031d%26%7B%22bt%22%3A%22WebApp%22%2C%22os%22%3A%22Android%22%2C%22osv%22%3A%227.1.2%22%2C%22m%22%3A%22MiPad%22%2C%22v%22%3A%22Xiaomi%22%2C%22b%22%3A%22Chrome%20Mobile%22%2C%22p%22%3A1%7D; _ga=GA1.2.512760015.1547386301; _gid=GA1.2.1715350982.1547386301; _fbp=fb.1.1547384522483.1656634192; usp.45=1; usp.57=1; cto_lwid=a66dc545-837d-4552-a2a9-10eee37dc653; up_28=VR_rHjnJUcA9Jrbi0ED5mchv5x6vXMYvhL73AMRSxrseVB1baTNqH9uVOE3o4ziiuOf6aIrfdeuXlCUlj6kFtbSwsx3qSNWfFKmahBXPahcEXRyS3s1YfHIJNIDEn74NK15vROiE4fp4lwivDXzdba2vpGZwBbBIub7bhalB9fHnn4hC8tPqFLWXVC4XfvlpUKAXJo6a; usp.19=1; __gads=ID=54277eee2b2082b3:T=1547386305:S=ALNI_Ma4ER3-KFoebjQj0BvBECzXDLRHRg; __ssds=2; usp.46=1; usp.14=1; usp.17=1; usp.51_52_53_54=1; usp.24=1; usp.11=1; usp.36=1; usp.23_25_26_29_33=1; __ssuzjsr2=a9be0cd8e; __uzmaj2=711f453b-5efb-4897-bb42-eb9181b0ac4e9116; __uzmbj2=1547386311; __uzmcj2=370511019882; __uzmdj2=1547386311; usp.9=1; usp.27=1; usp.55=1; usp.22=1; usp.5=1; usp.15=1; usp.2=1; usp.42=1; PM-UL-Sync={"2":1547472755493}; DigiTrust.v1.identity=eyJpZCI6IlhxUWNnNytWUUw3UTd1NkJjY2VLcCtJRnRqMGVlN3BJWDFLVWFmcWZ4a0FWTlVEbW5WZHNsekxIcE5nNFc0QXBMVCtua0NaZzhZLzRTeTlKUktsT28rSE40Qm9Db1VtdGwvc2RWNENqTktKTHJXVjlkN3c0V3E0ZTNObWhtbmJvYmJwNDRjY2JOUW9abkc1YXZvcng2dDJuTG94czBmRGw2b3VVbldUYnZXUGFjOWhKcnM2azBMbzhTLzc0anZyU0VTaGllU3lCYTlFMzFUM2czVlN1Ukd6OHpnOGJhdEVTS1BwVkZGazhISVpNQ1R2SEtvdjMwYVdQdWYwd0tQcDNJVWJ0a0ttWHlqb2cvTDZtcHZZVWZPa2lJdko4TDJHNWdwRFROUk5WRm5iUnovem81TGRhZ0J0R0RjZ0V5KzNob3FPaWRhUjIxM0V5Si9ma0NXYmQ2dz09IiwidmVyc2lvbiI6MiwicHJvZHVjZXIiOiIxQ3JzZFVOQW82IiwicHJpdmFjeSI6eyJvcHRvdXQiOmZhbHNlfSwia2V5diI6NH0%3D, User-Agent=Mozilla/5.0 (Linux; Android 7.1.2; MI PAD Build/NJH47F; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/60.0.3112.78 Safari/537.36}, downloaded=0, total=-1, status=QUEUED, error=NONE, networkType=ALL, created=1547386439618, tag=null, enqueueAction=UPDATE_ACCORDINGLY, identifier=0, downloadOnEnqueue=true, extras={"KEY_DOWNLOAD_SUPPORTS_RESUME":"true","KEY_DOWNLOAD_FILE_NAME":"attachment (1).php","KEY_DOWNLOAD_USER_AGENT":"Mozilla\/5.0 (Linux; Android 7.1.2; MI PAD Build\/NJH47F; wv) AppleWebKit\/537.36 (KHTML, like Gecko) Version\/4.0 Chrome\/60.0.3112.78 Safari\/537.36","KEY_DOWNLOAD_SAVE_PATH":"content:\/\/com.android.providers.downloads.documents\/document\/637"})
    com.tonyodev.fetch2.exception.FetchException: request_not_successful
        at com.tonyodev.fetch2.downloader.ParallelFileDownloaderImpl.run(ParallelFileDownloaderImpl.kt:156)
        at com.tonyodev.fetch2.downloader.DownloadManagerImpl$start$$inlined$synchronized$lambda$1.run(DownloadManagerImpl.kt:101)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
```
Download failed!

Tried with every combination & permutation
Fetch version: 2.3.4 & 2.3.5
Client: Http & OkHttp
Type: Sequential & Parellel

**Update 1:**

I think I figured out the cause of issue, but not the solution.
I use  `Fetch.Impl.getDefaultInstance().getServerResponse()` to display file name, size & resume support before starting to download. This causing issue on XDA website. But other sites works normally. Also may be there are websites similar to XDA. 
So I tried  `OkHttp` instead of `Fetch.Impl.getDefaultInstance().getServerResponse()`. This also causing issue.
Finally without any 'pre-processing' the link, fetch is able to download as normal.
So from my understanding, it seems like the server behaviour. It denies connection for the second time with some constraints. But I expect a way to handle it. Hope @tonyofrancis  can fix it.

**Update 2:**
Tested several times with several download apps. Confirmed that the webserver design is very defensive. Doesn't allow to download same link multiple times. So it seems like the root cause of this issue is webserver NOT fetch library!

**Comment by tonyofrancis** [comment]
@jpvs0101 What I can do I add a new method to the downloader interface that when anyone is experiencing this issue can turn off Fetch's behavior to do a pre check. Stay turned working on a fix.

**Comment by jpvs0101** [comment]
> @jpvs0101 What I can do I add a new method to the downloader interface that when anyone is experiencing this issue can turn off Fetch's behavior to do a pre check.
> 
> Edit: Just read you updated 2 comment again. Yeah there is nothing really Fetch can do to prevent a back to back call for information from the server. The best thing to do may be to wait an additional 5 seconds or more and try the server again.

Correct, the XDA webservers are extremely bulletproof, I guess they setup this to prevent server overload. Even if we reconnect after few seconds, it still refuses. So obviously we can't do anything from our side.
