### ISSUE TITLE
downloading file not being paused with download id

### ISSUE THREAD

**Issue by altaf2892** [tonyofrancis/Fetch#32]
project links removed code snippet commented

**Comment by tonyofrancis** [comment]
Ill have a look at the sample and will post back here

**Comment by tonyofrancis** [comment]
@altaf2892 Have not been able to have a look at your code. Can you replicate the issue and post the logs here? Do the downloadId match the request id you want to pause?

**Comment by altaf2892** [comment]
> see below implementation to pause running download onclkick

`if (fetch != null) {
                    List<RequestInfo> requestInfo = fetch.get();
                    for (int i = 0; i < requestInfo.size(); i++) {
                        if (requestInfo.get(i).getId() == model.getId()) {
                            Log.e("match", requestInfo.get(i).getId() + "  " + model.getId());
                            try {
                                fetch.pause(model.getId());

                            } catch (Exception e) {
                                Toast.makeText(holder.itemView.getContext(), e.toString(), Toast.LENGTH_SHORT).show();
                            }
                        }
                    }
                } else {
                    Toast.makeText(holder.itemView.getContext(), "error occurred", Toast.LENGTH_SHORT).show();
                }
            }`

**i get printed log with same match id but downloading not getting pause**

**Comment by tonyofrancis** [comment]
@altaf2892 you do not have to get all the requests from fetch in order to match the one you are looking for. Simply call `fetch.get(downloadId)` and it will return the request if it exists. Attach a FetchListener to fetch before performing any operations in order to get status updates of a request. Have a look at the sample code in this project.

**Comment by altaf2892** [comment]
as u suggested  i did but the problem is if i have same video in a downloading and its paused or any other but not downloading  and if i request for same file its getting started downloading but not getting paused ....
`holder.pause.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Toast.makeText(holder.itemView.getContext(), "paused click", Toast.LENGTH_SHORT).show();
                //      listener.performClick(model.getDownloadId() + "");
                Log.e("idlog" + " adapter", model.getDownloadId() + "");

                if (AppService.fetch != null) {

                    try {
                        fetch.pause(model.getDownloadId());
                        dbHelper.UpdateVideo(model);
                        Toast.makeText(holder.itemView.getContext(), model.getStatus(), Toast.LENGTH_SHORT).show();

                    } catch (Exception e) {
                        Log.e("catch:  pause", e.toString());
                        Toast.makeText(holder.itemView.getContext(), e.toString(), Toast.LENGTH_SHORT).show();

                    }
                } else {
                    Toast.makeText(holder.itemView.getContext(), "error occurred", Toast.LENGTH_SHORT).show();
                }


            }
        });`

**Comment by tonyofrancis** [comment]
@altaf2892 Are you sure you are pausing the right request with the right id? Please compare the id when you have enqueued the request with the model id when you are clicking the pause button. I do have a feeling they do not match.
