### ISSUE TITLE
Different downloaded file size compare to other download method

### ISSUE THREAD

**Issue by JumpLizard** [tonyofrancis/Fetch#320]
Hi, thanks for this awesome library! I got one question: when downloading m3u8 segment files from the link below, the files are always smaller than downloaded via other method, like browsers or Android default DownloadManager. Please help.

The download link is a little complicated because it has some protection, so sorry for that.

1. The original link is: [https://9xbuddy.org/process?url=https://www.zee5.com/movies/details/desi-boyz-2011-hindi-drama/0-0-8241](https://9xbuddy.org/process?url=https://www.zee5.com/movies/details/desi-boyz-2011-hindi-drama/0-0-8241)

2. Download the 256x144 m3u8 file, with a specified user-agent (it'll be used later). The link should be in the following format: 
`https://zee5vodnd.akamaized.net/hls1/1080p/movies/MOVIE_PROJECT/HINDI/26112018/DESI_BOYZ_MOVIE_hi.mp4/media-1/stream.m3u8?[some_token]`

3. Open the .m3u8 file, you'll get a set of segment file links. Except the first key file, all links are formatted as follows: `segment-0.ts?[another_token]`. You need to concatenate this part after the base url:
`https://zee5vodnd.akamaized.net/hls1/1080p/movies/MOVIE_PROJECT/HINDI/26112018/DESI_BOYZ_MOVIE_hi.mp4/media-1/`

4. Now you'll get a link formatted as follows: 
`https://zee5vodnd.akamaized.net/hls1/1080p/movies/MOVIE_PROJECT/HINDI/26112018/DESI_BOYZ_MOVIE_hi.mp4/media-1/segment-0.ts?[another_token]`. Downloading this file with the specified user-agent.

This is the file that cause the problem. For example, the size of `segment-0.ts` should be 41184 bytes. But via `Fetch 2`, the size is always smaller.

**Comment by tonyofrancis** [comment]
@JumpLizard what version of Fetch are you using.?Also what is your Fetchconfiguration/downloader  settings?

**Comment by JumpLizard** [comment]
The issue occurs on v2.3.6 and v2.3.3 (not tested other versions). Set max download to 5 in configuration, changed user-agent in request.

**Comment by JumpLizard** [comment]
Didn't change that configuration. So it should be the default setting.

**Comment by JumpLizard** [comment]
Ah, I also changed network type in configuration.

**Comment by JumpLizard** [comment]
Find some dirrerences: when downloading via browser, the response code is 200, and there's no "Range" header; while downloading via Fetch 2, the response code is 206, with "Range" header. Is this related?

**Comment by JumpLizard** [comment]
Added some screenshots. 1 & 2 are response and request from a PC Firefox browser, the Content-Length is 41184; 3 &4 are response and request from Fetch 2, the Content-Length is 41172.

![image 1](https://user-images.githubusercontent.com/46725178/51240333-6f168580-19b6-11e9-823a-47a2837d7f34.png)
![image 2](https://user-images.githubusercontent.com/46725178/51240348-750c6680-19b6-11e9-95d2-98751740ae51.png)
![image 3](https://user-images.githubusercontent.com/46725178/51240356-78075700-19b6-11e9-87bf-830ac6018797.png)
![image 4](https://user-images.githubusercontent.com/46725178/51240364-7a69b100-19b6-11e9-9336-9131dc640b62.png)

**Comment by tonyofrancis** [comment]
@JumpLizard Just had a look at your code and it does not seem like the issue. mhhmmm. Fetch has been using the range header field from day one to get the size of the download. So if it worked in previous versions then it should work in newer versions just like before. 

1. Are you fetching from the same server you used prior when it worked?
2. The range returned by the server will not always be the same size. This depends of if the download was paused. Fetch will only request data from the paused starting point to the end of the stream. 
3. Are you able to test this on a different server/service???

If Fetch is downloading the other files fine with no issue, then it should download any file with no issue unless the server is performing correctly.

**Comment by JumpLizard** [comment]
@tonyofrancis 
1. No, it works from other servers, which always works.
2. The downloads haven't been paused. The size is very small.
3. Since this problem never happened before, I don;t know there's other server could trigger this problem.

Are you working on this project now? If so, I could generate a link for you. I know it's complicated. But I need your test device user-agent.

**Comment by tonyofrancis** [comment]
If you generate a link I can test

**Comment by JumpLizard** [comment]
@tonyofrancis Could you provide your test device user-agent? The server checks this.

**Comment by JumpLizard** [comment]
Or I could provide a user-agent to you.

**Comment by JumpLizard** [comment]
ua: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0

https://zee5vodnd.akamaized.net/hls1/1080p/movies/MOVIE_PROJECT/HINDI/26112018/DESI_BOYZ_MOVIE_hi.mp4/media-1/segment-0.ts?hdntl=exp=1547745825~acl=/*~data=hdntl~hmac=f0743c8b4d9a4f21db5c76854535d8ce8de21ab918818885c681cf8f57376ccb&aka_me_session_id=AAAAAAAAAAAhukBcAAAAAI%2fjuQry4Cc26YfqMWKKSJZteCsTDtrUszv71+GhDq0fIfaToMbMPAARP1+cA0mW%2fRiNMHC1NjBN&aka_msn=0&aka_hls_version=4

**Comment by JumpLizard** [comment]
The correct file size should be 41184 bytes.

**Comment by tonyofrancis** [comment]
The server is returning 41172 bytes for the content-length. Which is wrong if it should be 41184 bytes.
The range request Fetch makes is `bytes=0-` Which tells the server we need all content bytes from position 0 bytes to end bytes. Seems like the server is sending the wrong content length when a 206 connection is made. Strangely if the request does not contain the range header the content length is 41184 for a 200 connection. The only work around I have for this below.
```java
 final FetchConfiguration fetchConfiguration = new FetchConfiguration.Builder(this)
                .setHttpDownloader(new CustomDownloader(Downloader.FileDownloaderType.SEQUENTIAL))
                .build();
        final Fetch fetch = Fetch.Impl.getInstance(fetchConfiguration);

   public class CustomDownloader extends HttpUrlConnectionDownloader {

        public CustomDownloader(@NotNull Downloader.FileDownloaderType fileDownloaderType) {
            super(fileDownloaderType);
        }

        @Nullable
        @Override
        public Void onPreClientExecute(@NotNull HttpURLConnection client, @NotNull com.tonyodev.fetch2core.Downloader.ServerRequest request) {
            super.onPreClientExecute(client, request);
            client.setRequestProperty("Range", "");
            return null;
        }
    }
```
This will prevent a range request. So the http response code will be 200 with the right content length. Let me know if this works well for you. **Note that is will not support resume of downloads. If you will want to support download resume, you will need to contact the server administrator and inform them of this.**

**Comment by JumpLizard** [comment]
Thanks, I'll try it. One question: I've tried to change the Range header, in 

```...
.setHttpDownloader(OkHttpDownloader(
		OkHttpClient.Builder().addInterceptor { chain ->
			val newRequestBuilder = chain.request().newBuilder()
					.addHeader("Range", "")
			chain.proceed(newRequestBuilder.build())
		}.build()
))
...
```
and 

```request.addHeader("Range", "")```

But neither works. Is your code the only way to change it?

**Comment by tonyofrancis** [comment]
thats because it needs to be change in the onPreClientExecute method of the downloader

**Comment by JumpLizard** [comment]
@tonyofrancis Sorry, I got onError in callback listener. The error info is UNKNOWN_IO_ERROR.

**Comment by tonyofrancis** [comment]
change the Parallel download type to Sequential. Being that you are not using range support you are unable to use the parallel downloader.

**Comment by JumpLizard** [comment]
Finally, it works. Thanks so much for you generous help!

**Comment by tonyofrancis** [comment]
No problem!
