### ISSUE TITLE
fetch.getHasActiveDownloads() issue!

### ISSUE THREAD

**Issue by jpvs0101** [tonyofrancis/Fetch#322]
I check `fetch.getHasActiveDownloads()` to stop the download service. But it sometimes wrongly stops the service even if there is pending downloads. So I dig through the code, I guess you missed this `'${Status.ADDED}', '${Status.NONE}'` in the below code.

```
private val pendingCountQuery = "SELECT ${DownloadDatabase.COLUMN_ID} FROM ${DownloadDatabase.TABLE_NAME}" +
            " WHERE ${DownloadDatabase.COLUMN_STATUS} = '${Status.QUEUED.value}'" +
            " OR ${DownloadDatabase.COLUMN_STATUS} = '${Status.DOWNLOADING}'"

    override fun getPendingCount(): Long {
        synchronized(lock) {
            return try {
                val cursor: Cursor? = database.query(pendingCountQuery)
                val count = cursor?.count?.toLong() ?: -1L
                cursor?.close()
                count
            } catch (e: Exception) {
                -1
            }
        }
    }
```

May be I am wrong, but issue is there...

**Comment by tonyofrancis** [comment]
So the query will only search for downloads that are **pending**. Pending meaning downloading or queued for downloading. Downloads with the status of added are not considered active. Its just a record in the database until they are set to queued by calling resume or retry. The database calls are synced so the call will always provide the latest snapshot at the time it is called.

**Comment by jpvs0101** [comment]
Hmm, seems like db latency. But it is critical. I check for pending downloads when every download complete call back. I guess the millisec difference closes the download service. Below is my logic.

```
downloadCompleteCallback() -> closeServiceIfNoActiveDownloads();

closeServiceIfNoActiveDownloads(){
   if (! fetch.getHasActiveDownloads())
      service.stopSelf();
}
```

Any work around?

**Comment by tonyofrancis** [comment]
@jpvs0101 I will try to have a look over the weekend.

**Comment by tonyofrancis** [comment]
Still  looking into this. Have been very busy lately. Hoping to get some time soon.

**Comment by munix** [comment]
I have the same issue

**Comment by tonyofrancis** [comment]
@jpvs0101 @jpvs0101 Fetch v3.0.1 has been released with a new method hasActiveDownloads(includeAddedDownloads: Boolean, func: Func<Boolean>).  Please test and let me know how it works for you.`Fetch.hasActiveDownloads` has not been deprecated yet until I get feedback.

@jpvs0101 Thanks for your proposed solutions but they would not work well inside the Fetch library especially with version 3 now allowing users of the library to create their own fetch database managers.

**Comment by jpvs0101** [comment]
> @jpvs0101 @munix Fetch v3.0.1 has been released with a new method hasActiveDownloads(includeAddedDownloads: Boolean, func: Func). Please test and let me know how it works for you.`Fetch.hasActiveDownloads` has not been deprecated yet until I get feedback.
> 
> @jpvs0101 Thanks for your proposed solutions but they would not work well inside the Fetch library especially with version 3 now allowing users of the library to create their own fetch database managers.

Seems like hasActiveDownloads(includeAddedDownloads: Boolean, func: Func) works. Actually it checks for both Added & Queued downloads. I found it by digging the source code. I think you should clearly mention this in the documentation. 

Also I love you added new fields on the Download objects. Fields: etaInMilliSeconds, downloadedBytesPerSecond. Phew... relief of complex wiring implementation recycler adapter!
Thanks for these simplification.

**Comment by tonyofrancis** [comment]
@jpvs0101 sounds good! Thanks for your feedback. I will def clean and update the documentation. Will remove the old Fetch.hasActiveDownloads method in the next release.

**Comment by tonyofrancis** [comment]
@jpvs0101 Shameless plug but I do value your feedback. Please check out my other library [Dispatcher](https://github.com/tonyofrancis/Dispatcher ) and let me know what you think.

**Comment by jpvs0101** [comment]
> @jpvs0101 Shameless plug but I do value your feedback. Please check out my other library [Dispatcher](https://github.com/tonyofrancis/Dispatcher) and let me know what you think.

@tonyofrancis Sorry, I have no interest/need on that lib, so i can't give you useful feedback!
But all the best for the new library. Thanks!
