### ISSUE TITLE
Issue with .enqueue() parameters after upgrading from 2.1.0 to 2.3.6

### ISSUE THREAD

**Issue by Greg222777** [tonyofrancis/Fetch#323]
Hello, 

I'm trying to upgrade from 2.1.0-RC15 to 2.3.6 and can't figure out the changes.  I was using `fun enqueue(request: Request, func: Func<Request>? = null, func2: Func<Error>? = null): Fetch`

Here is my code using 2.1.0 : 

```
fetch.enqueue(request, new Func<Request>() {
			@Override
			public void call(Request request) {
				///
			}
		}, new Func<Error>() {
			@Override
			public void call(Error error) {
				//
			}
		});
```

After upgrading to Fetch 2.3.6, I only have     `fun enqueue(request: Request): Convertible<Request>`.  Which doesn't work with sample code : 

```
        fetch.enqueue(request, updatedRequest -> {
            //Request was successfully enqueued for download.
        }, error -> {
            //An error occurred enqueuing the request.
        });
```

Am I missing something obvious ?  How can I get the request callbacks with the new method ?

**Comment by tonyofrancis** [comment]
@Greg222777 The method signature for enqueue has not changed. Seems like you have the RxFetch dependency but no the Fetch dependency added to your project. Double check that you application has the right dependencies and or perform a clean on the project. Hope this helps.

**Comment by Greg222777** [comment]
> @Greg222777 The method signature for enqueue has not changed. Seems like you have the RxFetch dependency but no the Fetch dependency added to your project. Double check that you application has the right dependencies and or perform a clean on the project. Hope this helps.

Ok so you put me in the right direction and I was able to correctly point the issue. 

I'm using an RXFetch singleton.  In 2.1.0, RXFetch extends Fetch (interface RxFetch : Fetch).  While in 2.3.6, it doesn't (interface RxFetch).  So I am unable to use the correct enqueue method and can only access the one in RXFetch, which doesn't take functions.

I can always work around this by not using RxFetch, but I'd like to know if this is normal, and how I should be using my singleton to access both RX-specific getDownloads(), and Fetch's enqueue().  Hope it is clear.  Thanks for your help.

**Comment by tonyofrancis** [comment]
@Greg222777 The method returns a converterable object which you can get a flowable or observable from. When you subscribe to the observable you can pass in a action callback for success and one for failure. You should be able to use RxFetch with little modification to your current code.

**Comment by Greg222777** [comment]
Converting enqueue to RX indeed works.  Thank you for the quick help !
