### ISSUE TITLE
Question: Is it possible to download using POST instead of GET

### ISSUE THREAD

**Issue by rs-georg** [tonyofrancis/Fetch#325]
Hi,

I need to download files from a server using a POST request instead of a GET request.
So, is it possible to do this with Fetch?

thanks

**Comment by tonyofrancis** [comment]
@rs-georg Fetch is fully customizable. Please have a look at the sample app and other closed issues for more help. If you get stuck on a specific issue. We are more than happy to guide you.

**Comment by rs-georg** [comment]
Hi @tonyofrancis,

thanks for your response.
I have another question: Is it possible to have a download consist of two requests?

The API I'm using requires to send a 'prepare download' request before sending the actual download request. Is it possible with Fetch to do this?

thanks

**Comment by rs-georg** [comment]
Oh, OK, I see. I could just use a custom `Downloader` instance. Right?

**Comment by tonyofrancis** [comment]
@rs-georg Yup. You are right. You can used a custom downloader and handle all the calls you need there.
