### ISSUE TITLE
Pause recently Added Requests won't work

### ISSUE THREAD

**Issue by Mahan3340** [tonyofrancis/Fetch#326]
Assume that the user wants to pause the download as soon as it just enqueued for the first time, then, it is not going to work till its status is changed to at least, Started or maybe this is happened due to the delay between calling enqueue function and the download request actually being added to database and so on, I call the enqueue function as soon as the click event is triggered so that's why I wonder this might be the problem. Then another tap is required to pause the download. I've tested this and have got this results and I think it's not much of a good experience for the user. correct me if i'm missing anything.

**Comment by tonyofrancis** [comment]
@Mahan3340 looking into this. Will post back soon.

**Comment by tonyofrancis** [comment]
@Mahan3340 Just doubled checked. Calling pause on any download with a status of Queued and Downloading will pause the Download. If the download does not have a status of queued or Downloading ,it will not get paused. Can you share logs. You can Enable Fetch logging with the FetchConfiguration builder. Also can you share an example of a request you enqueue?.

**Comment by Mahan3340** [comment]
I have to check again maybe its just in another state, this happens to downloads with very small size which, even when I request pause it will be downloaded anyway. Maybe it wont pause soon enough so it would be downloaded by that time. I'll check again and will let you know with logs and more details

**Comment by Mahan3340** [comment]
I tested again and the problem is just with very small files that will be downloaded fast and pause action wont get a chance to be done. its reasonable result so I will close the issue for now
