### ISSUE TITLE
Rename Request File

### ISSUE THREAD

**Issue by Mahan3340** [tonyofrancis/Fetch#328]
Due to some reasons I first download a file with a temporary name and then rename the file to the desired one after its completely downloaded. for this case, I have to update the request in order to contain the correct path for later usage But I have to create a new Request object which will have a different ID,  though it may be a good idea to add simple functions to Request Object to be able to modify file Path (which will update URI, download object if needed,... behind the scene as a result).
or to be cleaner I guess you could add a feature to save the file to a temporary file (set by a boolean maybe or a temporary path and then moving to desired path ,.. ) and then rename it to the final desired name when its completed so nothing is needed to be done on our side.

**Comment by tonyofrancis** [comment]
A new method will be added in the next version of Fetch. will post back soon

**Comment by Mahan3340** [comment]
@tonyofrancis just wanted to mention that currently updateRequest will have a download with ADDED status which i guess that should just replace the request will the same download

**Comment by tonyofrancis** [comment]
@Mahan3340  Fetch version 3.0.0 has been released and it includes this method. Please see the changelog

**Comment by Mahan3340** [comment]
@tonyofrancis thank you so much
