### ISSUE TITLE
re-download file asset game

### ISSUE THREAD

**Issue by devluckman** [tonyofrancis/Fetch#329]
I tried to follow the sample app available on Github to download game assets, but there was a bug when the game asset files were deleted or moved failed to download again and file downloaded to 0B.
source code : 
` val requestList : List<Request> = requests!!

        for (request in requestList) {

            request.groupId = groupId }

        enqueueDisposable = rxFetch!!.enqueue(requestList).flowable.subscribe({ updatedRequests ->

            for ((first) in updatedRequests) {

                fileProgressMap[first.id] = 0

                updateUIWithProgress()}

        }, { throwable ->

            val error = getErrorFromThrowable(throwable)

            Toast.makeText(this, "onEnqueue : "+error.toString(), Toast.LENGTH_SHORT).show()})

`
please help .. thank you

![test](https://user-images.githubusercontent.com/25347788/53314738-866c5b00-38f2-11e9-8dca-ea3c3a91451b.jpeg)

**Comment by tonyofrancis** [comment]
@devluckman By default each new request has an enqueue action of `UPDATE_ACCORDINGLY`eg: `request.enqueueAction = UPDATE_ACCORDINGLY;` See documentation:
```
   /** If Fetch is already managing an existing request with the same file path do one the following:
     * 1: If existing download is completed, Fetch will call onComplete method on attached Fetch Listeners.
     * 2: If existing download is not completed, resume download normally.
     * 3: If not downloaded, download will proceed normally.
     * Note: If download is existing, Fetch will update the old request/download with the new settings on
     * from the request object.
     * */
```
What you are looking for is `request.enqueueAction = REPLACE_EXISTING`

Once a download completes, Fetch will no longer check if the file was moved or deleted. Hope this helps.

**Comment by devluckman** [comment]
Thank you, @tonyofrancis , it's very helpful ... good luck always

**Comment by MahdiPishguy** [comment]
in new version of this library you can use this code:

`request.setEnqueueAction(EnqueueAction.REPLACE_EXISTING);`
