### ISSUE TITLE
Exception download exception

### ISSUE THREAD

**Issue by tejas-simprosys** [tonyofrancis/Fetch#33]
com.tonyodev.fetch.exception.DownloadInterruptedException: DIE
 at com.tonyodev.fetch.FetchRunnable.run(FetchRunnable.java:128)
 at java.lang.Thread.run(Thread.java:856)

In sample when i am start single download getting this exception.

**Comment by tonyofrancis** [comment]
@tejas-simprosys Does it crash the app? Can you explain more/steps of what is happening?

**Comment by TosinAF** [comment]
I got this happening to me if i queue 2 downloads and the concurrent limit is not 1. What would cause the thread to be interrupted?

**Comment by s9iper1** [comment]
whats the solution any one ?
