### ISSUE TITLE
Downloading strategy

### ISSUE THREAD

**Issue by ahar** [tonyofrancis/Fetch#332]
Hey @tonyofrancis !

First of all, thank you for your library. We are using it, and love it so far :) 

Secondly, I have a question. When I try to apply new download concurrent limit, fetch starting downloading files in unpredicted way. It can start download new files, and files with progress put on pause, either in different way. 

Do you have mechanism to control this downloading priority? 
For example, start with files with progress already/start with new files/FIFO/LIFO/etc. 

Thanks

**Comment by tonyofrancis** [comment]
@ahar can you share a sample project???
