### ISSUE TITLE
When pause & resume file get corrupted

### ISSUE THREAD

**Issue by rranjithkumar100** [tonyofrancis/Fetch#334]
First thanks for awesome library.
Everything working fine for me - except file resume.

### **Issue**
If I pause & resume the file it get corrupted. After 100% downloaded its not open. 

Note : It working fine if we not pause the file till completed. 

### **Corruption Detail**
For ex: Pdf download completed -> if I open pdf  it return "Cannot display pdf" error

### **Code Details**
used version -    **implementation "com.tonyodev.fetch2:fetch2:2.3.6"**

### **My initialisation code with okhttp**

     okhttp3.OkHttpClient okHttpClient = new OkHttpClient.Builder().build();

        FetchConfiguration fetchConfiguration = new FetchConfiguration.Builder(context)
                .setDownloadConcurrentLimit(30)
                .setHttpDownloader(new OkHttpDownloader(okHttpClient))
                .enableAutoStart(true)
                .enableRetryOnNetworkGain(true)
                .build();

        fetch = Fetch.Impl.getInstance(fetchConfiguration);

Pause using - fetch.pause(downloadId);
Resume using - fetch.resume(downloadId);

### **Device details**  
Moto C (Android 7.0) , Redmi Note 5 pro (android 8.1).. All devices my file get corrupted. 

My assumption - we are using headers for file authentication. This make the problem for resume?

**Comment by tonyofrancis** [comment]
@rranjithkumar100 Its hard to help with such issues without sample code. Is it possible you can email me sample code that recreates the issue. My email is on my profile.

Also latest version of Fetch is 3.0.1

**Comment by rranjithkumar100** [comment]
Hi @tonyofrancis We have authentication header in our project. So I can't sent sample project. If you want to see I will send entire project. Its chatting app. 

Its ok for you?

**Comment by tonyofrancis** [comment]
@rranjithkumar100 sure I will try to help as much as possible.

First can we make sure the downloader uses the Senquential downloader type.
eg
```java
new OkHttpDownloader(okHttpClient,
                Downloader.FileDownloaderType.SEQUENTIAL);
```

Also in order for Fetch to resume the download it sends the header value to continue download
at that location.
eg:
```java
val downloadedBytes = 66 //eg
request.addHeader("Range", "bytes=$downloadedBytes")
```
Please ensure that your server accepts this header and handles it correctly.

If that fails we can chat over skype or something.

**Comment by rranjithkumar100** [comment]
@tonyofrancis I will check and update you today. Thanks for the help.

**Comment by rranjithkumar100** [comment]
@tonyofrancis 

I tried 
new OkHttpDownloader(okHttpClient,
                Downloader.FileDownloaderType.SEQUENTIAL); 

Not working. 

"Range" header they not give support for me . 

Can you give how to I clear the previous download request? 
If I give fetch.enqueue() it will auto-resume and file corrupted

How can I download again with new request. 
1. fetch.delete(id) 
2. fetch.cancel(id) 
3. fetch.remove(id)

**Comment by rranjithkumar100** [comment]
I called all of them now its working fine.

**Comment by tonyofrancis** [comment]
@rranjithkumar100 all you have to do is set the proper `EnqueueAction` on the request. In your case `EnqueueAction.REPLACE_EXISITING` would delete the old request and always start at the beginning.

eg:
```java
 request = new Request(url, filePath);
 request.setExtras(getExtrasForRequest(request));
 request.setEnqueueAction(EnqueueAction.REPLACE_EXISTING);
fetch.enqueue(request, callback, errorcallback);
```
