### ISSUE TITLE
failed to enque, Func.Error call() method gets called every time

### ISSUE THREAD

**Issue by SoheibBettahar** [tonyofrancis/Fetch#335]
here's my code : 
val fetchConfiguration = FetchConfiguration.Builder(this)
            .setDownloadConcurrentLimit(1)
            .enableAutoStart(false)
            .enableLogging(false)
            .setNamespace("main")
            .build()

        fetch = Fetch.Impl.getInstance(fetchConfiguration)

        binding.detailButtonDownload.setOnClickListener {
            val url = getString(R.string.monokrome_url)
            val folder = File("${Environment.getExternalStorageDirectory()}/magazines")
            val monokrome = File(folder, "magazine")
            if (!folder.exists()) {
                folder.mkdir()
            }
            val request = Request(url, monokrome.path + ".pdf")
            request.priority = Priority.HIGH
            request.networkType = NetworkType.ALL
            request.addHeader("clientKey", "SD78DF93_3947&MVNGHE1WONG")
            // DownloadClass.download(fetch, request, application)
            fetch.enqueue(request, Func {
                Toast.makeText(applicationContext, "Called", Toast.LENGTH_SHORT).show()

            }, Func {
                Toast.makeText(applicationContext, "Error", Toast.LENGTH_SHORT).show()
            })
        }

**Comment by tonyofrancis** [comment]
@SoheibBettahar  What is the error you get? The function should return the exact error.
