### ISSUE TITLE
how to add listener for each download

### ISSUE THREAD

**Issue by diousk** [tonyofrancis/Fetch#338]
Hi,

I'm using v3.0 and there's a method called 'attachFetchObserversForDownload'.
I setup a button to click to enqueue a download(with different url for each click) to fetch instance,
but I found the FetchObserver become abnormal after I click twice or more on the button 
(the onChanged event not trigger properly)

the enqueue code is below

`request = new Request(url, filePath);`
`        request.setExtras(getExtrasForRequest(request));`
`        fetch.attachFetchObserversForDownload(request.getId(), new FetchObserver<Download>() {`
`            @Override`
`            public void onChanged(Download data, @NotNull Reason reason) {`
`                log("data = " + data.getUrl() + " reason " + reason);`
`                if (reason == Reason.DOWNLOAD_PROGRESS_CHANGED) {`
`                    log("data " + data.getUrl() + ", progress= " + data.getProgress());`
`                } else if (reason == Reason.DOWNLOAD_ERROR) {`
`                    log("data " + data.getUrl() + ", error= " + data.getError() + ", t=" + data.getError().getThrowable());`
`                }`
`            }`
`        });`

Since I don't want a global listener for all download event, 
is there any way to achieve "a listener for a download"?

**Comment by tonyofrancis** [comment]
@diousk your event listener for each download should work correctly. Are you enqueuing the same request each time?. Same url and filePath???? What you mean by abnormal? Does the first download listener get triggered and not the second?
