### ISSUE TITLE
Fetch vs built-in DownloadManager

### ISSUE THREAD

**Issue by hardcodet** [tonyofrancis/Fetch#339]
Hi all! I'm (very) new to Android development, and need to build background downloads into my app. Basically, all I need is to

- enqueue download jobs
- make sure downloads continue if the user leaves/kills the app
- have downloads resume in case of connectivity issues
- know once they have completed or failed

I really care mostly about stability across a wide range of devices rather than more specific features. Are there any reasons I should use a proprietary library like Fetch for this over the built-in DownloadManager? Thanks!

**Comment by tonyofrancis** [comment]
@hardcodet It depends on what you need. The build in download manages does not give you access to pause or resume through your app. That is handled by the system. If that works for you then use it. If your app requires you to pause and resume within the app, you will need to use another library to handle that. Fetch is not proprietary. It is open source. You are allows to copy the source code and use it how you want. Hope this helps.

**Comment by hardcodet** [comment]
It does - thanks for the response @tonyofrancis . And thanks for putting all the effort into the library! 👍 👍 👍
