### ISSUE TITLE
How can I download a file that has already been downloaded?

### ISSUE THREAD

**Issue by waister** [tonyofrancis/Fetch#34]
For example, the user downloaded a file and then deleted it from the sdcard. In the future, he wants to download the file again, but Fetch throws the exception:
EnqueueException: DatabaseHelper already containsFilePath a request with the filePath: [...]

Is there a way to force the download?

Thanks for lib!

**Comment by tonyofrancis** [comment]
@waister Every time the FetchService starts, its verifies the database by checking that the downloaded files still exist. If a file was deleted or cannot be accessed, the service sets the request status to `Fetch.STATUS_ERROR` with an error value of `Fetch.ERROR_FILE_NOT_FOUND`.

What you can do is query fetch for the request and check its status. If the status is invalid, remove the request and enqueue again. Example:

```java
        final Request request = new Request("url","dirPath","fileName");
        final RequestInfo requestInfo = fetch.get(request);

        if(requestInfo != null && requestInfo.getStatus() == Fetch.STATUS_ERROR
                && requestInfo.getError() == Fetch.ERROR_FILE_NOT_FOUND) {

            //Listen for when the request has be removed
            fetch.addFetchListener(new FetchListener() {
                @Override
                public void onUpdate(long id, int status, int progress, long downloadedBytes, long fileSize, int error) {

                    if(id == requestInfo.getId() && status == Fetch.STATUS_REMOVED) {
                        //Enqueue request
                        long downloadId = fetch.enqueue(request);
                        
                        //Save downloadId....
                        
                        fetch.removeFetchListener(this);
                    }
                }
            });

            fetch.remove(requestInfo.getId());
        }else {
           long downloadId =  fetch.enqueue(request); //Save downloadId....
        }
```
Let me know if this works how you except.

**Comment by waister** [comment]
Now it worked!!!
Thank you very much for the help and I'm sorry I did not respond.

**Comment by NainalChauhan** [comment]
How to check if the file has been deleted from sdcard using the new Fetch2 ?

**Comment by nowkin** [comment]
same questions as NainalChauhan.This is not working in Fetch2 anymore
