### ISSUE TITLE
setNetworkType of all requests at once

### ISSUE THREAD

**Issue by iBlueDust** [tonyofrancis/Fetch#342]
And otherwise, does getting the requests through getting all dowloads and setting their `NetworkType`s work? Or do I have to cancel the requests and redo them with a different `NetworkType`?

Anyway, thanks in advance.

**Comment by tonyofrancis** [comment]
@iBlueDust you can set a global NetworkType by setting it on the FetchConfiguration.
```java
    final FetchConfiguration fetchConfiguration = new FetchConfiguration.Builder(this)
                .enableRetryOnNetworkGain(true)
                .setDownloadConcurrentLimit(3)
                .setGlobalNetworkType(NetworkType.WIFI_ONLY)
                .build();
```
The global network type overrides the network type on the download. In order to update information on a request/download you have to call `fetch.updateRequest`  method. Hope this helps.

**Comment by iBlueDust** [comment]
Ok thanks. Btw can you override the global network type afterwards? It might be asking much I know but might as well ask.

The use case here is that I want a setting in my app that controls this. But say that the user does not want to download using data under normal circumstances, but for some reason the user would like to download using data for say one single download and I'd like to help those users.

@tonyofrancis

**Comment by tonyofrancis** [comment]
`fetch.setGlobalNetworkType(networkType)`

**Comment by iBlueDust** [comment]
That wasn't what I was looking for but thanks anyway. I'll just remove and resubmit the `Request` to override the Global `NetworkType`.

Note: I was looking for two layers of overrides or a way to change a single request's `NetworkType` after submitting basically.
