### ISSUE TITLE
hasActiveDownloads seems not working well

### ISSUE THREAD

**Issue by ahar** [tonyofrancis/Fetch#346]
Hi, 

using this method for displaying/hiding notification for android > O. 
Using like this: 
fetch.hasActiveDownloads(false, hasActiveDownloads -> {
            if (hasActiveDownloads) {
                saveCurrentProgress();
            } else {
                stopAndCleanNotification();
            }
        });

The problem is, if there are 2 files downloading and 1 paused, I pause one of 2 files - hasActiveDownloads returns false, however, we have 1 file downloading. 
Do you have what can cause this problem?

**Comment by tonyofrancis** [comment]
@ahar Found the bug. working on the fix

**Comment by tonyofrancis** [comment]
@ahar Fetch version 3.0.3 has been released with this fix.
