### ISSUE TITLE
Enable followsRedirect not working for custom HttpUrlConnectionDownloader

### ISSUE THREAD

**Issue by JumpLizard** [tonyofrancis/Fetch#347]
Hi, I've created a custom `HttpUrlConnectionDownloader` like this:

    class CustomDownloader(@NotNull fileDownloaderType: Downloader.FileDownloaderType) : HttpUrlConnectionDownloader(fileDownloaderType) {
      override fun onPreClientExecute(@NotNull client: HttpURLConnection, @NotNull request: com.tonyodev.fetch2core.Downloader.ServerRequest): Void? {
          super.onPreClientExecute(client, request)
          client.setRequestProperty("Range", "")
          client.setRequestProperty("User-Agent", USER_AGENT)
          client.instanceFollowRedirects = true
          return null
      }
    }

And implements it this way:

    val fetchConfiguration = FetchConfiguration.Builder(this)
          .setDownloadConcurrentLimit(5)
          .enableRetryOnNetworkGain(true)
          .setHttpDownloader(CustomDownloader(Downloader.FileDownloaderType.SEQUENTIAL))
          .build()

    mFetchObj = Fetch.getInstance(fetchConfiguration)

But for this [link](http://psv7.fyvideo.info/drive/hls/ef1247f668fb12e385b78a5b767eb090/ef1247f668fb12e385b78a5b767eb0900.html?ch=ef1247f668fb12e385b78a5b767eb090-chunk-0.txt&s=18&l=432400), I still got a 302 error in `AbstractFetchListener`. How to redirect correctly? Thanks in advance.

**Comment by tonyofrancis** [comment]
Fixed this issue. Will post back when released

**Comment by tonyofrancis** [comment]
@JumpLizard Fetch version 3.0.3 has been released with this improvement.

**Comment by JumpLizard** [comment]
@tonyofrancis Wow, that's really impressive work. I'll check it now. Thanks so much!

**Comment by chaosphinx** [comment]
Hi, this time I got `416 Requested range not satisfiable`. Maybe there's come conflicts with `client.setRequestProperty("Range", "")`?

**Comment by tonyofrancis** [comment]
Dont worry about setting the range header. Fetch sets the default range for you. Thats how it supports resume.

**Comment by JumpLizard** [comment]
But if the range isn't overrided, some files' size would be wrong. I've posted an issue before ([issue 320](https://github.com/tonyofrancis/Fetch/issues/320)). The link is expired. Here is a valid one: [test link](https://zee5vodnd.akamaized.net/hls/1080p/tvshows/ONAIR_SHOWS/Zee_Tv/October2018/03102018/Aap_Ke_Aa_Jane_Se_Ep181_03102018_hi.mp4/media-1/segment-0.ts?hdntl=exp=1554091891~acl=/*~data=hdntl~hmac=0c7ad48f5f49bfcca0b7aa7b0710c300f807760b9745803d1fa0a804f268bb64&aka_me_session_id=AAAAAAAAAABzj6FcAAAAAHVJ4AvdhJIN732ngAzD+ASFuS70vONtFhBXFjYnRuO6jrh7OOBzRevZJvaO0HNWnhVeTBOu7yHP&aka_msn=0&aka_hls_version=4). Note the user agent need to be set to `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0` otherwise you'll get a 403 error. The real size should be 96272 bytes. But if the range isn't overrided, we'll get 96256 bytes which is wrong.

**Comment by tonyofrancis** [comment]
@JumpLizard @chaosphinx Let me know if this code helps and I will try bake it in the next release

```java
        @Nullable
        @Override
        public Void onPreClientExecute(@NotNull HttpURLConnection client, @NotNull Downloader.ServerRequest request) {
            super.onPreClientExecute(client, request);
            try {
                final URL url = new URL(request.getUrl());
                final HttpURLConnection connection = (HttpURLConnection) url.openConnection();
                for (String key: request.getHeaders().keySet()) {
                    connection.addRequestProperty(key, request.getHeaders().get(key));
                }
                
                connection.connect();

                final Map<String, List<String>> responseHeaders = connection.getHeaderFields();
                final List<String> rangeResponseHeaders = responseHeaders.get("Accept-Ranges");
                boolean acceptRanges = false;

                if (connection.getResponseCode() == HttpURLConnection.HTTP_PARTIAL ||
                        (rangeResponseHeaders != null && rangeResponseHeaders.size() > 0 &&
                                "bytes".equals(rangeResponseHeaders.get(0)))) {
                    acceptRanges = true;
                }

                if (!acceptRanges) {
                    client.addRequestProperty("Range", ""); // or client.addRequestProperty("Range", null);
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
            return null;
        }
    }

```

**Comment by chaosphinx** [comment]
Hi, I changed the `if` statement to:

    if (acceptRanges) {
        client.setRequestProperty("Range", "")
    }

and it works for both the 302 link and different-size link.

Here's my full code (in Kotlin):

    override fun onPreClientExecute(@NotNull client: HttpURLConnection, @NotNull request: com.tonyodev.fetch2core.Downloader.ServerRequest): Void? {
        super.onPreClientExecute(client, request)
        client.setRequestProperty("User-Agent", USER_AGENT)

        try {
            val url = URL(request.url)
            val connection = url.openConnection() as HttpURLConnection
            request.headers.keys.forEach {
                connection.addRequestProperty(it, request.headers[it])
            }
            connection.setRequestProperty("User-Agent", USER_AGENT)
            connection.connect()

            val responseHeaders = connection.headerFields
            val rangeResponseHeaders = responseHeaders["Accept-Ranges"]
            val acceptRanges = connection.responseCode == HttpURLConnection.HTTP_PARTIAL
                    || (rangeResponseHeaders != null && rangeResponseHeaders.size > 0 && rangeResponseHeaders[0] == "bytes")
            if (acceptRanges) {
                client.setRequestProperty("Range", "")
            }
        } catch (e: Exception) {
            e.printStackTrace()
        }
        return null
    }

Thanks for your help, I'll test it more throughly later.

**Comment by JumpLizard** [comment]
Hi, I changed the if statement to:

    if (acceptRanges) {
        client.setRequestProperty("Range", "")
    }

and it works for both the 302 link and different-size link.

Here's my full code (in Kotlin):

    override fun onPreClientExecute(@NotNull client: HttpURLConnection, @NotNull request: com.tonyodev.fetch2core.Downloader.ServerRequest): Void? {
        super.onPreClientExecute(client, request)
        client.setRequestProperty("User-Agent", USER_AGENT)

        try {
            val url = URL(request.url)
            val connection = url.openConnection() as HttpURLConnection
            request.headers.keys.forEach {
                connection.addRequestProperty(it, request.headers[it])
            }
            connection.setRequestProperty("User-Agent", USER_AGENT)
            connection.connect()

            val responseHeaders = connection.headerFields
            val rangeResponseHeaders = responseHeaders["Accept-Ranges"]
            val acceptRanges = connection.responseCode == HttpURLConnection.HTTP_PARTIAL
                    || (rangeResponseHeaders != null && rangeResponseHeaders.size > 0 && rangeResponseHeaders[0] == "bytes")
            if (acceptRanges) {
                client.setRequestProperty("Range", "")
            }
        } catch (e: Exception) {
            e.printStackTrace()
        }
        return null
    }

Thanks for your help, I'll test it more throughly later.

**Comment by JumpLizard** [comment]
After some tests, I think it works pretty well. Thanks for your help!
