### ISSUE TITLE
Couldn't resume downloading after app is restarting

### ISSUE THREAD

**Issue by waqas117** [tonyofrancis/Fetch#348]
I saved the request ids and after restarting the app and call fetch.resume(id,fun{},fun{}) it gives this error  /** Indicates that the Request Being Queried does not exist.*/
    REQUEST_DOES_NOT_EXIST(24)

Its seems fetch not works after restarting app with same request ids to resume from where it lefts.

**Comment by tonyofrancis** [comment]
@waqas117. I just tested and the files resume correctly. Can you share your code? How are you enqueuing the downloads?

**Comment by waqas117** [comment]
`




    class DownloadActivity : AppCompatActivity() {


    private val TAG by lazy { DownloadActivity::class.simpleName }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_download)


        val re = Func<Request> {


        }
        val err = Func<Error> {


            Timber.tag(TAG).i("error ${it.throwable?.message} and value is ${it.value}")
        }


        val fetchConfiguration = FetchConfiguration.Builder(this)
            .setDownloadConcurrentLimit(3)
            .build()

        val  fetch = Fetch.getInstance(fetchConfiguration)



        var requestId: Int? = null



        start.setOnClickListener{
       // here i get the request id that saved in db if user pause downloading and leave app and return 
         back when app is killed by OS so he/she can resume but it gives error. 

           var id =  db.getRecentRunningDownloadingTask()

            Timber.tag(TAG).i("start with id $id")

            fetch.resume(id.toInt() , Func {
                Timber.tag(TAG).i("resume with ${it.progress}")
            } , err)
        }




        downloading_control.setOnClickListener {




            if (it.tag.equals("download")){//download is clicked lets start or resume clicked

                val url = "http://dl58.y2mate.com/?file=M3R4SUNiN3JsOHJ6WWQ2a3NQS1Y5ZGlxVlZIOCtyZzBuY2M4eUFJdUNLVkxtWm9tdyt5ZkxzWkFQS2dBOG91c0ZlRkc4Q2pkY055Q1BnaTJ1NEVaUUhhQTRzSWtoaS9kL0lvMVd0MWlhVWIxa2RPbnZodGFyQXl0UVl1YlJhZ1lZR2N2NVVacTN5T3MzUERBc1VpOTRWdTBxRmlYZVNZUDkya3RNT1dFdE0xdTBDeVpTZTYyM3BFUnFHaWM3WmNDbDd1TnNSUHd6S0F6c2RKeVlWTjlaNWhpMUpYNnpmL0Rta1lYaEtZTzMxdWhxTzZ2Q0prS0VieWhlekp4S3pZUTF2LzlVeDhMekRFTnh6eXovSm9oeGtvbFZLc3QxekhpcWVLbmF5L01PTUg2UnBTS1BzR04rNVNoc0xjdzV4U1A5TEdmMHM4UTBBMi9XTUh0UThVQnZFcCs4UGJXdHBWZ2xBZmhpdz09"

                Timber.tag(TAG).i("url is $url")




                 val file = File(Storage.Root.path.plus(File.separator).plus("new.mp4"))

                val request = Request(url, file.toUri())

                requestId = request.id

                Timber.tag(TAG).i("request id is $requestId")

                request.priority = com.tonyodev.fetch2.Priority.HIGH
                request.networkType = NetworkType.ALL

                fetch.enqueue(request, re, err)

                fetch.addListener(fetchListener);




            }else{ //pause button is clicked lets pause things

                it.tag = "download"

                requestId?.let {
                    fetch.pause(it)
                }





            }


        }


    }

    var fetchListener: FetchListener = object : FetchListener{
        override fun onAdded(download: Download) {
                  }

        override fun onCancelled(download: Download) {
            Timber.tag(TAG).i("on progress ${download.progress}")
                  }

        override fun onCompleted(download: Download) {
            Timber.tag(TAG).i("on progress ${download.progress}")
                  }

        override fun onDeleted(download: Download) {
            Timber.tag(TAG).i("on progress ${download.progress}")
                  }

        override fun onDownloadBlockUpdated(download: Download, downloadBlock: DownloadBlock, totalBlocks: Int) {
            Timber.tag(TAG).i("on progress ${download.progress}")
                  }

        override fun onError(download: Download, error: Error, throwable: Throwable?) {
            Timber.tag(TAG).i("on progress ${download.progress}")
                  }

        override fun onPaused(download: Download) {
            Timber.tag(TAG).i("on progress ${download.progress}")

            downloading_control.setImageDrawable(resources.getDrawable(R.drawable.ic_pause ))

                  }

        override fun onProgress(download: Download, etaInMilliSeconds: Long, downloadedBytesPerSecond: Long) {

            Timber.tag(TAG).i("on progress ${download.progress}")

        }

        override fun onQueued(download: Download, waitingOnNetwork: Boolean) {
            Timber.tag(TAG).i("on progress ${download.progress}")
                  }

        override fun onRemoved(download: Download) {
            Timber.tag(TAG).i("on progress ${download.progress}")
        }

        override fun onResumed(download: Download) {
            Timber.tag(TAG).i("on progress ${download.progress}")
            downloading_control.setImageDrawable(resources.getDrawable(R.drawable.ic_file_download ))
        }

        override fun onStarted(download: Download, downloadBlocks: List<DownloadBlock>, totalBlocks: Int) {
            Timber.tag(TAG).i("on progress ${download.progress}")
        }

        override fun onWaitingNetwork(download: Download) {
            Timber.tag(TAG).i("on progress ${download.progress}")
        }

    }




}
`

**Comment by tonyofrancis** [comment]
@waqas117 Where are you saving the request id to the database? I do not see any code that is saving the id to your database. I only see it retrieving it via `db.getRecentRunningDownloadingTask()` which may be returning an invalid id. Also you should always saved the id for the request in the `re` function.
Example:
```java
fetch.enqueue(request, new Func<Request>() {
                    @Override
                    public void call(@NotNull Request result) {
                        request = result;
                        saveIdToDatabase(result.id);
                       //save request id here because Fetch may update the id for a number of reasons. See     the documentation for more information.
                    }
                }, new Func<Error>() {
                    @Override
                    public void call(@NotNull Error result) {
                        Timber.d("SingleDownloadActivity Error: %1$s", result.toString());
                    }
                });
```
Let me know if this helps.

**Comment by waqas117** [comment]
I didn't share complete snippet of code where id is being saved anyways i will try and update here.

**Comment by tonyofrancis** [comment]
okay. Please let me know if it still does not work. Then maybe you can share your code via email and i can better help there. My email is on my profile page.

**Comment by tonyofrancis** [comment]
@waqas117 The request id `request.getId()` is based on the url and file name.  If the file name changes the request id will always be different. In your sample code, the file name is generated with `System.currentTimeMillis()` appendend to it's name. This function will always return a different value. Hence the reason Fetch will generate a new requestId each time.

**Comment by waqas117** [comment]
I understand the underlying concept but i saved all previous request ids i just want to resume with that ids but it gives error. `System.currentTimeMillis() ` just created new file and it gives new request id but that same ids should resume but it didn't.

Take a look an example.

`System.currentTimeMillis().toString.plus(".mp4")` generates 123372847327.mp4 with request id 67543

but when i want to resume for 675443 it gives error.

**Comment by tonyofrancis** [comment]
@waqas117 I had a look at the code you shared. Without the full picture there is not much I can help with.  Example Activity that works with resume after app is closed.
```java
package com.tonyodev.fetchapp;

import android.Manifest;
import android.content.pm.PackageManager;
import android.net.Uri;
import android.os.Build;
import android.os.Bundle;
import android.support.annotation.NonNull;
import android.support.design.widget.Snackbar;
import android.support.v7.app.AppCompatActivity;
import android.view.View;
import android.widget.TextView;

import com.tonyodev.fetch2.Download;
import com.tonyodev.fetch2.Error;
import com.tonyodev.fetch2.Fetch;
import com.tonyodev.fetch2.Request;
import com.tonyodev.fetch2.Status;
import com.tonyodev.fetch2core.Extras;
import com.tonyodev.fetch2core.FetchObserver;
import com.tonyodev.fetch2core.Func;
import com.tonyodev.fetch2core.MutableExtras;
import com.tonyodev.fetch2core.Reason;

import org.jetbrains.annotations.NotNull;

import timber.log.Timber;


public class SingleDownloadActivity extends AppCompatActivity implements FetchObserver<Download> {

    private static final int STORAGE_PERMISSION_CODE = 100;

    private View mainView;
    private TextView progressTextView;
    private TextView titleTextView;
    private TextView etaTextView;
    private TextView downloadSpeedTextView;
    private Request request;
    private Fetch fetch;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_single_download);
        mainView = findViewById(R.id.activity_single_download);
        progressTextView = findViewById(R.id.progressTextView);
        titleTextView = findViewById(R.id.titleTextView);
        etaTextView = findViewById(R.id.etaTextView);
        downloadSpeedTextView = findViewById(R.id.downloadSpeedTextView);
        fetch = Fetch.Impl.getDefaultInstance();
        checkStoragePermission();
    }

    @Override
    protected void onResume() {
        super.onResume();
        if (request != null) {
            fetch.attachFetchObserversForDownload(request.getId(), this);
        }
    }

    @Override
    protected void onPause() {
        super.onPause();
        if (request != null) {
            fetch.removeFetchObserversForDownload(request.getId(), this);
        }
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        fetch.close();
    }

    @Override
    public void onChanged(Download data, @NotNull Reason reason) {
        updateViews(data, reason);
    }

    private void checkStoragePermission() {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
            requestPermissions(new String[]{Manifest.permission.WRITE_EXTERNAL_STORAGE}, STORAGE_PERMISSION_CODE);
        } else {
            enqueueDownload();
        }
    }

    @Override
    public void onRequestPermissionsResult(int requestCode, @NonNull String[] permissions, @NonNull int[] grantResults) {
        if (requestCode == STORAGE_PERMISSION_CODE && grantResults.length > 0 && grantResults[0] == PackageManager.PERMISSION_GRANTED) {
            enqueueDownload();
        } else {
            Snackbar.make(mainView, R.string.permission_not_enabled, Snackbar.LENGTH_LONG).show();
        }
    }

    private void enqueueDownload() {
        final String url = Data.sampleUrls[0];
        final String filePath = Data.getSaveDir() + "/movies/" + Data.getNameFromUrl(url);
        request = new Request(url, filePath);
        request.setExtras(getExtrasForRequest(request));

        fetch.attachFetchObserversForDownload(request.getId(), this)
                .enqueue(request, new Func<Request>() {
                    @Override
                    public void call(@NotNull Request result) {
                        request = result;
                    }
                }, new Func<Error>() {
                    @Override
                    public void call(@NotNull Error result) {
                        Timber.d("SingleDownloadActivity Error: %1$s", result.toString());
                    }
                });
    }

    private Extras getExtrasForRequest(Request request) {
        final MutableExtras extras = new MutableExtras();
        extras.putBoolean("testBoolean", true);
        extras.putString("testString", "test");
        extras.putFloat("testFloat", Float.MIN_VALUE);
        extras.putDouble("testDouble",Double.MIN_VALUE);
        extras.putInt("testInt", Integer.MAX_VALUE);
        extras.putLong("testLong", Long.MAX_VALUE);
        return extras;
    }

    private void updateViews(@NotNull Download download, Reason reason) {
        if (request.getId() == download.getId()) {
            if (reason == Reason.DOWNLOAD_QUEUED || reason == Reason.DOWNLOAD_COMPLETED) {
                setTitleView(download.getFile());
            }
            setProgressView(download.getStatus(), download.getProgress());
            etaTextView.setText(Utils.getETAString(this, download.getEtaInMilliSeconds()));
            downloadSpeedTextView.setText(Utils.getDownloadSpeedString(this, download.getDownloadedBytesPerSecond()));
            if (download.getError() != Error.NONE) {
                showDownloadErrorSnackBar(download.getError());
            }
        }
    }

    private void setTitleView(@NonNull final String fileName) {
        final Uri uri = Uri.parse(fileName);
        titleTextView.setText(uri.getLastPathSegment());
    }

    private void setProgressView(@NonNull final Status status, final int progress) {
        switch (status) {
            case QUEUED: {
                progressTextView.setText(R.string.queued);
                break;
            }
            case ADDED: {
                progressTextView.setText(R.string.added);
                break;
            }
            case DOWNLOADING:
            case COMPLETED: {
                if (progress == -1) {
                    progressTextView.setText(R.string.downloading);
                } else {
                    final String progressString = getResources().getString(R.string.percent_progress, progress);
                    progressTextView.setText(progressString);
                }
                break;
            }
            default: {
                progressTextView.setText(R.string.status_unknown);
                break;
            }
        }
    }

    private void showDownloadErrorSnackBar(@NotNull Error error) {
        final Snackbar snackbar = Snackbar.make(mainView, "Download Failed: ErrorCode: " + error, Snackbar.LENGTH_INDEFINITE);
        snackbar.setAction(R.string.retry, v -> {
            fetch.retry(request.getId());
            snackbar.dismiss();
        });
        snackbar.show();
    }

}
```

**Comment by CarsonRedeye** [comment]
I can replicate this issue on the latest version. I've tried to debug this and I think this line is problematic:
FetchHandlerImpl.kt line 123
`var existingDownload = fetchDatabaseManagerWrapper.getByFile(downloadInfo.file)`
In my situation the urls rotate every 15 minutes or so to include a new token in the path, then when I try to observe the download via `getDownload(enqueuedRequest.id)` that id is calculated by combining the file AND the url so it never finds the "old" download.
This means with my setup that file can never be downloaded, as Fetch will never update the id of the download to match the request id. Here is the workaround I used:
```
getDownload(downloadId)
                .observable
                .onErrorResumeNext { error: Throwable ->
                    getDownloads().observable.flatMap { allDownloads ->
                        val awolDld = allDownloads.find { it.file == fileToDownloadTo }!!
                        delete(awolDld.id).observable.ignoreElements()
                                .andThen(Observable.error(IllegalStateException("We lost your download. You need to try again")))
                    }
                }
```
