### ISSUE TITLE
Lack of the methods to work with group downloads

### ISSUE THREAD

**Issue by ahar** [tonyofrancis/Fetch#349]
Hi @tonyofrancis ! 

I am aware of this issue: https://github.com/tonyofrancis/Fetch/issues/179

However, I found out that fetch doesn't have good api to work with group downloads. 
1) There is **no retry method** for group. However, **resume/delete/remove are there**
2) Fully understand, that the minimal entity for fetch right now is Request/Download, but, for more convenient work experience, I believe there should be RequestGroup/DownloadGroup, that's how users of the library can get more info without calculating everything in their own methods. 
3) For downloading m3u8, fetch doesn't handle a lot of situations. May be there is an opportunity to make step forward? 

Do you have any plans on improving these things?

**Comment by tonyofrancis** [comment]
1. Noted. I will add the retry method that takes in a list in the next release.
2. As of Fetch 3.0.0, Fetch has lots of Group support via the FetchGroup class and  FetchGroupListener. Here is the changeLog for group support:
```java
1. FetchGroupListener. FetchGroupListener extends from FetchListener and allows you to listener for
updates on a group. The methods on FetchGroupListener will return a FetchGroup object that contains
all the downloads in a group and will inform you which download triggered a change on the group. Also see AbstractFetchGroupListener.

2.Introducing FetchObserver. Fetch now allows you to subscribe from updates for a single Download or a Group of Downloads.
Using the FetchObserver and FetchGroupObserver interface respectively. See Fetch.attachFetchObserversForDownload(id, observers...) documentation
for more information. Also check the sample app for usage.

3. Introducing FetchGroup. FetchGroup is an object that contains all information about a group Fetch manages. The group is
automatically updated any time a download from the group updates. You can subscribe to FetchGroup's using the FetchGroupObserver.
FetchGroupObservers attached to a FetchGroup will be notified when downloads on a group changes. You will be notified of
the Reason for the change as well. See Fetch.getFetchGroup(id, callback) documentation for more information.
```
Sorry this information is not available in the readme. Way to much features to document there. At some point I will start a wiki.

4. Fetch is fully customizable and allows you to handle cases that the library does not. You can create a custom Downloader, StorageResolver, DatabaseManager and NotificaitonManager for Fetch to use if the out of box one does not work for you. I would recommend checking the methods on FetchConfiguration and going from there. The sample app have an example of a custom Downloader. Again, way to many features to document in a readme. I am a one man team as of now.

Let me know if I was able to answer all your questions or if you need further help with the above.

**Comment by ahar** [comment]
@tonyofrancis nice! 
Thank you for quick reply!
