### ISSUE TITLE
Wrong progress when downloading big files (Tested with 4.2 GB file)

### ISSUE THREAD

**Issue by ioltean** [tonyofrancis/Fetch#35]
httpURLConnection.getContentLenght() is not working correct when the file is bigger than the Integer.MAX_VALUE. In this case it will return -1 and I guess that's why the progress you return will always be 0%.

An option to fix this issue would be to get the content length directly from the headers and convert it to long:

Long.valueOf(connection.getHeaderField("Content-Length"))

instead of:

private void setContentLength() {
        if(Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
            fileSize = downloadedBytes + httpURLConnection.getContentLengthLong();
        } else {
            fileSize = downloadedBytes + httpURLConnection.getContentLength();
        }
    }

**Comment by tonyofrancis** [comment]
This fix will make it in the next release 1.1.2. @ioltean Thanks!
