### ISSUE TITLE
CPU cost heavily

### ISSUE THREAD

**Issue by ibosong** [tonyofrancis/Fetch#350]
Thanks for sharing this nice library. I found the sample app costs heavily in cpu when downloading.

![image](https://user-images.githubusercontent.com/4411010/55401635-f6ba6c00-5583-11e9-88fd-536f06a492c4.png)

**Comment by tonyofrancis** [comment]
@ibosong Thanks for using Fetch. I noticed that you are using the Parallel Downloader. The Parallel Downloader opens/creates the specified amount of connections(default I believe is 3-6) on different threads to download parts of the file in parallel resulting in a faster file download. This is per download. With that comes the cost of using more memory and cpu. So if you have 2 downloads going at the same time that could be very costly. 

 The Sequential Downloader only opens one connection and uses one thread per download to download a file. So the resource usage will be much lower. 

Hope this helps.
