### ISSUE TITLE
Difference between remove and cancel

### ISSUE THREAD

**Issue by DennisVanAcker01** [tonyofrancis/Fetch#351]
What is the difference between remove/cancel/delete of a download? I downloaded the sample and it's really not clear to me. It's not mentioned in the README either... Also, is there any way i can be notified when all downloads of a group are completed, or do i have to write code myself for that? Great library, a wiki would be awesome

**Comment by DennisVanAcker1** [comment]
Nevermind i found it by searching in the code:

Remove:
-cancels download
-deletes the download from the database
-deletes tmp files

Delete:
-cancels download
-deletes the download from the database
-deletes tmp files
-deletes created/download file 

Cancel:
-cancels the download
-adds the possibility to retry later
