### ISSUE TITLE
No error receive on wifi disconect

### ISSUE THREAD

**Issue by cepero91** [tonyofrancis/Fetch#355]
Hi developers sorry for my english, a got an issue. When start a download of a list of images and turn off wifi before downloads finish i am not receive notification of error via log or toast, i am using rxfetch with a class pretty similar to GameFilesActivity. Thanks for you help

**Comment by tonyofrancis** [comment]
@cepero91 Fetch will not throw an error because an error did **not** occur. The wifi was just disconnected. Fetch will continue to download the files the next time the wifi is connected.

**Comment by cepero91** [comment]
Then I have a question, there is some way to notify the user when the connection is interrupted. I have put Log in each of the methods of the AbstractFetchListener interface and none are triggered when the connection is lost.

My idea is the following:
- start the download
- cause a connection error
- stop the progress and put the background in red
- Notify that the connection has fallen

Is that possible to do?

Once again thank you very much for this incredible library

**Comment by cepero91** [comment]
Hi again, this issue can be closed, i found a solution, set enableRetryOnNetworkGain to false, this trigger enError method, in my case thats what i want

**Comment by CarsonRedeye** [comment]
This does not trigger onError when the download is started while offline :(
