### ISSUE TITLE
Default EnqueueAction should be REPLACE_EXISTING but is UPDATE_ACCORDINGLY instead

### ISSUE THREAD

**Issue by DennisVanAcker1** [tonyofrancis/Fetch#356]
I did not define any enqueueaction anywhere in my project. When i dive into the Fetch code, my request somehow has the UPDATE_ACCORDINGLY enqueue action...

**Comment by tonyofrancis** [comment]
@DennisVanAcker1 The default was Replace_Existing before. But after many complaints and confusion, it was replaced to Update_Accordinlgly. It is the best option and what many users expect.

**Comment by jpvs0101** [comment]
Update_Accordinlgly is more natural & best option!

**Comment by DennisVanAcker1** [comment]
I was confused because the comments in the EnqueueAction class say that the default is something else, so i thought i was a possible bug

**Comment by tonyofrancis** [comment]
@DennisVanAcker1 I will update the documentation
