### ISSUE TITLE
Downloads are not starting while Fetch is queueing  and adding DownloadInfo

### ISSUE THREAD

**Issue by DennisVanAcker1** [tonyofrancis/Fetch#358]
I need to download 1350 files. But while these files are queueing to be downloaded, the downloads do not start. Is there any way i can make the downloads start downloading while i'm queueing fetch requests? I'm probably going to need the awaitFinish() method and/or a JobScheduler. Any help/tips would be much appreciated

**Comment by Awsom3D** [comment]
Don't know if it helps, but I'm using a parallel foreach to speed up the enqueue

```
Set<String> parallel_download_list;
Collections.addAll(parallel_download_list = new HashSet<>(download_list));
            parallel_download_list.parallelStream().forEach((missing_file) -> {
    Uri download_uri =  Uri.parse(mUrl + missing_file);
    com.tonyodev.fetch2.Request request = new com.tonyodev.fetch2.Request(download_uri.toString(), mDataDirectory + "tmp/" + missing_file);
    request.setPriority(Priority.HIGH);
    request.setNetworkType(NetworkType.ALL);
    mFetch.enqueue(request, result -> {}, error -> {});
});
```

**Comment by DennisVanAcker1** [comment]
i'll check it out. Thanks alot!

**Comment by DennisVanAcker1** [comment]
I created some kind of request dispatcher, it's seems to solve alot. But it would be nice if this was included in Fetch

**Comment by tonyofrancis** [comment]
@DennisVanAcker1 @Awsom3D new Fetch version 3.0.4 release with the fixes for this. Just remove your dispatcher code and enqueue requests normally. Please let me know if this works well for you.

**Comment by DennisVanAcker1** [comment]
I'll check it out and will let you know. Thanks
