### ISSUE TITLE
SQLiteException when pass list with 1000+ elements to fun enqueue(requests: List<Request>)

### ISSUE THREAD

**Issue by midaslefkowitz** [tonyofrancis/Fetch#360]
First off, I really like this library. Thank you very much for it. 

I think that my issue is related to the one found here #277

**Comment by tonyofrancis** [comment]
@midaslefkowitz A fix for that issue was released in Fetch 2.3.1. Are you using Fetch 2.3.1 or greater? Are you still seeing this issue in later releases? Replicate on a physical device or emulator?.

**Comment by midaslefkowitz** [comment]
Im using Fetch and RxFetch 3.0.3, this is the first time that I am using Fetch in a project. I am using it to download potentially thousands of files at a time and monitoring their download status. To do that my original plan was to enqueue a List of Requests, map the result to a list of download ids, then flatmapped to RxFetch.getDownloads. I was able to work around it by calling flatmapIterable and using the single Request versions of these methods.

Testing was done on a physical device.
