### ISSUE TITLE
java.lang.IllegalArgumentException: byteCount < 0: -2

### ISSUE THREAD

**Issue by khaleeljageer** [tonyofrancis/Fetch#361]
I'm trying to download this file

> http://freetamilebooks.com/download/%e0%ae%87%e0%ae%9f-%e0%ae%92%e0%ae%a4%e0%af%81%e0%ae%95%e0%af%8d%e0%ae%95%e0%af%80%e0%ae%9f%e0%af%81-%e0%ae%89%e0%ae%b0%e0%ae%bf%e0%ae%ae%e0%af%88-epub/

always getting IllegalArgumentException. Don't know the reason. Using following code snippet. Same code working for other file url.

        val fetchConfiguration = FetchConfiguration.Builder(this)
                     .setDownloadConcurrentLimit(3)
                     .build()

        fetch = Fetch.getInstance(fetchConfiguration)

        val url = "https://www.engineerhammad.com/2015/04/Download-Test-Files.html"
        val file = getExternalFilesDir(Environment.DIRECTORY_DOWNLOADS)?.absolutePath + "/Test.html"

        val request = Request(url, file)
        request.priority = Priority.HIGH
        request.networkType = NetworkType.ALL

        fetch.enqueue(request)

**Comment by tonyofrancis** [comment]
@khaleeljageer Just tested the link. For some reason the server response header is returning the content length of -2. That is incorrect. It should be greater than 0.
Response:
Accept-Ranges = bytes
Content-Range = bytes 0--2/-1
Conent-Length = -2

Something does not seem right with this response. You may want to contact the webserver administrator. Hope this helps.

**Comment by jpvs0101** [comment]
> @khaleeljageer Just tested the link. For some reason the server response header is returning the content length of -2. That is incorrect. It should be greater than 0.
> Response:
> Accept-Ranges = bytes
> Content-Range = bytes 0--2/-1
> Conent-Length = -2
> 
> Something does not seem right with this response. You may want to contact the webserver administrator. Hope this helps.
> 
> Also you can create a custom download that fetch can use. See the sample app on how to create a custom downloader.

May we have error callback instead of crash exception?

**Comment by tonyofrancis** [comment]
An error callback can be added.

**Comment by tonyofrancis** [comment]
@jpvs0101 Just looked into this some more. An error callback can be added but I does not make much sense. If a client connection is not successful in the `fun execute(request: Downloader.ServerRequest, interruptMonitor: InterruptMonitor): Downloader.Response? ` method the Parallel or Sequential downloader that is handling the download needs to know this so they stop and return control to the download manager to enqueue other downloads. An error callback would only be for your debug purposes. An alternative would be the following code:
```java
   override fun execute(request: Downloader.ServerRequest, interruptMonitor: InterruptMonitor): Downloader.Response? {
        try {
            return super.execute(request, interruptMonitor)
        } catch (e: Exception) {
            //log error
        }
        return null // this will still cause the download to fail/error
    }
```

I am open to more options/debate.

**Comment by tonyofrancis** [comment]
Just reviewed this some more and an error callback will not be added to the Downloader for the following reasons:
1. If an exception is thrown, then it is most likely an IO error that we cannot recover from and the download will need to be marked as having failed.

2. The downloader  already has a method called `fun onServerResponse(request: ServerRequest, response: Response)`. This method is called to report the success or failure of a server request.
