### ISSUE TITLE
Is there a way to just remove "Range" header?

### ISSUE THREAD

**Issue by JumpLizard** [tonyofrancis/Fetch#364]
In issue #347 , I set the header `Range` to empty (`""`), but is there a way to just remove it? For this [link](https://youku.com-l-youku.com/20181208/2151_d49239e0/1000k/hls/4da8d792fd3000.ts), If set `Range` to empty, the download size will be 1 byte which is incorrect. In browser like Firefox and Chrome, when downloading files like these, there seems no `Range` header at all. Sorry to bother you again:)

**Comment by tonyofrancis** [comment]
@JumpLizard let me look into this.

**Comment by tonyofrancis** [comment]
@JumpLizard What you can do is override the `onPreClientExecute` of the Downloader. You would have to create a custom downloader by extending OkHttpDownloader or HttpUrlConnectionDownloader and setting it on the FetchConfiguration `config.setHttpDownloader(new HttpUrlConnectionDownloader(Downloader.FileDownloaderType.PARALLEL))`.

The `onPreClientExecute` method does some setting up on the client such as adding the request headers etc. You can easily copy the code from the super method, remove the super method call and prevent the code from adding the Range header. Example:
```java
 override fun onPreClientExecute(client: OkHttpClient, request: Downloader.ServerRequest): Request {
        val okHttpRequestBuilder = Request.Builder()
                .url(request.url)
                .method(request.requestMethod, null)
        request.headers.entries.forEach {
            if (it.key != "Range") {
                okHttpRequestBuilder.addHeader(it.key, it.value)
            }
        }
        return okHttpRequestBuilder.build()
    }
```
Please let me know if this helps.

**Comment by JumpLizard** [comment]
Hi, I've tested 3 links that I've mentioned in this and previous issues. They all worked. Thanks for your help, I'll keep testing.
