### ISSUE TITLE
ERROR: Failed to resolve: androidx.tonyodev.xfetch2:xfetch2:3.1.0

### ISSUE THREAD

**Issue by sealiasheq** [tonyofrancis/Fetch#367]
I am adding these:

```
implementation "androidx.tonyodev.xfetch2:xfetch2:3.1.0"
implementation "androidx.tonyodev.fetch2okhttp:xfetch2okhttp:3.1.0"
```

And I tested:

```
implementation 'androidx.tonyodev.xfetch2:xfetch2:3.1.0'
implementation 'androidx.tonyodev.fetch2okhttp:xfetch2okhttp:3.1.0'
```

but get me:

`ERROR: Failed to resolve: androidx.tonyodev.xfetch2:xfetch2:3.1.0`

Work with your library is hard!!!!! your support is very very weak.

**Comment by tonyofrancis** [comment]
@sealiasheq there was a typo in the readme.  Updated it. Try this
```java
    implementation "androidx.tonyodev.fetch2:xfetch2:3.1.0"
    implementation 'androidx.tonyodev.fetch2okhttp:xfetch2okhttp:3.1.0'
```
Also in terms of support what kind of support do you feel is missing?. Does the sample app not help or have inform information to get you started with the library?
