### ISSUE TITLE
Encoding Issue With .TS Files

### ISSUE THREAD

**Issue by sudovijay** [tonyofrancis/Fetch#368]
Hey,
Firstly thanks for such a beautiful lib. just today tried downloading some encrypted hls segments, it seems to generate corrupt / invalid segment file which can't be decrypted with key
its more of AES encrypted stuff, non utf-8 characters.
While regular hls segment downloads works fine. can you please look into? if i try to download the same segment file with chrome or curl it works pretty fine, it seems like it just not handling some non utf-8 characters may be. you probably know it better.

try this one - http://xxx

if you download it via normal browser, it gets decrypted otherwise it doesn't with **Fetch**

**Comment by sudovijay** [comment]
You can test that by this command.

openssl aes-128-cbc -d -in part-1.ts -out decrypted_segment.ts -nosalt -iv 0 -K <replace this with key_hex>

**Comment by tonyofrancis** [comment]
@sudovijay Are you using the Parallel or Sequential Downloader? What does your FetchConfiguration look like?

**Comment by sudovijay** [comment]
I did tried with both actually, lemme paste my configuration

```java
final OkHttpClient client = new OkHttpClient.Builder().readTimeout(20_000L, TimeUnit.MILLISECONDS) // increase read timeout as  needed
                .connectTimeout(20_000L, TimeUnit.MILLISECONDS) // increase connection timeout as needed
                .followRedirects(true).followSslRedirects(true).cookieJar(getDefaultCookieJar()).build();

        final Downloader customDownloader = new OkHttpCustomDownloader(client);

        FetchConfiguration fetchConfiguration = new FetchConfiguration.Builder(getReactApplicationContext())
                .setHttpDownloader(customDownloader)
                .enableAutoStart(false).enableRetryOnNetworkGain(true)
                .setDownloadConcurrentLimit(10).build();
```

**Comment by sudovijay** [comment]
tbh i was just working on this, it pretty weird actually the actual URL  is this one 
```
https://zee5vodnd.akamaized.net/hls1/NM4AWS7/Domestic/Promos/April2019/29042019/Why_Cheat_India_Trailer_Watch_Now_885720d1.mp4/media-1/stream.m3u8?hdnea=st=1556894634~exp=1556897634~acl=/*~hmac=f68ce880ce247519251b5ea71d2a51699b9524a5be6d44fbe1b8c18b2f542c21
```
some sort of header issue is there, like with regular chrome android browser or any other download manager it works pretty fine but with fetch it just break the file.

**Comment by sudovijay** [comment]
Seems to be solved, more like range issue :) thanks anyway mate !

**Comment by junior-jornada** [comment]
> I did tried with both actually, lemme paste my configuration
> 
> ```java
> final OkHttpClient client = new OkHttpClient.Builder().readTimeout(20_000L, TimeUnit.MILLISECONDS) // increase read timeout as  needed
>                 .connectTimeout(20_000L, TimeUnit.MILLISECONDS) // increase connection timeout as needed
>                 .followRedirects(true).followSslRedirects(true).cookieJar(getDefaultCookieJar()).build();
> 
>         final Downloader customDownloader = new OkHttpCustomDownloader(client);
> 
>         FetchConfiguration fetchConfiguration = new FetchConfiguration.Builder(getReactApplicationContext())
>                 .setHttpDownloader(customDownloader)
>                 .enableAutoStart(false).enableRetryOnNetworkGain(true)
>                 .setDownloadConcurrentLimit(10).build();
> ```

how did you solve it?
