### ISSUE TITLE
Help Wanted

### ISSUE THREAD

**Issue by ahar** [tonyofrancis/Fetch#369]
Hi @tonyofrancis ! 

I am developing downloader using your library. 
The main content to be downloaded is video files, including plain mp4 and ts files. 
I want to have limit over the downloads count. At the same time I would like to have PARALLEL download type, and have a limit for download, let's say 3 files in the same time. 

As far as I understand now, if I use PARALLEL type fetch concurrent limit is related only to parts count per one file. 

But do you have example on how to implement a list of instances limited by count? If no, what do you think will be better approach to implement this? 

Thanks

**Comment by tonyofrancis** [comment]
@ahar Thanks for using Fetch. The `setDownloadConcurrentLimit(3)` method on the FetchConfiguration.Builder class is to control how many requests/downloads can be downloaded at the same time. So if the limit is 3 only 3 downloads can be downloaded at the same time.

When you select to use the Parallel downloader, what it does is it breaks the download into smaller parts and downloads these parts in parallel(at the same time). So large files download faster. You can only set how many parts to download in parallel by creating a custom downloader and returning the parts amount via the `fun getFileSlicingCount(request: ServerRequest, contentLength: Long): Int?` method.

Example:
```java
public class App extends Application {

    @Override
    public void onCreate() {
        super.onCreate();
        FetchConfiguration fetchConfiguration = new FetchConfiguration.Builder(this)
                .setDownloadConcurrentLimit(3) //Sets how many request can be downloaded at the same time.
                .setHttpDownloader(new MyCustomDownloader())
                .build();

        Fetch fetch = Fetch.Impl.getInstance(fetchConfiguration);
    }

    private static class MyCustomDownloader extends OkHttpDownloader {

        public MyCustomDownloader() {
            super(FileDownloaderType.PARALLEL);
        }

        @Nullable
        @Override
        public Integer getFileSlicingCount(@NotNull Downloader.ServerRequest request, long contentLength) {
            /*
             * In this example we are returning 6 at random. But you can use the contentLength to
             * calculate how to slice(parts) the file for download.
             * */
            return 6;
        }

    }
}
```

Hope this helps.

**Comment by ahar** [comment]
Ok, thank you for info @tonyofrancis . 

But this is not what I mean :) Sorry for the poor explanation. 

I want to limit user downloads(i.e. files) in the same time. So, if I want to use parallel, I would need to create 3 instances of fetch, and spread files between them, something like queue. Is it normal for fetch? Do you have example for this?
