### ISSUE TITLE
`getInstance` method name is a misnomer

### ISSUE THREAD

**Issue by jacobtabak** [tonyofrancis/Fetch#37]
The `getInstance` method with a context parameter implies there is a single instance of Fetch per context. If you support multiple instances per context (which you do), you may want to consider renaming the method to `newInstance`. See item 1 in Effective Java for the naming conventions for static factory methods.

**Comment by tonyofrancis** [comment]
@jacobtabak thanks. The getInstance method will be deprecated, and the newInstance method will be added. This will make it in the next release. Fixed.
