### ISSUE TITLE
Adding big amount of ts files to download too slow

### ISSUE THREAD

**Issue by ahar** [tonyofrancis/Fetch#372]
If I download ts chunks, let's say file size is 1000 Mb, and each chunk is 10Mb. It will cause app to almost stop working. Is there another way to prevent this rather than using AsyncTask? 

Thanks

**Comment by tonyofrancis** [comment]
@ahar Fetch does the enqueuing on a background thread. The enqueue callbacks are called on the ui thread. Could it be your callback code is doing to much on the ui thread? Have you tried commenting out some code to pinpoint the exact location?.
