### ISSUE TITLE
Group id not found when deleting downloads

### ISSUE THREAD

**Issue by daniellAlgar** [tonyofrancis/Fetch#374]
Hi!

I'm struggling with an inconsistent behaviour using `groupId`.

Let's say I have

```
class FetchHelper {
    private val fetch = Fetch.getDefaultInstance()
    private val GROUP_ID = 1

    fun enqueueDownload(url: String, context: Context, fileName: String): Request {
        val filePath = getFile(...)
        val request = Request(url, filePath.absolutePath)
        request.groupId = GROUP_ID

        fetch.enqueue(request)
        return request
    }

    fun cancel(): Fetch = fetch.deleteGroup(id = GROUP_ID)
}
```

And I start a download in `Foo` by
```
class Foo {

    fun download() {
        val fetchHelper = FetchHelper().enqueueDownload(url, context, fileName)
    
        fetchHelper.cancel()
    }
}
```

I expect this to work, but it doesn't :). The `FetchHelper#cancel` function doesn't find the `groupId` (nor a `tag` if I would set it). The `groupId` is always `0` here, and the `tag = null`.

What am I doing wrong?

**Comment by tonyofrancis** [comment]
@daniellAlgar. Tested the deleteGroup method and it works correctly.  I suspect it is your cancel method. Write it this way an test again.
```java
fun cancel() {
  fetch.deleteGroup(GROUP_ID)
}
```
Please let me know if this helps.

**Comment by daniellAlgar** [comment]
@tonyofrancis Thanks for the response! (and library, of course!!).

I found my problem.. I had a few unit tests that used your library to download videos (the same video), and I would delete the video file from disk before each test. What I didn't understand was that Fetch doesn't care if I delete the file - it's internal cache will continue to say that it has downloaded given file.. Instead, I'm now `fetch.deleteAll()` in `@Before`, which resets the state to what I expected. 

Have you thought about letting Fetch track if its state is still valid? I.e. - check if downloaded file still exist? Maybe there's a backside to this I'm not thinking about?

Best regards,
Daniell Algar

**Comment by tonyofrancis** [comment]
Fetch has two removal methods. Delete which deletes the files and request/download from the database and the remove methods which just removes the request from the database but does not delete the file.  Fetch does check if the file exists. If the file does not exists the request/download status is set to error and the error field states why the error occurred. 

I think what you are experiencing may be a request.enqueueAction issue for your use case. Please have a look at EnqueueAction enum class. Basically the enqueue action enum types tells Fetch how to handle new requests if a request with certain values already exists.

**Comment by daniellAlgar** [comment]
Yeah I was playing around with `EnqueueAction` as well. Maybe I was doing something else wrong when I used that one but... It works now at least with what I wrote in my second answer here so I'll leave it like that for now :).
