### ISSUE TITLE
download error by unexpected end of stream

### ISSUE THREAD

**Issue by huongnv251291** [tonyofrancis/Fetch#378]
i'm got error when download file on samsung j2 
java.net.ProtocolException: unexpected end of stream
before it stop down because error sometime throw log
 FileDownloader downloads slice FileSlice(id=1506190530, position=4, startBytes=63909978, endBytes=85213304, downloaded=18539174)
    java.net.ProtocolException: unexpected end of stream
        at okhttp3.internal.http1.Http1Codec$FixedLengthSource.read(Http1Codec.java:4
my config 
        FetchConfiguration fetchConfiguration = new FetchConfiguration.Builder(context)
                .enableRetryOnNetworkGain(true)
                .setDownloadConcurrentLimit(10)
                .setHttpDownloader(new HttpUrlConnectionDownloader(Downloader.FileDownloaderType.PARALLEL))
                .build();
        Fetch.Impl.setDefaultInstanceConfiguration(fetchConfiguration);

**Comment by tonyofrancis** [comment]
@huongnv251291 are you able to reproduce the error more than once.

**Comment by BlackVick** [comment]
Hello @tonyofrancis, Great job on this library. It has been smooth up until now. I keep getting "Unexpected End of Stream" error
