### ISSUE TITLE
Background Download

### ISSUE THREAD

**Issue by fathimath-munisa** [tonyofrancis/Fetch#379]
How can I use this library to schedule a download using work manager along with other chained task(which should execute on success of download) in work manager

**Comment by tonyofrancis** [comment]
@fathimath-munisa Fetch creates and maintains its own thread and provide callbacks to return data. In order to work with work manager you would have to create an instance of Fetch and block the work manager thread until the download completes.
Example:
```java
    override fun doWork(): Result {
        val fetch = Fetch.getDefaultInstance()
        val request = Request("url", "file")
        fetch.enqueue(request, { updatedRequest ->
            //success
        }, { error ->
            //failure
        })
        var competedDownloads = false
        while (!competedDownloads) {
            try {
                Thread.sleep(5000)
            } catch (e: InterruptedException) {
                e.printStackTrace()
            }

            fetch.hasActiveDownloads(true) { result -> competedDownloads = result }
        }
        fetch.close()
    }
```
I am currently looking for a way to make this better.

**Comment by fathimath-munisa** [comment]
fetch.hasActiveDownloads(true) { result -> competedDownloads = result } 
result returns false on pausing download.

**Comment by mt131** [comment]
Type mismatch.
Required:
Func<Boolean>
Found:
(Nothing) → Unit

**Comment by juanagu** [comment]
> Type mismatch.
> Required:
> Func
> Found:
> (Nothing) → Unit

the correct code is : 
`fetch.hasActiveDownloads(true, Func { competedDownloads = it })`
