### ISSUE TITLE
Download start from begin when use fetch.resume

### ISSUE THREAD

**Issue by EbrahimSadeghi** [tonyofrancis/Fetch#384]
hi dear , when we want to resume a file, download start from begin

**Comment by tonyofrancis** [comment]
@EbrahimSadeghi The reason maybe because the server you are downloading the file from does not support resume. If you try another link does it resume properly?

**Comment by EbrahimSadeghi** [comment]
The server I'm currently using support resume, i test it with IDM , but with downloadManager the resume begin from start.

**Comment by EbrahimSadeghi** [comment]
thanks @tonyofrancis , issue was from server
