### ISSUE TITLE
Add support to getting content length for multiple requests.

### ISSUE THREAD

**Issue by msarelo-intive** [tonyofrancis/Fetch#385]
Hi @tonyofrancis 
I have case that I want to pull content length for multiple files. There is any chance to add support for it?
Eg.:
Fetch:
 ` fun getContentLengthForRequests(requests:List<Request>, fromServer: Boolean, func: Func<List<Pair<Id,Long>>>, func2: Func<Error>?): Fetch`
RxFetch:
`fun getContentLengthForRequests(requests:List<Request>, fromServer: Boolean): Convertible<List<Pair<Id,Long>>>>
`

**Comment by tonyofrancis** [comment]
@msarelo-intive I think this can be added. Going on vacation this week. Once Im back ill look into this.

**Comment by tonyofrancis** [comment]
@msarelo-intive this has been added to fetch. It will be in the next release.

**Comment by tonyofrancis** [comment]
@msarelo-intive  new version of fetch is now available with the new get content length method. see readme and changelog.
