### ISSUE TITLE
Concurrent download limit problems

### ISSUE THREAD

**Issue by jacobtabak** [tonyofrancis/Fetch#39]
If you try to set the download limit to something that is above `FetchConst.MAX_DOWNLOADS_LIMIT`, the method silently sets the value to the default value, which is 1.

This is problematic partially because `MAX_DOWNLOADS_LIMIT` isn't public, so you're relying on the developer to use second hand knowledge to not call that method with a value greater than 7.

Why is there a hard coded limit to how many files can be downloaded concurrently? Is the number 7 chosen arbitrarily or based on some data? I would much prefer if you laid out a recommendation for the maximum number of downloads in the documentation but allow the developer to use whatever number they choose.

**Comment by tonyofrancis** [comment]
@jacobtabak My initial thought was to limit concurrent downloads to provided the best user experience possible(Thinking overall system performance). I set max to 7 because I felt it was a good fit. I do not have data to back the max limit, and was waiting on the community to provide feedback.

**Comment by jacobtabak** [comment]
I feel like a "one size fits all" limit of 7 may be lacking since Androids come in all shapes and sizes. I also feel strongly that the silent failure when attempting to set a limit over the hard-coded cap should be addressed.

**Comment by tonyofrancis** [comment]
@jacobtabak Agreed. Ill remove the limit and update the documentation. Thanks!

**Comment by tonyofrancis** [comment]
done. This will be in version 1.1.2 in fetch which will be released in the next few days.
