### ISSUE TITLE
Wrong filename for google drive download links

### ISSUE THREAD

**Issue by maulik9898** [tonyofrancis/Fetch#390]
When using google drive download link like this one
  
`https://doc-08-60-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/vrjqdumliftd7s3pnk79ihs435nc5i4g/1560355200000/12024208594662412395/*/1wgeEKZDdf1-zS0vD-2YGVpLPzQcw4q3y?e=download`

it doesn't recognise the correct file name.
for the above link, it detects file name as ` 1wgeEKZDdf1-zS0vD-2YGVpLPzQcw4q3y`    
but what it should be is ` ChernobylS1R0X.part1.rar `

Here is Image 

![image](https://user-images.githubusercontent.com/21076623/59371217-031c2b80-8d62-11e9-9a9d-5933689fcef1.png)

if i download in chrome browser it is able to get correct file name  
here is response header i get from chrome network inspect
 
`access-control-allow-credentials: false`
`access-control-allow-methods: GET,OPTIONS`
`access-control-allow-origin: *`
`alt-svc: quic=":443"; ma=2592000; v="46,44,43,39"`
`cache-control: private, max-age=0`
`content-disposition: attachment;filename="ChernobylS1R0X.part1.rar";filename*=UTF-8''ChernobylS1R0X.part1.rar`
`content-type: application/rar`
`date: Wed, 12 Jun 2019 16:50:17 GMT`
`expires: Wed, 12 Jun 2019 16:50:17 GMT`
`server: UploadServer`
`status: 200`
`x-goog-hash: crc32c=CygWPA==`
`x-guploader-uploadid: AEnB2Ur_aNxDKmGnCaaCxUloQTwu-3SZ4k7nyanCvZGE1PgsOzlixHEQd1-CJDfZZMEeKmT8B1VSrFYh99DT9YfwEybd3Ooti4J-c7wZKmdbPNOqPIQ1IJA`        

Maybe using     `content-disposition: attachment;filename="ChernobylS1R0X.part1.rar";filename*=UTF-8''ChernobylS1R0X.part1.rar`    
Might help..?

And also not able to get size of file

Note : I am using fetch demo with modified url list in ListDownload activity

**Comment by tonyofrancis** [comment]
@maulik9898 looking into this.
