### ISSUE TITLE
Download speed is -1 

### ISSUE THREAD

**Issue by maulik9898** [tonyofrancis/Fetch#391]
I am getting download speed as -1 same for eta it is also -1
but for same link in fetch app demo i am getting correct speed why ..?

here is [gist](https://gist.github.com/maulik9898/5a5912f203bd3a81bc1b5d328bd1f44b) of my files

QueueFragment is where i show downloads
MainViewModel is shared ViewModel

**Comment by tonyofrancis** [comment]
@maulik9898 The server may not be returning the needed information to determine the eta and download speed. -1 mean it is undetermined. See the java documentation.

**Comment by maulik9898** [comment]
Oh i solve this. I was trying to get speed and eta from download object   from Listener
