### ISSUE TITLE
Download is not starting

### ISSUE THREAD

**Issue by deepakkumardk** [tonyofrancis/Fetch#393]
String imageFilePath = "";
        try {
            String root = Environment.getExternalStorageDirectory().toString();
            File myDir = new File(root + "/MyFolder/");
            if (!myDir.exists()) {
                myDir.mkdirs();
            }
            String name = title + "_" + new Date().getTime() + ".jpg";
            File imageFile = new File(myDir, name);
            imageFilePath = imageFile.getAbsolutePath();
        } catch (Exception e) {
            log(e.getMessage());
        }
        Request request = new Request(url, imageFilePath);
        request.setGroupId(groupId);
        fetch.addListener(fetchListener);//fetch and fetch listener is initialized already
        fetch.enqueue(request, updatedRequest -> {
        }, error -> {
        });

And in my Application class

          final FetchConfiguration fetchConfiguration = new FetchConfiguration.Builder(this)
                .enableRetryOnNetworkGain(true)
                .setDownloadConcurrentLimit(5)
                .setGlobalNetworkType(NetworkType.ALL)
                .setHttpDownloader(new HttpUrlConnectionDownloader(Downloader.FileDownloaderType.PARALLEL))
                .setNotificationManager(new DefaultFetchNotificationManager(this))
                .build();
        Fetch.Impl.setDefaultInstanceConfiguration(fetchConfiguration);

Is there something worng with this since the download is not starting, it's not even queued. This problem is happening with me second time, but I don't know what's causing it.

**Comment by tonyofrancis** [comment]
@deepakkumardk The Fetch onqueue method has 2 callbacks. Are any of them being called? Does the sample app work on your device?
