### ISSUE TITLE
Database Plugin

### ISSUE THREAD

**Issue by DHosseiny** [tonyofrancis/Fetch#394]
Fetch uses Room Database and we are using GreenDao Database in out app. This causes to two database connection to be open concurrently. How about a pluggable Database interface that the default implementation is with Room but clients can change it with their own implementations.
Thank you

**Comment by tonyofrancis** [comment]
@DHosseiny. This is already possible in Fetch. Extend the FetchDatabaseManager interface with your custom class and database and set an instance onto the FetchConfiguration.
