### ISSUE TITLE
can not download 2 request with same url ,concurrent!?

### ISSUE THREAD

**Issue by ali-bagheri** [tonyofrancis/Fetch#397]
Hi,
if start 2 Request by same URL and same file path, one of them not response and not call listener!!

i use Fetch in a chat messenger , and may be 2 message have same image ,when start download images (concurrent) one of them downloaded but another not  response.

**Comment by tonyofrancis** [comment]
@ali-bagheri Fetch cannot download 2 request to the same file path. It is unsafe to do so. The file path have to be unique for each request managed by Fetch. What you can do is replace the existing request or increment the file path. Here is how it is done:
```java
        request = new Request("url", "filePath");
        request.setEnqueueAction(EnqueueAction.INCREMENT_FILE_NAME);
        fetch.enqueue(request, new Func<Request>() {
            @Override
            public void call(@NotNull Request result) {
               SingleDownloadActivity.this.request = result;  
               String filePath = result.getFile(); // check new file path
                //success . note the new file path
            }
        }, new Func<Error>() {
            @Override
            public void call(@NotNull Error result) {
                //error
            }
        });
```
See the other `EnqueueAction`'s  for more use cases.
