### ISSUE TITLE
r u there i need help how to implement in web 2 view 

### ISSUE THREAD

**Issue by iramgarhia** [tonyofrancis/Fetch#398]
hello,
sir i need help i have project web 2 view app i want to implement download manager can u guide me

**Comment by tonyofrancis** [comment]
@iramgarhia please have a look at the sample app. It will guide you in the right direction

**Comment by iramgarhia** [comment]
@tonyofrancis how to fix this sir?
![Capture](https://user-images.githubusercontent.com/52193487/60302690-54dbbe80-98e9-11e9-88e5-8f4088d25f3e.PNG)

**Comment by iramgarhia** [comment]
unable to debug app where is problem
