### ISSUE TITLE
FetchDatabaseManager should work with Download not DownloadInfo

### ISSUE THREAD

**Issue by DHosseiny** [tonyofrancis/Fetch#399]
I want to use greenDao to implement FetchDatabaseManager. but FetchDatabaseManager uses DownloadInfo and GreenDao does not let this line of code:
`greenDaoDownloadInfoDao.insert(downloadInfo)`

> Type mismatch: inferred type is DownloadInfo but GreenDaoDownloadInfo! was expected

Must insert exact type not inherited type.
Is there a way to change FetchDatabaseManager signature to `FetchDatabaseManager<T : Download>` or `FetchDatabaseManager<T : DownloadInfo>`?

Note: GreenDaoDownloadInfo extends DownloadInfo

**Comment by tonyofrancis** [comment]
looking into this

**Comment by tonyofrancis** [comment]
@DHosseiny an update for this is in the next release. Just polishing everything up and will post back here soon.

**Comment by tonyofrancis** [comment]
@DHosseiny   This issue is now fixed in new Fetch version 3.0.10/Androidx 3.1.4. See change log. FetchDatabaseManager has been updated to allow you better customization. Please let me know how well it works for you.

**Comment by DHosseiny** [comment]
Thank you. I will check it.
