### ISSUE TITLE
Design for supporting multiple  downloads

### ISSUE THREAD

**Issue by raju249** [tonyofrancis/Fetch#40]
Hi @tonyofrancis ,

I wanted help in designing the feature to support multiple downloads in my application.
How do I go about updating progress for each download in same notification ?

I have been thinking of showing something like ```1 of 4 in progress``` in the notification and then when `1` completes update the notification as ```2 of 4 in progress```.

Any idea on this of what should be the efficient design for this feature and have good user experience ?

**Comment by tonyofrancis** [comment]
@raju249 Please have a look at the sample app in this Project. There is a GamesActivity class that shows you how to do what you described.
