### ISSUE TITLE
Using two fetch instances simulaneously

### ISSUE THREAD

**Issue by tosam144** [tonyofrancis/Fetch#402]
In two different tabs in my app, I am using two instances of fetch to download files. When the user downlaods the file in tab 1 (which takes a while) and then switches to tab 2 in order to start the download of the file in tab 2 (while the download in tab 1 is still ongoing), the event onCompleted from fetchListener in tab 1 is called and contains the downloads of tab 2. It seems that the two instances of fetch get into each other's way. Could that be?

**Comment by maulik9898** [comment]
U can use groupId to distinguish from which group this download belong.
here is small example

In Tab 1 fragment

```
public static final int TAB_1=1;


Request request = new Request(url, fileName);
                    request.setAutoRetryMaxAttempts(5);
                    request.setPriority(Priority.HIGH);
                    request.setGroupId(TAB_1);

FetchListener fetchListener=new FetchListener() {
     ...............................

        @Override
        public void onCompleted(@NotNull Download download) {
            if(download.getGroup()==TAB_1){
          // Update your view or list

            }


        }

        ..............................................
  
    };



```

In Tab 2 fragment

```
public static final int TAB_2=2;

Request request = new Request(url, fileName);
                    request.setAutoRetryMaxAttempts(5);
                    request.setPriority(Priority.HIGH);
                    request.setGroupId(TAB_2);

FetchListener fetchListener=new FetchListener() {
     ...............................

        @Override
        public void onCompleted(@NotNull Download download) {
            if(download.getGroup()==TAB_2){
          // Update your view or list

            }


        }

        ..............................................
  
    };



```

**Comment by tosam144** [comment]
Thanks! So is it recommended to only have exactly **one single** instance of fetch and **one single** fetchListener throughout the entire application?

**Comment by maulik9898** [comment]
I think that depends on your application.  In my case, I have only one instance of fetch running in background service with a single listener and I use **LiveData** to post data to fragments

**Comment by tonyofrancis** [comment]
@tosam144  If you want two different instances of fetch and have them be separated you need to specify a namespace for each fetch instance.
```java
     final FetchConfiguration fetchConfiguration = new FetchConfiguration.Builder(this)
                .setNamespace("tab1")
                .enableRetryOnNetworkGain(true)
                .setDownloadConcurrentLimit(3)
                .build();
        final Fetch fetchTab1 = Fetch.Impl.getInstance(fetchConfiguration);
```
Please have a look at the sample app!

**Comment by tosam144** [comment]
Thank you!
