### ISSUE TITLE
Bug: download complete return me an empty file

### ISSUE THREAD

**Issue by shuwenyouxi** [tonyofrancis/Fetch#403]
1.download a file
2. delete the file in file system after download complete
3.download this file again

result: Fetch will return me an empty file and complete callback was invoked

**Comment by maulik9898** [comment]
@shuwenyouxi  I am also facing this issue. 
@tonyofrancis please look into this

**Comment by JakubNeukirch** [comment]
Same issue here

**Comment by JakubNeukirch** [comment]
I done small investigation, the problem occurs when the file url and filename is the same with each download. Only first download happen, next request will be completed instantly with file size 0B. I guess this is something about storing ids somewhere - ids are generated by hashcode of url and filename, so if any of them doesnt change the id will be the same as requests before.

**Comment by maulik9898** [comment]
Yes mostly because fetch doesn't check file existance when we try to add download with same filename as previously completed download.
Fetch only check if any download with this filename present or not and if present it will just move new request to completed downloas as default behavior of UPDATE_ACCCORDINGLY enque action.

**Comment by tonyofrancis** [comment]
@maulik9898 is correct! What you need to do is set `enableFileExistChecks(true)` on the fetchConfiguration or use a different enqueue action. See `enableFileExistChecks(true)` documentation. EnableFileExistChecks is off by default.
```java
      final FetchConfiguration fetchConfiguration = new FetchConfiguration.Builder(this)
                .enableFileExistChecks(true)
                .enableRetryOnNetworkGain(true)
                .setDownloadConcurrentLimit(3)
                .build();
        final Fetch fetch = Fetch.Impl.getInstance(fetchConfiguration);
```

**Comment by alvince** [comment]
> @maulik9898 is correct! What you need to do is set `enableFileExistChecks(true)` on the fetchConfiguration or use a different enqueue action. See `enableFileExistChecks(true)` documentation. EnableFileExistChecks is off by default.
> 
> ```java
>       final FetchConfiguration fetchConfiguration = new FetchConfiguration.Builder(this)
>                 .enableFileExistChecks(true)
>                 .enableRetryOnNetworkGain(true)
>                 .setDownloadConcurrentLimit(3)
>                 .build();
>         final Fetch fetch = Fetch.Impl.getInstance(fetchConfiguration);
> ```

But the checks fileExistChecksEnabled is true default, in the source code latest

```Kotlin
const val DEFAULT_FILE_EXIST_CHECKS = true
```

@tonyofrancis

**Comment by tonyofrancis** [comment]
@alvince You are correct!. That was my mistake. File checking is enabled by default. The issue is with the enqueue action. The default is update_accordingly. It should be set to a different option.

**Comment by alvince** [comment]
> @alvince You are correct!. That was my mistake. File checking is enabled by default. The issue is with the enqueue action. The default is update_accordingly. It should be set to a different option.

I think it was effected by file checking, and fixed it. #410 

Please check it @tonyofrancis

**Comment by tonyofrancis** [comment]
@alvince  provided a fix. It will be pushed in the next release.

**Comment by shuwenyouxi** [comment]
@tonyofrancis May I known the time of next release

**Comment by rranjithkumar100** [comment]
Still issue persists 

**My dependency** 
 implementation "androidx.tonyodev.fetch2:xfetch2:3.1.4"

**My config**

       FetchConfiguration fetchConfiguration = new FetchConfiguration.Builder(context)
                .enableFileExistChecks(false)
                .enableHashCheck(false)
                .setAutoRetryMaxAttempts(30)
                .setDownloadConcurrentLimit(20)
                .build();

First time downloading fine. Next time it will return success result. but file empty (0KB)

Tried   this too. .enableFileExistChecks(true) &&  .enableHashCheck(true) but same result

**Comment by rranjithkumar100** [comment]
> Still issue persists
> 
> **My dependency**
> implementation "androidx.tonyodev.fetch2:xfetch2:3.1.4"
> 
> **My config**
> 
> ```
>    FetchConfiguration fetchConfiguration = new FetchConfiguration.Builder(context)
>             .enableFileExistChecks(false)
>             .enableHashCheck(false)
>             .setAutoRetryMaxAttempts(30)
>             .setDownloadConcurrentLimit(20)
>             .build();
> ```
> 
> First time downloading fine. Next time it will return success result. but file empty (0KB)
> 
> Tried this too. .enableFileExistChecks(true) && .enableHashCheck(true) but same result

waiting for this long time
