### ISSUE TITLE
getDownload() methods' callbacks very often aren't triggered until the end of downloading process.

### ISSUE THREAD

**Issue by alex-berdnikov** [tonyofrancis/Fetch#405]
I encountered a bug on attempt to get result from fetch.getDownload()  and all other related methods. Very often when I call getDownload() method during group downloading process it's callback method might be called only once or never called at all until the very end of the downloading. 
So for instance we have a group download process in progress, while it's running I call getDownload(id, result -> { /* some stuff */  }); and the result never returns, then I call it two more times and it never returns either. Then the downloading process ends, and callback get's called for three times in a row. I also observe same result with getFetchGroup() method.

**Comment by alex-berdnikov** [comment]
I observe this behavior both in Fetch and FetchRx.

**Comment by tonyofrancis** [comment]
@alex-berdnikov Can you please share a sample code? 

There should be no reason to call fetch.getDownload() method inside a listener callback. Attach a `FetchGroupListener` or `AbstractFetchGroupListener` which has group download listeners. Please let me know if this helps.

**Comment by alex-berdnikov** [comment]
I don't call it in listener callbacks, no. I call it in my code, while group downloading is in progress.

**Comment by alex-berdnikov** [comment]
Here's an example
<img width="607" alt="Screen Shot 2019-06-27 at 21 12 09" src="https://user-images.githubusercontent.com/2362513/60289957-4fe63180-9920-11e9-8763-f790e4c6d2f7.png">

If current download is not a group download, everything goes smooth, but if it's a series of downloads in a group going on, getDownload()'s result is delayed until downloading process is ended.

**Comment by tonyofrancis** [comment]
@alex-berdnikov Tested something this simple and I get a callback each time.
```java
    private void enqueueDownloads() {
        final List<Request> requests = Data.getFetchRequestWithGroupId(GROUP_ID);
        int id = requests.get(0).getId();
        fetch.enqueue(requests, updatedRequests -> {
           
        });
        fetch.addListener(new AbstractFetchListener() {
            @Override
            public void onProgress(@NotNull Download download, long etaInMilliSeconds, long downloadedBytesPerSecond) {
                super.onProgress(download, etaInMilliSeconds, downloadedBytesPerSecond);
                fetch.getDownload(id, new Func2<Download>() {
                    @Override
                    public void call(@Nullable Download result) {
                        Log.d("tonyoTest", "i am here");
                    }
                });
            }
        });

    }
```
What does you fetch configuration look like?
Note that all callbacks are done on the main thread So if your progress reporting interval is set too low it may be blocking the results of the get download.

**Comment by alex-berdnikov** [comment]
OkHttpClient client = new OkHttpClient.Builder()
                .writeTimeout(5, TimeUnit.MINUTES)
                .connectTimeout(5, TimeUnit.MINUTES)
                .readTimeout(5, TimeUnit.MINUTES)
                .retryOnConnectionFailure(true)
                .addInterceptor(new HttpLoggingInterceptor())
                .protocols(Arrays.asList(Protocol.HTTP_1_1))
                .addNetworkInterceptor(chain -> {
                    Request request = chain.request();

                    long t1 = System.nanoTime();
                    Timber.tag("DownloadService").e("Sending request %s on %s%n%s",
                            request.url(), chain.connection(), request.headers());

                    Response response = chain.proceed(request);

                    long t2 = System.nanoTime();
                    Timber.tag("DownloadService").e("Received response for %s in %.1fms%n%s",
                            response.request().url(), (t2 - t1) / 1e6d, response.headers());

                    return response;
                })
                .build();

        OkHttpDownloader downloader = new OkHttpDownloader(
                Downloader.FileDownloaderType.PARALLEL);
        downloader.setClient(client);

        final FetchConfiguration fetchConfiguration = new FetchConfiguration.Builder(this)
                .setDownloadConcurrentLimit(3)
                .setProgressReportingInterval(REFRESH_DELAY)
                .enableAutoStart(true)
                .enableRetryOnNetworkGain(true)
                .enableHashCheck(true)
                .enableLogging(true)
                .setNamespace("DownloadService")
                .setHttpDownloader(downloader)
                .setNotificationManager(new FetchNotificationManager() {
                    @Override
                    public long getProgressReportingIntervalInMillis() {
                        return 0;
                    }

                    @Override
                    public void setProgressReportingIntervalInMillis(long l) {

                    }

                    @Override
                    public boolean updateGroupSummaryNotification(int i, NotificationCompat.@NotNull Builder builder, @NotNull List<? extends DownloadNotification> list, @NotNull Context context) {
                        return false;
                    }

                    @Override
                    public void updateNotification(NotificationCompat.@NotNull Builder builder, @NotNull DownloadNotification downloadNotification, @NotNull Context context) {
                    }

                    @Override
                    public void notify(int i) {

                    }

                    @NotNull
                    @Override
                    public PendingIntent getGroupActionPendingIntent(int i, @NotNull List<? extends DownloadNotification> list, DownloadNotification.@NotNull ActionType actionType) {
                        return null;
                    }

                    @NotNull
                    @Override
                    public PendingIntent getActionPendingIntent(@NotNull DownloadNotification downloadNotification, DownloadNotification.@NotNull ActionType actionType) {
                        return null;
                    }

                    @Override
                    public void cancelOngoingNotifications() {
                    }

                    @Override
                    public void cancelNotification(int i) {
                    }

                    @Override
                    public void createNotificationChannels(@NotNull Context context, @NotNull NotificationManager notificationManager) {

                    }

                    @NotNull
                    @Override
                    public String getChannelId(int i, @NotNull Context context) {
                        return null;
                    }

                    @Override
                    public boolean postNotificationUpdate(@NotNull Download download, long l, long l1) {
                        if (download.getStatus() == Status.COMPLETED) {
                            if (isVibrateTurnOn) {
                                vibrator.vibrate(500);
                            }
                        }
                        return false;
                    }

                    @Override
                    public void handleNotificationOngoingDismissal(int i, int i1, boolean b) {

                    }

                    @Override
                    public long getOngoingDismissalDelay(int i, int i1) {
                        return 0;
                    }

                    @NotNull
                    @Override
                    public NotificationCompat.Builder getNotificationBuilder(int i, int i1) {
                        return null;
                    }
                })
                .setLogger(new Logger())
                .build();
        fetch = Fetch.Impl.getInstance(fetchConfiguration)

**Comment by tonyofrancis** [comment]
@alex-berdnikov what is the value of `.REFRESH_DELAY`? any thing less than 2 seconds will cause slow ui performance.

**Comment by alex-berdnikov** [comment]
It's 500 ms at the moment

**Comment by tonyofrancis** [comment]
@alex-berdnikov 500 ms is too low. Fetch will keep posting progress updates every 500 ms and causes other ui events to be super delayed. Its best to set it no lower than 2 seconds. 

The reason why fetch allow for low progress reporting is because fetch can be used anywhere outside of an activity, such as a services etc.

**Comment by asker517** [comment]
@alex-berdnikov any progress on this issue?

**Comment by alex-berdnikov** [comment]
No, unfortunately

**Comment by asker517** [comment]
@alex-berdnikov i just found  remove``HttpLoggingInterceptor`` or HttpLoggingInterceptor set level to `basic` or `none` can solved...
