### ISSUE TITLE
Unable to debug this app can u fix this

### ISSUE THREAD

**Issue by iramgarhia** [tonyofrancis/Fetch#407]
unable to debug check and please tell me sultions sir?
![60302690-54dbbe80-98e9-11e9-88e5-8f4088d25f3e](https://user-images.githubusercontent.com/52193487/60323598-5b912280-9937-11e9-932a-b83b22faf5ae.png)

**Comment by iramgarhia** [comment]
![60302690-54dbbe80-98e9-11e9-88e5-8f4088d25f3e](https://user-images.githubusercontent.com/52193487/60323552-3e5c5400-9937-11e9-935d-162436f5977b.png)

**Comment by tonyofrancis** [comment]
@iramgarhia We would need more context to help. Did you download the project from github? What branch are you working on. You should be able to build against the v3.0 or the v3.0-develop branch.

**Comment by iramgarhia** [comment]
M download latest verison
