### ISSUE TITLE
ERROR: Failed to resolve: com.tonyodev.fetch2core:fetch2core:3.0.9

### ISSUE THREAD

**Issue by ghost** [tonyofrancis/Fetch#409]
When I try to implement com.tonyodev.fetch2:fetch2:3.0.9 I get that error.
Error does not occur with version 3.0.8

**Comment by tonyofrancis** [comment]
looking into this

**Comment by tonyofrancis** [comment]
@munix this will be fixed in next release. will post back soon. Use 3.0.8 in the mean time

**Comment by tonyofrancis** [comment]
@munix This issue is now fixed in new Fetch version 3.0.10/Androidx 3.1.4.

**Comment by ghost** [comment]
Thanks!
