### ISSUE TITLE
Not able to download redirected url in android version 4.4(Kitkat)

### ISSUE THREAD

**Issue by ShantiRanjanDas** [tonyofrancis/Fetch#41]
It is not downloading form redirected links, as I am using Vimeo video for download, As the first links which Vimeo provides is an "https url" and later it changes to "http url" . Here I am proving a vimeo link from which am trying to download a video, 

https://player.vimeo.com/play/720138981?s=210197530_1494265285_b46e1ab154e0464a03760f8805892af8&loc=external&context=Vimeo%5CController%5CApi%5CResources%5CUser%5CVideoController.&download=1&filename=Untitledsource.mp4

You can use the link to download the file in browser and it is downloading fine. And if you check the downloading url, it is an http url.

So, what I have to do to download, this kind of files.

**Comment by tonyofrancis** [comment]
@ShantiRanjanDas Thanks for reporting this. Seems like Fetch needs a little bit of tuning to get redirects to work properly. I will look into this and do hope to find a solution as soon as possible. Ill keep this issue open and post updates here.

**Comment by ShantiRanjanDas** [comment]
Thanks for your support @tonyofrancis

**Comment by ShantiRanjanDas** [comment]
@tonyofrancis it is still not downloading and giving me "unknown handshake error"

Here is the log, 
05-09 15:46:31.046 23729-23729/test.download.app E/download_id: 26066080638565
05-09 15:46:31.747 23729-23831/test.download.app E/NativeCrypto: ssl=0x60b9d410 cert_verify_callback x509_store_ctx=0x61a778c0 arg=0x0
05-09 15:46:31.747 23729-23831/test.download.app E/NativeCrypto: ssl=0x60b9d410 cert_verify_callback calling verifyCertificateChain authMethod=ECDHE_RSA
05-09 15:46:33.130 23729-23831/test.download.app E/NativeCrypto: Unknown error during handshake
05-09 15:46:33.668 23729-23831/test.download.app E/NativeCrypto: Unknown error during handshake
05-09 15:46:33.713 23729-23729/test.download.app E/id: 26066080638565
05-09 15:46:33.714 23729-23729/test.download.app E/status: 904
05-09 15:46:33.714 23729-23729/test.download.app E/progress: 0
05-09 15:46:33.715 23729-23729/test.download.app E/downloadedBytes: 0
05-09 15:46:33.716 23729-23729/test.download.app E/fileSize: 0
05-09 15:46:33.716 23729-23729/test.download.app E/error: -101

Here I am providing you a new link which will be valid for 1 day(not sure)

https://player.vimeo.com/play/722584443?s=210709564_1494368443_14f9df95237aa387ff6a15a2675bf809&loc=external&context=Vimeo%5CController%5CApi%5CResources%5CUser%5CVideoController.&download=1&filename=Untitled164.mp4

**Comment by tonyofrancis** [comment]
@ShantiRanjanDas I am still looking into this

**Comment by tonyofrancis** [comment]
@ShantiRanjanDas are you able to download these links with fetch on a different version of android? I am unable to view them in a web browser. This does not look like a redirection issue.

**Comment by ShantiRanjanDas** [comment]
No
