### ISSUE TITLE
FetchService is running always in backgound?

### ISSUE THREAD

**Issue by KulwinderSinghRahal** [tonyofrancis/Fetch#42]
i have noticed that after calling fetch.release(); method on fetch instance the FetchService is not stop it is running forever even  if not downloading anything. did i need to do anything else to stop this service.

**Comment by tonyofrancis** [comment]
@KulwinderSinghRahal The FetchService is not stopped when calling fetch.release(). The FetchService only stops after all downloads are complete. Are you able to reproduce this bug?

**Comment by KulwinderSinghRahal** [comment]
Actually I am creating Download manager app with your library therefore I'm creating Service in which getting  instance of Fetch. my service class handles actions like start,stop,pause etc. So when my app is destroyed I'm sending Bus(otto) message to service to stop my service class if not downloading anything. it destroy the service and release fetch if not downloading but after destroying service fetchservcie is still running and after some time my service is also restarted.

I'm also want to know that is I'm doing it right or there any better way to do it with help of  library ?

**Comment by AnushSR** [comment]
Thanks for the amazing library!

As the OP said, the service runs in the background even after all downloads have been completed.

Tried calling remove(id) removeAll() and release() but the service doesn't stop. Is this the correct way to stop the service?

**Comment by tonyofrancis** [comment]
It seems that there is a bug thats preventing fetch from stopping properly. I am looking into it and will update as soon as possible. In the mean time a work around is to call `context.stopService(new Intent(context,FetchService.class))`.

**Comment by tonyofrancis** [comment]
This has been fixed and will make it in the next version of Fetch 1.1.2. The new version will be released in a few days. Please check back.
