### ISSUE TITLE
Small initial part of file is not getting downloaded

### ISSUE THREAD

**Issue by NitishGadangi** [tonyofrancis/Fetch#420]
**Issue Description:**
I am using fetch to download mp3 files from the server.
But later realized that the first 3 seconds of the mp3 file is missing in the downloaded file.
This is happening with all of my mp3 links.
here is a test [link](https://aac.saavncdn.com/426/f64ddaeb6ff9142d2aade5fe57f06f55_320.mp4).

**Version Details:**
using `fetch2:3.0.10`
and `fetch2okhttp:3.0.10`
with following configuration:
```
FetchConfiguration fetchConfiguration = new FetchConfiguration.Builder(this)
                .setDownloadConcurrentLimit(1)
                .setHttpDownloader(new OkHttpDownloader(Downloader.FileDownloaderType.PARALLEL))
                .setNamespace(FETCH_NAMESPACE).build();
```

**Comment by tonyofrancis** [comment]
@NitishGadangi What happens if you try to download another file? Does it download correctly?. You can try a previous version of Fetch also and let me know if that worked?

**Comment by tonyofrancis** [comment]
is this still an issue?

**Comment by jpvs0101** [comment]
Might be related to #419 ?

**Comment by tonyofrancis** [comment]
@NitishGadangi @jpvs0101 Just test and have been able to successfully download the file several times matching the md5 hash code each time vs the one I downloaded via a web browser. I am wondering if this could be related to network connection, network hops etc. Not sure what else I can try to reproduce this issue. Any other information would be much appreciated.

**Comment by NitishGadangi** [comment]
If you are using Chrome
You can use this link to stream the Audio (and listen first few seconds without Downloading)

https://aac.saavncdn.com/426/f64ddaeb6ff9142d2aade5fe57f06f55_320.mp4

Now try downloading the same and listen the difference in the first 1second..

Don't know why but this bug is happening with only these kind of links.

**Comment by tonyofrancis** [comment]
This bug may be related to #419 . A fix will be released in the the next few days.
