### ISSUE TITLE
RxFetch should not return nullable types for Convertible

### ISSUE THREAD

**Issue by CarsonRedeye** [tonyofrancis/Fetch#421]
`getDownloads` and `resetAutoRetryAttempts` have the return type of Convertible<Download?> which throws an "item is null" exception. It's not hard to wrap this with an "onErrorResumeNext" but it leads to messy code.

**Comment by tonyofrancis** [comment]
@CarsonRedeye I will try ton have a look into this soon.

**Comment by tonyofrancis** [comment]
Fixed this bug. A new version of Fetch will be released in the next few days.
