### ISSUE TITLE
How to fail download due to network connection

### ISSUE THREAD

**Issue by CarsonRedeye** [tonyofrancis/Fetch#426]
My use case is I want to enqueue a download, but have it fail if there is no network connection and delete the download and never retry. I tried setting `request.autoRetryMaxAttempts = 0` but when I attach an observer with `attachFetchObserversForDownload(downloadId, object : FetchObserver<Download> {...` all I ever receive in onChanged is QUEUED status, never failed.

I would like a callback for failed. How would I do that?

**Comment by tonyofrancis** [comment]
@CarsonRedeye on your` FetchConfiguration` set `.enableRetryOnNetworkGain(false)`

**Comment by CarsonRedeye** [comment]
Hi tony. I did that and it works partially. It now throws an error if the network connection fails after the download has started. However if there is no network connection when the download is queued, no error is thrown. Is that a bug? The workaround for now is to check for connection before downloading myself, but that is a bit hacky imo.

**Comment by tonyofrancis** [comment]
Mhm. If a download is ongoing and internet connection is lost then then we check if we need to retry, if retry is false then we throw an error. It can take some time depending on the timeout values set on the client. Are you using a custom downloader?

**Comment by CarsonRedeye** [comment]
Hi Tony. The functionality you describe is working. However this scenario isn't: 
1. The device is offline
2. A download is queued.
EXPECTED: An error is thrown that there is no connectivity. (I want to show the user there is no network and they can try again later, but the API doesn't allow me this)
ACTUAL: onChanged only fires with QUEUED status and nothing else.

**Comment by tonyofrancis** [comment]
@CarsonRedeye I see what you are saying. There is not built in logic to throw an exception if there is no internet connection when a new download is enqueued. Fetch stores the download information normally and waits till there is internet connect. The best solution is to check for network connection before enqueuing. Will make a not of this for future releases.
