### ISSUE TITLE
okhttp3.internal.http2.StreamResetException: stream was reset: CANCEL

### ISSUE THREAD

**Issue by DennisVanAcker1** [tonyofrancis/Fetch#427]
I'm encountering this issue alot. It causes downloads to fail. I'm aware that this doesn't have much to do with Fetch itself, but this is kind of a last resort before using Http1.1. Any help would be much appreciated

![image (1)](https://user-images.githubusercontent.com/20066687/62778057-8ed6dd80-baaf-11e9-8252-81c13686d23e.png)
![image (2)](https://user-images.githubusercontent.com/20066687/62778058-8ed6dd80-baaf-11e9-8153-67975398c896.png)

Does anyone have a solution for this?

**Comment by tonyofrancis** [comment]
@DennisVanAcker1 You can pass a custom okhttp client to Fetch. 
```java
  private OkHttpDownloader getOkHttpDownloader() {
        final OkHttpClient okHttpClient = new OkHttpClient.Builder().build();
        return new OkHttpDownloader(okHttpClient,
                Downloader.FileDownloaderType.SEQUENTIAL);
    }
```
In your application add the latest okhttp client packages and provide that to fetch. Not sure if that will fix your problem.

**Comment by DennisVanAcker1** [comment]
Ok i'll try that out, thank you.

I commented multiple times last week on the issue "progress return back? #185" I spend quite some time on debugging and reproducing the issue; and i think i found the problem. Could you please look into that aswell?

**Comment by tonyofrancis** [comment]
@DennisVanAcker1 Were you able to get this resolved?

**Comment by DennisVanAcker1** [comment]
haven't encountered the issue anymore but it's hard to reproduce. I can't say for sure. 
Can you please re-open issue #185, this is a big and way more urgent problem in your library. I can also provide feedback on a fix for that because i can reproduce it. I would even have done a pull request myself but i don't have permission
