### ISSUE TITLE
UI becomes unresponsive when downloading files from certain urls

### ISSUE THREAD

**Issue by cdn34** [tonyofrancis/Fetch#428]
An example of when this happens is when I try to download this particular url https://www.nejm.org/doi/pdf/10.1056/NEJMoa1813865. This file is under a subscription and I'm only able to download it once I log in.

If I set the cookies I get after logging in the website, the download finishes successfully and the UI is responsive as always. If I don't set the cookies the download fails and the UI becomes completely unresponsive for around 3 seconds.

Observation: https://www.nejm.org/doi/full/10.1056/NEJMoa1813865?query=featured_home, despite the fact that is is a subscriber based article, any new account can subscribe to it for free, so this behaviour should be easy to replicate.

Version: 
- fetch2:3.0.10
- fetch2okhttp:3.0.10

Config:
```
        CookieManager cookieManager = new CookieManager();
        cookieManager.setCookiePolicy(CookiePolicy.ACCEPT_ALL);
        OkHttpClient okHttpClient = new OkHttpClient
                .Builder()
                .readTimeout(20_000L, TimeUnit.MILLISECONDS)
                .connectTimeout(15_000L, TimeUnit.MILLISECONDS)
                .cache(null)
                .followRedirects(true)
                .followSslRedirects(true)
                .retryOnConnectionFailure(false)
                .cookieJar(new JavaNetCookieJar(cookieManager)).build();

        FetchConfiguration fetchConfiguration = new FetchConfiguration.Builder(context)
                .setDownloadConcurrentLimit(4)
                .setProgressReportingInterval(100)
                .setNamespace("PPBackgroundDownloader")
                .setHttpDownloader(new OkHttpDownloader(okHttpClient))
                .build();
```

**Comment by tonyofrancis** [comment]
@cdn34 Your issue is ` .setProgressReportingInterval(100)`. You are updating the UI on the main thread every 100 milliseconds. This will cause serious performance issues. Fetch sets the default to 2_000 milliseconds. Every two seconds.

**Comment by cdn34** [comment]
@tonyofrancis the report interval being set to a low value can perhaps cause issues, but that's not the problem here, or at least it doesn't seem to be, as when the correct cookies are passed the file downloads without issues and there's no slowness. 

The slowness comes when no cookies are passed and the downloader reaches the onCompleted listener, it seems to freeze here for a second or more depending on the device. This happens with both `.setProgressReportingInterval(100)` and `.setProgressReportingInterval(2000)`.

**Comment by tonyofrancis** [comment]
mhm. So it seems the server is doing some kind of check at some point and causes the slow/ freeze up. That does not seem like an issue with Fetch being that it downloads fine when the cookies are passed. What cookie values are you sending back?

**Comment by cdn34** [comment]
It seems like it is an issue with fetch, since the slowness only happens on android using fetch, on iOS using NSURLSessionDownloadTask that works fine in either case. The cookies are retrieved after login so its value vary.
