### ISSUE TITLE
fetch view is reducing it size with weight.

### ISSUE THREAD

**Issue by ShantiRanjanDas** [tonyofrancis/Fetch#43]
What I see is, When I use weight for height of fetch view. it is reducing its size,I will try to explain with the help of an example.
Please do visit this [link ](https://cloud.githubusercontent.com/assets/28480802/26046631/6def42c6-396d-11e7-84e5-3304399eb5ed.png).

As I have used the main views as "Linear layout" with "weight_sum=2", and two views one is video_view and the other is textview. I am using weight for making both views of equal height. but when I run the application, video_view(your fetch view) is reducing its size. For knowing it better I have set background color to green and textview color to blue.

Here is the below code what I have used in xml.

<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="#90b94b"
    android:orientation="vertical"
    android:weightSum="2">
    
    <fm.jiecao.jcvideoplayer_lib.JCVideoPlayerStandard
        android:id="@+id/MyVideoPlayer"
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:layout_weight="1"
        android:keepScreenOn="true" />

    <TextView
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:layout_weight="1"
        android:background="#4fa0ab"
        android:gravity="center"
        android:text="TextView Area" />

</LinearLayout>

**Comment by tonyofrancis** [comment]
Closing this issue. Its not related to fetch.
