### ISSUE TITLE
Download not starting after 404

### ISSUE THREAD

**Issue by BlueCobold** [tonyofrancis/Fetch#430]
Hi.

When one of my downloads fails due to 404, I can create a new fetch-instance and enqueue new downloads, but they will never start. The enqueue-callbacks are called (just the enqueue-one, not the error-one).
Using xfetch2:3.1.4 on Android 6.0.1

`

        val fetchConfiguration = FetchConfiguration.Builder(context)
                .setDownloadConcurrentLimit(3)
                .build()
        val fetch = Fetch.getInstance(fetchConfiguration)

        val fetchListener = object : FetchListener {...}

        fetch.addListener(fetchListener)
        for (file in files) {
            val request = Request(file, downloadPath)
            request.priority = Priority.HIGH
            request.networkType = NetworkType.ALL
            fetch.enqueue(request,
                    Func {
                    },
                    Func {
                    })
        }
`

Any ideas? It's not a problem if all downloads succeed. I can totally reproduce it. The only fix is to uninstall the app and install it again. Closing and re-opening does not fix the issue.

Edit:
If I chose a different download-path than the previous failed run (the usual name is "tmp{i}" whereas i is 0..n), it all works fine. Is it possible there are some files/caches remaining that prevent the failed download to be re-scheduled?

**Comment by tonyofrancis** [comment]
@BlueCobold . Each Fetch request has an `enqueueAction` Field that states how fetch should handle downloads that are already enqueued. Please have a look at `EnqueueAction` documentation.

**Comment by BlueCobold** [comment]
The default is UPDATE_ACCORDINGLY, but the docs don't say what the manager will do if that download was failed previously. I would assume it would either count as "not downloaded" and thus be started or as "not completed" and thus resume. Both is not the case. I imagine REPLACE_EXISTING would solve the issue, but updated docs would still be helpful. It surely does not count as "completed" though as the onComplete callback is not being called.

**Comment by tonyofrancis** [comment]
If a download error-ed it will stay as error-ed. I will update the docs.
