### ISSUE TITLE
FetchObservers get garbage collected if created as local variable

### ISSUE THREAD

**Issue by CarsonRedeye** [tonyofrancis/Fetch#436]
I'm trying to observe the status of a download, but quite often `val observer = it.get()` on line 270 of `ListenerCoordinator` returns null, since they are stored as WeakReferences. The effect of this is that my view never receives a callback that the download is complete and sits there permanently with the loading indicator.

**Comment by tonyofrancis** [comment]
Observers and Listener and are store with weak references in Fetch. You should store then in a field variable to prevent them from going out of scope.
