### ISSUE TITLE
Status Update

### ISSUE THREAD

**Issue by tonyofrancis** [tonyofrancis/Fetch#439]
Hello Fetch users! 

This is just a quick update on the status of Fetch. I recently switch job two months ago so this is the reason for the long delay in my responses and library updates. I should be getting back to my normal progress in the next two weeks. Thanks for your patience!.

RoadMap:
1. Fix open issues in Fetch version 3.
2. Start work on Fetch version 4 which will be using kotlin coroutines. I am hoping to fix many of the usage issues with Fetch and making it much lighter.

Suggestions are welcomed for version 4!!

**Comment by jpvs0101** [comment]
Good to hear from you, Please give priority to this #419, since it is serious issue for users, because of valuable data might lost!

**Comment by tonyofrancis** [comment]
Hello Fetch users!

Sorry for the delayed Update. A new version of Fetch with a ton of Fixes will be released in the next few days.

RoadMap:

- Fix open issues in Fetch version 3.

- Start work on Fetch version 4 which will be much easier to use. I am hoping to fix many of the usage issues with Fetch and making it much lighter.

Suggestions are welcomed for version 4!!

**Comment by tonyofrancis** [comment]
A version 3 update will be released this weekend!!

**Comment by macgills** [comment]
@tonyofrancis any updates on the release? Would love to get a new version out to Kiwix users.

**Comment by tonyofrancis** [comment]
@macgills I plan on releasing a preview of v3 with lots of bug fixes today. Once I have feedback, It should go public this week.

**Comment by tonyofrancis** [comment]
New version of Fetch 3.0.11 and AndroidX version 3.1.5 has been released. See readme for new version number.

**Comment by macgills** [comment]
Awesome, thank you
