### ISSUE TITLE
UNKNOWN_IO_ERROR while downloading file

### ISSUE THREAD

**Issue by mrshadow98** [tonyofrancis/Fetch#441]
![Image 2019-08-04 at 11 25 17 PM](https://user-images.githubusercontent.com/42746938/65877203-af812c80-e3a8-11e9-8004-336925d44fb3.jpeg)
This error comes while downloading files in Android x or API 29

**Comment by tonyofrancis** [comment]
Can you provide more details: You can enable logging in Fetch:
```java
 final FetchConfiguration fetchConfiguration = new FetchConfiguration.Builder(this)
                .enableLogging(true)
                .setDownloadConcurrentLimit(3)
                .build();
```

**Comment by subhadiprudra** [comment]
android:requestLegacyExternalStorage="true" 

add on manifest under application section
