### ISSUE TITLE
:app:checkDebugDuplicateClasses

### ISSUE THREAD

**Issue by abdulsnovasys** [tonyofrancis/Fetch#448]
> 1 exception was raised by workers:
  java.lang.RuntimeException: Duplicate class org.intellij.lang.annotations.Flow found in modules annotations-13.0.jar (org.jetbrains:annotations:13.0) and annotations-java5-17.0.0.jar (org.jetbrains:annotations-java5:17.0.0)
  Duplicate class org.intellij.lang.annotations.Identifier found in modules annotations-13.0.jar (org.jetbrains:annotations:13.0) and annotations-java5-17.0.0.jar (org.jetbrains:annotations-java5:17.0.0)
  Duplicate class org.intellij.lang.annotations.JdkConstants found in modules annotations-13.0.jar (org.jetbrains:annotations:13.0) and annotations-java5-17.0.0.jar (org.jetbrains:annotations-java5:17.0.0)
  Duplicate class org.intellij.lang.annotations.JdkConstants$AdjustableOrientation found in modules annotations-13.0.jar (org.jetbrains:annotations:13.0) and annotations-java5-17.0.0.jar (org.jetbrains:annotations-java5:17.0.0)
  Duplicate class org.intellij.lang.annotations.JdkConstants$BoxLayoutAxis found in modules annotations-13.0.jar (org.jetbrains:annotations:13.0) and annotations-java5-17.0.0.jar (org.jetbrains:annotations-java5:17.0.0)
  Duplicate class org.intellij.lang.annotations.JdkConstants$CalendarMonth found in modules annotations-13.0.jar (org.jetbrains:annotations:13.0) and annotations-java5-17.0.0.jar (org.jetbrains:annotations-java5:17.0.0)
  Duplicate class org.intellij.lang.annotations.JdkConstants$CursorType found in modules annotations-13.0.jar (org.jetbrains:annotations:13.0) and annotations-java5-17.0.0.jar (org.jetbrains:annotations-java5:17.0.0)
  Duplicate class org.intellij.lang.annotations.JdkConstants$FlowLayoutAlignment found in modules annotations-13.0.jar (org.jetbrains:annotations:13.0) and annotations-java5-17.0.0.jar (org.jetbrains:annotations-java5:17.0.0)
  Duplicate class org.intellij.lang.annotations.JdkConstants$FontStyle found in modules annotations-13.0.jar (org.jetbrains:annotations:13.0) and annotations-java5-17.0.0.jar (org.jetbrains:annotations-java5:17.0.0)
  Duplicate class org.intellij.lang.annotations.JdkConstants$HorizontalAlignment found in modules annotations-13.0.jar (org.jetbrains:annotations:13.0) and annotations-java5-17.0.0.jar (org.jetbrains:annotations-java5:17.0.0)
  Duplicate class org.intellij.lang.annotations.JdkConstants$InputEventMask found in modules annotations-13.0.jar (org.jetbrains:annotations:13.0) and annotations-java5-17.0.0.jar (org.jetbrains:annotations-java5:17.0.0)
  Duplicate class org.intellij.lang.annotations.JdkConstants$ListSelectionMode found in modules annotations-13.0.jar (org.jetbrains:annotations:13.0) and annotations-java5-17.0.0.jar (org.jetbrains:annotations-java5:17.0.0)
  Duplicate class org.intellij.lang.annotations.JdkConstants$PatternFlags found in modules annotations-13.0.jar (org.jetbrains:annotations:13.0) and annotations-java5-17.0.0.jar (org.jetbrains:annotations-java5:17.0.0)
  Duplicate class org.intellij.lang.annotations.JdkConstants$TabLayoutPolicy found in modules annotations-13.0.jar (org.jetbrains:annotations:13.0) and annotations-java5-17.0.0.jar (org.jetbrains:annotations-java5:17.0.0)
  Duplicate class org.intellij.lang.annotations.JdkConstants$TabPlacement found in modules annotations-13.0.jar (org.jetbrains:annotations:13.0) and annotations-java5-17.0.0.jar (org.jetbrains:annotations-java5:17.0.0)
  Duplicate class org.intellij.lang.annotations.JdkConstants$TitledBorderJustification found in modules annotations-13.0.jar (org.jetbrains:annotations:13.0) and annotations-java5-17.0.0.jar (org.jetbrains:annotations-java5:17.0.0)
  Duplicate class org.intellij.lang.annotations.JdkConstants$TitledBorderTitlePosition found in modules annotations-13.0.jar (org.jetbrains:annotations:13.0) and annotations-java5-17.0.0.jar (org.jetbrains:annotations-java5:17.0.0)
  Duplicate class org.intellij.lang.annotations.JdkConstants$TreeSelectionMode found in modules annotations-13.0.jar (org.jetbrains:annotations:13.0) and annotations-java5-17.0.0.jar (org.jetbrains:annotations-java5:17.0.0)
  Duplicate class org.intellij.lang.annotations.Language found in modules annotations-13.0.jar (org.jetbrains:annotations:13.0) and annotations-java5-17.0.0.jar (org.jetbrains:annotations-java5:17.0.0)
  Duplicate class org.intellij.lang.annotations.MagicConstant found in modules annotations-13.0.jar (org.jetbrains:annotations:13.0) and annotations-java5-17.0.0.jar (org.jetbrains:annotations-java5:17.0.0)
  Duplicate class org.intellij.lang.annotations.Pattern found in modules annotations-13.0.jar (org.jetbrains:annotations:13.0) and annotations-java5-17.0.0.jar (org.jetbrains:annotations-java5:17.0.0)
  Duplicate class org.intellij.lang.annotations.PrintFormat found in modules annotations-13.0.jar (org.jetbrains:annotations:13.0) and annotations-java5-17.0.0.jar (org.jetbrains:annotations-java5:17.0.0)
  Duplicate class org.intellij.lang.annotations.PrintFormatPattern found in modules annotations-13.0.jar (org.jetbrains:annotations:13.0) and annotations-java5-17.0.0.jar (org.jetbrains:annotations-java5:17.0.0)
  Duplicate class org.intellij.lang.annotations.RegExp found in modules annotations-13.0.jar (org.jetbrains:annotations:13.0) and annotations-java5-17.0.0.jar (org.jetbrains:annotations-java5:17.0.0)
  Duplicate class org.intellij.lang.annotations.Subst found in modules annotations-13.0.jar (org.jetbrains:annotations:13.0) and annotations-java5-17.0.0.jar (org.jetbrains:annotations-java5:17.0.0)
  Duplicate class org.jetbrains.annotations.Contract found in modules annotations-13.0.jar (org.jetbrains:annotations:13.0) and annotations-java5-17.0.0.jar (org.jetbrains:annotations-java5:17.0.0)
  Duplicate class org.jetbrains.annotations.Nls found in modules annotations-13.0.jar (org.jetbrains:annotations:13.0) and annotations-java5-17.0.0.jar (org.jetbrains:annotations-java5:17.0.0)
  Duplicate class org.jetbrains.annotations.NonNls found in modules annotations-13.0.jar (org.jetbrains:annotations:13.0) and annotations-java5-17.0.0.jar (org.jetbrains:annotations-java5:17.0.0)
  Duplicate class org.jetbrains.annotations.NotNull found in modules annotations-13.0.jar (org.jetbrains:annotations:13.0) and annotations-java5-17.0.0.jar (org.jetbrains:annotations-java5:17.0.0)
  Duplicate class org.jetbrains.annotations.Nullable found in modules annotations-13.0.jar (org.jetbrains:annotations:13.0) and annotations-java5-17.0.0.jar (org.jetbrains:annotations-java5:17.0.0)
  Duplicate class org.jetbrains.annotations.PropertyKey found in modules annotations-13.0.jar (org.jetbrains:annotations:13.0) and annotations-java5-17.0.0.jar (org.jetbrains:annotations-java5:17.0.0)
  Duplicate class org.jetbrains.annotations.TestOnly found in modules annotations-13.0.jar (org.jetbrains:annotations:13.0) and annotations-java5-17.0.0.jar (org.jetbrains:annotations-java5:17.0.0)

**Comment by abdulsnovasys** [comment]
Still issue is exits

**Comment by tonyofrancis** [comment]
@abdulsnovasys There seems to be a mismatch of dependencies inside your project. Not an issue with Fetch per-say.
