### ISSUE TITLE
Why all the interfaces are not abstract classes

### ISSUE THREAD

**Issue by Lucaffo** [tonyofrancis/Fetch#449]
Every time i use this library, I have to create my own abstract class for each interface you use.
I do this because, i had to implements 25 methods for each listener, and obviously i don't use each of them.

Should be awesome, if we can implement methods into interfaces that we really want. 

This is short solution that i can give about this feature:

Open your interface file class, and write as above.

`
// This is the abstract class that can handle this feature
public abstract class FetchCallbacks implements FetchListener {

}

// This is your current Fetch Listener interface (!)
interface FetchListener
{
    
}`

**Comment by tonyofrancis** [comment]
@Xedoll There are abstract Listeners. ` AbstractFetchListener` and `AbstractFetchGroupListener`

**Comment by Lucaffo** [comment]
My question is why all the interfaces are public and not private. Might be awesome that only the abstract interfaces are public. (And rename the AbstractFetchListener into FetchListener)

**Comment by jobhh** [comment]
I'm not sure I understand your question. Per definition all methods in an interface are public and declared with an empty body.

AbstractFetchListener is a FetchListener. If you create a AbstractFetchListener you can choose which methods to implement, either none, some or all. What is exactly the functionality you're missing in the current implementation?
