### ISSUE TITLE
How can I customize Notification?

### ISSUE THREAD

**Issue by randauto** [tonyofrancis/Fetch#450]
I saw in your lib this code, class : DefaultFetchNotificationManager.kt

override fun getDownloadNotificationTitle(download: Download): String {
        return download.fileUri.lastPathSegment ?: Uri.parse(download.url).lastPathSegment
        ?: download.url
    }

But I don't want to show lastPathSegment, how can I change it by other value from my project?
Thanks in advance!

**Comment by tonyofrancis** [comment]
@randauto you can fully customize the notifications. See my answer [here](https://github.com/tonyofrancis/Fetch/issues/452)

**Comment by randauto** [comment]
Many thanks!
