### ISSUE TITLE
Sometime image downloading failed

### ISSUE THREAD

**Issue by razi3742** [tonyofrancis/Fetch#451]
hi first of all thank you for providing such a nice solution.

I am using your library to download parallel images. while downloading images some time i got socket  time out exception although your solution try to re download images in background after few interval. in my case i have 88 images to download but some time it fails to download 1 or 2 images and their size remain to 0 byte and download all remaining images. 

following are my implementations to download image

```
var fetchConfiguration = FetchConfiguration.Builder(this)
                .enableFileExistChecks(false)
                .enableRetryOnNetworkGain(true)
                .enableLogging(true)
                .setDownloadConcurrentLimit(10)
                .build()

        fetch = Fetch.Impl.getInstance(fetchConfiguration)
```

            fun downloadFileFromUrl(context: Context, url: String, fileName: String): Request? {
        try {
            var mediaStorageDir = File(Environment.getExternalStorageDirectory(), "directory")
            if (!mediaStorageDir.exists()) {
                if (!mediaStorageDir.mkdirs()) {
                    Log.d("MyCameraApp", "failed to create directory")
                }
            }

            var mediaFile = File(mediaStorageDir.absolutePath + File.separator + fileName)
            if (mediaFile.exists()) {
                mediaFile.delete()
            }

            var request = Request(url, mediaFile.absolutePath);
            request.priority = Priority.HIGH
            request.networkType = NetworkType.ALL
            request.addHeader("Authorization", "JWT " + AppPreferences.getString(loggedInToken, ""));
            return request

        } catch (ex: Exception) {
            ex.printStackTrace()
            return null
        }
    }

```
var list = arraylistof(Request)
for(i in items){
list.add(downloadFileFromUrl(context,"url","imagename"))
}
```

`fetch.enqueue(list);`

**Comment by tonyofrancis** [comment]
Hi @razi3742 On your request try adding `request.setAutoRetryMaxAttempts(n)`. Fetch will retry your download if it fails n number of times. Hope this helps.
