### ISSUE TITLE
Notification: Change the Title for request (download)

### ISSUE THREAD

**Issue by xeinebiu** [tonyofrancis/Fetch#452]
Hi.

Is there any possibility to change the Title displayed on notification for each download.
Or would help more, if the Request model can accept a Title property.

**Comment by tonyofrancis** [comment]
@xeinebiu Fetch uses the DefaultFetchNotificationManager to display notifications. What you can do is extend `DefaultFetchNotificationManager` and override the `updateNotification` method. `DefaultFetchNotificationManager` extends from `FetchNotificationManager` so you can provide your own full implementation.
Example:
```java
        final FetchConfiguration fetchConfiguration = new FetchConfiguration.Builder(this)
                .setDownloadConcurrentLimit(4)
                .setHttpDownloader(new OkHttpDownloader(Downloader.FileDownloaderType.PARALLEL))
                .setNamespace(FETCH_NAMESPACE)
                .setNotificationManager(new DefaultFetchNotificationManager(this) {
                    @NotNull
                    @Override
                    public Fetch getFetchInstanceForNamespace(@NotNull String namespace) {
                        return fetch;
                    }

                    @Override
                    public void updateNotification(
                            @NotNull NotificationCompat.Builder notificationBuilder, 
                            @NotNull DownloadNotification downloadNotification,
                            @NotNull Context context
                    ) {
                        super.updateNotification(notificationBuilder, downloadNotification, context);
                        //update builder title here
                        notificationBuilder.setContentTitle("new title")
                    }
                })
                .build();
        fetch = Fetch.Impl.getInstance(fetchConfiguration);

```

**Comment by xeinebiu** [comment]
> @xeinebiu Fetch uses the DefaultFetchNotificationManager to display notifications. What you can do is extend `DefaultFetchNotificationManager` and override the `updateNotification` method. `DefaultFetchNotificationManager` extends from `FetchNotificationManager` so you can provide your own full implementation.
> Example:
> 
> ```java
>         final FetchConfiguration fetchConfiguration = new FetchConfiguration.Builder(this)
>                 .setDownloadConcurrentLimit(4)
>                 .setHttpDownloader(new OkHttpDownloader(Downloader.FileDownloaderType.PARALLEL))
>                 .setNamespace(FETCH_NAMESPACE)
>                 .setNotificationManager(new DefaultFetchNotificationManager(this) {
>                     @NotNull
>                     @Override
>                     public Fetch getFetchInstanceForNamespace(@NotNull String namespace) {
>                         return fetch;
>                     }
> 
>                     @Override
>                     public void updateNotification(
>                             @NotNull NotificationCompat.Builder notificationBuilder, 
>                             @NotNull DownloadNotification downloadNotification,
>                             @NotNull Context context
>                     ) {
>                         super.updateNotification(notificationBuilder, downloadNotification, context);
>                         //update builder title here
>                         notificationBuilder.setContentTitle("new title")
>                     }
>                 })
>                 .build();
>         fetch = Fetch.Impl.getInstance(fetchConfiguration);
> ```

Hi.

I already was doing on this way but I find it hard to know the correct title for correct Download.
