### ISSUE TITLE
Dowloading stops when application is killed

### ISSUE THREAD

**Issue by mustansarsaeed** [tonyofrancis/Fetch#453]
Hi,

Thank you for the nice library. I have experienced an issue that when I have grouped some downloads and after grouping I kill the application, the downloading also gets stopped. It doesn't resume even if I relaunch the application. Can you please give me some pointer how can I achieve this functionality?

Thank you in advance.

**Comment by mustansarsaeed** [comment]
@tonyofrancis Any pointer on this? 1. Stops downloading when application is killed, 2. Downloaded files get corrupted in specific cases.

**Comment by tonyofrancis** [comment]
@mustansarsaeed You can use work manager or a foreground service to continue the downloads.
