### ISSUE TITLE
downloaded count is weired

### ISSUE THREAD

**Issue by akaisun** [tonyofrancis/Fetch#459]
![image](https://user-images.githubusercontent.com/17962656/68522125-13254080-02eb-11ea-885e-f6c12f98aa39.png)

This is my log.
I downloaded only one.
But they say they've downloaded a total of 13 of them.
I think It is holding the previously downloaded in my cache.
fetch.delete is deletes the file and fetch.remove is deletes notification.
Is it possible to reset only what is contained in the previous variable? thank you.

**Comment by nikhilmaurya10** [comment]
I have same issue onCompleted callback is a mess. I can't figure out how this is happening. If i put a counter variable and increment it in the onComplete callback the incremented value is not correct.

**Comment by akaisun** [comment]
I think I found out why there is a problem.
First, I didn't remove the listener.
second, there was left after download completed in fetch request db

and this is my fixed code

`
fetchModulesBuilder = FetchModulesBuilder.buildModulesFromPrefs(fetchConfiguration)
fetch = FetchImpl.newInstance(fetchModulesBuilder)


fetchModulesBuilder.handlerWrapper.post {
            fetchModulesBuilder.fetchDatabaseManagerWrapper.delete(download as DownloadInfo)
            fetchModulesBuilder.fetchHandler.removeListener(this@DownloadListener)
        }

`

it works for me. but i think is not good code to use. its a temporary expedient.
please fix it.

**Comment by nikhilmaurya10** [comment]
@akaisun Why would the listener notify using onCompleted() even after the download is completed. See this issue #458 
The download++ is not reliable at all I don't know what kind of concurrency issues are there.

**Comment by akaisun** [comment]
> @akaisun Why would the listener notify using onCompleted() even after the download is completed. See this issue #458
> The download++ is not reliable at all I don't know what kind of concurrency issues are there.

1.you have to remove listener after finish download.
2.have to delete rows of table in database which finish downloaded.
fetch seem to searching database before request to server. and use it.
