### ISSUE TITLE
Need a "get" method that accepts several download IDs

### ISSUE THREAD

**Issue by jacobtabak** [tonyofrancis/Fetch#46]
It appears that Fetch is lacking a method that allows you to query for a list of download IDs. Would you be opposed to adding a method that looks like this:

`public synchronized List<RequestInfo> get(long... ids)`?

**Comment by tonyofrancis** [comment]
@jacobtabak sounds good! Ill update this post when its implemented. I am hoping for a release in the new few days.

**Comment by tonyofrancis** [comment]
done. This will be in version 1.1.2 of Fetch which will be released in the next few days.
