### ISSUE TITLE
onCompleted event called twice !!!!

### ISSUE THREAD

**Issue by ralphgabrielle** [tonyofrancis/Fetch#461]
This project seems to work before, but for some reason some event callback are getting called twice (worse is 3x) on onCompleted event when downloading. I already remove listener and still persists. Guess I will switch to other downloader such a waste I've been using this for few projects and this bug is a killer.  If you guys faced this before and found a solution, I would appreciate any help. Thanks. 

`
override fun onCompleted(download: Download)  {
            fileDownload.onFileDownloaded()
            plantLog("Ralph Progress - onCompleted " + System.currentTimeMillis())
            fetch.removeListener(this)
            fetch.close()
        }
`

**Comment by nikhilmaurya10** [comment]
Do you have any Ideas about how to debug this bug, make be we can do a collab to fix this issue, cause I think this is the best library available since it's so simple to use #458

**Comment by jpvs0101** [comment]
Facing the same issue...

**Comment by tonyofrancis** [comment]
I was able to replicate this issue. A fix is coming in the next few days.

**Comment by nomizodiac** [comment]
@tonyofrancis as you have closed this issue? is it fixed? Because i am getting this issue and i am using version
androidx.tonyodev.fetch2:xfetch2:3.1.4

**Comment by ralphgabrielle** [comment]
I think its time to check similar/other libraries. This issue is already closed.

**Comment by alosoft** [comment]
Any workarounds?

**Comment by tonyofrancis** [comment]
New version of Fetch has been released. See readme for new version number.

**Comment by hypeben** [comment]
I don't know why the issue is closed because the bug still exists in the latest version. OnCompleted is being called twice, it's very frustrating.

**Comment by saeed74** [comment]
its still happening in xfetch 3.1.6

**Comment by andr3aLucch3si85** [comment]
Same error for me!!

**Comment by LunevNF** [comment]
Same error, but onStarted called twice too

**Comment by LunevNF** [comment]
Found the reason of problem: I was add fetch.resumeAll() after first complete of download. So, it runs second time this download :)

**Comment by LunevNF** [comment]
the bug still exists in the latest version

**Comment by LunevNF** [comment]
onCompleted event called twice for group listener (when 2 files downloaded in group).
