### ISSUE TITLE
How can I only resume download via Wifi?

### ISSUE THREAD

**Issue by randauto** [tonyofrancis/Fetch#462]
Method: enableRetryOnNetworkGain(true) will make resume download when I switch on, of internet. But I only want execute only in wifi and not execute in other like 3G, 4G,...
Can this library set up like that?
Thanks!

**Comment by tonyofrancis** [comment]
You can use `FetchConfiguration.setGlobalNetworkType(NetworkType.WIFI)` or `Fetch.setGlobalNetworkType(NetworkType.WIFI)` or you can set it when you create a request `request.setNetworkType(NetworkType.WIFI)`
