### ISSUE TITLE
Downloading not working in android 10.

### ISSUE THREAD

**Issue by saurabh983** [tonyofrancis/Fetch#463]
I have implemented the library in my app to download videos. It is working great till android 9 with fast speed.
But download is not even getting started in android 10.

i have initialized the fetch instance in application class. and using default notification manager provided with the library.

Please help me out.

**Comment by razar-dev** [comment]
Add in AndroidManifest.xml to section Application
android:requestLegacyExternalStorage="true"

https://developer.android.com/training/data-storage/files/external-scoped
