### ISSUE TITLE
How can i access the DatabaseManager used by fetch instance?

### ISSUE THREAD

**Issue by obirawa** [tonyofrancis/Fetch#472]
`Fetch.Impl.getDefaultInstance().getFetchConfiguration().getFetchDatabaseManager(); //returns null`

I didn't create set a database manager when i created the FetchConfiguration object, how do i get the default one in use?!!

**Comment by XiXiongMaoXiong** [comment]
This is one of if not the most shittiest repos in Github where the developer does't give 2 fucks about any of the opened issues.

**Comment by obirawa** [comment]
for now, accessing the Database manager wrapper was enough in my case so i used reflection to access it using the following code:

FetchImpl fetch = (FetchImpl) Fetch.Impl.getDefaultInstance();

            FetchDatabaseManagerWrapper fetchDatabaseManagerWrapper = null;
            try {
                Field field = FetchImpl.class.getDeclaredField("fetchDatabaseManagerWrapper");
                field.setAccessible(true);
                fetchDatabaseManagerWrapper = (FetchDatabaseManagerWrapper) field.get(fetch);
            } catch (NoSuchFieldException e) {
                e.printStackTrace();
            } catch (IllegalAccessException e) {
                e.printStackTrace();
            }

**Comment by tonyofrancis** [comment]
You cannot get a instance of the Fetch Database. What you can do is provide Fetch your own custom database manager . `FetchConfiguration.setDatabaseManager(manager)`
