### ISSUE TITLE
`FetchConst` should probably be public

### ISSUE THREAD

**Issue by jacobtabak** [tonyofrancis/Fetch#48]
When you query the status of a download, you get a `RequestInfo` object that has a `status` value which is an integer that corresponds to the status codes in `FetchConst`. However, since `FetchConst` is not public, there is no way to to perform logic on the status unless the client app hard codes those values.

**Comment by tonyofrancis** [comment]
@jacobtabak the Fetch class implements FetchConst. You you can access the different statuses and error messages like so: `Fetch.STATUS_DOWNLOADING or Fetch.ERROR_FILE_NOT_FOUND*`. FetchService also extends FetchConst.

**Comment by jacobtabak** [comment]
Hm, I don't find that very intuitive. What is the point of having those consts live anywhere other than in the place they are defined? It seems like FetchConst should be a public class and all of the members should be `public static final`.

**Comment by DevOfLife** [comment]
as tonyo said, the Fetch class implements FetchConst
and Fetch defined public, so don't worry about FetchConst public or not
anyone code different, i cannot see the reason of "FetchConst should be a public class"
