### ISSUE TITLE
How do you compile your library code?

### ISSUE THREAD

**Issue by NickPakhomov** [tonyofrancis/Fetch#481]
Tonyo, first of all, great work writing this amazing library that we've been using for so long.

Due to the circumstances, we have to copy all of the lib source code into our project and introduce few tweaks along the way.

One thing that I don't quite get, is how do you manage to compile your project with `Interface Func does not have constuctors`? The 2 ways of solving this is either create an anonymous object, or introduce `typealias FuncInterface<T> = (t: T) -> Unit`, with `.invoke` instead of `.call`.

I've tried to dig through open and closed issues, I did manage to find one mention about this: it is an issue of Android Studio's Kotlin plugin. Is that so? I've tried 1.4-M1, wouldn't work.

Sincerely,
Nick

**Comment by tonyofrancis** [comment]
@NickPakhomov I have not encountered this issue. Your project is probably on a newer version of kotlin, gradle and other libs whiles the Fetch library is still on older versions. I am currently updating the project to use newer versions.

**Comment by NickPakhomov** [comment]
I've only managed to compile your project with newest Kotlin 1.4M-1 and adding keyword `fun` to `interface Func` so I could use SAM. Super weird anyways. Didn't expect older versions of Kotlin to support compilation of the current source code.

**Comment by tonyofrancis** [comment]
When using Fetch in older versions of Kotlin pre 1.4, the callbacks are call like this:`fetch.hasActiveDownloads(true, Func { competedDownloads = it })`. The reason for this is because I wanted to support Java lambas in the library and this was the best balance for java and kotlin users.
