### ISSUE TITLE
Crash when "No space left on device".

### ISSUE THREAD

**Issue by xwh3238557** [tonyofrancis/Fetch#484]
Hi:
I got a exception,when there is no space left on device.

android.system.ErrnoException:write failed: ENOSPC (No space left on device)
--
 libcore.io.Posix.writeBytes(Native Method)
 libcore.io.Posix.write(Posix.java:273)
 libcore.io.BlockGuardOs.write(BlockGuardOs.java:319)
 libcore.io.IoBridge.write(IoBridge.java:496)
 java.io.RandomAccessFile.writeBytes(RandomAccessFile.java:478)
 java.io.RandomAccessFile.write(RandomAccessFile.java:506)
 com.tonyodev.fetch2core.StorageResolverHelper$getOutputResourceWrapper$2.void write(byte[],int,int)(StorageResolverHelper.kt:1)
 com.tonyodev.fetch2.downloader.SequentialFileDownloaderImpl.void writeToOutput(java.io.BufferedInputStream,com.tonyodev.fetch2core.OutputResourceWrapper,int)(SequentialFileDownloaderImpl.kt:12)
 com.tonyodev.fetch2.downloader.SequentialFileDownloaderImpl.void run()(SequentialFileDownloaderImpl.kt:46)
 com.tonyodev.fetch2.downloader.DownloadManagerImpl$start$$inlined$synchronized$lambda$1.void run()(DownloadManagerImpl.kt:10)
 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
 java.lang.Thread.run(Thread.java:762)

I think this exception should be catch and call the listener's onError(...), instead of sending to thread's default exception handler.

**Comment by AlexStarc** [comment]
Seems this one is already has been adressed in https://github.com/tonyofrancis/Fetch/pull/480
