### ISSUE TITLE
Progress returns back when reopen after destroying app. 

### ISSUE THREAD

**Issue by LathiyaVinal** [tonyofrancis/Fetch#487]
Follow steps to generate issue : 
1) start download 
2) when downloaded started and progress returns after queued, pause app and destroy app.
3) reopen app and again start downloading
4) progress returns back  
onProgress: 9
onProgress: 7
onProgress: 18
onProgress: 17
onProgress: 26
onProgress: 21
onProgress: 35
onProgress: 24
onProgress: 44
onProgress: 28.

**Comment by tonyofrancis** [comment]
When the app was forced closed, Fetch may have not had a chance to save the progress and data after 24%. When the app was relaunched it must have restarted at 24 which was the last saved progress and then downloaded a few bytes reporting 28% when the app reopened.
