### ISSUE TITLE
Video Download Error

### ISSUE THREAD

**Issue by Adil-Sattar** [tonyofrancis/Fetch#489]
https://likee.com/@448061210/video/6824273807885114484

Not downloading video from this url

**Comment by razar-dev** [comment]
This is not a link to video, this is HTML page.
To get a video, you need to parse the page and find the link to the video.
Valid url: http://video.like.video//eu_live//5uN//11xuP7_4.mp4?crc=2377112116&type=5

**Comment by mellowfunk** [comment]
a question??

anyone know how can I download this video https://www.kadgroove.net/watch.php?vid=cd4a48874

regards

**Comment by Adil-Sattar** [comment]
Thanks razer-dev
