### ISSUE TITLE
Should -1 should be defined in FetchConst?

### ISSUE THREAD

**Issue by jacobtabak** [tonyofrancis/Fetch#49]
It seems that -1 is a magic const that means there is no error. If this is the case, should it be defined in FetchConst?

**Comment by tonyofrancis** [comment]
@jacobtabak I see what you are saying. Fetch uses -1 to indicated that there is no error, -1 could also mean that a request was not enqueued. Fetch contains a constant `DEFAULT_EMPTY_VALUE = -1` but its name/use is not clear. Ill have to define proper constants. Thanks for the suggestion.

**Comment by tonyofrancis** [comment]
New Constants have been added to FetchConst

```java
    /** indicates that no errors occurred*/
    int NO_ERROR = -1;

    /** The ID value that is returned when a request was not enqueued*/
    int ENQUEUE_ERROR_ID = -1;
```
