### ISSUE TITLE
Download Progress is -1

### ISSUE THREAD

**Issue by Teityan** [tonyofrancis/Fetch#490]
When downloading, the progress and time will be -1.
Some files are displayed correctly.
Why is that?When downloading, the progress and time will be -1.
Some files are displayed correctly.
Why is that?

```
@Override
        public void onProgress(@NotNull Download download, long etaInMilliSeconds, long downloadedBytesPerSecond) {
            int progress = download.getProgress();
                progressBar.setProgress(progress);
}
```

**Comment by mahdiazarm** [comment]
Does the URL you trying to download from accept ranges?
I faced the same issue couple of days ago, The URL that I'm trying to download from wasn't a direct link and didn't accept any ranges.

**Comment by Teityan** [comment]
Thank you.
The reason was that the Content-Length was not set.
Disabling Gzip compression in Apache cured it.
