### ISSUE TITLE
File corrupted if change network

### ISSUE THREAD

**Issue by gmanrainy** [tonyofrancis/Fetch#492]
Hi.
I use 3.1.4 version
FetchConfiguration: 
`FetchConfiguration fetchConfiguration = new FetchConfiguration.Builder(this)
.setDownloadConcurrentLimit(2)
.enableRetryOnNetworkGain(true)
.setAutoRetryMaxAttempts(10)
.createDownloadFileOnEnqueue(true)
.enableHashCheck(true)
.setHttpDownloader(new OkHttpDownloader(NetworkProvider.getClient(), Downloader.FileDownloaderType.PARALLEL))
.build();`
So, if i start download file and change network to another type (from WiFi to Mobile or back) then file will be downloaded corrupted. This does not happen in 100% of cases, but in most.
If need i can provide some download links

Update:
I found where is error, in ParallelFileDownloaderImpl->downloadSliceFiles->read = downloadResponse.byteStream?.read(buffer, 0, bufferSize), I was able to fix the beaten file only by restarting downloading part file, delete and creating a new part file, but this is not a good solution.

**Comment by tonyofrancis** [comment]
@gmanrainy Thanks for reporting this issue. A fix has been made. I will be releasing a new version of Fetch this weekend.

**Comment by tonyofrancis** [comment]
New version of Fetch has been released. See readme for new version number.
