### ISSUE TITLE
Send local broadcasts instead of System wide

### ISSUE THREAD

**Issue by amsurana** [tonyofrancis/Fetch#494]
I noticed that the library sends a system wide broadcast: com.tonyodev.fetch2.action.QUEUE_BACKOFF_RESET

I wanted to know what made you send system-wide broadcasts? It is not possible to use LocalBroadcastManager for this purpose ?

**Comment by tonyofrancis** [comment]
@amsurana Great catch! I have added `intent.setPackageName(context.packageName)` to limit the scope. The reason why we don't use LocalBroadcastManager is because we would have to add the androidx support library as a dependency to only use `LocalBroadcastManager`.
