### ISSUE TITLE
Get background download status.

### ISSUE THREAD

**Issue by Teityan** [tonyofrancis/Fetch#495]
I get the background download status by storing the ID in sharedpreferences so that it can be retrieved when the Activity is reopened.
However, getDownload only calls it once, and you don't know what happens afterwards.
Is there any good way to reconfigure the Listner?

**Comment by razar-dev** [comment]
To get information about the status of downloads you can use
`fetch.addListener(fetchListener)`
In order to stop
`fetch.removeListener(fetchListener)`

You can also configure the frequency of receiving messages
`setProgressReportingInterval`
