### ISSUE TITLE
SD Card support

### ISSUE THREAD

**Issue by razar-dev** [tonyofrancis/Fetch#496]
Environment: Android 10, Fetch Sample APP (+code mod)

To select a directory I build and send an ACTION_OPEN_DOCUMENT_TREE intent like in the following code:
val intent = Intent(Intent.ACTION_OPEN_DOCUMENT_TREE)
startActivityForResult(intent, 999)

And give URI path:
content://com.android.externalstorage.documents/tree/0403-0201%3A

Path to file: 
content://com.android.externalstorage.documents/tree/0403-0201%3Atest100Mb.db
```
       fetch.attachFetchObserversForDownload(request.getId(), this)
                .enqueue(request, result -> request = result, result -> Timber.d("SingleDownloadActivity Error: %1$s", result.toString()));
```

Fetch log
`2020-05-20 18:45:00.654 5542-5542/com.tonyodev.fetchapp E/SingleDownloadActivity: content://com.android.externalstorage.documents/tree/0403-0201%3Atest100Mb.db
2020-05-20 18:45:00.698 5542-5542/com.tonyodev.fetchapp D/SingleDownloadActivity: SingleDownloadActivity Error: UNKNOWN`

Is it possible to upload SD card files?

**Comment by tonyofrancis** [comment]
@razar-dev It is possible. You will have to provide the FetchConfiguration a custom instance of StorageResolver. See the `DefaultStorageResolver` class to get started.
