### ISSUE TITLE
Any plan to support observables instead of callbacks?

### ISSUE THREAD

**Issue by wax911** [tonyofrancis/Fetch#497]
Hi @tonyofrancis, thanks for the amazing library really appreciate the work that you've put in! I was just wondering that since the androidx variant of the project uses kotlin it would be nice if you ship minor artifacts with either lifecycle `livedata` or coroutines `flow` to replace/complement the follwoing:
- `com.tonyodev.fetch2core.Func<R>`
- `com.tonyodev.fetch2core.DownloadBlock.AbstractFetchListener`

The idea was to take something like: `fun addListener(listener: FetchListener): Fetch` and turn it into something like `fun addListener(): Flow<DownloadItem>`, where I `DownloadItem` could be a sealed class that other **download** classes extend from for each event class type. I don't know what you've got planned for the future, so let me know what you think.

Right now I am currently doing the following:
```kotlin
internal sealed class Downloadable(
    val download: Download
)

internal class DownloadCompleted(
    download: Download
) : Downloadable(download)

internal class DownloadAdded(
    download: Download
) : Downloadable(download)

internal class DownloadResumed(
    download: Download
) : Downloadable(download)

internal class DownloadPaused(
    download: Download
) : Downloadable(download)

internal class DownloadCanceled(
    download: Download
) : Downloadable(download)

internal class DownloadRemoved(
    download: Download
) : Downloadable(download)

internal class DownloadDeleted(
    download: Download
) : Downloadable(download)

internal class DownloadQueued(
    download: Download,
    val waitingOnNetwork: Boolean
) : Downloadable(download)

internal class DownloadError(
    download: Download,
    val error: Error,
    val throwable: Throwable?
) : Downloadable(download)

internal class DownloadProgress(
    download: Download,
    val etaInMilliSeconds: Long,
    val downloadedBytesPerSecond: Long
) : Downloadable(download)
```

```kotlin
internal class DownloadSourceImpl(
    private val fetch: Fetch,
    supportDispatchers: SupportDispatchers
) : DownloadSource(supportDispatchers) {

    @ExperimentalCoroutinesApi
    override val downloadableListenerFlow =
        callbackFlow<Downloadable> {
            val fetchListener = object : AbstractFetchListener() {
                override fun onAdded(download: Download) {
                    super.onAdded(download)
                    offer(DownloadAdded(download))
                }

                override fun onCancelled(download: Download) {
                    super.onCancelled(download)
                    offer(DownloadCanceled(download))
                }

                override fun onCompleted(download: Download) {
                    super.onCompleted(download)
                    offer(DownloadCompleted(download))
                }

                override fun onDeleted(download: Download) {
                    super.onDeleted(download)
                    offer(DownloadDeleted(download))
                }

                override fun onError(download: Download, error: Error, throwable: Throwable?) {
                    super.onError(download, error, throwable)
                    offer(DownloadError(download, error, throwable))
                }

                override fun onPaused(download: Download) {
                    super.onPaused(download)
                    offer(DownloadPaused(download))
                }

                override fun onProgress(download: Download, etaInMilliSeconds: Long, downloadedBytesPerSecond: Long) {
                    super.onProgress(download, etaInMilliSeconds, downloadedBytesPerSecond)
                    offer(DownloadProgress(download, etaInMilliSeconds, downloadedBytesPerSecond))
                }

                override fun onQueued(download: Download, waitingOnNetwork: Boolean) {
                    super.onQueued(download, waitingOnNetwork)
                    offer(DownloadQueued(download, waitingOnNetwork))
                }

                override fun onRemoved(download: Download) {
                    super.onRemoved(download)
                    offer(DownloadRemoved(download))
                }

                override fun onResumed(download: Download) {
                    super.onResumed(download)
                    offer(DownloadResumed(download))
                }
            }
            fetch.addListener(fetchListener)
            awaitClose {
                fetch.removeListener(fetchListener)
            }
        }
}
```

**Comment by tonyofrancis** [comment]
@wax911 I plan on bringing live data and flow to fetch in version 4. Please stay tune!

**Comment by Sternbach-Software** [comment]
@tonyofrancis Any timeline on when we can expect version 4?? Anxiously waiting!

**Comment by Sternbach-Software** [comment]
I am making a fork ([here](https://github.com/shmueldabomb441/Fetch)) that will add `fun getAllDownloads(): kotlin.Flow<List<Download>>` to the dao, because that is all _i_ need. I will post to this thread when I have a working version.

**Comment by Sternbach-Software** [comment]
I finished. The copy-pastable files are [here](https://github.com/shmueldabomb441/Fetch/tree/v3.0/flowablefetch) (18 classes in total, all in one package). 

Just copy-paste them into your project, and instead of calling `Fetch.getInstance(fetchConfig)` call `FlowableFetch.getInstance(flowableConfig, { fetchConfig })`, where flowableConfig is an instance of `FlowableFetchConfiguration` instead of `FetchConfiguration`, (just replace `FetchConfiguration.Builder` with `FlowableFetchConfiguration.Builder`). Effectively, my changes have not done anything except added the `getFlow()` function.

There are a lot of helper classes/interfaces+implementations, so I subclassed the classes that permitted just to add one helper function for that dao method, and copy-pasted the classes that couldn't be subclassed, just so that I could change the return types of the necessary helper functions, etc. 

The only change that wasn't able to be done smoothly was mocking `FetchConfiguration` because it is not `open`, so the fetch configuration instance used for the active downloads observer is different than the one used everywhere else. I have not tested what happens when you need to take advantage of that observer, because that is not within the scope of my use cases.

**Comment by wax911** [comment]
@shmueldabomb441 Do you have a PR/branch for your changes on your fork would love to review the changes (saw the folder)
