### ISSUE TITLE
Allowed Networks

### ISSUE THREAD

**Issue by visuall** [tonyofrancis/Fetch#499]
Hello,

It is not actually a bug but probably an extension. Currently the lib supports WiFi and All for download types. This kind of fails for devices that are connected to the network via Ethernet and has no WiFi. In such case the only way to make downloads work is to allow all downloads which leads to allowing Cellular downloads too. It should be possible to allow Ethernet only without Cellular. 

Best Regards,
Nick

**Comment by tonyofrancis** [comment]
@visuall Thanks for using Fetch!
How about I do this for you.
```java
request = new Request(url, filePath);
request.setNetworkType(NetworkType.UNMETERED);
```
In the next version of Fetch due to be released this week, you will be able to specify `NetworkType.UNMETERED`

Best,
-Tonyo

**Comment by tonyofrancis** [comment]
@visuall If you would like to test. I pushed a preview build. You can test and let me know if it works well for you
```
implementation 'com.tonyodev.fetch2:fetch2:3.0.11-preview2'
//or android x
implementation 'androidx.tonyodev.fetch2:xfetch2:3.1.5-preview2'
```

**Comment by tonyofrancis** [comment]
New version of Fetch has been released. See readme for new version number.
