### ISSUE TITLE
Enhancement: Display the File size (of the File being downloaded)

### ISSUE THREAD

**Issue by CeJienAJPC** [tonyofrancis/Fetch#50]
Thanks

**Comment by rupinderjeet** [comment]
for me, in `onUpdate()`, `fileSize` is always -1. and, hence, progress is always zero. When a download completes Fetch shows its `fileSize` and progress(100) both.

**Comment by CeJienAJPC** [comment]
Sorry. Didn't have a close look at what FETCH offers. **long downloadedBytes, long fileSize**

My bad. Thanks.
