### ISSUE TITLE
Questions regarding the lib

### ISSUE THREAD

**Issue by ayodelekehinde** [tonyofrancis/Fetch#500]
Hi, awesome lib. I have questions though.
1. Can we use fetch in production app?
2. Connectivity change: does fetch handle network change? With a pause mechanism to resume after full connectivity restored ?
3. To ensure download keep running we wanna use fetch with workmanager, can we?

**Comment by tonyofrancis** [comment]
1. Yes!
2. Fetch handles connectivity changes! You can also specify what network types a download can be performed on.
3. Create a worker and call `fetch.awaitFinishOrTimeout(allowTimeInMilliseconds: Long)` to keep the worker alive whiles fetch performs the downloads. Workers have a maximum of 10 minutes. So the most you can set is 10 minutes.

Try out the sample project in the repository!

**Comment by tonyofrancis** [comment]
New version of Fetch has been released. See readme for new version number.

**Comment by ayodelekehinde** [comment]
Aiit, thanks I'm implementing it as I type
