### ISSUE TITLE
Getting CONNECTION_TIMED_OUT only when network is changed from data to WIFI

### ISSUE THREAD

**Issue by Nandish96** [tonyofrancis/Fetch#501]
Hi, 
I wanted to handle network changes for download so I set enableRetryOnNetworkGain(true) in fetchConfiguration.
It works really well when network changed from wifi to mobile data, or when turning on and off the wifi /mobile Data.
But when i change the network from mobile data to wifi without switching off the mobile data I'm receiving a download fail with CONNECTION_TIMED_OUT error. 
Is there a way I can handle it?

**Comment by tonyofrancis** [comment]
@Nandish96 Thanks for using Fetch.

The NetworkManager may still be reporting that the network is still available and connected, even though it is no longer available. Hence the reason the download fails with `CONNECTION_TIMED_OUT`. There is nothing the library can do to handle this issue.

What you can do is to attempt a retry. You can set how many times a download should be retried before Fetch gives up.
```java
        request = new Request(url, filePath);
        request.setAutoRetryMaxAttempts(5); // retry 5 times before giving up
```
