### ISSUE TITLE
Disable notification sound

### ISSUE THREAD

**Issue by kayesn786** [tonyofrancis/Fetch#504]
@tonyofrancis in some devices(Android 10) am getting notification sound.

FetchConfiguration fetchConfiguration = new FetchConfiguration.Builder(context).setDownloadConcurrentLimit(3)
                .setNotificationManager(new DefaultFetchNotificationManager(context) {
                    @NotNull
                    @Override
                    public Fetch getFetchInstanceForNamespace(@NotNull String namespace) {
                        return fetch;
                    }

                }).enableRetryOnNetworkGain(true).build();

any changes i need to do to disable notification sound?

Thanks

**Comment by cowboybkit** [comment]
I get notification sound each update progress percent, it is crazy

**Comment by tonyofrancis** [comment]
Fix is coming this week.

**Comment by tonyofrancis** [comment]
New version of Fetch has been released. See readme for new version number.
