### ISSUE TITLE
IllegalArgumentException thrown by ContentResolver

### ISSUE THREAD

**Issue by tobiasdroste** [tonyofrancis/Fetch#507]
`context.contentResolver.delete(uri, null, null)` will throw an IllegalArgumentException when the url is not starting with "content". This has the effect that enqueuing with enqueue action "REPLACE_EXISTING" is not working when no existing file is found.

This
https://github.com/tonyofrancis/Fetch/blob/61e5b53f1598380e60fdfe1f12133310355576ea/fetch2core/src/main/java/com/tonyodev/fetch2core/StorageResolverHelper.kt#L137

calls the content resolver where the IllegalArgumentException is thrown here: 

https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/content/ContentResolver.java#1945

because acquireProvider returns null.

Why is `context.contentResolver.delete(uri, null, null) > 0 ` called anyway? The scheme will never be "content" here as we are only in this block when scheme is file:
https://github.com/tonyofrancis/Fetch/blob/61e5b53f1598380e60fdfe1f12133310355576ea/fetch2core/src/main/java/com/tonyodev/fetch2core/StorageResolverHelper.kt#L135

Thanks for looking into it!

**Comment by tobiasdroste** [comment]
My suggestion to solve this would be to replace `else context.contentResolver.delete(uri, null, null) > 0` by `else false`

**Comment by tonyofrancis** [comment]
@tobiasdroste Great catch. Will be fixed in the next version of fetch that will be released this week.

**Comment by tonyofrancis** [comment]
New version of Fetch has been released. See readme for new version number.
