### ISSUE TITLE
Resuming or restarting download issue after app kill

### ISSUE THREAD

**Issue by KhurramShahzad094** [tonyofrancis/Fetch#510]
@tonyofrancis I am facing an issue in downloading a video. It downloads successfully, if i dont kill the app. but if the download is in progress and I kill the app and again go into app and click to download that particular video then it doesnot resume or restart the download and only calls these two callbacks. 1) onAdded. 2)onQueued
After that nothing happens.

I tried to find out the issue but not able to. Can you please guide me what could be the issue or what could be the fix?

* I am using this version 
    implementation "androidx.tonyodev.fetch2:xfetch2:3.1.4"

**Comment by tonyofrancis** [comment]
@KhurramShahzad094 Fetch uses `EnqueueAction` to handle different situations when enqueuing a download. Have a look at the `EnqueueAction` enum class.
```java
request = new Request(url, filePath);
request.setEnqueueAction(EnqueueAction.REPLACE_EXISTING); // replaces an existing download request 
```
Note the default enqueue action is `EnqueueAction.UPDATE_ACCORDINGLY` which does the following
```
    /** If Fetch is already managing an existing request with the same file path do one the following:
     * 1: If existing download is completed, Fetch will call onComplete method on attached Fetch Listeners.
     * 2: If existing download is not completed, resume download normally.
     * 3: If not downloaded, download will proceed normally.
     * Note: If download is existing, Fetch will update the old request/download with the new settings on
     * from the request object.
     * */
```

If the enqueue action is not the issue, it could be that an error occurred for the download. Query the download first and log its status and error fields. Let me know if this helps.
