### ISSUE TITLE
A resource failed to call close

### ISSUE THREAD

**Issue by Braxeo** [tonyofrancis/Fetch#512]
When closing the app while "Don't keep activities" is turned on, i receive several "W/System: A resource failed to call close." warnings

As well as once i've gotten a Download to Status.COMPLETED then cleared the cache and go back into the app, i'll also receive this same error

(I've used StrictMode to get more detailed information on the issue)
[Report.txt](https://github.com/tonyofrancis/Fetch/files/5094102/Report.txt)

Changes to Manifest:
    android:usesCleartextTraffic="true"

Dependencies used:
    implementation "androidx.tonyodev.fetch2:xfetch2:3.1.4"
    implementation "androidx.tonyodev.fetch2okhttp:xfetch2okhttp:3.1.4"
    implementation "androidx.tonyodev.fetch2rx:xfetch2rx:3.1.4"
    implementation 'io.reactivex.rxjava2:rxkotlin:2.4.0'
    implementation 'io.reactivex.rxjava2:rxandroid:2.1.1'

MainActivity for replicating(Kt file wrapped in zip file):
    [MainActivity.zip](https://github.com/tonyofrancis/Fetch/files/5094109/MainActivity.zip)

Remember to have developer mode enabled and Don't keep activities = true

My throughts:
    I believe it might be a result of the behavior inside DefaultStorageResolve.fileExists(file: String): Boolean
   Inside we check if file is empty, if not we then call getOutputResourceWrapper() and immediately true, this call will throw an exception if the file is missing, resulting in the return of false

I believe the solution to this issue would be to change it from 
    `getOutputResourceWrapper(file, context.contentResolver) 
    true`
to
    `getOutputResourceWrapper(file, context.contentResolver).close() 
    true`

This would need to be implemented throughout the codebase to make sure all the issues are resolved, as i've only come by this one

I'm unsure as to if this is a bug or if i'm forgetting something in the implementation, please advise if so

**Comment by tonyofrancis** [comment]
@Braxeo I will have to take a closer look into this issue. Will report back.

**Comment by tobiasdroste** [comment]
I'm getting a lot of those messages `W/System: A resource failed to call close. ` too. But not only when closing the app. Also when doing many downloads.

**Comment by tonyofrancis** [comment]
Found the bug. working on a fix.

**Comment by tonyofrancis** [comment]
@Braxeo  A new version of Fetch 3.0.12 & AndroidX version 3.1.6 has been released

**Comment by ssivaram3103** [comment]
How to find the bug

**Comment by hkoladiya1127** [comment]
W/System  ( 3699): A resource failed to call close.
