### ISSUE TITLE
Low download speed

### ISSUE THREAD

**Issue by bensadiku** [tonyofrancis/Fetch#515]
Is there a configuration to improve the speed of the download.

I'm downloading large files 1gb+, on a 200+mbps network and it's taking few hrs. Was wondering if there is a configuration i missed to improve this. I'm using `androidx.tonyodev.fetch2:xfetch2:3.1.5`

Something that might be useful is that i'm noticing the `onDownloadBlockUpdated` show up on logs often. Not sure how relevant that is.

Note that the server (where i download the data) isn't at fault here either because it's significantly faster with wget or just through the browser.

The setup is same as the Readme, basically this:

```Java
public class TestActivity extends AppCompatActivity {

    private Fetch fetch;

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

 FetchConfiguration fetchConfiguration = new FetchConfiguration.Builder(this)
                .setDownloadConcurrentLimit(3)
                .build();

        fetch = Fetch.Impl.getInstance(fetchConfiguration);

        String url = "http:www.example.com/test.txt";
        String file = "/downloads/test.txt";
        
        final Request request = new Request(url, file);
        request.setPriority(Priority.HIGH);
        request.setNetworkType(NetworkType.ALL);
        request.addHeader("clientKey", "SD78DF93_3947&MVNGHE1WONG");
        
        fetch.enqueue(request, updatedRequest -> {
            //Request was successfully enqueued for download.
        }, error -> {
            //An error occurred enqueuing the request.
        });

    }
}
```

Any help is appreciated

**Comment by tonyofrancis** [comment]
Hello @bensadiku. `.setDownloadConcurrentLimit(3)` allows fetch to download more than one file at a time. If you need a single file to download faster you must provide fetch with a parallel downloader.

```java
      final FetchConfiguration fetchConfiguration = new FetchConfiguration.Builder(this)
                .enableRetryOnNetworkGain(true)
                .setDownloadConcurrentLimit(3)
                .setHttpDownloader(new HttpUrlConnectionDownloader(Downloader.FileDownloaderType.PARALLEL))
                // OR
                //.setHttpDownloader(getOkHttpDownloader())
                .build();
```

Check out the sample app in the repo for more examples.
