### ISSUE TITLE
Request with POST Method

### ISSUE THREAD

**Issue by viveking** [tonyofrancis/Fetch#516]
Hi found this library helpful in many ways.
But was searching around for a while, regarding some configurations to download a file.
We have to consume a POST method with some request Body.

Help Appreciated. 
Good Work @tonyofrancis

**Comment by tonyofrancis** [comment]
@viveking Thanks for using Fetch. Fetch only uses the Get and Head method out of the box to download files. If you need to make a post request before downloading a request, you may need to create a custom Downloader. Have a look at the sample app in the repo and checkup the Java docs.

**Comment by AbreuY** [comment]
@viveking You can manage your response with another library like volley and then pass the download link obtained from response to your download service or any other method you have.
