### ISSUE TITLE
Error REQUEST_NOT_SUCCESSFUL when Download Failed from getintopc.com

### ISSUE THREAD

**Issue by abhishekhugetech** [tonyofrancis/Fetch#517]
**URL Downloading**-> http://51.83.136.12/Getintopc.com/BluffTitler_Ultimate_15.0.0.1_Multilingual.rar?md5=_jQwKLaEW30Wk-ArOgA6sg&expires=1600940204

**throwable** -> **String** -> com.tonyodev.fetch2.exception.FetchException: request_not_successful

**throwable** -> **StackTrace** ->
com.tonyodev.fetch2.downloader.ParallelFileDownloaderImpl.run(ParallelFileDownloaderImpl.kt:160)
com.tonyodev.fetch2.downloader.DownloadManagerImpl$start$$inlined$synchronized$lambda$1.run(DownloadManagerImpl.kt:103)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
java.lang.Thread.run(Thread.java:919)

**httpResponse** -> 404 Not Found, Nginx

on the other hand, downloading from the same URL using chrome browser works?

**Comment by tonyofrancis** [comment]
@abhishekhugetech Have you tried the download on a different device or emulator?. Does the download work in a browser on the device. I noticed the the url uses the ip address instead if host name eg: google.com. What if you tried the host name instead does it work??

**Comment by nikzdevz** [comment]
I got the solution for this issue. You'll have to add header Referrer and value will be getintopc
