### ISSUE TITLE
setDownloadConcurrentLimit(10) not working 

### ISSUE THREAD

**Issue by Tabassum789** [tonyofrancis/Fetch#518]
i have changed the .setDownloadConcurrentLimit(1) to .setDownloadConcurrentLimit(10) but there is no difference in downloading 
Is there any way to download files parallel ????

**Comment by tonyofrancis** [comment]
@Tabassum789 `setDownloadConcurrentLimit(number)` allows you to download files in parallel. Check out the sample app in the repo to see how its done.
