### ISSUE TITLE
Scalability issues with a large amount of downloads

### ISSUE THREAD

**Issue by jacobtabak** [tonyofrancis/Fetch#52]
There are several issues I've encountered while trying to see if this library would scale for a large amount of downloads. I've tried enqueueing 500+ downloads at once and there are a few major issues. Doing this takes several seconds and causes noticeable lag in the UI.

1. Even in a transaction, executing multiple queries is much more expensive than executing a single query. When inserting multiple rows, for example, it is much more efficient to do something like `INSERT INTO TABLE VALUES (A, B, C), (D, E, F)` than performing two insert statements in a transaction.
2. `containsFilePath` is executed for each inserted row and it executes a query of its own. If the file path column was set to be `UNIQUE` you could catch `SQLiteConstraintException` and handle duplicate inserts much more efficiently.
3. Cursors aren't closed correctly in some cases. Whenever you have `cursor.close()` in a `try` block, the cursor isnt closed if an exception happens. `cursor.close()` should always be in a `finally` block.

I've made a bunch of changes locally to remedy this situation but at this point the codebase has changed so much it would be difficult to port them back. I'm willing to do it, however, if you'd like help with these things.

**Comment by tonyofrancis** [comment]
@jacobtabak I have some free time this weekend and will defiantly take a look into some of your concerns and keep you updated

**Comment by tonyofrancis** [comment]
@jacobtabak I have been working on a completely new rewritten version of Fetch which will solve many of the shortcomings of the old version. I will have something testable before the week end.

**Comment by jacobtabak** [comment]
Great, looking forward to it

**Comment by tonyofrancis** [comment]
Thanks for the suggestions. I made the fixes in fetch version 1 and will be pushing to version 1.1.3 today
