### ISSUE TITLE
enableRetryOnNetworkGain(false) not working

### ISSUE THREAD

**Issue by tosam144** [tonyofrancis/Fetch#520]
I am using

        FetchConfiguration fetchConfiguration = new FetchConfiguration.Builder(mContext)
                .setNamespace("docs")
                .enableRetryOnNetworkGain(false)
                .setDownloadConcurrentLimit(3)
                .build();

and expected that `onError` is thrown once Internet connection is lost. I want `onError` to be thrown once Internet is lost during a download. It is quite strange that sometimes an error is thrown, sometimes not. When no error is thrown, the download resumes once Internet is back (which is not desired in my use case). I am using the androidx version of fetch. Any ideas?

**Comment by tonyofrancis** [comment]
@tosam144 . What is the testing procedure?. Airplane mode. Switching the wifi on or off??. Does it work as expected on a different device or emulator?

Also, the http client fetch uses to download has a minimum timeout of about 15 seconds before failing.

**Comment by tosam144** [comment]
While downloading, turn off Wifi (or turn on Airplaine mode, both brings up the issue). My setup is: I have 2 tabs in my app and in each of the 2 fragments, the user can download something. Each fragment uses a new fetch instance with its own namespace. In both fragments, the fetch config is the same (the one I posted already), using `enableRetryOnNetworkGain(false)`. Now the interesting thing is, it always works as expected in Fragment 2 (in Tab 2) but it does not work in Fragment 1 (Tab 1), even though the Fetch config is identical (see above). In Fragment 1, onError is also not thrown after 15 seconds (it's never thrown). In Fragment 2, however, onErorr is thrown immediately (no need to wait 15 sec.). I am testing on an Emulator and Android API 29.

**Comment by tonyofrancis** [comment]
@tosam144 . If it works in one fragment it should work in the other fragment. Can you share a sample app? My email is located in my profile

**Comment by serhiy-mazur** [comment]
I have the same behavior. Is there any update?

**Comment by XiXiongMaoXiong** [comment]
> @tosam144 . What is the testing procedure?. Airplane mode. Switching the wifi on or off??. Does it work as expected on a different device or emulator?
> 
> Also, the http client fetch uses to download has a minimum timeout of about 15 seconds before failing.

Answer me!

**Comment by XiXiongMaoXiong** [comment]
> @tosam144 . If it works in one fragment it should work in the other fragment. Can you share a sample app? My email is located in my profile

Answer my issue!
