### ISSUE TITLE
okhttp 4.* min sdk 21 (android 5)

### ISSUE THREAD

**Issue by badrazizi** [tonyofrancis/Fetch#521]
you can bump library_min_version to 21 or set okhttp to version 3.12.12 which is the last version that support sdk older than 21

**Comment by badrazizi** [comment]
@tonyofrancis your last commit almost 2 month ago, since a lot of developers relay on this in their apps and it's a lot of work to write our own or move to another library.

if you can not maintain this project anymore you can transform the repo to any of the contributors or any developer willing to take the work.

**Comment by tonyofrancis** [comment]
@badrazizi Thanks for reporting this issue. I will be setting the okhttp version to 3.12.12 to support older version.

**Comment by tonyofrancis** [comment]
@badrazizi  A new version of Fetch 3.0.12 & AndroidX version 3.1.6 has been released
