### ISSUE TITLE
issue with pause / resume

### ISSUE THREAD

**Issue by alighasemia81** [tonyofrancis/Fetch#522]
hi
thank you for this useful library 
in new version 3.1.5 lots of bugs have been fixed.thanks a lot
but a major bug have been created!
if we pause a file that is downloading and then resume it download will stop and get error!
This causes the system to be completely unused!
please follow up this problem.thanks a lot

**Comment by alighasemia81** [comment]
i got this error 

`<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
    <html><head>
    <title>416 Requested Range Not Satisfiable</title>
    </head><body>
    <h1>Requested Range Not Satisfiable</h1>
    <p>None of the range-specifier values in the Range
    request-header field overlap the current extent
    of the selected resource.</p>
    </body></html>`

**Comment by AbreuY** [comment]
> i got this error
> 
> `<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> <html><head> <title>416 Requested Range Not Satisfiable</title> </head><body> <h1>Requested Range Not Satisfiable</h1> <p>None of the range-specifier values in the Range request-header field overlap the current extent of the selected resource.</p> </body></html>`

Hi @alighasemia81 This seems more like a problem with the server than with the fetch library. Please check this link. [416 Requested Range Not Satisfiable](https://stackoverflow.com/questions/5891431/416-requested-range-not-satisfiable)

**Comment by tonyofrancis** [comment]
@alighasemia81 Are you experiencing this issue on a different server/url?

**Comment by alighasemia81** [comment]
yes.i had this experiencing with many servers

**Comment by alighasemia81** [comment]
> 
> 
> @alighasemia81 Are you experiencing this issue on a different server/url?

yes.i had this experiencing with many servers

**Comment by tonyofrancis** [comment]
@alighasemia81 can you share a url so I can test?

**Comment by alighasemia81** [comment]
> 
> 
> @alighasemia81 can you share a url so I can test?

sure

https://cdn.wave-music.ir/new_data/mp3s/homayoun_shajarian/homayoun_shajarian_koli_remix.mp3

**Comment by tonyofrancis** [comment]
Thanks. Looking into it.

**Comment by tonyofrancis** [comment]
@alighasemia81  A new version of Fetch 3.0.12 & AndroidX version 3.1.6 has been released. Please let me know if it fixes your issue
