### ISSUE TITLE
Concurrent Limit Not Working

### ISSUE THREAD

**Issue by joelphilippage** [tonyofrancis/Fetch#523]
I only want to allow downloading of 1 file at a time in my app. I believe this is supposed to be the default fetch configuration, but their appears to be no limit for me even if I set it to 1. 

Here is my method for initiating fetch:
```
private fun initFetch() {
        if(!::fetch.isInitialized) {
            val fetchConfiguration = FetchConfiguration.Builder(this)
                    .setDownloadConcurrentLimit(1)
                    .enableLogging(true)
                    .enableRetryOnNetworkGain(true)
                    .setGlobalNetworkType(NetworkType.ALL)
                    .build()

            fetch = Fetch.getInstance(fetchConfiguration)
            fetch.addListener(this)
        }
    }
```
I am using the fetch.enque method to start a download. I want the first download to start immediately and all the others to be added to a queue where they will be downloaded one at a time after that one completes. Is there some other way this should work? I am only ever using that one instance of fetch in my app as I did a whole project search to make sure I wasn't using a different configuration somewhere else.

[Update]
Doing some seaching, I see the same issue has been closed twice, but don't see a solution:
https://github.com/tonyofrancis/Fetch/issues/443
https://github.com/tonyofrancis/Fetch/issues/196

I am using androidx.tonyodev.fetch2:xfetch2:3.1.5
I also tried to make fetch in the companion object so it will be static to make sure there could only be one instance but am still seeing the issue.

[Update 2]
Got it working, but only with the default instance.
I set the configuration in the Application onCreate method this way:
```
val fetchConfiguration = FetchConfiguration.Builder(this)
                .enableRetryOnNetworkGain(true)
                .setDownloadConcurrentLimit(1)
                .build()
        Fetch.Impl.setDefaultInstanceConfiguration(fetchConfiguration)
```

Then get an instance this way:

`fetch = Fetch.Impl.getDefaultInstance()`

I wouldn't call this fixed, but it is working this is a workaround.

**Comment by joelphilippage** [comment]
Doing some seaching, I see the same issue has been closed twice, but don't see a solution:
https://github.com/tonyofrancis/Fetch/issues/443
https://github.com/tonyofrancis/Fetch/issues/196

I am using androidx.tonyodev.fetch2:xfetch2:3.1.5
I also tried to make fetch in the companion object so it will be static to make sure there could only be one instance but am still seeing the issue.

**Comment by tonyofrancis** [comment]
@joelphilippage I have tested this several ways on my end and have been unable to replicate this issue. Is it possible to provide me with a sample project so I can replicate?
