### ISSUE TITLE
Fetch Issue When Run in Background

### ISSUE THREAD

**Issue by Jatin-Sondagar** [tonyofrancis/Fetch#525]
Hello, First of all thanks for this wonderful library.
I was integrating this lib in one of my project but i found one issue that when i start download from list its working fine but when i press back button and get back to same activity it doesnot resume download. I want every queued download to complete in background even if i leave screen.

So please suggest me if i am missing something or resolve this issue ASAP.

Thank You.

**Comment by AbreuY** [comment]
@Jatin-Sondagar are you using a download service for this? I recommend you to do a download service to manage it on background.
