### ISSUE TITLE
ConnectivityManager$TooManyRequestsException

### ISSUE THREAD

**Issue by iroidzeel** [tonyofrancis/Fetch#526]
I'm getting crash sometimes 

ConnectivityManager$TooManyRequestsException

when I start for downloading files

**Comment by l132a** [comment]
i have the same problem

**Comment by tonyofrancis** [comment]
@l132a @iroidzeel Fetch only attaches one Callback listener to the connectivity manager when a fetch instance is created. The callback is also un-registered after you release the fetch instance.

Looks like the problem occurs when multiple instance of fetch is created and not released correctly.
How many instances of Fetch are you creating in your application? Most of the time, 1 shared instance of Fetch is sufficient.

**Comment by tonyofrancis** [comment]
@jpvs0101 A new version of Fetch 3.0.12 & AndroidX version 3.1.6 has been released

**Comment by moisoni97** [comment]
Occasionally I still see this "ConnectivityManager$TooManyRequestsException" exception in Crashlytics, but it happens very rarely...  for like 40k installs, 6 crash events affecting 5 users.
I tried to investigate it but I cannot find the root problem...
