### ISSUE TITLE
REQUEST_NOT_SUCCESSFUL

### ISSUE THREAD

**Issue by sanjaysingh1990** [tonyofrancis/Fetch#528]
File downloading 50% after it's not getting downloaded but file is working fine.

{
    "autoRetryAttempts": 5,
    "autoRetryMaxAttempts": 5,
    "created": 1602328936848,
    "downloadOnEnqueue": true,
    "downloaded": 17017742,
    "downloadedBytesPerSecond": -1,
    "enqueueAction": "UPDATE_ACCORDINGLY",
    "error": "REQUEST_NOT_SUCCESSFUL",
    "etaInMilliSeconds": -1,
    "extras": {
      "data": {
        
      }
    },
    "file": "/data/user/0/com.sdll/files/fetch/nNlcHuJfcFKzrg2Txe0yayOkQdvkg8GbKZL8njx8.mp4",
    "group": 4,
    "headers": {
      
    },
    "id": 211440922,
    "identifier": 8,
    "namespace": "DownloadListActivity",
    "networkType": "ALL",
    "priority": "NORMAL",
    "status": "FAILED",
    "tag": "6",
    "total": 27391464,
    "url": "https://green-jakobsen.s3-accelerate.amazonaws.com/sitemap/6/nNlcHuJfcFKzrg2Txe0yayOkQdvkg8GbKZL8njx8/nNlcHuJfcFKzrg2Txe0yayOkQdvkg8GbKZL8njx8.mp4"
  }

**Comment by tonyofrancis** [comment]
@sanjaysingh1990 I was able to successfully download the file using Fetch.
```
"url": "https://green-jakobsen.s3-accelerate.amazonaws.com/sitemap/6/nNlcHuJfcFKzrg2Txe0yayOkQdvkg8GbKZL8njx8/nNlcHuJfcFKzrg2Txe0yayOkQdvkg8GbKZL8njx8.mp4
```
Here is the MD5 hash of the file: `93148314a92e6912490deefca14940d1` and its 16.2MB

The error `REQUEST_NOT_SUCCESSFUL` signals that there was an issue with the server `REQUEST_NOT_SUCCESSFUL`. Could be a very slow connection. Please try on a different connection and let us know how it worked for you.
