### ISSUE TITLE
Downloading not resumed after app is restarted

### ISSUE THREAD

**Issue by nikola5ra** [tonyofrancis/Fetch#53]
Hi Tony,

Thanks for awesome library :)
In order to make it perfect I mast report one issue that I noticed.

So if you do next everything work fine:
1. start downloading
2. pause downloading
3. resume downloading

But if you do
1. start downloading
2. pause downloading
3. kill the app
4. start the app and resume downloading
then nothing happened. On onUpdate I received status 900 which I saw that means STATUS_QUEUED, but after that I never received any other status like STATUS_DOWNLOADING or STATUS_DONE. If I call one more time fetch.resume(mDownloadId) that download continues from point where was paused.

The same I notice for fetch.retry(mDownloadId) when download fails with SERVER_ERROR = -110. If I try to retry download, I received status 900, but nothing after that.

If you have some questions, please ask.

Best,
Nikola

**Comment by tonyofrancis** [comment]
@nikola5ra Thanks for reporting. Are you able to replicate this behavior in another project?
In you application's onCreate method you can call `Fetch.startService(context);` and the queued downloads should start downloading without having to call `fetch.resume(downloadid);`.

**Comment by nikola5ra** [comment]
Hi Tonyo,

Thanks for the answer, that was really quick.

I try Fetch only on one project.
With Fetch.startService(context) I made work around. Thing is when I pause download and restart the app that request have status 902 (paused) not 900. So I still do fetch.resume(downloadId) and then on onUpdate when I get status 900, I do Fetch.startService(context) which will continue downloading from point where download stops.

Your post definitely help me to solve the problem.

**Comment by tonyofrancis** [comment]
@nikola5ra Happy to help.
