### ISSUE TITLE
After Close the fetch and start again dowloading the same file not started download

### ISSUE THREAD

**Issue by kambrish** [tonyofrancis/Fetch#530]
I started multiple download and it is working successfully but when I kill my app I close the Fetch instance at that time some files was not completely downloaded. after some time I again start the app and again put these file for download it added successfully in fetch but actually files was not downloading.

**Comment by tonyofrancis** [comment]
@kambrish 

Before enqueuing Requests to Fetch, you can first check if the file was already downloaded.
```java
    List<Integer> requestIdLists = new ArrayList<>();
        requestIdLists.add(request.getId());
        fetch.getDownloads(requestIdLists, new Func<List<Download>>() {
            @Override
            public void call(@NotNull List<Download> result) {
                //check if download exists and status is completed.
                
                //enqueue new requests only
                fetch.enqueue(newRequests);
            }
        }).
```

 If not, you can enqueue the new request but be sure to set the EnqueueAction to`request.setEnqueueAction(EnqueueAction.REPLACE_EXISTING);` This will force fetch to clear the old request and to download the file again. See EnqueueAction Java docs for more information.
