### ISSUE TITLE
How to implement a custom FetchHandler ?

### ISSUE THREAD

**Issue by thib-rdr** [tonyofrancis/Fetch#534]
Hi, long term user of you lib, thanks for your hard work !

I've created in my code a new FetchHandlerImpl, extending FetchHandler, and added all the necessary code. How can I tell my local Fetch implementation to use this custom handler ? Something to do with the modules ? I'm having trouble figuring it out. Just a quick FYI my app is still in Java 😄 

Thanks in advance

**Comment by tonyofrancis** [comment]
@thib-rdr Thanks for using Fetch and sorry for the very late reply. 

Looks like there is no easy way to inject your own `FetchHandlerImpl`. I am currently working on an update in the next few days and can add this functionality for you.

**Comment by tonyofrancis** [comment]
@jpvs0101 A new version of Fetch 3.0.12 & AndroidX version 3.1.6 has been released. You are now able to add your custom FetchHandler
