### ISSUE TITLE
After retry or resume , the download does not complete

### ISSUE THREAD

**Issue by Matin69** [tonyofrancis/Fetch#538]
**After 50 to 70% of the download**, I get **REQUEST_NOT_SUCCESSFUL** error, when i :
1 - close and reopen the Fetch
2 - pause and resume the download
3 - allow the Fetch to try download auto
and the download does not complete
i saw almost similar scenarios in issues so i migrate to version 1.3.4 of Android X and everything is fine , but this is not we want and this is not the correct way.
so i want from contributors to fix this bugs and give us an amazing and reliable Fetch
@tonyofrancis 
tnks

**Comment by tonyofrancis** [comment]
@Matin-Javatar I would be more than happy to look into this issue. Please provide sample code so we can reliably replicate this issue.

**Comment by tonyofrancis** [comment]
@jpvs0101 A new version of Fetch 3.0.12 & AndroidX version 3.1.6 has been released
