### ISSUE TITLE
Integrate CI (CircleCI)

### ISSUE THREAD

**Issue by jacobtabak** [tonyofrancis/Fetch#54]
It would be great to build the app with CircleCI so we can green light pull requests from external developers before merging. I can take care of this issue if you can give me the appropriate permissions, otherwise I can fork the repo and set it up on my fork and then we can copy the config in this repo.

**Comment by tonyofrancis** [comment]
@jacobtabak I was able to setup the CircleCI for the project. Would be nice to have a second pair of eyes to make sure that it was setup correctly and is not missing anything.
