### ISSUE TITLE
onProgress call only when download completed

### ISSUE THREAD

**Issue by omidnaghipoor** [tonyofrancis/Fetch#541]
I'm trying to download a single zip file and show a progress percent.
The problem is onProgress callback called only when download is completed.
How can I update progress percent during download progress?

**Comment by tonyofrancis** [comment]
@omidngp74 I just tested the library and onProgress callback on the FetchListener is always called. 

You can also attach a FetchObserver to observe download progress

```java
        FetchObserver<Download> observer = new FetchObserver<Download>() {
            @Override
            public void onChanged(Download data, @NotNull Reason reason) {
                if (data.getStatus() == Status.DOWNLOADING) {
                    // downloading
                } else if (data.getStatus() == Status.COMPLETED) {
                    //completed

                    //remove observer when done.
                    fetch.removeFetchObserversForDownload(request.getId(), this);
                }
            }
        };
        fetch.attachFetchObserversForDownload(request.getId(), observer);
```

Let me know if this works for you.

**Comment by tonyofrancis** [comment]
@jpvs0101 A new version of Fetch 3.0.12 & AndroidX version 3.1.6 has been released
