### ISSUE TITLE
Error during downloading

### ISSUE THREAD

**Issue by praveenkumar2K06** [tonyofrancis/Fetch#542]
I am getting FILE_NOT_FOUND error when enqueing request

**Comment by tonyofrancis** [comment]
@Hacker437 If you are running Fetch on Android 10 and above you need to have the proper storage permissions. You get the FILE_NOT_FOUND when fetch is unable to create the file on the device.

See: https://developer.android.com/about/versions/10/privacy/changes

Also I will be updating the sample app to work with Android 10 and above.

**Comment by Hacker437** [comment]
I am testing my app on Redmi 7 android 9

**Comment by Hacker437** [comment]
I will send a screen recorded video if needed.

**Comment by praveenkumar2K06** [comment]
Thanks.Now i can download
