### ISSUE TITLE
What is Priority?

### ISSUE THREAD

**Issue by AlirezaGhanbarinia** [tonyofrancis/Fetch#558]
thank you for useful library 

what are the priority properties in the Fetch Library? 

what is the difference between high, normal and low? 

when high priority is set to a download request, does Fetch do the request earlier or the request will be repeated when fails?

**Comment by tonyofrancis** [comment]
By default, Fetch downloads requests on a first come first serve basis. Priority helps boost a request to the top of the queue based on importance. 

For example:  If Fetch is currently downloading the maximum number of request it can handle, and a request with a high priority comes in. It will try to pause a low or normal priority request and begin downloading the high priority request.

**Comment by AlirezaGhanbarinia** [comment]
thank you
