### ISSUE TITLE
Downloading in Background Without Blocking UI Thread.

### ISSUE THREAD

**Issue by Jatin-Sondagar** [tonyofrancis/Fetch#561]
Hello there
I have integrate Fetch in one of my projects and its working quite well.
But I want to know if fetch downloads files in background or not because it some time makes UI jittery and laggy.
So, can you assist me with this issue?

**Comment by praveenkumar2K06** [comment]
@Jatin-Sondagar Fetch uses another thread, It didn't have any UI Jittrey Or something

**Comment by Jatin-Sondagar** [comment]
ok thanks for letting me know

**Comment by praveenkumar2K06** [comment]
Please close the issue,If your doubt has been clarified

**Comment by Jatin-Sondagar** [comment]
Thanks for your support.
