### ISSUE TITLE
How to avoid layout blinking when downloading?

### ISSUE THREAD

**Issue by AbreuY** [tonyofrancis/Fetch#572]
When a file is downloaded, the design always flashes as the download completes. How can this be avoided? Just update the progress bar.

![image](https://user-images.githubusercontent.com/5095949/111044116-fc31b980-841c-11eb-8774-a4174270b419.png)

**Comment by KunalDhyani** [comment]
Hi, I was having problem with same issue and it got solved by  implementing 
"onBindViewHolder(holder, position,payloads)" function inside the RecyclerViewAdapter.
 There you can use the payload list's zeroeth element and bind or modify your item again.
(Here you need to cast your object to desired type)

To invoke this particular function, you need to use "notifyItemChanged(position, PayloadObject)"
(Here payload will accept "Any" type MutableList)

I explained it in kotlin terms but everything should be understandable. You can query back if needed.

![IMG_20210330_190806~2.jpg](https://user-images.githubusercontent.com/38094647/112998113-59eb3300-918b-11eb-83dd-0ae34d7a54cf.jpg)

![IMG_20210330_190652.jpg](https://user-images.githubusercontent.com/38094647/112998538-c108e780-918b-11eb-9f06-858b81728c21.jpg)

**Comment by passmanagerapp** [comment]
recyclerView.itemAnimator = null that worked for me.

**Comment by AbreuY** [comment]
Thank you, guys! @passmanagerapp @KunalDhyani
