### ISSUE TITLE
Can you provide a sample code in java  for downloading a google drive pdf file in java 

### ISSUE THREAD

**Issue by pbgetwayscitech** [tonyofrancis/Fetch#592]
can you provide a sample code in java  for downloading a google drive file . while i am trying to download i am getting this error :

java.net.ProtocolException: Too many follow-up requests: 21 

sample drive link : 

https://drive.google.com/file/d/1AqjIoYo3B7m5H-huGqXR1myoPcMvHPIM/view?usp=sharing

**Comment by nikzdevz** [comment]
Hey have you got solution for this?
