### ISSUE TITLE
Unexpected End of Stream Error

### ISSUE THREAD

**Issue by BlackVick** [tonyofrancis/Fetch#603]
Hello @tonyofrancis, Great job on this library. It has been smooth up until now. I keep getting "Unexpected End of Stream" error

**Comment by Velord** [comment]
I used OkHttpDownloader and it always on a first attempt throw I/O exception when downloading from S3. You can resolve this issue via migrate to HttpUrlConnectionDownloader or set setAutoRetryMaxAttempts.

**Comment by BlackVick** [comment]
Alright thanks
