### ISSUE TITLE
Android 12 can't call onCompleted method

### ISSUE THREAD

**Issue by TheDam1999** [tonyofrancis/Fetch#633]
Android 12 can't call onCompleted method, 100% loading process returns to onQueued. Please tell me how to fix it. With Android 11 this library is still in use.

**Comment by moisoni97** [comment]
On my Samsung S10+ with Android 12, everything works and the onCompleted method is called. I guess it's something with your code... or maybe it's depending on the device...

**Comment by TheDam1999** [comment]
I found the cause. because FLAG_UPDATE_CURRENT is deprecated.thank.
