### ISSUE TITLE
Consecutively pausing and resuming stops download.

### ISSUE THREAD

**Issue by khaleeljageer** [tonyofrancis/Fetch#64]
Implemented UI for Pause/Resume download. Consecutively clicking on pause/resume button leads to download stops. When Refreshing UI, `requestInfo.getStatus()` returns 900(Queued). Help me to fix this. Using version 1.1.3.

**Comment by tonyofrancis** [comment]
@khaleeljageer  Fetch process downloads in a queue based system. The default is 1 download at a time. All other downloads are then queued until its their time for downloading. When a download is paused, it technically goes to the back of the queue and the next request at the head of the queue is processed. If you change `fetch.setConcurrentDownloadsLimit(limit)` your are then able to download multi request at a time. The README and WIKI has more information. Please let me know if this helped.

**Comment by xeinebiu** [comment]
Using the below code, still the Pause and cancel button are stopping the download.

MAX_DOWNLOAD_COCURRENT_LIMIT = 5;
PROGRESS_REPORTING_INTERVAL = 1000;

 FetchConfiguration fetchConfiguration = new FetchConfiguration.Builder(this)
                .setDownloadConcurrentLimit(FETCH_MAX_DOWNLOAD_CONCURRENT_LIMIT)
                .setProgressReportingInterval(FETCH_PROGRESS_REPORTING_INTERVAL)
                .setNotificationManager(new DefaultFetchNotificationManager(this) {
                    @NotNull
                    @Override
                    public Fetch getFetchInstanceForNamespace(@NotNull String s) {
                        return sFetch;
                    }

                    @NotNull
                    @Override
                    public String getChannelId(int notificationId, @NotNull Context context) {
                        return super.getChannelId(notificationId, context);
                    }
                })
                .build();
        sFetch = Fetch.Impl.getInstance(fetchConfiguration);
