### ISSUE TITLE
Fetch.getInstance(this)

### ISSUE THREAD

**Issue by Xenolion** [tonyofrancis/Fetch#65]
I have just wrote this in my Activity onCreate() method and Android Studio says the method getInstance(Context) is deprecated.

`Fetch fetch = Fetch.getInstance(this);`

Hey whats going on? is a problem in the library or really deprecated!? Or android studio problem because it is even cut through as the way deprecated method are treated in android studio!!
Help me with this!

**Comment by VitorAndrioli** [comment]
It seems the getInstance() is really deprecated, although the README still uses it. I believe Fetch.newInstance(Context context) should be used.

**Comment by Xenolion** [comment]
Yeah I have already done that!! And it worked! The read me should be changed then! @VitorAndrioli

**Comment by tonyofrancis** [comment]
Thanks for reporting this. I will change.

**Comment by tonyofrancis** [comment]
fixed.
