### ISSUE TITLE
Today i face error :Failed to resolve:

### ISSUE THREAD

**Issue by ThreeMinutesFix** [tonyofrancis/Fetch#657]
Failed to resolve: androidx.tonyodev.fetch2:xfetch2:3.1.6
Add Google Maven repository and sync project
Show in Project Structure dialog
Affected Modules: app

Failed to resolve: androidx.tonyodev.fetch2okhttp:xfetch2okhttp:3.1.6
Add Google Maven repository and sync project
Show in Project Structure dialog
Affected Modules: app

ss: https://ibb.co/vHz8q08
Dont know whats wrong because it was working fine till today noon

**Comment by RamProg** [comment]
You need to migrate to 

`implementation "com.github.tonyofrancis.Fetch:xfetch2:3.1.6"`

https://github.com/tonyofrancis/Fetch/issues/586

**Comment by ThreeMinutesFix** [comment]
Thanks but still http shows error
Failed to resolve: androidx.tonyodev.fetch2okhttp:xfetch2okhttp:3.1.6
Add Google Maven repository and sync project
Show in Project Structure dialog
Affected Modules: app

**Comment by RamProg** [comment]
Did you see this? https://github.com/tonyofrancis/Fetch/issues/586#issuecomment-997966318

**Comment by ThreeMinutesFix** [comment]
yes friend i have implemented soln error gone for first dependency and error 2 is still there
https://ibb.co/cJq3J3M
and i read that recommended to use on my own project with  that two classes 
but i dont get the line-->
` you also need to implement okhttp dependency separately in your build.gradle and maybe other dependencies.`

**Comment by ahmedsalemelzeiny** [comment]
@ThreeMinutesFix @RamProg Did you find any solution?

**Comment by ThreeMinutesFix** [comment]
> @ThreeMinutesFix @RamProg Did you find any solution?

no As mentioned by repo owner and in #152 we need to add those 2 classes inside our module

**Comment by omidnaghipoor** [comment]
I have the same issue.
Does anyone know how to fix that?

**Comment by omidnaghipoor** [comment]
@ThreeMinutesFix You should use ### implementation "com.github.tonyofrancis.Fetch:xfetch2:3.1.6"### instead of ### implementation "androidx.tonyodev.fetch2:xfetch2:3.1.6"###

**Comment by omidnaghipoor** [comment]
You should use 

> implementation "com.github.tonyofrancis.Fetch:xfetch2:3.1.6"

Insted of

> implementation "androidx.tonyodev.fetch2:xfetch2:3.1.6"

**Comment by ThreeMinutesFix** [comment]
yeah thanks now its fixed 👍
