### ISSUE TITLE
fetch.setOnUpdateInterval() is not working 

### ISSUE THREAD

**Issue by KulwinderSinghRahal** [tonyofrancis/Fetch#66]
first of all thanks for this really useful libarary,
I have set `fetch.setOnUpdateInterval(2000)` but it is not updating after 2 seconds as expected

**Comment by tonyofrancis** [comment]
@KulwinderSinghRahal are you getting progress updates?

**Comment by KulwinderSinghRahal** [comment]
yes, onUpdate is called at random time but i want it to be after 2 seconds

**Comment by tonyofrancis** [comment]
@KulwinderSinghRahal if you have more than one download processing on update may be called at a different times for download 1, download 2 and so on. Also, depending on how long it takes to write the downloaded bytes to the file, onUpdate may be called after two seconds or the time you set. I had a look at the code and verified that it does work as expected. Can you test in a test project?
