### ISSUE TITLE
v3.2.0 build broken

### ISSUE THREAD

**Issue by rlce** [tonyofrancis/Fetch#671]
The build for version v3.2.0 seems broken.

More details on build log:
https://jitpack.io/com/github/tonyofrancis/Fetch/3.2.0/build.log

**Comment by resilient-aadi** [comment]
I’m  also getting build issue in v 3.2.0

**Comment by tonyofrancis** [comment]
Fetch 3.3.0 has been released. [See Release Notes](https://github.com/tonyofrancis/Fetch/releases/tag/3.3.0)
