### ISSUE TITLE
Failed to resolve library

### ISSUE THREAD

**Issue by Doumith** [tonyofrancis/Fetch#678]
hello I am facing this issue while trying to use latest version 
failed to resolve: androidx.tonyodev.fetch2:xfetch2:3.2.0

**Comment by SultanAyubi360** [comment]
did you resolve this? how i resolve this issue i am stuck from 2 days

**Comment by Doumith** [comment]
use this @SultanAyubi360 
    implementation("com.github.Akaizz.Fetch:fetch2:3.3")

**Comment by SultanAyubi360** [comment]
but how i give my own list to this?

**Comment by tonyofrancis** [comment]
Latest version of Fetch has been released. Please check out the readme and changelog.
