### ISSUE TITLE
remove broadcast com.tonyodev.fetch2.action.QUEUE_BACKOFF_RESET

### ISSUE THREAD

**Issue by Reginer** [tonyofrancis/Fetch#682]
Can the broadcast be changed to an observer in another way? The system application prohibits sending broadcasts.

Sending non-protected broadcast com.tonyodev.fetch2.action.QUEUE_BACKOFF_RESET from system

**Comment by tonyofrancis** [comment]
Issues with the broadcast has been fixed in the latest version

**Comment by Reginer** [comment]
Oh , no fixed .
The system application can only send protected broadcasts.
Fetch still sendBroadcast in https://github.com/tonyofrancis/Fetch/blob/860e26d75c72b9c07f43371909e8962e5e95103a/fetch2/src/main/java/com/tonyodev/fetch2/downloader/DownloadManagerImpl.kt#L114

**Comment by tonyofrancis** [comment]
@Reginer 

Released a new version that removes the broadcast and uses a callback instead. Please try version 3.4.1 and let me know if that fixes your issue. Thanks.

**Comment by Reginer** [comment]
Elegant and silky smooth, wonderful beyond words.  Fixed
