### ISSUE TITLE
V3.2.0 version can not find

### ISSUE THREAD

**Issue by subhadiprudra** [tonyofrancis/Fetch#683]
Failed to resolve: androidx.tonyodev.fetch2:xfetch2:3.2.0

**Comment by anhduy5689h** [comment]
My solution:
repositories {
        google()
        mavenCentral()
        // Add JitPack repository to support downloading dependencies,
        // including 'androidx.tonyodev.fetch2okhttp:xfetch2okhttp:3.2.0' from JitPack.
        maven { url = uri("https://jitpack.io") }
    }

**Comment by tonyofrancis** [comment]
Fetch 3.3.0 has been released. [See Release Notes](https://github.com/tonyofrancis/Fetch/releases/tag/3.3.0)
