### ISSUE TITLE
not resolve this error please 

### ISSUE THREAD

**Issue by Yash222-ui** [tonyofrancis/Fetch#689]
implementation "com.tonyodev.fetch2:fetch2:3.0.12"
    implementation "com.tonyodev.fetch2okhttp:fetch2okhttp:3.0.12"

Execution failed for task ':app:desugarDebugFileDependencies'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform fetch2-3.0.12.aar (com.tonyodev.fetch2:fetch2:3.0.12) to match attributes {artifactType=processed-jar, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Could not find fetch2-3.0.12.aar (com.tonyodev.fetch2:fetch2:3.0.12).
        Searched in the following locations:
            https://jcenter.bintray.com/com/tonyodev/fetch2/fetch2/3.0.12/fetch2-3.0.12.aar
            https://jcenter.bintray.com/com/tonyodev/fetch2/fetch2/3.0.12/fetch2-3.0.12.jar

**Comment by tonyofrancis** [comment]
Fetch 3.3.0 has been released. [See Release Notes](https://github.com/tonyofrancis/Fetch/releases/tag/3.3.0)
