### ISSUE TITLE
Proxy support?

### ISSUE THREAD

**Issue by JusticeRage** [tonyofrancis/Fetch#71]
Hi! I'm looking for a download manager that supports proxies to replace android's default one (mainly because it doesn't!).
I've been browsing through your library and it seems that this feature doesn't exist at the moment either. Is this something you plan on adding in the future?

**Comment by tonyofrancis** [comment]
@JusticeRage I am planning on providing proxy support in version 2.0. But that may take some time.

**Comment by rana01645** [comment]
Is proxy support available now?

**Comment by winnerawan** [comment]
any update ?
