### ISSUE TITLE
Concurrent error

### ISSUE THREAD

**Issue by gurjantbhullar34** [tonyofrancis/Fetch#74]
When re_download same file again if it was failed get concurrent error .

**Comment by tonyofrancis** [comment]
@gurjantbhullar34 can you share your code?

**Comment by gurjantbhullar34** [comment]
private void startDownload(String murl, String title, String mime,String image) {
    Request    request = new Request(murl, mPath, title + "." + mime);
      long  downloadId = mFetch.enqueue(request);
        if (downloadId != Fetch.ENQUEUE_ERROR_ID) {
            //Download was successfully queued for download.
            String currentDateTimeString = DateFormat.getDateTimeInstance().format(new Date());
             Toast.makeText(this, "added to queue", Toast.LENGTH_SHORT).show();
        }
    }

**Comment by gurjantbhullar34** [comment]
please send me your email i will send you complete class.

**Comment by tonyofrancis** [comment]
@gurjantbhullar34 it would be best to create an example project and recreate the issue so we can test in the open.

**Comment by gurjantbhullar34** [comment]
public class MainActivity extends AppCompatActivity implements View.OnClickListener, FetchListener {
    private Button mStart, mPause, mResume;
    private ProgressBar mProgressBar;
    private Fetch fetch;
    private long mDownloadId;

    @Override

    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        mStart = (Button) findViewById(R.id.start);
        mPause = (Button) findViewById(R.id.pause);
        mResume = (Button) findViewById(R.id.resume);
        mProgressBar = (ProgressBar) findViewById(R.id.progress);
        fetch = Fetch.newInstance(this);
        fetch.addFetchListener(this);
        mStart.setOnClickListener(this);
        mPause.setOnClickListener(this);
        mResume.setOnClickListener(this);
    }

    @Override
    public void onClick(View view) {
        switch (view.getId()) {
            case R.id.start:
                startDownload();
                break;
            case R.id.pause:
                pauseDownload();
                break;
            case R.id.resume:
                resumeDownload();
                break;
        }

    }

    private void resumeDownload() {
        try {
            fetch.resume(mDownloadId);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void pauseDownload() {
        fetch.pause(mDownloadId);
    }

    private void startDownload() {
        Request request = new Request("https://dl.jatt.link/hd.jatt.link/aa2bc2a60cbb8eb17fcf6039c37955ed/ocnzv/Breakup-(Mr-Jatt.com).mp3","/Downloads","geeta");
        mDownloadId = fetch.enqueue(request);
        if(mDownloadId != Fetch.ENQUEUE_ERROR_ID) {
            Toast.makeText(this, "queue", Toast.LENGTH_SHORT).show();        }

    }

    @Override
    public void onUpdate(long id, int status, int progress, long downloadedBytes, long fileSize, int error) {
        if(mDownloadId == id && status == Fetch.STATUS_DOWNLOADING) {

            mProgressBar.setProgress(progress);

        }else if(error != Fetch.NO_ERROR) {
            //An error occurred

            if(error == Fetch.ERROR_HTTP_NOT_FOUND) {
                //handle error
            }

        }
    }
}

**Comment by gurjantbhullar34** [comment]
My downloading class is above and i am getting error code 904. please explain me reason of this error.

**Comment by tonyofrancis** [comment]
@gurjantbhullar34  If you get a status of 904. you can get the error code from a RequestInfo object. and comparing it against the different constants  from fetch like `Fetch.ERROR_*`
