### ISSUE TITLE
DownloadInterruptedException: DIE when doing concurrent downloads on API 26

### ISSUE THREAD

**Issue by TosinAF** [tonyofrancis/Fetch#75]
Attempt to do multiple downloads on an API 26 emulator. It seems the thread is interrupted and throws that error.

**Comment by tonyofrancis** [comment]
@TosinAF Fetch 1 is not compatible with API 26 because of the new service restrictions. I am currently working on Fetch 2.

**Comment by TosinAF** [comment]
Thanks. To Note, it works if you perform downloads one a time. Will close.

**Comment by s9iper1** [comment]
Doesn't work with android 5 compiled with api 25. same error
