### ISSUE TITLE
Can't do fetch.remove(id) when no storage error occurs 

### ISSUE THREAD

**Issue by martinmek** [tonyofrancis/Fetch#77]
Hi, I'm trying to remove both request and partially downloaded file when there's no storage on device, but I get this error stack trace, and it doesn't remove neither request or file.
This is what I'm trying to do:
<img width="687" alt="screenshot at oct 17 17-20-14" src="https://user-images.githubusercontent.com/22835433/31673440-8228ec3a-b35f-11e7-8f23-b561aa1599b6.png">

And here is log message:
<img width="915" alt="screenshot at oct 17 17-15-37" src="https://user-images.githubusercontent.com/22835433/31673287-2d28d970-b35f-11e7-9dd7-1145aac53de6.png">

Can you give some workaround for this issue fast, please, I need a solution really soon.

Thanks.

**Comment by tonyofrancis** [comment]
@martinmek Being that the disk is full there is not enough space for the sqlite table to be edited. What you can do is query fetch to get the RequestInfo. You can then get the file name from the requestInfo object and delete the file using the normally java File object/ methods. If your app also caches data that can be deleted, you can clear the cache to help free up space on the device. Hope this helps.

**Comment by martinmek** [comment]
I did as you sad and it works. For anyone with same issue later, first I deleted file like @tonyofrancis said, then I called fetch.removeRequest(id).
