### ISSUE TITLE
Progress and filesize on fetch listener gives wrong values

### ISSUE THREAD

**Issue by mchowkar** [tonyofrancis/Fetch#81]
On download started progress returns only 0 and 100 in return
while filesize returns -1 while downloading and once download completes it returns right filesize
I'm unable to set progress bar because of it

**Comment by tonyofrancis** [comment]
@mchowkar the library depends on the server to send the file size when the initial download starts. A file size of -1 means that the library was unable to determine the proper file size. In that case, it would be best to show the user an indeterminate progress bar.
