### ISSUE TITLE
Expose cookie store

### ISSUE THREAD

**Issue by sethchhim** [tonyofrancis/Fetch#83]
I need to authenticate with server and store the cookie. Is there any way to add a cookie to Fetch so access will be granted? This is not Basic Auth so no header authorization. Thank you for any help!

**Comment by tonyofrancis** [comment]
Unfortunately no.

**Comment by sethchhim** [comment]
I'm looking at your Fetch2 sample and if I can drop in my own custom OkHttp client then that will solve this issue. Looking forward to giving it a try!

`Fetch/fetch2sample/src/main/java/com/tonyodev/fetch2sample/GameFilesActivity.java`

```
fetch = new Fetch.Builder(this)
                .name("GameFiles")
                .client(new OkHttpClient()) <-- Solution
                .build();
```
