### ISSUE TITLE
Timing issue when re-downloading a file to the same location

### ISSUE THREAD

**Issue by dougkeen** [tonyofrancis/Fetch#84]
Let's say a file previous downloaded by Fetch was deleted from its location on disk from some external process, and we want to re-download that file to the same location. If you try to do a `fetch.enqueue(request)` with the same url and file path, you'll throw a `com.tonyodev.fetch.exception.EnqueueException: UNIQUE constraint failed: requests._file_path`, as one might expect.

It seems like you should be able to avoid this situation with this code:
```
        RequestInfo requestInfo = fetch.get(request);
        if (requestInfo != null) {
            // Just delete the existing request and move on
            mFetch.removeRequest(requestInfo.getId());
        }
        final long requestId = fetch.enqueue(request);
```
However, the enqueue operation _still_ fails with the same `com.tonyodev.fetch.exception.EnqueueException: UNIQUE constraint failed: requests._file_path`. This is because the `removeRequest` call is delegated to the `FetchService` asynchronously, and the offending row isn't deleted in time for the subsequent `enqueue` call.

Right now, there doesn't seem to be a good workaround for this situation beyond a somewhat crappy "wait and retry" loop.

**Comment by sethchhim** [comment]
I guess the callback would have to happen at `onUpdate` of your `FetchListener` that is attached.

```
    /**
     * Status of a download request if it was successfully removed.
     * */
    int STATUS_REMOVED = 905;
```
I would make a list of `requestId` that are marked to retry. When fetch updates the request to `status = 905`, cross check it with your retry list and handle it from there. Remove from retry list when finished.

**Comment by dougkeen** [comment]
The problem is that the request is never enqueued in the first place, so we don't get a requestId to retry (Fetch just catches the `EnqueueException` and returns -1). Also, since the request is never enqueued, we don't get updates in our `FetchListener`.

**Comment by tonyofrancis** [comment]
@dougkeen If the requestInfo is not null you should be able to get the requestId for the old download. As @sethchhim mentioned, attach a Fetch listener before the remove request and wait for the status of `REMOVED` for that Id. before enqueuing. I am still working on Fetch2 which should over come many async issues. Please let me know if this helps

**Comment by dougkeen** [comment]
Ah, I see. Basically make enqueue an async task triggered by the removal event of the existing request record (only when that conflicting record already exists). I can give that a whirl.
