### ISSUE TITLE
Add possibility for configuration of HttpURLConnection at FetchRunnable.

### ISSUE THREAD

**Issue by guerrillalg** [tonyofrancis/Fetch#85]
Hello, I am considering to use your library in my application, however there is a need for me to customize the `HttpURLConnection` on the initiation. And this cannot be avoided. 
So, I am considering to introduce some changes allowing the configuration of `FetchRunnable`. As it is going to be quite a big change in the library, I want to ask for approval from your side and a green light.
My suggestion would be to introduce the notion of `FetchRunnableFactory` or `ConnectionFactory`.
Users would be able to set one or another by Fetch.Settings, and passing the class name of the Factory. On the initiation we use reflection to create the class that will be used to create objects. 
Default factories would do the current code and optionally users would be able to override the processes.

`FetchRunnableFactory` vs `ConnectionFactory`. Here we need to discuss, on which level we implement the configuration. `FetchRunnableFactory` can give more flexibility, however it will need more access-level changes and more possibilities to shoot in your leg (which I prefer).
`ConnectionFactory` - more conservative approach.

**Comment by tonyofrancis** [comment]
@guerrillalg You are more than welcome to fork Fetch v1 and tweak it to your liking. I am currently working on Fetch v2 which will allow you pass in your own okhttp client. With that said I do not have an eta on its release yet.

**Comment by guerrillalg** [comment]
That's good to hear!

What is the status of V2? When do you expect it to be released?
