### ISSUE TITLE
Redirects aren't followed

### ISSUE THREAD

**Issue by dougkeen** [tonyofrancis/Fetch#86]
If the download URL returns a 3xx redirect status code, and the redirect is from http → https, the download immediately fails with a `IllegalStateException` rather than following the redirect(s) (up to some limited number of redirects). There's no option to allow that type of cross-protocol redirect.

**Comment by tonyofrancis** [comment]
Fetch 1.1.4 and older does not fully support followSslRedirects. Fetch version 2 which I am working on will. Hoping to release it soon

**Comment by dougkeen** [comment]
It will support `followSslRedirects` if you merge my pull request ;)
