### ISSUE TITLE
Fetch.remove(requestID) not removing Request from Fetch

### ISSUE THREAD

**Issue by Mithrandir21** [tonyofrancis/Fetch#90]
I currently have a scenario where I need to remove a Request from Fetch and then finish an activity.
I would think that the following code would do what is needed:
```
Fetch fetch = Fetch.newInstance(this); <- Tried both act context and app context.
Request req = new Request(...);
fetch.enqueue(req);
...
fetch.remove(requestID);
activity.finish();
```
But after the activity has been finished and cleaned up, any new instance of Fetch created will still contain the old `req`. Even worse, the Request still has it's previous status (whatever it was before remove and activity.finish was called).

I am forced to call `fetch.remove(requestID)`, wait until the callback has been made to the `onUpdate` with the status `Fetch.STATUS_REMOVED` and then somehow do `activity.finish()`.

It seems like the Fetch instance cannot update the status of the Request or remove it from it's internal db.

**Comment by tonyofrancis** [comment]
@Mithrandir21 What version of fetch are you using. The latest is 1.1.15?

**Comment by Mithrandir21** [comment]
I'm using:
```
compile("com.tonyodev.fetch:fetch:1.1.5", {
    exclude group: 'com.android.support'
})
```

**Comment by tonyofrancis** [comment]
@Mithrandir21 This seems like an edge case. I do not have a better workaround at this time other than the on you suggested. I'll mark this as a bug and look into it.

**Comment by Mithrandir21** [comment]
Note that might or might not help:
I am running ```fetch.release()``` on destroy, which is happening shortly after ```activity.finish()```.

Not sure this has or should have any impact. Wanted to mention it just in case.

**Comment by tonyofrancis** [comment]
@Mithrandir21 Just to let you know that I have released a new version of Fetch with lots of feature improvements and bug fixes. Please checkout the readme for me details.
