### ISSUE TITLE
Error code : -101 (No such file or directory)

### ISSUE THREAD

**Issue by polaris0227** [tonyofrancis/Fetch#91]
Hi, 
I'm trying to use this library but I always get error when I'm trying to download a file.
Error code : -101
-------------------------- Logcat --------------------------------
java.io.IOException: No such file or directory
java.io.UnixFileSystem.createFileExclusively0(Native Method)
java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:280)
java.io.File.createNewFile(File.java:948)
com.tonyodev.fetch.Utils.createFileIfNotExist(Utils.java:179)
com.tonyodev.fetch.Utils.createFileOrThrow(Utils.java:223)
com.tonyodev.fetch.FetchRunnable.run(FetchRunnable.java:113)
java.lang.Thread.run(Thread.java:761)
-------------------------------------------------------------------
I'll appreciate if you give me a solution.
Thanks.

**Comment by tonyofrancis** [comment]
@polaris0227 It seems that your application does not have write or read  storage permissions to the destination file. The user will have to grant storage permissions first before fetch can download the file to the intended location.
