### ISSUE TITLE
Final classes prevent Unit testing

### ISSUE THREAD

**Issue by Mithrandir21** [tonyofrancis/Fetch#92]
I have been trying to run some unit tests on logic code that I have written using Fetch classes, ```Fetch, Request and RequestInfo```.

But because they are final, they are not mockable.
Just wondering if they could be not-final, so that mocking and testing could be possible.

**Comment by tonyofrancis** [comment]
@Mithrandir21 The easiest way to do this would be to fork the project and make the classes you need non final.
