### ISSUE TITLE
Incorrect downloadedBytes if app is reopened after killed

### ISSUE THREAD

**Issue by Mithrandir21** [tonyofrancis/Fetch#94]
The FetchService runs and keeps track of all downloads, the files and sizes.

If the app is killed while FetchService is downloading a file and the same file is attempted queued after te app is reopened, there will exist a ```RequestInfo``` that will contain the information from the previously downloading file (with the number of bytes downloaded).

However, I have found that the downloadedBytes returned by the FetchService is incorrect. When the app is killed, the number of bytes downloaded is kept and a new download is started from that point, but the actual file has to be downloaded from the beginning. This results in it seeming like the file is being downloaded from the previously stopped point, but in reality, it is being downloaded from the byte 0.

As an example, this Fork is created, with a ```SingleDownloadActivityBroken``` demonstrating the issue:
[Branch](https://github.com/Mithrandir21/Fetch.git)

Please take a look and advice.

**Comment by Mithrandir21** [comment]
This does seem to be related to whether the HTTP server does or does not support "byte range" downloads.

Evident by the following 2 commands:

- curl -O --header "Range: bytes=0-1000" [URL PATH TO FILE]
- curl -O -C - [URL PATH TO FILE]

If you get a message saying something like: 
>  HTTP server doesn't seem to support byte ranges. Cannot resume.

It means the file cannot be continued, which would force the download of the file from the beginning.

**Comment by tonyofrancis** [comment]
@Mithrandir21 Thanks for your interest in Fetch. I just released a new version of Fetch. It has many new feature improvements and better reporting of download status and progress. Please checkout the readme for more details.
