### ISSUE TITLE
Download not working with redirect URL

### ISSUE THREAD

**Issue by Sp4Rx** [tonyofrancis/Fetch#95]
Download fails when URL redirects from http:// to https://
Example: [http://hck.re/Rh8KTk]( http://hck.re/Rh8KTk) -- this is a short URL

Check this post for getting real url [302 Redirect from http to https ](https://stackoverflow.com/questions/14749307/302-redirect-from-http-to-https-in-android-using-dropbox-short-hyperlinks)

**Comment by tonyofrancis** [comment]
@Sp4Rx I just released a newer version of Fetch that allows you to use and configure okhttp and other http clients to perform the downloads using Fetch. Also it has lots of improvements. Please check the readme.
