### ISSUE TITLE
fetch.enqueue(request) returns -1

### ISSUE THREAD

**Issue by SagarKhurana** [tonyofrancis/Fetch#96]
What is the reason of fetch.enqueue method returning -1 instead of (long)downloadid, how can I resolve it... I have implemented the code to download 3 out of 10 download requests it is returning -1[ERROR_ENQUEUE_ID].

**Comment by tonyofrancis** [comment]
@SagarKhurana it means that there was an issue enqueuing the download. Most likely fetch is already managing that download. Fetch does not allow you to enqueue the same download more than once unless its removed first. Also I just released a newer version of Fetch which is much more simpler to use. Please check out the readme.
