### ISSUE TITLE
SocketTimeoout Error

### ISSUE THREAD

**Issue by Minu-Sarraf** [tonyofrancis/Fetch#98]
I am getting following error while downloading images: Can i change readtimeout duration?
java.net.SocketTimeoutException
01-04 18:08:03.494 7422-7983/edu.uw.naturecollections W/System.err:     at java.net.PlainSocketImpl.read(PlainSocketImpl.java:488)
01-04 18:08:03.494 7422-7983/edu.uw.naturecollections W/System.err:     at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:37)
01-04 18:08:03.494 7422-7983/edu.uw.naturecollections W/System.err:     at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
01-04 18:08:03.494 7422-7983/edu.uw.naturecollections W/System.err:     at com.android.okio.Okio$2.read(Okio.java:116)
01-04 18:08:03.494 7422-7983/edu.uw.naturecollections W/System.err:     at com.android.okio.RealBufferedSource.read(RealBufferedSource.java:51)
01-04 18:08:03.494 7422-7983/edu.uw.naturecollections W/System.err:     at com.android.okhttp.internal.http.HttpConnection$ChunkedSource.read(HttpConnection.java:518)
01-04 18:08:03.494 7422-7983/edu.uw.naturecollections W/System.err:     at com.android.okio.RealBufferedSource.exhausted(RealBufferedSource.java:61)
01-04 18:08:03.494 7422-7983/edu.uw.naturecollections W/System.err:     at com.android.okio.InflaterSource.refill(InflaterSource.java:96)
01-04 18:08:03.494 7422-7983/edu.uw.naturecollections W/System.err:     at com.android.okio.InflaterSource.read(InflaterSource.java:62)
01-04 18:08:03.494 7422-7983/edu.uw.naturecollections W/System.err:     at com.android.okio.GzipSource.read(GzipSource.java:75)
01-04 18:08:03.494 7422-7983/edu.uw.naturecollections W/System.err:     at com.android.okio.RealBufferedSource$1.read(RealBufferedSource.java:174)
01-04 18:08:03.494 7422-7983/edu.uw.naturecollections W/System.err:     at java.io.InputStream.read(InputStream.java:162)
01-04 18:08:03.494 7422-7983/edu.uw.naturecollections W/System.err:     at java.io.BufferedInputStream.fillbuf(BufferedInputStream.java:149)
01-04 18:08:03.494 7422-7983/edu.uw.naturecollections W/System.err:     at java.io.BufferedInputStream.read(BufferedInputStream.java:295)
01-04 18:08:03.494 7422-7983/edu.uw.naturecollections W/System.err:     at com.tonyodev.fetch.FetchRunnable.writeToFileAndPost(FetchRunnable.java:259)
01-04 18:08:03.494 7422-7983/edu.uw.naturecollections W/System.err:     at com.tonyodev.fetch.FetchRunnable.run(FetchRunnable.java:148)
01-04 18:08:03.499 7422-7983/edu.uw.naturecollections W/System.err:     at java.lang.Thread.run(Thread.java:818)

**Comment by tonyofrancis** [comment]
@Minu-Sarraf what version of fetch are you using?

**Comment by Minu-Sarraf** [comment]
@tonyofrancis I am using  'com.tonyodev.fetch:fetch:1.1.5'

**Comment by tonyofrancis** [comment]
Hello @Minu-Sarraf . The server is taking a very long time to respond. Unfortunately there is no easy way to change the timeout time in Fetch 1.1.5. I have released a newer version of Fetch check it out.
`implementation "com.tonyodev.fetch2:fetch2:2.0.0-RC2"`. See the readme for more details. With that being said I will be deprecating Fetch version 1 soon.
