### ISSUE TITLE
SSRV 416 issue

### ISSUE THREAD

**Issue by Minu-Sarraf** [tonyofrancis/Fetch#99]
Why I am getting following issue?
 java.lang.IllegalStateException: SSRV:416
01-04 12:37:04.680 5500-6073/edu.uw.naturecollections W/System.err:     at com.tonyodev.fetch.FetchRunnable.run(FetchRunnable.java:176)
01-04 12:37:04.680 5500-6073/edu.uw.naturecollections W/System.err:     at java.lang.Thread.run(Thread.java:818)

**Comment by tonyofrancis** [comment]
Hello @Minu-Sarraf . I have released a newer version of Fetch check it out.
`implementation "com.tonyodev.fetch2:fetch2:2.0.0-RC2"`. See the readme for more details. With that being said I will be deprecating Fetch version 1 soon.
